package autofix

import (
	"fmt"
	"strings"

	"github.com/finsavvyai/pushci/internal/heal"
)

// FormatPRBody generates a markdown PR description from fixes.
func FormatPRBody(fixes []heal.Fix, diagnosis string) string {
	var b strings.Builder
	b.WriteString("## PushCI Auto-Fix\n\n")
	writeWhatFailed(&b, fixes)
	writeWhatWasFixed(&b, fixes)
	writeFilesChanged(&b, fixes)
	writeConfidence(&b, fixes)
	writeDiagnosis(&b, diagnosis)
	writeFooter(&b)
	return b.String()
}

func writeWhatFailed(b *strings.Builder, fixes []heal.Fix) {
	b.WriteString("### What failed\n\n")
	seen := map[string]bool{}
	for _, f := range fixes {
		if !seen[f.Check] {
			fmt.Fprintf(b, "- **%s**\n", f.Check)
			seen[f.Check] = true
		}
	}
	b.WriteString("\n")
}

func writeWhatWasFixed(b *strings.Builder, fixes []heal.Fix) {
	b.WriteString("### What was fixed\n\n")
	for _, f := range fixes {
		fmt.Fprintf(b, "- %s (pattern: `%s`)\n", f.Action, f.Pattern)
	}
	b.WriteString("\n")
}

func writeFilesChanged(b *strings.Builder, fixes []heal.Fix) {
	b.WriteString("### Files changed\n\n")
	seen := map[string]bool{}
	for _, f := range fixes {
		for _, file := range f.FilesChanged {
			if !seen[file] {
				fmt.Fprintf(b, "- `%s`\n", file)
				seen[file] = true
			}
		}
	}
	b.WriteString("\n")
}

func writeConfidence(b *strings.Builder, fixes []heal.Fix) {
	b.WriteString("### Confidence\n\n")
	for _, f := range fixes {
		level := classifyConfidence(f.Pattern)
		fmt.Fprintf(b, "- **%s**: %s\n", f.Check, level)
	}
	b.WriteString("\n")
}

func classifyConfidence(pattern string) string {
	if pattern == "ai" || pattern == "ai-generated" {
		return "AI-generated (review recommended)"
	}
	return "Pattern match (high confidence)"
}

func writeDiagnosis(b *strings.Builder, diagnosis string) {
	if diagnosis == "" {
		return
	}
	b.WriteString("### Diagnosis\n\n")
	b.WriteString(diagnosis + "\n\n")
}

func writeFooter(b *strings.Builder) {
	b.WriteString("---\n")
	b.WriteString("*Generated by [PushCI.dev](https://pushci.dev) — AI-native CI/CD*\n")
}
