package ingestion

const unIndividualXML = `<CONSOLIDATED_LIST>
	<INDIVIDUALS><INDIVIDUAL>
		<DATAID>12345</DATAID>
		<FIRST_NAME>John</FIRST_NAME>
		<SECOND_NAME>Smith</SECOND_NAME>
		<UN_LIST_TYPE>Al-Qaida</UN_LIST_TYPE>
	</INDIVIDUAL></INDIVIDUALS>
</CONSOLIDATED_LIST>`

const unCompanyXML = `<CONSOLIDATED_LIST>
	<ENTITIES><ENTITY>
		<DATAID>99999</DATAID>
		<FIRST_NAME>ACME</FIRST_NAME>
		<SECOND_NAME>Corporation</SECOND_NAME>
	</ENTITY></ENTITIES>
</CONSOLIDATED_LIST>`

const unSingleWordXML = `<CONSOLIDATED_LIST>
	<INDIVIDUALS><INDIVIDUAL>
		<DATAID>11111</DATAID>
		<FIRST_NAME>Madonna</FIRST_NAME>
	</INDIVIDUAL></INDIVIDUALS>
</CONSOLIDATED_LIST>`

const unAliasXML = `<CONSOLIDATED_LIST>
	<INDIVIDUALS><INDIVIDUAL>
		<DATAID>22222</DATAID>
		<FIRST_NAME>Ahmed</FIRST_NAME>
		<SECOND_NAME>Hassan</SECOND_NAME>
		<DESIGNATION>Terrorist</DESIGNATION>
		<TITLE>Mr</TITLE>
		<INDIVIDUAL_ALIAS>
			<ALIAS_NAME>Abu Ahmed</ALIAS_NAME>
		</INDIVIDUAL_ALIAS>
	</INDIVIDUAL></INDIVIDUALS>
</CONSOLIDATED_LIST>`

const unBothTypesXML = `<CONSOLIDATED_LIST>
	<INDIVIDUALS><INDIVIDUAL>
		<DATAID>33333</DATAID>
		<FIRST_NAME>Ali</FIRST_NAME>
		<SECOND_NAME>Khan</SECOND_NAME>
	</INDIVIDUAL></INDIVIDUALS>
	<ENTITIES><ENTITY>
		<DATAID>44444</DATAID>
		<FIRST_NAME>Terror</FIRST_NAME>
		<SECOND_NAME>Network</SECOND_NAME>
	</ENTITY></ENTITIES>
</CONSOLIDATED_LIST>`
