/**
 * E2E: PushCI Production Test
 * Generated by Qestro AI, then refined for real execution.
 * Tests pushci.dev (landing) and app.pushci.dev (dashboard).
 */
import { test, expect } from '@playwright/test';

test.describe('PushCI Landing Page (pushci.dev)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('https://pushci.dev', { waitUntil: 'networkidle', timeout: 15000 });
  });

  test('page loads with correct title', async ({ page }) => {
    const title = await page.title();
    expect(title).toContain('PushCI');
  });

  test('loads in under 5 seconds', async ({ page }) => {
    const timing = await page.evaluate(() => {
      const nav = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;
      return nav.loadEventEnd - nav.startTime;
    });
    expect(timing).toBeLessThan(5000);
  });

  test('hero section shows AI-Native CI/CD', async ({ page }) => {
    // PushCI renders via JS — wait for content then check
    await page.waitForTimeout(1000);
    const body = (await page.textContent('body')) || '';
    const lower = body.toLowerCase();
    expect(lower.includes('ai-native') || lower.includes('ai native')).toBeTruthy();
    expect(lower.includes('ci/cd') || lower.includes('ci cd')).toBeTruthy();
  });

  test('displays npx pushci init command', async ({ page }) => {
    const body = await page.textContent('body');
    expect(body).toContain('pushci init');
  });

  test('has CTA / action buttons', async ({ page }) => {
    const links = await page.locator('a[href]').count();
    expect(links).toBeGreaterThan(3);
  });

  test('shows pricing or free tier info', async ({ page }) => {
    const body = (await page.textContent('body'))?.toLowerCase() || '';
    expect(body.includes('free') || body.includes('pricing') || body.includes('$0')).toBeTruthy();
  });

  test('has no JS errors', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', (e) => errors.push(e.message));
    await page.reload({ waitUntil: 'networkidle' });
    expect(errors.length).toBe(0);
  });

  test('mobile responsive — no overflow at 390px', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(500);
    const overflow = await page.evaluate(() =>
      document.documentElement.scrollWidth > document.documentElement.clientWidth + 1
    );
    expect(overflow).toBe(false);
  });
});

test.describe('PushCI App Dashboard (app.pushci.dev)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('https://app.pushci.dev', { waitUntil: 'networkidle', timeout: 15000 });
  });

  test('app loads with HTTP 200', async ({ page }) => {
    const resp = await page.goto('https://app.pushci.dev');
    expect(resp?.status()).toBe(200);
  });

  test('page has meaningful content', async ({ page }) => {
    const bodyLen = (await page.textContent('body'))?.length || 0;
    expect(bodyLen).toBeGreaterThan(100);
  });

  test('has interactive elements (links or buttons)', async ({ page }) => {
    await page.waitForTimeout(1000);
    const interactive = await page.locator('a, button').count();
    expect(interactive).toBeGreaterThan(0);
  });

  test('references pipelines or CI/CD concepts', async ({ page }) => {
    const body = (await page.textContent('body'))?.toLowerCase() || '';
    const hasCIConcepts = body.includes('pipeline') || body.includes('build') ||
      body.includes('deploy') || body.includes('ci') || body.includes('run');
    expect(hasCIConcepts).toBeTruthy();
  });

  test('mobile responsive at 390px', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(500);
    const overflow = await page.evaluate(() =>
      document.documentElement.scrollWidth > document.documentElement.clientWidth + 1
    );
    expect(overflow).toBe(false);
  });

  test('no JS errors on load', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', (e) => errors.push(e.message));
    await page.reload({ waitUntil: 'networkidle' });
    expect(errors.length).toBe(0);
  });
});
