/**
 * Inline DLP regex packs for the SWG.
 *
 * These rules are matched against POST/PUT request bodies inside the
 * e2guardian content scanner. Each rule pairs a fast regex with an
 * optional checksum validator so we don't fire on random digit runs
 * (the public differentiator vs. Cisco SSE's regex-only DLP).
 *
 * Render via `renderE2guardianRegexBody(rules)` and write to
 *   /etc/e2guardian/lists/dlp/regex-content
 * then reference from e2guardianf1.conf via `bannedregexpcontentlist`.
 */

export type DlpRuleId = 'pci_pan' | 'il_id' | 'iban' | 'email';

export interface DlpRule {
  id: DlpRuleId;
  description: string;
  regex: RegExp;
  /** Optional post-match validator (Luhn, mod-97, etc.). */
  validate?: (match: string) => boolean;
  /** Severity is used by the API when emitting tf_swg_decisions audit rows. */
  severity: 'low' | 'medium' | 'high' | 'critical';
}

const PAN_RE = /\b(?:\d[ -]?){13,19}\b/g;
const IL_ID_RE = /\b\d{9}\b/g;
const IBAN_RE = /\b[A-Z]{2}\d{2}[A-Z0-9]{4,30}\b/g;
const EMAIL_RE = /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi;

export function luhnValid(digits: string): boolean {
  const d = digits.replace(/\D/g, '');
  if (d.length < 13 || d.length > 19) return false;
  let sum = 0;
  let alt = false;
  for (let i = d.length - 1; i >= 0; i--) {
    let n = d.charCodeAt(i) - 48;
    if (alt) {
      n *= 2;
      if (n > 9) n -= 9;
    }
    sum += n;
    alt = !alt;
  }
  return sum % 10 === 0;
}

export function ilIdValid(id: string): boolean {
  const d = id.replace(/\D/g, '');
  if (d.length !== 9) return false;
  let sum = 0;
  for (let i = 0; i < 9; i++) {
    let n = (d.charCodeAt(i) - 48) * ((i % 2) + 1);
    if (n > 9) n -= 9;
    sum += n;
  }
  return sum % 10 === 0;
}

export function ibanValid(iban: string): boolean {
  const s = iban.replace(/\s+/g, '').toUpperCase();
  if (s.length < 15 || s.length > 34) return false;
  // Move first 4 chars to the end, then convert letters A=10..Z=35.
  const rearranged = s.slice(4) + s.slice(0, 4);
  let n = '';
  for (const ch of rearranged) {
    const code = ch.charCodeAt(0);
    if (code >= 48 && code <= 57) n += ch;
    else if (code >= 65 && code <= 90) n += String(code - 55);
    else return false;
  }
  // mod-97 over the very long integer string, processed in chunks of 9 digits.
  let remainder = 0;
  for (let i = 0; i < n.length; i += 9) {
    const block = String(remainder) + n.slice(i, i + 9);
    remainder = Number(block) % 97;
  }
  return remainder === 1;
}

export const DLP_RULES: DlpRule[] = [
  {
    id: 'pci_pan',
    description: 'Credit card PAN (Luhn-validated)',
    regex: PAN_RE,
    validate: luhnValid,
    severity: 'critical',
  },
  {
    id: 'il_id',
    description: 'Israeli Teudat Zehut (check-digit validated)',
    regex: IL_ID_RE,
    validate: ilIdValid,
    severity: 'high',
  },
  {
    id: 'iban',
    description: 'IBAN account number (mod-97 validated)',
    regex: IBAN_RE,
    validate: ibanValid,
    severity: 'high',
  },
  {
    id: 'email',
    description: 'Email address',
    regex: EMAIL_RE,
    severity: 'medium',
  },
];

export interface DlpMatch {
  ruleId: DlpRuleId;
  severity: DlpRule['severity'];
  /** Redacted preview (first 4 + last 4 chars only). */
  preview: string;
}

function redact(value: string): string {
  if (value.length <= 8) return '*'.repeat(value.length);
  return `${value.slice(0, 4)}${'*'.repeat(value.length - 8)}${value.slice(-4)}`;
}

export function evaluateDlp(text: string, rules: DlpRule[] = DLP_RULES): DlpMatch[] {
  const out: DlpMatch[] = [];
  for (const rule of rules) {
    const re = new RegExp(rule.regex.source, rule.regex.flags);
    let m: RegExpExecArray | null;
    while ((m = re.exec(text)) !== null) {
      const candidate = m[0];
      if (rule.validate && !rule.validate(candidate)) continue;
      out.push({ ruleId: rule.id, severity: rule.severity, preview: redact(candidate) });
    }
  }
  return out;
}

/**
 * Render a `bannedregexpcontentlist`-style file body. Each non-empty,
 * non-comment line is a PCRE pattern; e2guardian flags content matching
 * any of them. Validators run server-side via `evaluateDlp` — e2guardian
 * blocks first, the API confirms with the validator before logging the
 * tf_swg_decisions row at the rule's severity.
 */
export function renderE2guardianRegexBody(rules: DlpRule[] = DLP_RULES): string {
  const lines = [
    '# OpenSyber DLP regex pack — generated by swg-orchestrator',
    '# Validators (Luhn, mod-97, IL check digit) run in the API.',
    '',
  ];
  for (const r of rules) {
    lines.push(`# ${r.id}: ${r.description}`);
    lines.push(r.regex.source);
    lines.push('');
  }
  return lines.join('\n');
}
