name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    tags:
      - "worker-*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install wrangler -g

      - name: Publish Worker
        run: wrangler deploy --config workers/lunaforge-worker/wrangler.toml
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}