apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: upm-plus-psp
  namespace: upm-plus
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: upm-plus-psp-role
  namespace: upm-plus
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - upm-plus-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: upm-plus-psp-binding
  namespace: upm-plus
roleRef:
  kind: Role
  name: upm-plus-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: upm-plus