{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pipewarden.serviceAccountName" . }}
  labels: {{- include "pipewarden.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
