package udp.bridges.${ecosystem};

import udp.runtime.UDPBridge;
import udp.runtime.${bridgeType}Module;

/**
 * Auto-generated UDP bridge for ${packageName} (${ecosystem}).
 * This class provides Java bindings for the ${packageName} library.
 *
 * Generated by UDP Maven Plugin v${pluginVersion}
 * Source: ${ecosystem}:${packageName}@${version}
 * Bridge Type: ${bridgeType}
 */
@SuppressWarnings("unused")
public class ${className} {

    private final ${bridgeType}Module module;
    private static ${className} instance;

    /**
     * Private constructor - use getInstance() to get the singleton instance.
     */
    private ${className}() {
        this.module = UDPBridge.load${bridgeType}("${packageName}");
    }

    /**
     * Get the singleton instance of this bridge.
     *
     * @return the ${className} instance
     */
    public static synchronized ${className} getInstance() {
        if (instance == null) {
            instance = new ${className}();
        }
        return instance;
    }

    /**
     * Get the underlying module for advanced operations.
     *
     * @return the ${bridgeType}Module instance
     */
    public ${bridgeType}Module getModule() {
        return module;
    }

<#list methods as method>
    /**
     * ${method.description}
     <#list method.parameters as param>
     * @param ${param.name} ${param.description}
     </#list>
     <#if method.returnType != "void">
     * @return ${method.returnDescription}
     </#if>
     */
    public ${method.returnType} ${method.name}(${method.parameterString}) {
        <#if method.returnType == "void">
        module.call("${method.originalName}"<#if method.parameters?size > 0>, ${method.parameterNames}</#if>);
        <#else>
        return module.call("${method.originalName}"<#if method.parameters?size > 0>, ${method.parameterNames}</#if>).as(${method.returnType}.class);
        </#if>
    }

</#list>
<#if hasConstants>
    // Constants from ${packageName}
<#list constants as constant>
    public static final ${constant.type} ${constant.name} = ${constant.value};
</#list>
</#if>

<#if hasNestedClasses>
    // Nested classes for complex types
<#list nestedClasses as nestedClass>

    /**
     * ${nestedClass.description}
     */
    public static class ${nestedClass.name} {
        private final Object nativeObject;

        public ${nestedClass.name}(Object nativeObject) {
            this.nativeObject = nativeObject;
        }

        public Object getNativeObject() {
            return nativeObject;
        }

    <#list nestedClass.methods as method>
        /**
         * ${method.description}
         */
        public ${method.returnType} ${method.name}(${method.parameterString}) {
            <#if method.returnType == "void">
            // Implementation would call native method
            <#else>
            return null; // Placeholder - implementation would call native method
            </#if>
        }

    </#list>
    }
</#list>
</#if>
}