cluster.name: quantumbeam-cluster
node.name: quantumbeam-es-node
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node
bootstrap.memory_lock: true
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true
xpack.watcher.enabled: true
action.auto_create_index: true
action.destructive_requires_name: false
