#!/bin/bash

# Questro SaaS - First Cloud Deployment Script
# Comprehensive deployment script for multiple cloud providers
# Supports: Render, Vercel, Netlify, Railway, Heroku, DigitalOcean

set -e  # Exit on any error

# Script version and info
SCRIPT_VERSION="1.0.0"
SCRIPT_NAME="Questro First Deploy"

echo "🚀 $SCRIPT_NAME v$SCRIPT_VERSION"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Utility functions
print_status() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }
print_header() { echo -e "${PURPLE}[DEPLOY]${NC} $1"; }

# Global variables
DEPLOYMENT_METHOD=""
CLOUD_PROVIDER=""
PROJECT_NAME="questro"
ROOT_DIR=$(pwd)
LOG_FILE="deployment-$(date +%Y%m%d_%H%M%S).log"

# Logging function
log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"
    echo "$1"
}

# Error handling
handle_error() {
    print_error "Deployment failed at line $1"
    print_error "Check $LOG_FILE for details"
    exit 1
}

trap 'handle_error $LINENO' ERR

# Dependency checks
check_system_requirements() {
    print_header "Checking System Requirements"
    
    local requirements_met=true
    
    # Check Node.js version
    if command -v node &> /dev/null; then
        local node_version=$(node --version | cut -d'v' -f2)
        local node_major=$(echo $node_version | cut -d'.' -f1)
        if [ "$node_major" -ge 18 ]; then
            print_success "Node.js $node_version (✓)"
        else
            print_error "Node.js 18+ required, found $node_version"
            requirements_met=false
        fi
    else
        print_error "Node.js not found"
        requirements_met=false
    fi
    
    # Check npm
    if command -v npm &> /dev/null; then
        local npm_version=$(npm --version)
        print_success "npm $npm_version (✓)"
    else
        print_error "npm not found"
        requirements_met=false
    fi
    
    # Check git
    if command -v git &> /dev/null; then
        local git_version=$(git --version | cut -d' ' -f3)
        print_success "Git $git_version (✓)"
    else
        print_error "Git not found"
        requirements_met=false
    fi
    
    if [ "$requirements_met" = false ]; then
        print_error "Please install missing requirements and try again"
        exit 1
    fi
    
    log "System requirements check passed"
}

# Environment setup
setup_environment() {
    print_header "Setting Up Environment"
    
    # Create .env files if they don't exist
    if [ ! -f backend/.env ]; then
        if [ -f backend/.env.example ]; then
            cp backend/.env.example backend/.env
            print_success "Created backend/.env from example"
        else
            create_backend_env
        fi
    fi
    
    if [ ! -f frontend/.env ]; then
        if [ -f frontend/.env.example ]; then
            cp frontend/.env.example frontend/.env
            print_success "Created frontend/.env from example"
        else
            create_frontend_env
        fi
    fi
    
    # Generate JWT secret if not exists
    if ! grep -q "JWT_SECRET=" backend/.env || grep -q "JWT_SECRET=$" backend/.env; then
        local jwt_secret=$(openssl rand -base64 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")
        echo "JWT_SECRET=$jwt_secret" >> backend/.env
        print_success "Generated JWT secret"
    fi
    
    log "Environment setup completed"
}

create_backend_env() {
    cat > backend/.env << EOF
# Generated by Questro First Deploy Script
NODE_ENV=production
PORT=10000

# Database (Supabase)
USE_SUPABASE=true
SUPABASE_URL=
SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
SUPABASE_DB_HOST=
SUPABASE_DB_PORT=5432
SUPABASE_DB_NAME=postgres
SUPABASE_DB_USER=postgres
SUPABASE_DB_PASSWORD=

# Authentication
JWT_SECRET=

# Frontend URL
FRONTEND_URL=https://your-app.com

# Features
ENABLE_RECORDING=true
ENABLE_MOBILE_TESTING=true
ENABLE_WEB_TESTING=true

# Logging
LOG_LEVEL=info
EOF
    print_success "Created backend/.env template"
}

create_frontend_env() {
    cat > frontend/.env << EOF
# Generated by Questro First Deploy Script
VITE_APP_ENV=production
VITE_API_BASE_URL=https://your-backend.com
VITE_ENABLE_RECORDING=true
VITE_ENABLE_MOBILE_TESTING=true
VITE_ENABLE_WEB_TESTING=true
VITE_ENABLE_ANALYTICS=true
EOF
    print_success "Created frontend/.env template"
}

# Build validation
validate_build() {
    print_header "Validating Build Configuration"
    
    # Check package.json files
    if [ ! -f package.json ]; then
        print_error "Root package.json not found"
        return 1
    fi
    
    if [ ! -f backend/package.json ]; then
        print_error "Backend package.json not found"
        return 1
    fi
    
    if [ ! -f frontend/package.json ]; then
        print_error "Frontend package.json not found"
        return 1
    fi
    
    # Validate build scripts
    if ! grep -q '"build"' backend/package.json; then
        print_error "Backend build script not found in package.json"
        return 1
    fi
    
    if ! grep -q '"build"' frontend/package.json; then
        print_error "Frontend build script not found in package.json"
        return 1
    fi
    
    print_success "Build configuration validated"
    log "Build validation passed"
}

# Install dependencies
install_dependencies() {
    print_header "Installing Dependencies"
    
    # Install root dependencies
    print_status "Installing root dependencies..."
    npm install || {
        print_error "Failed to install root dependencies"
        return 1
    }
    
    # Install backend dependencies
    print_status "Installing backend dependencies..."
    cd backend
    npm install || {
        print_error "Failed to install backend dependencies"
        cd ..
        return 1
    }
    cd ..
    
    # Install frontend dependencies
    print_status "Installing frontend dependencies..."
    cd frontend
    npm install || {
        print_error "Failed to install frontend dependencies"
        cd ..
        return 1
    }
    cd ..
    
    print_success "All dependencies installed"
    log "Dependencies installation completed"
}

# Test build locally
test_build() {
    print_header "Testing Build Process"
    
    # Test backend build
    print_status "Testing backend build..."
    cd backend
    npm run build || {
        print_error "Backend build failed"
        cd ..
        return 1
    }
    print_success "Backend build successful"
    cd ..
    
    # Test frontend build
    print_status "Testing frontend build..."
    cd frontend
    npm run build || {
        print_error "Frontend build failed"
        cd ..
        return 1
    }
    print_success "Frontend build successful"
    cd ..
    
    log "Build test completed successfully"
}

# Cloud provider detection and CLI checks
check_cloud_cli() {
    local provider=$1
    case $provider in
        "render")
            print_status "Render uses Git-based deployment - no CLI needed"
            return 0
            ;;
        "vercel")
            if command -v vercel &> /dev/null; then
                print_success "Vercel CLI found"
                return 0
            else
                print_warning "Vercel CLI not found"
                print_status "Install with: npm i -g vercel"
                return 1
            fi
            ;;
        "netlify")
            if command -v netlify &> /dev/null; then
                print_success "Netlify CLI found"
                return 0
            else
                print_warning "Netlify CLI not found"
                print_status "Install with: npm i -g netlify-cli"
                return 1
            fi
            ;;
        "railway")
            if command -v railway &> /dev/null; then
                print_success "Railway CLI found"
                return 0
            else
                print_warning "Railway CLI not found"
                print_status "Install from: https://railway.app/cli"
                return 1
            fi
            ;;
        "heroku")
            if command -v heroku &> /dev/null; then
                print_success "Heroku CLI found"
                return 0
            else
                print_warning "Heroku CLI not found"
                print_status "Install from: https://devcenter.heroku.com/articles/heroku-cli"
                return 1
            fi
            ;;
        "digitalocean")
            if command -v doctl &> /dev/null; then
                print_success "DigitalOcean CLI found"
                return 0
            else
                print_warning "DigitalOcean CLI not found"
                print_status "Install from: https://github.com/digitalocean/doctl"
                return 1
            fi
            ;;
        *)
            print_error "Unknown cloud provider: $provider"
            return 1
            ;;
    esac
}

# Deploy to Render.com
deploy_render() {
    print_header "Deploying to Render.com"
    
    # Check if render.yaml exists
    if [ ! -f render.yaml ]; then
        print_error "render.yaml not found - creating one"
        create_render_yaml
    fi
    
    print_status "Render deployment steps:"
    echo "1. 🌐 Go to https://render.com and create account"
    echo "2. 🔗 Connect your GitHub repository"
    echo "3. 📋 Create new Blueprint"
    echo "4. 📁 Select your repository and render.yaml"
    echo "5. ⚙️  Configure environment variables:"
    echo "   - SUPABASE_URL"
    echo "   - SUPABASE_ANON_KEY"
    echo "   - SUPABASE_SERVICE_ROLE_KEY"
    echo "   - SUPABASE_DB_PASSWORD"
    echo "6. 🚀 Deploy!"
    
    echo ""
    print_success "render.yaml is ready for deployment"
    print_status "Push your code to GitHub and follow the steps above"
    
    log "Render deployment configuration completed"
}

create_render_yaml() {
    cat > render.yaml << 'EOF'
# Render.com Blueprint for Questro SaaS
services:
  # Backend API Service
  - type: web
    name: questro-api
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: USE_SUPABASE
        value: true
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://questro.onrender.com
      - key: ENABLE_RECORDING
        value: true
      - key: ENABLE_MOBILE_TESTING
        value: true
      - key: ENABLE_WEB_TESTING
        value: true
    
  # Frontend Static Site
  - type: web
    name: questro-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_APP_ENV
        value: production
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: questro-api
          property: host
      - key: VITE_ENABLE_RECORDING
        value: true
      - key: VITE_ENABLE_MOBILE_TESTING
        value: true
      - key: VITE_ENABLE_WEB_TESTING
        value: true
EOF
    print_success "Created render.yaml"
}

# Deploy to Vercel
deploy_vercel() {
    print_header "Deploying to Vercel"
    
    if ! check_cloud_cli "vercel"; then
        print_error "Please install Vercel CLI first"
        return 1
    fi
    
    # Create vercel.json if it doesn't exist
    if [ ! -f vercel.json ]; then
        create_vercel_config
    fi
    
    print_status "Logging into Vercel..."
    vercel login
    
    print_status "Deploying to Vercel..."
    vercel --prod
    
    print_success "Deployed to Vercel successfully"
    log "Vercel deployment completed"
}

create_vercel_config() {
    cat > vercel.json << 'EOF'
{
  "version": 2,
  "builds": [
    {
      "src": "backend/package.json",
      "use": "@vercel/node"
    },
    {
      "src": "frontend/package.json",
      "use": "@vercel/static-build",
      "config": {
        "distDir": "dist"
      }
    }
  ],
  "routes": [
    {
      "src": "/api/(.*)",
      "dest": "/backend/$1"
    },
    {
      "src": "/(.*)",
      "dest": "/frontend/$1"
    }
  ],
  "env": {
    "NODE_ENV": "production"
  }
}
EOF
    print_success "Created vercel.json"
}

# Deploy to Railway
deploy_railway() {
    print_header "Deploying to Railway"
    
    if ! check_cloud_cli "railway"; then
        print_error "Please install Railway CLI first"
        return 1
    fi
    
    print_status "Logging into Railway..."
    railway login
    
    print_status "Creating Railway project..."
    railway project create questro
    
    print_status "Deploying to Railway..."
    railway up
    
    print_success "Deployed to Railway successfully"
    log "Railway deployment completed"
}

# Main deployment selection
select_deployment_method() {
    echo ""
    print_header "Select Deployment Method"
    echo ""
    echo "🌥️  Cloud Providers:"
    echo "1. Render.com (Recommended - Free tier available)"
    echo "2. Vercel (Great for full-stack apps)"
    echo "3. Netlify + Railway (Frontend + Backend)"
    echo "4. Railway (All-in-one platform)"
    echo "5. Heroku (Classic platform)"
    echo "6. DigitalOcean App Platform"
    echo ""
    echo "🏠 Self-hosted:"
    echo "7. Docker Compose (Local/VPS)"
    echo "8. Generate deployment configs only"
    echo ""
    
    read -p "Enter your choice (1-8): " choice
    
    case $choice in
        1) DEPLOYMENT_METHOD="render" ;;
        2) DEPLOYMENT_METHOD="vercel" ;;
        3) DEPLOYMENT_METHOD="netlify_railway" ;;
        4) DEPLOYMENT_METHOD="railway" ;;
        5) DEPLOYMENT_METHOD="heroku" ;;
        6) DEPLOYMENT_METHOD="digitalocean" ;;
        7) DEPLOYMENT_METHOD="docker" ;;
        8) DEPLOYMENT_METHOD="configs" ;;
        *)
            print_error "Invalid choice. Please run the script again."
            exit 1
            ;;
    esac
    
    log "Selected deployment method: $DEPLOYMENT_METHOD"
}

# Database setup instructions
show_database_setup() {
    print_header "Database Setup Required"
    echo ""
    echo "🗄️  Questro requires a PostgreSQL database. Recommended options:"
    echo ""
    echo "1. 🟢 Supabase (Free tier: 500MB, 2 projects)"
    echo "   - Go to https://supabase.com"
    echo "   - Create new project"
    echo "   - Get connection details from Settings > Database"
    echo ""
    echo "2. 🐘 Railway PostgreSQL (Free tier: 1GB)"
    echo "   - railway add postgresql"
    echo ""
    echo "3. 🔵 DigitalOcean Managed Database ($15/month)"
    echo "   - Fully managed PostgreSQL"
    echo ""
    echo "4. 🟦 Heroku Postgres (Free tier deprecated)"
    echo "   - Basic: $5/month"
    echo ""
    
    read -p "Press Enter when you have set up your database..."
    echo ""
}

# Pre-flight checks
pre_flight_check() {
    print_header "Pre-flight Deployment Check"
    
    local check_passed=true
    
    # Check if in git repository
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        print_error "Not in a git repository"
        print_status "Run: git init && git add . && git commit -m 'Initial commit'"
        check_passed=false
    else
        print_success "Git repository (✓)"
    fi
    
    # Check for uncommitted changes
    if ! git diff --quiet && ! git diff --cached --quiet; then
        print_warning "Uncommitted changes found"
        print_status "Consider committing changes before deployment"
    fi
    
    # Check build files exist
    if [ ! -f backend/package.json ] || [ ! -f frontend/package.json ]; then
        print_error "Missing package.json files"
        check_passed=false
    else
        print_success "Package files (✓)"
    fi
    
    # Check environment files
    if [ ! -f backend/.env ]; then
        print_warning "Backend .env file missing"
        print_status "Will be created during setup"
    else
        print_success "Backend .env (✓)"
    fi
    
    if [ "$check_passed" = false ]; then
        print_error "Pre-flight check failed. Please fix issues above."
        exit 1
    fi
    
    print_success "Pre-flight check passed"
    log "Pre-flight check completed"
}

# Generate deployment configs
generate_configs() {
    print_header "Generating Deployment Configurations"
    
    mkdir -p deploy-configs
    
    # Create deployment configs for different providers
    create_render_yaml
    mv render.yaml deploy-configs/
    
    create_vercel_config
    mv vercel.json deploy-configs/
    
    # Docker Compose
    create_docker_config
    
    # Railway
    create_railway_config
    
    print_success "Deployment configurations generated in deploy-configs/"
    
    echo ""
    echo "📁 Generated configs:"
    echo "   - render.yaml (Render.com)"
    echo "   - vercel.json (Vercel)"
    echo "   - docker-compose.prod.yml (Docker)"
    echo "   - railway.toml (Railway)"
    echo ""
    echo "Copy the appropriate config to your project root and deploy!"
}

create_docker_config() {
    cat > deploy-configs/docker-compose.prod.yml << 'EOF'
version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: unless-stopped
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001
    restart: unless-stopped
    
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: questro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
EOF
    print_success "Created docker-compose.prod.yml"
}

create_railway_config() {
    cat > deploy-configs/railway.toml << 'EOF'
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend/"

[[services]]
name = "frontend"
source = "frontend/"
EOF
    print_success "Created railway.toml"
}

# Execute deployment
execute_deployment() {
    case $DEPLOYMENT_METHOD in
        "render")
            deploy_render
            ;;
        "vercel")
            deploy_vercel
            ;;
        "railway")
            deploy_railway
            ;;
        "configs")
            generate_configs
            ;;
        *)
            print_error "Deployment method not implemented yet: $DEPLOYMENT_METHOD"
            return 1
            ;;
    esac
}

# Post-deployment steps
post_deployment() {
    if [ "$DEPLOYMENT_METHOD" != "configs" ]; then
        print_header "Post-Deployment Steps"
        echo ""
        echo "✅ Next Steps:"
        echo "1. 🗄️  Set up your database (if not done already)"
        echo "2. ⚙️  Configure environment variables in your platform"
        echo "3. 🔑 Update CORS origins for your frontend URL"
        echo "4. 🧪 Test your deployed application"
        echo "5. 📊 Set up monitoring and logging"
        echo "6. 🔒 Configure SSL certificates (if needed)"
        echo "7. 📈 Set up analytics and error tracking"
        echo ""
        
        echo "🔗 Important URLs to configure:"
        echo "   - FRONTEND_URL: Your frontend domain"
        echo "   - VITE_API_BASE_URL: Your backend API domain"
        echo "   - CORS_ORIGINS: Frontend domain for API access"
        echo ""
    fi
}

# Main execution function
main() {
    log "Starting Questro deployment script"
    
    print_status "Starting deployment process..."
    echo ""
    
    # Run pre-checks
    check_system_requirements
    pre_flight_check
    
    # Setup environment
    setup_environment
    validate_build
    
    # Show database setup if needed
    if [ ! -f backend/.env ] || ! grep -q "SUPABASE_URL=https://" backend/.env; then
        show_database_setup
    fi
    
    # Install and test
    install_dependencies
    test_build
    
    # Select and execute deployment
    select_deployment_method
    execute_deployment
    
    # Post-deployment instructions
    post_deployment
    
    # Completion
    echo ""
    print_success "🎉 Deployment script completed!"
    print_status "Check $LOG_FILE for detailed logs"
    
    if [ "$DEPLOYMENT_METHOD" != "configs" ]; then
        echo ""
        print_status "⭐ Don't forget to:"
        echo "   - Star the repository"
        echo "   - Configure monitoring"
        echo "   - Set up backups"
        echo "   - Update documentation"
    fi
    
    log "Deployment script completed successfully"
}

# Error handling and cleanup
cleanup() {
    if [ -f "package-lock.json.bak" ]; then
        mv package-lock.json.bak package-lock.json
    fi
}

trap cleanup EXIT

# Run main function if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi