#!/bin/bash

# 🔧 QUESTRO ACCOUNT SETUP AUTOMATION SCRIPT
# This script helps you set up all required accounts and configurations

# Colors for better UX
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${PURPLE}"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                 QUESTRO SETUP WIZARD                     ║"
echo "║              Get Ready to Make Money! 💰                ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Function to wait for user input
wait_for_user() {
    echo -e "${YELLOW}Press any key to continue...${NC}"
    read -n 1 -s
    echo
}

# Function to get user input
get_input() {
    local prompt="$1"
    local var_name="$2"
    echo -e "${CYAN}$prompt${NC}"
    read -r $var_name
}

# Function to open URL
open_url() {
    local url="$1"
    echo -e "${GREEN}Opening: $url${NC}"
    if command -v open &> /dev/null; then
        open "$url"  # macOS
    elif command -v xdg-open &> /dev/null; then
        xdg-open "$url"  # Linux
    elif command -v start &> /dev/null; then
        start "$url"  # Windows
    else
        echo -e "${YELLOW}Please manually open: $url${NC}"
    fi
}

echo -e "${BLUE}📋 ACCOUNT SETUP CHECKLIST${NC}"
echo "We'll help you set up all required accounts step by step."
echo

# Check if .env file exists
ENV_FILE="backend/.env"
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  Found existing .env file. Creating backup...${NC}"
    cp "$ENV_FILE" "$ENV_FILE.backup.$(date +%s)"
fi

# Create .env file
cat > "$ENV_FILE" << 'EOF'
# 🔐 QUESTRO ENVIRONMENT CONFIGURATION
# Generated by setup script - Fill in your actual values

# ═══════════════════════════════════════════════════════════════
# 📊 DATABASE CONFIGURATION (Required)
# ═══════════════════════════════════════════════════════════════
DATABASE_URL=postgresql://postgres:password@db.supabase.co:5432/postgres
USE_SUPABASE=true

# ═══════════════════════════════════════════════════════════════
# 🔑 AUTHENTICATION (Required)
# ═══════════════════════════════════════════════════════════════
JWT_SECRET=your-super-secret-jwt-key-minimum-32-characters-long
JWT_REFRESH_SECRET=another-super-secret-refresh-key-minimum-32-chars

# ═══════════════════════════════════════════════════════════════
# 🌐 FRONTEND URL (Update when deployed)
# ═══════════════════════════════════════════════════════════════
FRONTEND_URL=http://localhost:3000

# ═══════════════════════════════════════════════════════════════
# 📧 EMAIL CONFIGURATION (Required for user verification)
# ═══════════════════════════════════════════════════════════════
EMAIL_PROVIDER=smtp
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=your-email@gmail.com
SMTP_PASS=your-app-specific-password
FROM_EMAIL=noreply@yourdomain.com

# ═══════════════════════════════════════════════════════════════
# 🍋 LEMONSQUEEZY PAYMENT CONFIGURATION (Required for monetization)
# ═══════════════════════════════════════════════════════════════
LEMONSQUEEZY_API_KEY=your_lemonsqueezy_api_key_here
LEMONSQUEEZY_STORE_ID=your_store_id_here
LEMONSQUEEZY_WEBHOOK_SECRET=your_webhook_secret_here
LEMONSQUEEZY_VARIANT_ID_PRO=your_pro_variant_id
LEMONSQUEEZY_VARIANT_ID_ENTERPRISE=your_enterprise_variant_id

# ═══════════════════════════════════════════════════════════════
# 🧠 AI CONFIGURATION (Required for test generation)
# ═══════════════════════════════════════════════════════════════
OPENAI_API_KEY=sk-your-openai-api-key-here
OPENAI_MODEL=gpt-4
OPENAI_MAX_TOKENS=2000
OPENAI_TEMPERATURE=0.3

# ═══════════════════════════════════════════════════════════════
# ⚙️  BASIC CONFIGURATION
# ═══════════════════════════════════════════════════════════════
NODE_ENV=development
PORT=8000
LOG_LEVEL=info

# ═══════════════════════════════════════════════════════════════
# 🛡️  SECURITY CONFIGURATION
# ═══════════════════════════════════════════════════════════════
RATE_LIMIT_WINDOW=15
RATE_LIMIT_MAX=100

# ═══════════════════════════════════════════════════════════════
# 🚀 FEATURES CONFIGURATION
# ═══════════════════════════════════════════════════════════════
ENABLE_RECORDING=true
ENABLE_MOBILE_TESTING=true
ENABLE_WEB_TESTING=true
ENABLE_AI_GENERATION=true
EOF

echo -e "${GREEN}✅ Created environment file at $ENV_FILE${NC}"
echo

# 1. SUPABASE DATABASE SETUP
echo -e "${BLUE}🗄️  STEP 1: SUPABASE DATABASE SETUP (FREE)${NC}"
echo -e "${YELLOW}Supabase provides a free PostgreSQL database perfect for Questro.${NC}"
echo
echo "What we'll do:"
echo "• Open Supabase website"
echo "• Help you create a free account"
echo "• Get your database connection string"
echo
wait_for_user

open_url "https://supabase.com"
echo
echo -e "${CYAN}Follow these steps in Supabase:${NC}"
echo "1. Click 'Start your project'"
echo "2. Sign up with GitHub (recommended)"
echo "3. Create a new project (choose any name like 'questro-db')"
echo "4. Wait 2-3 minutes for database to be ready"
echo "5. Go to Settings → Database"
echo "6. Copy the 'Connection string' under 'Connection parameters'"
echo
echo -e "${YELLOW}The connection string looks like:${NC}"
echo "postgresql://postgres:[YOUR-PASSWORD]@db.[PROJECT-REF].supabase.co:5432/postgres"
echo
wait_for_user

get_input "📋 Paste your Supabase connection string here:" DATABASE_URL
sed -i.bak "s|DATABASE_URL=.*|DATABASE_URL=$DATABASE_URL|g" "$ENV_FILE"
echo -e "${GREEN}✅ Database URL configured!${NC}"
echo

# 2. LEMONSQUEEZY PAYMENT SETUP
echo -e "${BLUE}🍋 STEP 2: LEMONSQUEEZY PAYMENT SETUP (BETTER THAN STRIPE!)${NC}"
echo -e "${YELLOW}LemonSqueezy handles payments + taxes automatically - perfect for SaaS${NC}"
echo
echo "Why LemonSqueezy > Stripe for SaaS:"
echo "• Handles ALL tax compliance (VAT, GST, etc.)"
echo "• Built specifically for SaaS"
echo "• 5% + 50¢ vs Stripe 2.9% + 30¢ + tax headaches"
echo "• They are the Merchant of Record (less legal work!)"
echo
wait_for_user

open_url "https://lemonsqueezy.com"
echo
echo -e "${CYAN}Follow these steps in LemonSqueezy:${NC}"
echo "1. Click 'Get Started' (FREE account)"
echo "2. Complete onboarding"
echo "3. Create your first store"
echo "4. Go to Settings → API"
echo "5. Create API key"
echo
wait_for_user

get_input "📋 Paste your LemonSqueezy API Key:" LEMONSQUEEZY_API_KEY
get_input "📋 What's your Store ID? (found in store settings):" LEMONSQUEEZY_STORE_ID

sed -i.bak "s|LEMONSQUEEZY_API_KEY=.*|LEMONSQUEEZY_API_KEY=$LEMONSQUEEZY_API_KEY|g" "$ENV_FILE"
sed -i.bak "s|LEMONSQUEEZY_STORE_ID=.*|LEMONSQUEEZY_STORE_ID=$LEMONSQUEEZY_STORE_ID|g" "$ENV_FILE"
echo -e "${GREEN}✅ LemonSqueezy configured!${NC}"
echo -e "${YELLOW}💡 We'll set up products during deployment${NC}"
echo

# 3. OPENAI API SETUP
echo -e "${BLUE}🧠 STEP 3: OPENAI API SETUP (\$5 minimum)${NC}"
echo -e "${YELLOW}OpenAI powers the AI test generation - this is what makes Questro special!${NC}"
echo
echo "What we'll do:"
echo "• Open OpenAI platform"
echo "• Add \$5 credit (minimum)"
echo "• Get your API key"
echo
wait_for_user

open_url "https://platform.openai.com"
echo
echo -e "${CYAN}Follow these steps in OpenAI:${NC}"
echo "1. Sign up / Sign in to OpenAI"
echo "2. Go to 'API' section"
echo "3. Add \$5 credit in 'Billing' (this will last months)"
echo "4. Go to 'API keys'"
echo "5. Click 'Create new secret key'"
echo "6. Copy the key (starts with sk-...)"
echo
echo -e "${YELLOW}API key looks like: sk-...${NC}"
echo
wait_for_user

get_input "📋 Paste your OpenAI API key:" OPENAI_API_KEY
sed -i.bak "s|OPENAI_API_KEY=.*|OPENAI_API_KEY=$OPENAI_API_KEY|g" "$ENV_FILE"
echo -e "${GREEN}✅ OpenAI API configured!${NC}"
echo

# 4. EMAIL SETUP
echo -e "${BLUE}📧 STEP 4: EMAIL CONFIGURATION${NC}"
echo -e "${YELLOW}Choose your email provider for user verification emails:${NC}"
echo
echo "1. Gmail (Easiest - use app password)"
echo "2. SendGrid (Professional)"
echo "3. Custom SMTP"
echo

get_input "Choose option (1-3) [1]:" EMAIL_CHOICE
EMAIL_CHOICE=${EMAIL_CHOICE:-1}

case $EMAIL_CHOICE in
    1)
        echo -e "${CYAN}Gmail Setup:${NC}"
        echo "1. Go to Google Account settings"
        echo "2. Enable 2-factor authentication"
        echo "3. Generate app password for 'Mail'"
        echo "4. Use that password (not your regular password)"
        echo
        wait_for_user
        
        get_input "📧 Your Gmail address:" SMTP_USER
        get_input "🔑 Your Gmail app password:" SMTP_PASS
        get_input "📤 From email address (can be same as Gmail):" FROM_EMAIL
        
        sed -i.bak "s|EMAIL_PROVIDER=.*|EMAIL_PROVIDER=smtp|g" "$ENV_FILE"
        sed -i.bak "s|SMTP_USER=.*|SMTP_USER=$SMTP_USER|g" "$ENV_FILE"
        sed -i.bak "s|SMTP_PASS=.*|SMTP_PASS=$SMTP_PASS|g" "$ENV_FILE"
        sed -i.bak "s|FROM_EMAIL=.*|FROM_EMAIL=$FROM_EMAIL|g" "$ENV_FILE"
        ;;
    2)
        echo -e "${CYAN}SendGrid Setup:${NC}"
        open_url "https://signup.sendgrid.com/"
        echo "1. Sign up for SendGrid free account"
        echo "2. Go to Settings → API Keys"
        echo "3. Create new API key"
        echo
        wait_for_user
        
        get_input "🔑 SendGrid API Key:" SENDGRID_API_KEY
        get_input "📤 From email address:" FROM_EMAIL
        
        sed -i.bak "s|EMAIL_PROVIDER=.*|EMAIL_PROVIDER=sendgrid|g" "$ENV_FILE"
        echo "SENDGRID_API_KEY=$SENDGRID_API_KEY" >> "$ENV_FILE"
        sed -i.bak "s|FROM_EMAIL=.*|FROM_EMAIL=$FROM_EMAIL|g" "$ENV_FILE"
        ;;
    *)
        echo -e "${YELLOW}Keeping SMTP configuration - update manually if needed${NC}"
        ;;
esac

echo -e "${GREEN}✅ Email configuration complete!${NC}"
echo

# 5. GENERATE JWT SECRETS
echo -e "${BLUE}🔐 STEP 5: GENERATING SECURITY KEYS${NC}"
echo -e "${YELLOW}Creating secure JWT secrets for authentication...${NC}"

JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || date +%s | sha256sum | head -c 32)
JWT_REFRESH_SECRET=$(openssl rand -base64 32 2>/dev/null || date +%s%N | sha256sum | head -c 32)

sed -i.bak "s|JWT_SECRET=.*|JWT_SECRET=$JWT_SECRET|g" "$ENV_FILE"
sed -i.bak "s|JWT_REFRESH_SECRET=.*|JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET|g" "$ENV_FILE"

echo -e "${GREEN}✅ Security keys generated!${NC}"
echo

# 6. FRONTEND ENVIRONMENT
echo -e "${BLUE}🌐 STEP 6: FRONTEND CONFIGURATION${NC}"
cat > "frontend/.env" << EOF
# Questro Frontend Configuration
VITE_API_URL=http://localhost:8000
VITE_LEMONSQUEEZY_STORE_URL=https://questro.lemonsqueezy.com
VITE_APP_NAME=Questro
VITE_APP_DESCRIPTION=The World's Most Comprehensive Test Automation Platform
EOF

echo -e "${GREEN}✅ Frontend environment configured!${NC}"
echo

# 7. CONFIGURATION SUMMARY
echo -e "${PURPLE}"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                 SETUP COMPLETE! 🎉                      ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "${GREEN}✅ Configuration Summary:${NC}"
echo "• Database: Supabase configured"
echo "• Payments: LemonSqueezy configured" 
echo "• AI: OpenAI configured"
echo "• Email: Configured"
echo "• Security: JWT secrets generated"
echo "• Frontend: Environment ready"
echo

echo -e "${BLUE}📁 Files created/updated:${NC}"
echo "• backend/.env - Main configuration"
echo "• frontend/.env - Frontend configuration"
echo "• backend/.env.backup.* - Backup of previous config (if any)"
echo

echo -e "${YELLOW}🔧 Next Steps:${NC}"
echo "1. Run: ./scripts/test-local.sh to test locally"
echo "2. Run: ./scripts/deploy-production.sh to deploy"
echo "3. Run: ./scripts/marketing-launch.sh to start making money"
echo

echo -e "${CYAN}💡 Pro Tip:${NC}"
echo "Keep your .env file secure and never commit it to version control!"
echo

echo -e "${GREEN}Ready to make money with Questro! 💰${NC}"
echo "Run the next script: ./scripts/test-local.sh"