/**
 * Render the hardened generated server's source files.
 * Output server:
 *  - loads tools from tools.json (single source of truth)
 *  - Object.freeze's the list at startup
 *  - recomputes SHA-256 over canonical tools and asserts against the manifest
 *  - denies any fetch to a host not in mcp-manifest.json:egress
 *  - exposes notifyToolsListChanged() — never silently swaps
 */

export function renderHardenedIndex(name: string, version: string): string {
  return `#!/usr/bin/env node
/**
 * ${name} - Hardened MCP Server (generated by MCPOverflow)
 * Frozen tool list, signed manifest, declared egress.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { tools, executeTool, getAggregateHash } from "./tools.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const manifestPath = join(__dirname, "..", "mcp-manifest.json");
const manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));

const liveHash = await getAggregateHash();
if (liveHash !== manifest.aggregateHash) {
  console.error(\`[hardened] tool list drift detected — refusing to start. manifest=\${manifest.aggregateHash} live=\${liveHash}\`);
  process.exit(2);
}

const server = new Server(
  { name: "${name}", version: "${version}" },
  { capabilities: { tools: { listChanged: true } } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools }));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  try {
    const result = await executeTool(name, args || {});
    return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
  } catch (error) {
    return {
      content: [{ type: "text", text: \`Error: \${(error as Error).message}\` }],
      isError: true,
    };
  }
});

// Tool list is frozen. If you must change it, call this AND re-sign the manifest.
export async function notifyToolsListChanged(): Promise<void> {
  await server.notification({ method: "notifications/tools/list_changed" });
}

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("${name} hardened MCP server running on stdio");
}

main().catch((err) => { console.error(err); process.exit(1); });
`
}

export function renderHardenedTools(): string {
  return `/**
 * Hardened tool registry — loaded ONCE from tools.json, frozen, and re-hashed
 * at startup. The handler returns the same object on every tools/list call.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { webcrypto as crypto } from "node:crypto";
import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import { executors } from "./executors.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const toolsPath = join(__dirname, "..", "tools.json");
const raw = JSON.parse(readFileSync(toolsPath, "utf-8")) as Tool[];

export const tools: ReadonlyArray<Tool> = Object.freeze(raw.map((t) => Object.freeze(t)));

function canonicalize(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return "[" + value.map(canonicalize).join(",") + "]";
  const keys = Object.keys(value as Record<string, unknown>).sort();
  return "{" + keys.map((k) => JSON.stringify(k) + ":" + canonicalize((value as Record<string, unknown>)[k])).join(",") + "}";
}

let cachedAggregate: string | null = null;
export async function getAggregateHash(): Promise<string> {
  if (cachedAggregate) return cachedAggregate;
  const ordered = [...tools]
    .map((t) => ({ name: t.name, description: t.description, inputSchema: t.inputSchema }))
    .sort((a, b) => a.name.localeCompare(b.name));
  const bytes = new TextEncoder().encode(canonicalize(ordered));
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  const hex = [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
  cachedAggregate = "sha256:" + hex;
  return cachedAggregate;
}

export async function executeTool(name: string, args: Record<string, unknown>): Promise<unknown> {
  const fn = executors[name];
  if (!fn) throw new Error(\`Unknown tool: \${name}\`);
  return fn(args);
}
`
}
