/**
 * FinSavvy Shield - Unified Authentication
 * 
 * Shared JWT token validation that works with both QuantumBeam and PipeWarden.
 * Tokens generated by either service can be validated by the other.
 */

import { sha256 } from '@noble/hashes/sha256';
import { hmac } from '@noble/hashes/hmac';

// Unified JWT Claims structure - compatible with QuantumBeam Go backend
export interface UnifiedJWTClaims {
    user_id: string;
    email: string;
    role: string;
    tenant_id?: string;
    subscription_tier?: 'free' | 'startup' | 'growth' | 'enterprise';
    iat: number;
    exp: number;
    iss: string;
    aud: string;
    sub: string;
}

// Unified API Key structure
export interface UnifiedAPIKey {
    key_id: string;
    user_id: string;
    tier: 'free' | 'startup' | 'growth' | 'enterprise';
    rate_limit: number;
    is_active: boolean;
    created_at: number;
    expires_at?: number;
}

/**
 * Unified Auth Service
 * Compatible with both QuantumBeam (Go) and PipeWarden (TypeScript)
 */
export class UnifiedAuthService {
    private secretKey: string;
    private issuer: string;
    private audience: string;

    constructor(config: {
        secretKey: string;
        issuer?: string;
        audience?: string;
    }) {
        this.secretKey = config.secretKey;
        this.issuer = config.issuer || 'finsavvy-shield';
        this.audience = config.audience || 'finsavvy-api';
    }

    /**
     * Generate a JWT token compatible with QuantumBeam backend
     */
    generateToken(claims: Omit<UnifiedJWTClaims, 'iat' | 'exp' | 'iss' | 'aud'>, expiresInSeconds: number = 3600): string {
        const now = Math.floor(Date.now() / 1000);

        const fullClaims: UnifiedJWTClaims = {
            ...claims,
            sub: claims.user_id,
            iat: now,
            exp: now + expiresInSeconds,
            iss: this.issuer,
            aud: this.audience,
        };

        const header = { alg: 'HS256', typ: 'JWT' };
        const encodedHeader = this.base64UrlEncode(JSON.stringify(header));
        const encodedPayload = this.base64UrlEncode(JSON.stringify(fullClaims));

        const signature = this.sign(`${encodedHeader}.${encodedPayload}`);

        return `${encodedHeader}.${encodedPayload}.${signature}`;
    }

    /**
     * Verify a JWT token - works with tokens from QuantumBeam or PipeWarden
     */
    verifyToken(token: string): UnifiedJWTClaims | null {
        try {
            const parts = token.split('.');
            if (parts.length !== 3) {
                throw new Error('Invalid token format');
            }

            const [header, payload, signature] = parts;

            // Verify signature
            const expectedSignature = this.sign(`${header}.${payload}`);
            if (signature !== expectedSignature) {
                throw new Error('Invalid signature');
            }

            // Decode and validate claims
            const claims = JSON.parse(this.base64UrlDecode(payload)) as UnifiedJWTClaims;

            const now = Math.floor(Date.now() / 1000);
            if (claims.exp < now) {
                throw new Error('Token expired');
            }

            return claims;
        } catch (error) {
            console.error('Token verification failed:', error);
            return null;
        }
    }

    /**
     * Generate a secure API key with prefix
     */
    generateAPIKey(userId: string, tier: UnifiedAPIKey['tier']): { key: string; keyData: UnifiedAPIKey } {
        const keyId = this.generateId();
        const rawKey = this.generateId() + this.generateId();
        const prefix = tier === 'enterprise' ? 'fs_live' : 'fs_test';
        const key = `${prefix}_${rawKey}`;

        const keyData: UnifiedAPIKey = {
            key_id: keyId,
            user_id: userId,
            tier,
            rate_limit: this.getRateLimitForTier(tier),
            is_active: true,
            created_at: Date.now(),
        };

        return { key, keyData };
    }

    /**
     * Hash an API key for storage (never store raw keys)
     */
    hashAPIKey(key: string): string {
        const encoder = new TextEncoder();
        const data = encoder.encode(key);
        const hashArray = sha256(data);
        return Array.from(hashArray as Uint8Array)
            .map((b: number) => b.toString(16).padStart(2, '0'))
            .join('');
    }

    // Private helpers
    private sign(data: string): string {
        const encoder = new TextEncoder();
        const keyData = encoder.encode(this.secretKey);
        const messageData = encoder.encode(data);

        // Use proper HMAC-SHA256
        const signature = hmac(sha256, keyData, messageData);
        return this.base64UrlEncode(String.fromCharCode(...signature));
    }

    private base64UrlEncode(str: string): string {
        return btoa(str)
            .replace(/\+/g, '-')
            .replace(/\//g, '_')
            .replace(/=/g, '');
    }

    private base64UrlDecode(str: string): string {
        str = str.replace(/-/g, '+').replace(/_/g, '/');
        while (str.length % 4) str += '=';
        return atob(str);
    }

    private generateId(): string {
        const array = new Uint8Array(16);
        crypto.getRandomValues(array);
        return Array.from(array).map(b => b.toString(16).padStart(2, '0')).join('');
    }

    private getRateLimitForTier(tier: UnifiedAPIKey['tier']): number {
        switch (tier) {
            case 'free': return 100;      // 100 req/min
            case 'startup': return 1000;  // 1000 req/min
            case 'growth': return 5000;   // 5000 req/min
            case 'enterprise': return 50000; // 50000 req/min
            default: return 100;
        }
    }
}

/**
 * Middleware factory for Hono apps
 */
export function createAuthMiddleware(authService: UnifiedAuthService) {
    return async (c: any, next: any) => {
        const authHeader = c.req.header('Authorization');

        if (!authHeader) {
            return c.json({ error: 'Missing authorization header' }, 401);
        }

        // Support both Bearer tokens and API keys
        if (authHeader.startsWith('Bearer ')) {
            const token = authHeader.slice(7);
            const claims = authService.verifyToken(token);

            if (!claims) {
                return c.json({ error: 'Invalid or expired token' }, 401);
            }

            c.set('user', claims);
            c.set('authType', 'jwt');
        } else if (authHeader.startsWith('ApiKey ') || authHeader.startsWith('fs_')) {
            const apiKey = authHeader.startsWith('ApiKey ') ? authHeader.slice(7) : authHeader;
            c.set('apiKeyHash', authService.hashAPIKey(apiKey));
            c.set('authType', 'apikey');
        } else {
            return c.json({ error: 'Invalid authorization format' }, 401);
        }

        await next();
    };
}

// Export singleton for shared use
export const sharedAuthConfig = {
    issuer: 'finsavvy-shield',
    audience: 'finsavvy-api',
    accessTokenTTL: 3600,      // 1 hour
    refreshTokenTTL: 604800,   // 7 days
};

export default UnifiedAuthService;
