/** Public/unauthenticated read endpoints */
export const publicSection = {
  title: 'Public Endpoints',
  description: 'Unauthenticated public endpoints',
  endpoints: [
    {
      method: 'GET',
      path: '/health',
      auth: 'none',
      description: 'API health check',
      response: '{ status: healthy }',
    },
    {
      method: 'GET',
      path: '/api/platform/health',
      auth: 'none',
      description: 'Detailed platform health metrics',
      response: '{ status, components }',
    },
    {
      method: 'GET',
      path: '/api/badges/:instanceId/security-score',
      auth: 'none',
      description: 'SVG badge with security score',
      response: 'SVG image (image/svg+xml)',
    },
    {
      method: 'GET',
      path: '/api/badges/:instanceId/security-score.json',
      auth: 'none',
      description: 'Shields.io JSON endpoint for badge embedding',
      response: '{ schemaVersion, label, message, color }',
    },
    {
      method: 'GET',
      path: '/api/threats/live',
      auth: 'none',
      description: 'Live threat feed for public dashboard',
      response: { data: 'Threat[]' },
    },
    {
      method: 'GET',
      path: '/api/achievements/:instanceId/:slug',
      auth: 'none',
      description: 'Public achievement card (shareable)',
      response: { achievement: 'Achievement' },
    },
    {
      method: 'POST',
      path: '/api/trust/events',
      auth: 'none',
      description: 'Submit trust funnel analytics events',
      requestBody: { event: 'string', metadata: 'object?' },
      response: '{ received: true }',
    },
    {
      method: 'POST',
      path: '/api/enterprise/contact',
      auth: 'none',
      description: 'Submit enterprise contact/demo request',
      requestBody: { name: 'string', email: 'string', company: 'string', message: 'string' },
      response: { data: '{ id }' },
    },
    {
      method: 'GET',
      path: '/api/score/:instanceId',
      auth: 'bearer',
      description: 'Get security score for an instance',
      response: { data: '{ score, breakdown }' },
    },
    {
      method: 'GET',
      path: '/api/score/trend',
      auth: 'bearer',
      description: 'Get security score trend',
      response: { data: 'TrendEntry[]' },
    },
  ],
} as const;
