/** Admin panel, SCIM provisioning, and platform management endpoints */
export const adminSection = {
  title: 'Admin Panel',
  description: 'Platform administration (requires admin role)',
  endpoints: [
    {
      method: 'GET',
      path: '/api/admin/stats',
      auth: 'admin',
      description: 'Platform-wide statistics (users, instances, events)',
      response: { data: '{ users, instances, orgs, events, leads }' },
    },
    {
      method: 'GET',
      path: '/api/admin/users',
      auth: 'admin',
      description: 'List all users with pagination',
      queryParams: { cursor: 'string?', limit: 'number?' },
      response: { data: 'User[]', nextCursor: 'string?', hasMore: 'boolean' },
    },
    {
      method: 'GET',
      path: '/api/admin/users/:id',
      auth: 'admin',
      description: 'Get user detail',
      response: { data: 'User' },
    },
    {
      method: 'PATCH',
      path: '/api/admin/users/:id',
      auth: 'admin',
      description: 'Update user plan, role, or status',
      requestBody: { plan: 'string?', role: 'string?' },
      response: { data: 'User' },
    },
    {
      method: 'GET',
      path: '/api/admin/organizations',
      auth: 'admin',
      description: 'List all organizations',
      queryParams: { cursor: 'string?', limit: 'number?' },
      response: { data: 'Organization[]', nextCursor: 'string?', hasMore: 'boolean' },
    },
    {
      method: 'PATCH',
      path: '/api/admin/organizations/:id',
      auth: 'admin',
      description: 'Update org plan or limits',
      requestBody: { plan: 'string?', maxInstances: 'number?' },
      response: { data: 'Organization' },
    },
    {
      method: 'DELETE',
      path: '/api/admin/organizations/:id',
      auth: 'admin',
      description: 'Delete org and all resources (requires ?confirm=true)',
      response: 'null (204)',
    },
    {
      method: 'GET',
      path: '/api/admin/instances',
      auth: 'admin',
      description: 'List all instances',
      queryParams: { cursor: 'string?', limit: 'number?' },
      response: { data: 'Instance[]', nextCursor: 'string?', hasMore: 'boolean' },
    },
    {
      method: 'POST',
      path: '/api/admin/instances/:id/stop',
      auth: 'admin',
      description: 'Force stop an instance',
      response: { data: '{ id, status: stopped }' },
    },
    {
      method: 'POST',
      path: '/api/admin/instances/:id/restart',
      auth: 'admin',
      description: 'Force restart an instance',
      response: { data: '{ id, status: provisioning }' },
    },
    {
      method: 'DELETE',
      path: '/api/admin/instances/:id',
      auth: 'admin',
      description: 'Delete an instance',
      response: 'null (204)',
    },
    {
      method: 'GET',
      path: '/api/admin/events',
      auth: 'admin',
      description: 'List all security events',
      queryParams: { severity: 'string?', cursor: 'string?', from: 'ISO date', to: 'ISO date' },
      response: { data: 'SecurityEvent[]', nextCursor: 'string?', hasMore: 'boolean' },
    },
    {
      method: 'GET',
      path: '/api/admin/skills',
      auth: 'admin',
      description: 'List skills pending moderation',
      response: { data: 'Skill[]' },
    },
    {
      method: 'PATCH',
      path: '/api/admin/skills/:id',
      auth: 'admin',
      description: 'Approve or reject a skill',
      requestBody: { action: 'approve | reject', reason: 'string?' },
      response: { data: '{ id, action }' },
    },
    {
      method: 'GET',
      path: '/api/admin/billing',
      auth: 'admin',
      description: 'Revenue overview (MRR, plan distribution)',
      response: { data: '{ mrr, planDistribution, recentSubscriptions }' },
    },
    {
      method: 'GET',
      path: '/api/admin/audit',
      auth: 'admin',
      description: 'Unified audit + security events log',
      queryParams: { source: 'audit|security?', severity: 'string?', from: 'ISO date', to: 'ISO date' },
      response: { data: 'UnifiedEntry[]' },
    },
    {
      method: 'GET',
      path: '/api/admin/audit/export',
      auth: 'admin',
      description: 'Export audit log',
      response: 'File download',
    },
    {
      method: 'GET',
      path: '/api/admin/data-room',
      auth: 'admin',
      description: 'Investor data room metrics',
      response: { data: 'DataRoomMetrics' },
    },
    {
      method: 'GET',
      path: '/api/admin/data-room/export',
      auth: 'admin',
      description: 'Export data room as report',
      response: 'File download',
    },
    {
      method: 'GET',
      path: '/api/metrics/dataroom',
      auth: 'bearer (billing.manage)',
      description: 'Detailed platform metrics for data room',
      response: { data: 'MetricsDataroom' },
    },
  ],
} as const;

