/** Cloud accounts, CSPM, multi-cloud, and SaaS endpoints */
export const cloudAccountSection = {
  title: 'Cloud Accounts',
  description: 'Connect and manage AWS, Azure, and GCP cloud accounts',
  endpoints: [
    {
      method: 'GET',
      path: '/api/cloud/accounts',
      auth: 'bearer',
      description: 'List connected cloud accounts',
      response: { data: 'CloudAccount[]' },
    },
    {
      method: 'POST',
      path: '/api/cloud/accounts',
      auth: 'bearer',
      description: 'Connect a new cloud account (enforces plan limits)',
      requestBody: { provider: 'string (aws|azure|gcp)', credentials: 'object' },
      response: { data: 'CloudAccount' },
    },
    {
      method: 'PATCH',
      path: '/api/cloud/accounts/:id',
      auth: 'bearer',
      description: 'Update cloud account credentials or settings',
      response: { data: 'CloudAccount' },
    },
    {
      method: 'DELETE',
      path: '/api/cloud/accounts/:id',
      auth: 'bearer',
      description: 'Disconnect a cloud account',
      response: 'null (204)',
    },
    {
      method: 'POST',
      path: '/api/cloud/accounts/validate',
      auth: 'bearer',
      description: 'Validate cloud account credentials',
      requestBody: { provider: 'string', credentials: 'object' },
      response: { data: '{ valid, message }' },
    },
    {
      method: 'GET',
      path: '/api/cloud/setup/aws',
      auth: 'bearer',
      description: 'Get AWS setup instructions and IAM role template',
      response: { data: '{ instructions, template }' },
    },
    {
      method: 'GET',
      path: '/api/cloud/setup/azure',
      auth: 'bearer',
      description: 'Get Azure setup instructions',
      response: { data: '{ instructions }' },
    },
    {
      method: 'GET',
      path: '/api/cloud/setup/gcp',
      auth: 'bearer',
      description: 'Get GCP setup instructions',
      response: { data: '{ instructions }' },
    },
  ],
} as const;

export const cspmSection = {
  title: 'Cloud Security (CSPM)',
  description: 'Cloud security posture scanning, findings, and risk',
  endpoints: [
    {
      method: 'POST',
      path: '/api/cloud/accounts/:accountId/scan',
      auth: 'bearer',
      description: 'Trigger a CSPM scan for a cloud account',
      response: { data: '{ scanId, status }' },
    },
    {
      method: 'GET',
      path: '/api/cloud/accounts/:accountId/scans',
      auth: 'bearer',
      description: 'List scan results for a cloud account',
      response: { data: 'Scan[]' },
    },
    {
      method: 'GET',
      path: '/api/cloud/scans/:scanId/findings',
      auth: 'bearer',
      description: 'List findings from a specific scan',
      response: { data: 'Finding[]' },
    },
    {
      method: 'GET',
      path: '/api/cloud/findings',
      auth: 'bearer',
      description: 'List all CSPM findings across accounts',
      queryParams: { severity: 'string?', status: 'string?' },
      response: { data: 'Finding[]' },
    },
    {
      method: 'GET',
      path: '/api/cloud/findings/summary',
      auth: 'bearer',
      description: 'Get aggregated finding summary by severity',
      response: { data: '{ critical, high, medium, low }' },
    },
    {
      method: 'PATCH',
      path: '/api/cloud/findings/:id/mute',
      auth: 'bearer',
      description: 'Mute a finding (suppress from dashboards)',
      response: { data: 'Finding' },
    },
    {
      method: 'PATCH',
      path: '/api/cloud/findings/:id/resolve',
      auth: 'bearer',
      description: 'Mark a finding as resolved',
      response: { data: 'Finding' },
    },
    {
      method: 'GET',
      path: '/api/cloud/risk',
      auth: 'bearer',
      description: 'Get overall cloud risk score',
      response: { data: '{ score, breakdown }' },
    },
    {
      method: 'GET',
      path: '/api/cloud/risk/:accountId',
      auth: 'bearer',
      description: 'Get risk score for a specific account',
      response: { data: '{ score }' },
    },
    {
      method: 'GET',
      path: '/api/cloud/drift/:accountId',
      auth: 'bearer',
      description: 'Get configuration drift for an account',
      response: { data: 'DriftEvent[]' },
    },
  ],
} as const;

