/** AI-powered query, triage, chat, and insights endpoints */
export const aiSection = {
  title: 'AI Features',
  description: 'AI-powered security analysis, chat, and triage',
  endpoints: [
    {
      method: 'POST',
      path: '/api/ai/query',
      auth: 'bearer',
      description: 'Natural language query over security data',
      requestBody: { query: 'string' },
      response: { data: '{ answer, sources, sql }' },
    },
    {
      method: 'POST',
      path: '/api/ai/triage',
      auth: 'bearer',
      description: 'AI triage a single security finding',
      requestBody: { finding: 'object' },
      response: { data: '{ severity, recommendation, confidence }' },
    },
    {
      method: 'POST',
      path: '/api/ai/triage/batch',
      auth: 'bearer',
      description: 'Batch triage multiple findings',
      requestBody: { findings: 'object[]' },
      response: { data: 'TriageResult[]' },
    },
    {
      method: 'POST',
      path: '/api/ai/chat',
      auth: 'bearer',
      description: 'Chat with the AI security assistant (rate limited)',
      requestBody: { message: 'string', context: 'object?' },
      response: { data: '{ response, usage }' },
    },
    {
      method: 'POST',
      path: '/api/ai/explain',
      auth: 'bearer',
      description: 'Get AI explanation for a security finding',
      requestBody: { finding: 'object' },
      response: { data: '{ explanation, remediation }' },
    },
    {
      method: 'POST',
      path: '/api/ai/compliance-narrative',
      auth: 'bearer',
      description: 'Generate compliance narrative from evidence',
      requestBody: { evidence: 'object[]' },
      response: { data: '{ narrative }' },
    },
    {
      method: 'POST',
      path: '/api/ai/classify-risk',
      auth: 'bearer',
      description: 'Classify risk level for an asset or finding',
      requestBody: { item: 'object' },
      response: { data: '{ riskLevel, reasoning }' },
    },
    {
      method: 'GET',
      path: '/api/ai/insights',
      auth: 'bearer',
      description: 'Get AI-generated security insights',
      response: { data: 'Insight[]' },
    },
    {
      method: 'POST',
      path: '/api/ai/insights',
      auth: 'bearer',
      description: 'Generate new AI insights from current data',
      response: { data: 'Insight[]' },
    },
    {
      method: 'PATCH',
      path: '/api/ai/insights/:id',
      auth: 'bearer',
      description: 'Dismiss or acknowledge an insight',
      requestBody: { status: 'string' },
      response: { data: 'Insight' },
    },
    {
      method: 'GET',
      path: '/api/ai/recommendations',
      auth: 'bearer',
      description: 'Get AI recommendations for improving security posture',
      response: { data: 'Recommendation[]' },
    },
  ],
} as const;
