/** Credential vault, rotation, and JIT access endpoints */
export const vaultSection = {
  title: 'Credential Vault',
  description: 'Secret management, rotation, and JIT access',
  endpoints: [
    {
      method: 'GET',
      path: '/api/security/instances/:id/secrets',
      auth: 'bearer',
      description: 'List secrets for an instance (keys only, values masked)',
      response: { data: 'Secret[]' },
    },
    {
      method: 'POST',
      path: '/api/security/instances/:id/secrets',
      auth: 'bearer (vault.write)',
      description: 'Add a secret to an instance vault',
      requestBody: { key: 'string', value: 'string' },
      response: { data: '{ key, createdAt }' },
    },
    {
      method: 'DELETE',
      path: '/api/security/instances/:id/secrets/:key',
      auth: 'bearer (vault.delete)',
      description: 'Remove a secret from the vault',
      response: 'null (204)',
    },
    {
      method: 'GET',
      path: '/api/vault/rotation-policies',
      auth: 'bearer',
      description: 'List secret rotation policies',
      response: { data: 'RotationPolicy[]' },
    },
    {
      method: 'POST',
      path: '/api/vault/rotation-policies',
      auth: 'bearer (vault.write)',
      description: 'Create a rotation policy',
      response: { data: 'RotationPolicy' },
    },
    {
      method: 'DELETE',
      path: '/api/vault/rotation-policies/:id',
      auth: 'bearer (vault.delete)',
      description: 'Delete a rotation policy',
      response: 'null (204)',
    },
    {
      method: 'GET',
      path: '/api/vault/aging',
      auth: 'bearer',
      description: 'Get secret age report for rotation planning',
      response: { data: 'AgingReport[]' },
    },
    {
      method: 'GET',
      path: '/api/vault/rotation-policies/evaluate',
      auth: 'bearer',
      description: 'Evaluate which secrets need rotation',
      response: { data: 'EvaluationResult[]' },
    },
    {
      method: 'GET',
      path: '/api/vault/jit-requests',
      auth: 'bearer',
      description: 'List just-in-time access requests',
      response: { data: 'JitRequest[]' },
    },
    {
      method: 'POST',
      path: '/api/vault/jit-requests',
      auth: 'bearer',
      description: 'Create a JIT access request',
      requestBody: { secretKey: 'string', reason: 'string', duration: 'number' },
      response: { data: 'JitRequest' },
    },
    {
      method: 'PATCH',
      path: '/api/vault/jit-requests/:id/approve',
      auth: 'bearer (vault.write)',
      description: 'Approve a JIT access request',
      response: { data: 'JitRequest' },
    },
    {
      method: 'PATCH',
      path: '/api/vault/jit-requests/:id/deny',
      auth: 'bearer (vault.write)',
      description: 'Deny a JIT access request',
      response: { data: 'JitRequest' },
    },
    {
      method: 'POST',
      path: '/api/vault/jit-requests/expire',
      auth: 'bearer',
      description: 'Expire elapsed JIT access grants',
      response: { data: '{ expired: number }' },
    },
  ],
} as const;
