/** Compliance, policies, vault, and data export endpoints */
export const complianceSection = {
  title: 'Compliance & Reporting',
  description: 'Compliance reports, SOC 2 readiness, and audit exports',
  endpoints: [
    {
      method: 'GET',
      path: '/api/security/instances/:instanceId/compliance-reports',
      auth: 'bearer',
      description: 'List compliance reports for an instance',
      response: { data: 'ComplianceReport[]' },
    },
    {
      method: 'POST',
      path: '/api/security/instances/:instanceId/compliance-reports',
      auth: 'bearer (compliance.generate)',
      description: 'Generate a new compliance report',
      requestBody: { framework: 'string (SOC2|NIST|ISO27001)' },
      response: { data: 'ComplianceReport' },
    },
    {
      method: 'GET',
      path: '/api/security/instances/:instanceId/compliance-reports/:reportId',
      auth: 'bearer',
      description: 'Get a specific compliance report',
      response: { data: 'ComplianceReport' },
    },
    {
      method: 'GET',
      path: '/api/security/instances/:id/compliance-reports/:reportId/export',
      auth: 'bearer',
      description: 'Export compliance report as PDF or CSV',
      response: 'File download',
    },
    {
      method: 'GET',
      path: '/api/security/instances/:id/audit/export',
      auth: 'bearer',
      description: 'Export audit log entries',
      response: 'File download',
    },
    {
      method: 'GET',
      path: '/api/compliance/ai/risk-classification',
      auth: 'bearer',
      description: 'AI-powered risk classification of assets',
      response: { data: 'RiskClassification' },
    },
    {
      method: 'GET',
      path: '/api/compliance/ai/audit-trail',
      auth: 'bearer',
      description: 'Export AI-enriched audit trail',
      queryParams: { from: 'ISO date', to: 'ISO date' },
      response: { data: 'AuditTrailEntry[]' },
    },
    {
      method: 'GET',
      path: '/api/compliance/ai/nist-mapping',
      auth: 'bearer',
      description: 'Map findings to NIST framework controls',
      response: { data: 'NistMapping' },
    },
    {
      method: 'GET',
      path: '/api/compliance/evidence',
      auth: 'bearer (compliance.view)',
      description: 'List compliance evidence artifacts',
      response: { data: 'Evidence[]' },
    },
    {
      method: 'GET',
      path: '/api/soc2',
      auth: 'bearer',
      description: 'SOC 2 readiness dashboard',
      response: { data: '{ controls, readinessScore }' },
    },
    {
      method: 'GET',
      path: '/api/soc2/mappings',
      auth: 'bearer',
      description: 'SOC 2 trust service criteria mappings',
      response: { data: 'Mapping[]' },
    },
    {
      method: 'GET',
      path: '/api/soc2/evidence',
      auth: 'bearer',
      description: 'SOC 2 evidence collection status',
      response: { data: 'Evidence[]' },
    },
    {
      method: 'POST',
      path: '/api/soc2/evidence',
      auth: 'bearer (compliance.generate)',
      description: 'Submit compliance evidence',
      requestBody: { controlId: 'string', type: 'string', content: 'string' },
      response: { data: 'Evidence' },
    },
    {
      method: 'GET',
      path: '/api/soc2/evidence/auto-collect',
      auth: 'bearer',
      description: 'Trigger automatic evidence collection',
      response: { data: '{ collected: number }' },
    },
  ],
} as const;
export const policySection = {
  title: 'Security Policies',
  description: 'Instance-level and agent-level security policies',
  endpoints: [
    {
      method: 'GET',
      path: '/api/security/instances/:instanceId/policies',
      auth: 'bearer',
      description: 'List security policies for an instance',
      response: { data: 'SecurityPolicy[]' },
    },
    {
      method: 'POST',
      path: '/api/security/instances/:instanceId/policies',
      auth: 'bearer (policy.create)',
      description: 'Create a security policy',
      requestBody: { name: 'string', rules: 'Rule[]', severity: 'string' },
      response: { data: 'SecurityPolicy' },
    },
    {
      method: 'PATCH',
      path: '/api/security/instances/:instanceId/policies/:id',
      auth: 'bearer (policy.update)',
      description: 'Update a security policy',
      response: { data: 'SecurityPolicy' },
    },
    {
      method: 'DELETE',
      path: '/api/security/instances/:instanceId/policies/:id',
      auth: 'bearer (policy.delete)',
      description: 'Delete a security policy',
      response: 'null (204)',
    },
    {
      method: 'GET',
      path: '/api/agents/policies',
      auth: 'bearer (agent.policy.read, policyEngine plan)',
      description: 'List agent governance policies',
      response: { data: 'AgentPolicy[]' },
    },
    {
      method: 'POST',
      path: '/api/agents/policies',
      auth: 'bearer (agent.policy.write, policyEngine plan)',
      description: 'Create an agent governance policy',
      response: { data: 'AgentPolicy' },
    },
    {
      method: 'PATCH',
      path: '/api/agents/policies/:id',
      auth: 'bearer (agent.policy.write)',
      description: 'Update an agent governance policy',
      response: { data: 'AgentPolicy' },
    },
    {
      method: 'DELETE',
      path: '/api/agents/policies/:id',
      auth: 'bearer (agent.policy.write)',
      description: 'Delete an agent governance policy',
      response: 'null (204)',
    },
    {
      method: 'GET',
      path: '/api/agents/policies/:id/violations',
      auth: 'bearer (agent.policy.read)',
      description: 'List violations for a specific policy',
      response: { data: 'Violation[]' },
    },
  ],
} as const;
