/** Webhooks, gateway, public, and miscellaneous endpoints */
export const webhookSection = {
  title: 'Webhooks (Inbound)',
  description: 'Webhook endpoints for external service callbacks',
  endpoints: [
    {
      method: 'POST',
      path: '/webhooks/auth',
      auth: 'hmac-signature',
      description: 'Auth webhook for user lifecycle events (created, updated, deleted)',
      response: '{ received: true }',
    },
    {
      method: 'POST',
      path: '/webhooks/lemonsqueezy',
      auth: 'hmac-signature',
      description: 'LemonSqueezy subscription events (created, updated, cancelled)',
      response: '{ received: true }',
    },
    {
      method: 'POST',
      path: '/webhooks/integrations/github',
      auth: 'none',
      description: 'GitHub webhook events (push, PR, issues)',
      response: '{ received: true }',
    },
    {
      method: 'POST',
      path: '/webhooks/integrations/gitlab',
      auth: 'none',
      description: 'GitLab webhook events',
      response: '{ received: true }',
    },
    {
      method: 'POST',
      path: '/webhooks/integrations/:slug',
      auth: 'none',
      description: 'Generic integration webhook endpoint',
      response: '{ received: true }',
    },
  ],
} as const;

export const gatewaySection = {
  title: 'Agent Gateway',
  description: 'Agent-to-API communication (X-Gateway-Token + X-Instance-Id)',
  endpoints: [
    {
      method: 'GET',
      path: '/api/agent/instances/:id/updates',
      auth: 'gateway-token',
      description: 'Check for pending skill updates',
      response: { data: 'Update[]' },
    },
    {
      method: 'GET',
      path: '/api/agent/skills/:slug/:version/package',
      auth: 'gateway-token',
      description: 'Download skill package tar.gz',
      response: 'File download',
    },
    {
      method: 'POST',
      path: '/api/agent/security/instances/:instanceId/events',
      auth: 'gateway-token',
      description: 'Report security events from agent',
      requestBody: { events: 'SecurityEvent[]' },
      response: '{ received: number }',
    },
    {
      method: 'POST',
      path: '/api/agent/security/instances/:instanceId/audit',
      auth: 'gateway-token',
      description: 'Report audit log entries from agent',
      requestBody: { entries: 'AuditEntry[]' },
      response: '{ received: number }',
    },
    {
      method: 'POST',
      path: '/api/agent/security/instances/:instanceId/vulnerability-scans',
      auth: 'gateway-token',
      description: 'Submit vulnerability scan results',
      requestBody: { scan: 'VulnScan' },
      response: '{ scanId }',
    },
    {
      method: 'POST',
      path: '/api/agent/security/instances/:instanceId/network-activity',
      auth: 'gateway-token',
      description: 'Report network connections from agent',
      requestBody: { connections: 'NetworkConnection[]' },
      response: '{ received: number }',
    },
    {
      method: 'POST',
      path: '/api/agent/security/instances/:instanceId/file-baselines',
      auth: 'gateway-token',
      description: 'Submit file integrity baselines',
      response: '{ received: number }',
    },
    {
      method: 'POST',
      path: '/api/agent/security/instances/:instanceId/file-events',
      auth: 'gateway-token',
      description: 'Report file change events',
      response: '{ received: number }',
    },
    {
      method: 'POST',
      path: '/api/agent/security/instances/:instanceId/access-log',
      auth: 'gateway-token',
      description: 'Report access log entries',
      response: '{ received: number }',
    },
    {
      method: 'GET',
      path: '/api/agent/security/instances/:instanceId/policies',
      auth: 'gateway-token',
      description: 'Fetch security policies for enforcement',
      response: { data: 'SecurityPolicy[]' },
    },
    {
      method: 'GET',
      path: '/api/agent/instances/:id/secrets',
      auth: 'gateway-token',
      description: 'Retrieve secrets for agent runtime',
      response: { data: 'Secret[]' },
    },
    {
      method: 'POST',
      path: '/webhooks/agent/health',
      auth: 'gateway-token',
      description: 'Agent heartbeat and health check',
      requestBody: { cpu: 'number', memory: 'number', uptime: 'number' },
      response: '{ received: true }',
    },
    {
      method: 'POST',
      path: '/webhooks/agent/provisioned',
      auth: 'gateway-token',
      description: 'Agent reports provisioning complete',
      response: '{ received: true }',
    },
  ],
} as const;

