/** Instances & Agent management endpoints */
export const instancesSection = {
  title: 'Instances & Agents',
  description: 'Deploy, manage, and monitor agent instances',
  endpoints: [
    {
      method: 'GET',
      path: '/api/instances',
      auth: 'bearer',
      description: 'List all instances for the authenticated user/org',
      response: { data: 'Instance[]' },
    },
    {
      method: 'GET',
      path: '/api/instances/:id',
      auth: 'bearer',
      description: 'Get instance details including health and skills',
      response: { data: 'Instance' },
    },
    {
      method: 'GET',
      path: '/api/instances/:id/health',
      auth: 'bearer',
      description: 'Get cached health metrics for an instance',
      response: { data: '{ status, cpu, memory, uptime }' },
    },
    {
      method: 'POST',
      path: '/api/instances',
      auth: 'bearer (instance.create)',
      description: 'Deploy a new agent instance (enforces plan limits)',
      requestBody: { name: 'string', region: 'string?' },
      response: { data: '{ id, name, status, gatewayToken }' },
    },
    {
      method: 'PATCH',
      path: '/api/instances/:id',
      auth: 'bearer (instance.update)',
      description: 'Update instance name or configuration',
      requestBody: { name: 'string?' },
      response: { data: 'Instance' },
    },
    {
      method: 'POST',
      path: '/api/instances/:id/restart',
      auth: 'bearer (instance.restart)',
      description: 'Restart an agent instance',
      response: { data: '{ id, status }' },
    },
    {
      method: 'DELETE',
      path: '/api/instances/:id',
      auth: 'bearer (instance.delete)',
      description: 'Destroy an agent instance and clean up resources',
      response: 'null (204)',
    },
    {
      method: 'GET',
      path: '/api/instances/:id/skills',
      auth: 'bearer',
      description: 'List skills installed on an instance',
      response: { data: 'SkillInstallation[]' },
    },
    {
      method: 'POST',
      path: '/api/instances/:id/skills',
      auth: 'bearer (skill.install)',
      description: 'Install a skill on an instance',
      requestBody: { skillId: 'string' },
      response: { data: 'SkillInstallation' },
    },
    {
      method: 'DELETE',
      path: '/api/instances/:id/skills/:skillId',
      auth: 'bearer (skill.install)',
      description: 'Uninstall a skill from an instance',
      response: 'null (204)',
    },
  ],
} as const;

/** Agent Registry (NHI) endpoints */
export const agentRegistrySection = {
  title: 'Agent Registry',
  description: 'Non-human identity inventory and risk tracking',
  endpoints: [
    {
      method: 'GET',
      path: '/api/registry',
      auth: 'bearer',
      description: 'List all registered agents for the user',
      response: { data: 'Agent[]' },
    },
    {
      method: 'POST',
      path: '/api/registry',
      auth: 'bearer',
      description: 'Register a new agent identity',
      requestBody: { name: 'string', type: 'string', metadata: 'object?' },
      response: { data: 'Agent' },
    },
    {
      method: 'GET',
      path: '/api/registry/:id',
      auth: 'bearer',
      description: 'Get agent detail including risk score',
      response: { data: 'Agent' },
    },
    {
      method: 'PATCH',
      path: '/api/registry/:id/risk',
      auth: 'bearer',
      description: 'Update agent risk score',
      requestBody: { riskScore: 'number (0-100)' },
      response: { data: '{ id, riskScore }' },
    },
    {
      method: 'POST',
      path: '/api/agents/suspend/:agentId',
      auth: 'bearer',
      description: 'Suspend an agent',
      response: { data: '{ status: suspended }' },
    },
    {
      method: 'POST',
      path: '/api/agents/resume/:agentId',
      auth: 'bearer',
      description: 'Resume a suspended agent',
      response: { data: '{ status: active }' },
    },
    {
      method: 'POST',
      path: '/api/agents/quarantine/:agentId',
      auth: 'bearer',
      description: 'Quarantine a compromised agent',
      response: { data: '{ status: quarantined }' },
    },
  ],
} as const;
