import { Page } from 'puppeteer';
import { AIAssertion, ElementInfo, RecordedAction } from '../types/recording.js';
import { logger } from '../utils/logger.js';
import { AIService } from './AIService.js';

export class AssertionSuggestionService {
  private aiService: AIService;

  constructor() {
    this.aiService = new AIService();
  }

  async generateAssertionSuggestions(
    page: Page,
    action: RecordedAction,
    context: {
      previousActions: RecordedAction[];
      pageContent?: string;
      userIntent?: string;
    }
  ): Promise<AIAssertion[]> {
    const suggestions: AIAssertion[] = [];

    try {
      // Get current page state
      const pageState = await this.capturePageState(page);
      
      // Generate different types of assertions based on action type
      switch (action.type) {
        case 'click':
          suggestions.push(...await this.generateClickAssertions(page, action, pageState, context));
          break;
        case 'input':
          suggestions.push(...await this.generateInputAssertions(page, action, pageState, context));
          break;
        case 'navigation':
          suggestions.push(...await this.generateNavigationAssertions(page, action, pageState, context));
          break;
        case 'submit':
          suggestions.push(...await this.generateSubmitAssertions(page, action, pageState, context));
          break;
      }

      // Add general page-level assertions
      suggestions.push(...await this.generatePageLevelAssertions(page, action, pageState, context));

      // Use AI to enhance and prioritize suggestions
      const enhancedSuggestions = await this.enhanceWithAI(suggestions, action, context);

      return enhancedSuggestions.sort((a, b) => b.confidence - a.confidence);
    } catch (error) {
      logger.error(`Failed to generate assertion suggestions: ${error}`);
      return [];
    }
  }

  private async capturePageState(page: Page): Promise<any> {
    return await page.evaluate(() => {
      return {
        url: window.location.href,
        title: document.title,
        visibleText: document.body.innerText.substring(0, 1000),
        forms: Array.from(document.forms).map(form => ({
          action: form.action,
          method: form.method,
          elements: form.elements.length
        })),
        buttons: Array.from(document.querySelectorAll('button, input[type="button"], input[type="submit"]')).map(btn => ({
          text: btn.textContent?.trim(),
          type: (btn as HTMLInputElement).type,
          disabled: (btn as HTMLButtonElement).disabled
        })),
        inputs: Array.from(document.querySelectorAll('input, textarea, select')).map(input => ({
          type: (input as HTMLInputElement).type,
          name: (input as HTMLInputElement).name,
          value: (input as HTMLInputElement).value,
          placeholder: (input as HTMLInputElement).placeholder,
          required: (input as HTMLInputElement).required
        })),
        errors: Array.from(document.querySelectorAll('.error, .alert-danger, [role="alert"]')).map(error => ({
          text: error.textContent?.trim(),
          visible: (error as HTMLElement).offsetParent !== null
        })),
        success: Array.from(document.querySelectorAll('.success, .alert-success, .notification-success')).map(success => ({
          text: success.textContent?.trim(),
          visible: (success as HTMLElement).offsetParent !== null
        }))
      };
    });
  }

  private async generateClickAssertions(
    page: Page,
    action: RecordedAction,
    pageState: any,
    context: any
  ): Promise<AIAssertion[]> {
    const assertions: AIAssertion[] = [];

    // Check if click resulted in navigation
    if (pageState.url !== action.url) {
      assertions.push({
        type: 'text',
        selector: 'body',
        expected: 'url_changed',
        confidence: 0.9,
        reasoning: 'Click action resulted in navigation, should verify URL change',
        autoGenerated: true
      });
    }

    // Check for modal or popup appearance
    const modals = await page.evaluate(() => {
      return Array.from(document.querySelectorAll('.modal, .popup, .dialog, [role="dialog"]'))
        .filter(modal => (modal as HTMLElement).offsetParent !== null)
        .map(modal => ({
          selector: modal.className ? `.${modal.className.split(' ')[0]}` : modal.tagName.toLowerCase(),
          text: modal.textContent?.trim().substring(0, 100)
        }));
    });

    modals.forEach(modal => {
      assertions.push({
        type: 'visual',
        selector: modal.selector,
        expected: 'visible',
        confidence: 0.85,
        reasoning: 'Modal or dialog appeared after click, should verify visibility',
        autoGenerated: true
      });
    });

    // Check for form submission or validation
    if (pageState.errors.some((error: any) => error.visible)) {
      assertions.push({
        type: 'text',
        selector: '.error, .alert-danger, [role="alert"]',
        expected: 'error_message_displayed',
        confidence: 0.8,
        reasoning: 'Error message appeared after click, should verify error handling',
        autoGenerated: true
      });
    }

    return assertions;
  }

  private async generateInputAssertions(
    page: Page,
    action: RecordedAction,
    pageState: any,
    context: any
  ): Promise<AIAssertion[]> {
    const assertions: AIAssertion[] = [];

    if (typeof action.selector === 'string') {
      // Verify input value was set correctly
      assertions.push({
        type: 'attribute',
        selector: action.selector,
        expected: { attribute: 'value', value: action.text },
        confidence: 0.95,
        reasoning: 'Input value should match what was typed',
        autoGenerated: true
      });

      // Check for real-time validation
      const hasValidation = await page.evaluate((selector) => {
        const element = document.querySelector(selector) as HTMLInputElement;
        if (!element) return false;
        
        return element.checkValidity && !element.checkValidity();
      }, action.selector);

      if (hasValidation) {
        assertions.push({
          type: 'attribute',
          selector: action.selector,
          expected: { attribute: 'aria-invalid', value: 'true' },
          confidence: 0.7,
          reasoning: 'Input has validation, should check validation state',
          autoGenerated: true
        });
      }
    }

    return assertions;
  }

  private async generateNavigationAssertions(
    page: Page,
    action: RecordedAction,
    pageState: any,
    context: any
  ): Promise<AIAssertion[]> {
    const assertions: AIAssertion[] = [];

    // Verify URL change
    assertions.push({
      type: 'text',
      selector: 'body',
      expected: { url: pageState.url },
      confidence: 0.95,
      reasoning: 'Navigation should result in correct URL',
      autoGenerated: true
    });

    // Verify page title
    if (pageState.title) {
      assertions.push({
        type: 'text',
        selector: 'title',
        expected: pageState.title,
        confidence: 0.8,
        reasoning: 'Page should have correct title after navigation',
        autoGenerated: true
      });
    }

    // Check for loading states
    const hasLoader = await page.evaluate(() => {
      return !!document.querySelector('.loading, .spinner, .loader, [aria-busy="true"]');
    });

    if (hasLoader) {
      assertions.push({
        type: 'visual',
        selector: '.loading, .spinner, .loader, [aria-busy="true"]',
        expected: 'hidden',
        confidence: 0.7,
        reasoning: 'Loading indicator should disappear after navigation completes',
        autoGenerated: true
      });
    }

    return assertions;
  }

  private async generateSubmitAssertions(
    page: Page,
    action: RecordedAction,
    pageState: any,
    context: any
  ): Promise<AIAssertion[]> {
    const assertions: AIAssertion[] = [];

    // Check for success messages
    if (pageState.success.some((success: any) => success.visible)) {
      assertions.push({
        type: 'visual',
        selector: '.success, .alert-success, .notification-success',
        expected: 'visible',
        confidence: 0.9,
        reasoning: 'Form submission should show success message',
        autoGenerated: true
      });
    }

    // Check for error messages
    if (pageState.errors.some((error: any) => error.visible)) {
      assertions.push({
        type: 'visual',
        selector: '.error, .alert-danger, [role="alert"]',
        expected: 'visible',
        confidence: 0.85,
        reasoning: 'Form validation errors should be displayed',
        autoGenerated: true
      });
    }

    // Check for form reset or redirect
    const formCleared = await page.evaluate(() => {
      const forms = Array.from(document.forms);
      return forms.some(form => {
        const inputs = Array.from(form.querySelectorAll('input, textarea')) as HTMLInputElement[];
        return inputs.every(input => !input.value || input.type === 'hidden');
      });
    });

    if (formCleared) {
      assertions.push({
        type: 'attribute',
        selector: 'form input, form textarea',
        expected: { attribute: 'value', value: '' },
        confidence: 0.7,
        reasoning: 'Form should be cleared after successful submission',
        autoGenerated: true
      });
    }

    return assertions;
  }

  private async generatePageLevelAssertions(
    page: Page,
    action: RecordedAction,
    pageState: any,
    context: any
  ): Promise<AIAssertion[]> {
    const assertions: AIAssertion[] = [];

    // Performance assertions
    const performanceMetrics = await page.evaluate(() => {
      const navigation = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;
      return {
        loadTime: navigation.loadEventEnd - navigation.loadEventStart,
        domContentLoaded: navigation.domContentLoadedEventEnd - navigation.domContentLoadedEventStart
      };
    });

    if (performanceMetrics.loadTime > 0) {
      assertions.push({
        type: 'performance',
        selector: 'body',
        expected: { loadTime: { lessThan: 5000 } },
        confidence: 0.6,
        reasoning: 'Page should load within reasonable time',
        autoGenerated: true
      });
    }

    // Accessibility assertions
    const accessibilityIssues = await page.evaluate(() => {
      const issues = [];
      
      // Check for images without alt text
      const imagesWithoutAlt = document.querySelectorAll('img:not([alt])');
      if (imagesWithoutAlt.length > 0) {
        issues.push('images_missing_alt');
      }

      // Check for form inputs without labels
      const inputsWithoutLabels = Array.from(document.querySelectorAll('input, textarea, select')).filter(input => {
        const id = (input as HTMLInputElement).id;
        return id && !document.querySelector(`label[for="${id}"]`) && !(input as HTMLInputElement).getAttribute('aria-label');
      });
      
      if (inputsWithoutLabels.length > 0) {
        issues.push('inputs_missing_labels');
      }

      return issues;
    });

    if (accessibilityIssues.length === 0) {
      assertions.push({
        type: 'accessibility',
        selector: 'body',
        expected: 'no_violations',
        confidence: 0.5,
        reasoning: 'Page should meet basic accessibility standards',
        autoGenerated: true
      });
    }

    return assertions;
  }

  private async enhanceWithAI(
    suggestions: AIAssertion[],
    action: RecordedAction,
    context: any
  ): Promise<AIAssertion[]> {
    try {
      const prompt = `
        Analyze these auto-generated test assertions and improve them:
        
        Action: ${action.type} on ${action.selector}
        Context: ${context.userIntent || 'User interaction'}
        Previous actions: ${context.previousActions.slice(-3).map((a: RecordedAction) => a.type).join(', ')}
        
        Current assertions:
        ${suggestions.map(s => `- ${s.type}: ${s.selector} should ${JSON.stringify(s.expected)} (confidence: ${s.confidence})`).join('\n')}
        
        Please:
        1. Adjust confidence scores based on context
        2. Add missing critical assertions
        3. Remove redundant or low-value assertions
        4. Improve assertion descriptions
        
        Respond with JSON array of enhanced assertions.
      `;

      const response = await this.aiService.generateText(prompt);
      const enhanced = JSON.parse(response);
      
      if (Array.isArray(enhanced) && enhanced.length > 0) {
        return enhanced.map(assertion => ({
          ...assertion,
          autoGenerated: true
        }));
      }
    } catch (error) {
      logger.debug(`AI enhancement failed: ${error}`);
    }

    return suggestions;
  }

  async generateVisualAssertions(
    page: Page,
    action: RecordedAction,
    baselineImage?: Buffer
  ): Promise<AIAssertion[]> {
    const assertions: AIAssertion[] = [];

    try {
      // Take screenshot for visual comparison
      const screenshot = await page.screenshot({ type: 'png', fullPage: false });
      
      if (baselineImage) {
        assertions.push({
          type: 'visual',
          selector: 'body',
          expected: { 
            baseline: baselineImage.toString('base64'),
            threshold: 0.1 
          },
          confidence: 0.8,
          reasoning: 'Visual appearance should match baseline',
          autoGenerated: true
        });
      }

      // Check for visual elements that should be present
      const visualElements = await page.evaluate(() => {
        const elements = [];
        
        // Check for important visual elements
        const buttons = document.querySelectorAll('button, input[type="button"], input[type="submit"]');
        const links = document.querySelectorAll('a[href]');
        const images = document.querySelectorAll('img');
        
        if (buttons.length > 0) elements.push('buttons');
        if (links.length > 0) elements.push('links');
        if (images.length > 0) elements.push('images');
        
        return elements;
      });

      visualElements.forEach(elementType => {
        assertions.push({
          type: 'visual',
          selector: this.getElementSelector(elementType),
          expected: 'visible',
          confidence: 0.6,
          reasoning: `${elementType} should be visible on the page`,
          autoGenerated: true
        });
      });

    } catch (error) {
      logger.error(`Failed to generate visual assertions: ${error}`);
    }

    return assertions;
  }

  private getElementSelector(elementType: string): string {
    switch (elementType) {
      case 'buttons':
        return 'button, input[type="button"], input[type="submit"]';
      case 'links':
        return 'a[href]';
      case 'images':
        return 'img';
      default:
        return 'body';
    }
  }
}

export const assertionSuggestionService = new AssertionSuggestionService();