/**
 * Copilot Readiness PDF Report Generator.
 * Produces a stakeholder-ready HTML document for PDF rendering.
 */

import type { ReadinessResult, CategoryKey, Recommendation } from './readiness-types';
import { CATEGORY_LABELS } from './readiness-types';

const PRIORITY_COLORS: Record<string, string> = {
	critical: '#dc2626', high: '#ea580c', medium: '#ca8a04', low: '#16a34a',
};

function scoreColor(score: number): string {
	if (score >= 70) return '#16a34a';
	if (score >= 40) return '#ca8a04';
	return '#dc2626';
}

function renderCategoryRow(key: CategoryKey, score: number): string {
	return `<tr>
		<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${CATEGORY_LABELS[key]}</td>
		<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center">
			<span style="color:${scoreColor(score)};font-weight:700">${score}%</span>
		</td>
		<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">
			<div style="background:#e5e7eb;border-radius:4px;height:8px;width:100%">
				<div style="background:${scoreColor(score)};border-radius:4px;height:8px;width:${score}%"></div>
			</div>
		</td>
	</tr>`;
}

function renderRecommendation(rec: Recommendation, index: number): string {
	return `<tr>
		<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center">${index + 1}</td>
		<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">
			<span style="display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600;color:#fff;background:${PRIORITY_COLORS[rec.priority]}">${rec.priority}</span>
		</td>
		<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">
			<strong>${rec.title}</strong><br>
			<span style="color:#6b7280;font-size:13px">${rec.description}</span>
		</td>
		<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;color:#6b7280">${CATEGORY_LABELS[rec.category]}</td>
	</tr>`;
}

export function generateReadinessReportHtml(
	result: ReadinessResult,
	tenantName: string,
	orgName: string,
): string {
	const catKeys = Object.keys(result.categories) as CategoryKey[];
	const catRows = catKeys.map((k) => renderCategoryRow(k, result.categories[k].score)).join('');
	const recRows = result.recommendations.map((r, i) => renderRecommendation(r, i)).join('');
	const label = result.overallScore >= 70 ? 'Ready' : result.overallScore >= 40 ? 'Needs Work' : 'Not Ready';
	const date = new Date(result.assessedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

	return `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#111;margin:0;padding:40px}
table{width:100%;border-collapse:collapse;margin:16px 0}th{text-align:left;padding:8px 12px;border-bottom:2px solid #111;font-size:13px}
.header{text-align:center;margin-bottom:40px}.score{font-size:64px;font-weight:800;color:${scoreColor(result.overallScore)}}
.label{font-size:18px;color:#6b7280;margin-top:4px}h2{margin:32px 0 8px;font-size:18px}
.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af;text-align:center}</style>
</head><body>
<div class="header">
	<h1 style="margin:0">Microsoft 365 Copilot Readiness Report</h1>
	<p style="color:#6b7280;margin:8px 0">${orgName} &mdash; ${tenantName}</p>
	<p style="color:#9ca3af;font-size:13px">${date}</p>
	<div class="score">${result.overallScore}%</div>
	<div class="label">${label}</div>
</div>
<h2>Category Breakdown</h2>
<table><thead><tr><th>Category</th><th style="text-align:center">Score</th><th>Progress</th></tr></thead>
<tbody>${catRows}</tbody></table>
<h2>Recommendations (${result.recommendations.length})</h2>
<table><thead><tr><th style="text-align:center">#</th><th>Priority</th><th>Recommendation</th><th>Category</th></tr></thead>
<tbody>${recRows}</tbody></table>
<div class="footer">Generated by TenantIQ &mdash; ${date}</div>
</body></html>`;
}
