apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdlc-gateway.fullname" . }}
  labels:
    {{- include "sdlc-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sdlc-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sdlc-gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: REDIS_HOST
              value: {{ if .Values.redis.enabled }}{{ printf "%s-redis-master" .Release.Name }}{{ else }}{{ .Values.externalRedis.host }}{{ end }}
            - name: REDIS_PORT
              value: "{{ if .Values.redis.enabled }}6379{{ else }}{{ .Values.externalRedis.port }}{{ end }}"
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
