apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: "localhost:6379"
    - name: redisPassword
      value: ""
    - name: enableTLS
      value: "false"
    - name: processingTimeout
      value: "15s"
    - name: redeliverInterval
      value: "60s"
    - name: handleRetry
      value: "true"
    - name: maxRetryCount
      value: "3"
    - name: maxRetryBackoff
      value: "2s"
    - name: maxConcurrentHandlers
      value: "10"
  scopes:
    - lunaos-api
    - lunaos-agent-runtime
    - lunaos-plugin-gateway
