name = "mcp-overflow"
main = "mcp-overflow-worker.js"
compatibility_date = "2023-05-18"

routes = [
  { pattern = "mcpoverflow.com/*", zone_name = "mcpoverflow.com" },
  { pattern = "app.mcpoverflow.io/*", zone_name = "mcpoverflow.io" },
  { pattern = "mcpoverflow.ai/*", zone_name = "mcpoverflow.ai" }
]