#!/usr/bin/env python3
"""Fail CI if critical files are below the required line coverage."""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate per-file coverage thresholds for critical files."
    )
    parser.add_argument(
        "--coverage-xml",
        default="coverage.xml",
        help="Path to coverage.xml generated by pytest-cov",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=95.0,
        help="Required minimum line coverage percentage for each critical file",
    )
    parser.add_argument(
        "--critical",
        nargs="+",
        required=True,
        help="List of repo-relative critical files to enforce",
    )
    return parser.parse_args()


def load_line_rates(xml_path: Path) -> dict[str, float]:
    if not xml_path.exists():
        raise FileNotFoundError(f"Coverage file not found: {xml_path}")

    root = ET.parse(xml_path).getroot()
    results: dict[str, float] = {}

    for cls in root.findall(".//class"):
        filename = cls.get("filename")
        line_rate = cls.get("line-rate")
        if not filename or line_rate is None:
            continue
        try:
            results[Path(filename).as_posix()] = float(line_rate) * 100.0
        except ValueError:
            continue
    return results


def main() -> int:
    args = parse_args()
    xml_path = Path(args.coverage_xml)

    try:
        rates = load_line_rates(xml_path)
    except Exception as exc:
        print(f"Coverage parsing failed: {exc}")
        return 2

    failures: list[tuple[str, str]] = []
    print(f"Critical coverage threshold: {args.threshold:.1f}%")

    for critical_file in args.critical:
        key = Path(critical_file).as_posix()
        lookup_key = key
        if lookup_key not in rates and lookup_key.startswith("src/"):
            lookup_key = lookup_key[4:]
        if lookup_key not in rates:
            failures.append((key, "missing from coverage report"))
            continue

        pct = rates[lookup_key]
        status = "PASS" if pct >= args.threshold else "FAIL"
        print(f"[{status}] {key}: {pct:.2f}%")
        if pct < args.threshold:
            failures.append((key, f"{pct:.2f}% < {args.threshold:.1f}%"))

    if failures:
        print("\nCritical coverage gate failed:")
        for filename, reason in failures:
            print(f" - {filename}: {reason}")
        return 1

    print("Critical coverage gate passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
