"""Initial migration

Revision ID: 220840b8ae8d
Revises: 
Create Date: 2025-09-06 11:23:52.904551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220840b8ae8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('spdx_id', sa.String(length=50), nullable=True),
    sa.Column('license_type', sa.Enum('MIT', 'APACHE_2_0', 'BSD_2_CLAUSE', 'BSD_3_CLAUSE', 'GPL_2_0', 'GPL_3_0', 'LGPL_2_1', 'LGPL_3_0', 'ISC', 'UNLICENSE', 'PROPRIETARY', 'UNKNOWN', name='licensetype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_osi_approved', sa.Boolean(), nullable=False),
    sa.Column('is_copyleft', sa.Boolean(), nullable=False),
    sa.Column('allows_commercial_use', sa.Boolean(), nullable=False),
    sa.Column('allows_modification', sa.Boolean(), nullable=False),
    sa.Column('allows_distribution', sa.Boolean(), nullable=False),
    sa.Column('requires_attribution', sa.Boolean(), nullable=False),
    sa.Column('requires_source_disclosure', sa.Boolean(), nullable=False),
    sa.Column('compatibility_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licenses'))
    )
    op.create_index('ix_licenses_commercial_copyleft', 'licenses', ['allows_commercial_use', 'is_copyleft'], unique=False)
    op.create_index(op.f('ix_licenses_is_copyleft'), 'licenses', ['is_copyleft'], unique=False)
    op.create_index(op.f('ix_licenses_is_deleted'), 'licenses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_licenses_is_osi_approved'), 'licenses', ['is_osi_approved'], unique=False)
    op.create_index(op.f('ix_licenses_license_type'), 'licenses', ['license_type'], unique=False)
    op.create_index(op.f('ix_licenses_name'), 'licenses', ['name'], unique=True)
    op.create_index(op.f('ix_licenses_requires_source_disclosure'), 'licenses', ['requires_source_disclosure'], unique=False)
    op.create_index(op.f('ix_licenses_spdx_id'), 'licenses', ['spdx_id'], unique=True)
    op.create_index('ix_licenses_type_osi', 'licenses', ['license_type', 'is_osi_approved'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('compliance_frameworks', sa.JSON(), nullable=False),
    sa.Column('allowed_licenses', sa.JSON(), nullable=False),
    sa.Column('blocked_licenses', sa.JSON(), nullable=False),
    sa.Column('max_vulnerability_score', sa.Float(), nullable=False),
    sa.Column('auto_update_enabled', sa.Boolean(), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('notification_emails', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_domain'), 'organizations', ['domain'], unique=False)
    op.create_index('ix_organizations_industry', 'organizations', ['industry'], unique=False)
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_index('ix_organizations_size', 'organizations', ['size'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('packages',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('ecosystem', sa.Enum('NPM', 'PYPI', 'MAVEN', 'CARGO', 'NUGET', 'COMPOSER', 'RUBYGEMS', 'GO', name='ecosystemtype'), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('homepage', sa.String(length=500), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('license', sa.Enum('MIT', 'APACHE_2_0', 'BSD_2_CLAUSE', 'BSD_3_CLAUSE', 'GPL_2_0', 'GPL_3_0', 'LGPL_2_1', 'LGPL_3_0', 'ISC', 'UNLICENSE', 'PROPRIETARY', 'UNKNOWN', name='licensetype'), nullable=False),
    sa.Column('license_text', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('maintainers', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages')),
    sa.UniqueConstraint('name', 'version', 'ecosystem', 'namespace', name='uq_package_version_ecosystem')
    )
    op.create_index(op.f('ix_packages_ecosystem'), 'packages', ['ecosystem'], unique=False)
    op.create_index('ix_packages_ecosystem_name', 'packages', ['ecosystem', 'name'], unique=False)
    op.create_index('ix_packages_full_name', 'packages', ['ecosystem', 'namespace', 'name'], unique=False)
    op.create_index(op.f('ix_packages_is_deleted'), 'packages', ['is_deleted'], unique=False)
    op.create_index('ix_packages_license', 'packages', ['license'], unique=False)
    op.create_index(op.f('ix_packages_name'), 'packages', ['name'], unique=False)
    op.create_index(op.f('ix_packages_namespace'), 'packages', ['namespace'], unique=False)
    op.create_index('ix_packages_published_at', 'packages', ['published_at'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('cve_id', sa.String(length=20), nullable=True),
    sa.Column('advisory_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='securitylevel'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('affected_versions', sa.JSON(), nullable=False),
    sa.Column('fixed_versions', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('cwe_ids', sa.JSON(), nullable=False),
    sa.Column('exploit_available', sa.Boolean(), nullable=False),
    sa.Column('patch_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerabilities'))
    )
    op.create_index(op.f('ix_vulnerabilities_advisory_id'), 'vulnerabilities', ['advisory_id'], unique=True)
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=True)
    op.create_index(op.f('ix_vulnerabilities_cvss_score'), 'vulnerabilities', ['cvss_score'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_exploit_available'), 'vulnerabilities', ['exploit_available'], unique=False)
    op.create_index('ix_vulnerabilities_exploit_patch', 'vulnerabilities', ['exploit_available', 'patch_available'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_is_deleted'), 'vulnerabilities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_patch_available'), 'vulnerabilities', ['patch_available'], unique=False)
    op.create_index('ix_vulnerabilities_published', 'vulnerabilities', ['published_at', 'severity'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_published_at'), 'vulnerabilities', ['published_at'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_index('ix_vulnerabilities_severity_score', 'vulnerabilities', ['severity', 'cvss_score'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_source'), 'vulnerabilities', ['source'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_action', 'audit_logs', ['created_at', 'action'], unique=False)
    op.create_index('ix_audit_logs_entity_action', 'audit_logs', ['entity_type', 'entity_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_index('ix_audit_logs_organization_action', 'audit_logs', ['organization_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index('ix_audit_logs_success_created', 'audit_logs', ['success', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('dependency_graphs',
    sa.Column('root_package_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('vulnerabilities', sa.JSON(), nullable=False),
    sa.Column('license_issues', sa.JSON(), nullable=False),
    sa.Column('total_packages', sa.Integer(), nullable=False),
    sa.Column('total_vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_strategy', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_dependency_graphs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_package_id'], ['packages.id'], name=op.f('fk_dependency_graphs_root_package_id_packages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependency_graphs'))
    )
    op.create_index(op.f('ix_dependency_graphs_is_deleted'), 'dependency_graphs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dependency_graphs_is_resolved'), 'dependency_graphs', ['is_resolved'], unique=False)
    op.create_index('ix_dependency_graphs_organization_risk', 'dependency_graphs', ['organization_id', 'risk_score'], unique=False)
    op.create_index(op.f('ix_dependency_graphs_risk_score'), 'dependency_graphs', ['risk_score'], unique=False)
    op.create_index('ix_dependency_graphs_root_org', 'dependency_graphs', ['root_package_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_dependency_graphs_total_vulnerabilities'), 'dependency_graphs', ['total_vulnerabilities'], unique=False)
    op.create_index('ix_dependency_graphs_vulnerabilities_resolved', 'dependency_graphs', ['total_vulnerabilities', 'is_resolved'], unique=False)
    op.create_table('package_vulnerabilities',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=False),
    sa.Column('affected_version_range', sa.String(length=200), nullable=False),
    sa.Column('fixed_version', sa.String(length=50), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_vulnerabilities_package_id_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], name=op.f('fk_package_vulnerabilities_vulnerability_id_vulnerabilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_vulnerabilities')),
    sa.UniqueConstraint('package_id', 'vulnerability_id', name='uq_package_vulnerability')
    )
    op.create_index('ix_package_vulnerabilities_detected', 'package_vulnerabilities', ['first_detected_at'], unique=False)
    op.create_index(op.f('ix_package_vulnerabilities_is_deleted'), 'package_vulnerabilities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_package_vulnerabilities_is_fixed'), 'package_vulnerabilities', ['is_fixed'], unique=False)
    op.create_index('ix_package_vulnerabilities_package', 'package_vulnerabilities', ['package_id'], unique=False)
    op.create_index('ix_package_vulnerabilities_vulnerability', 'package_vulnerabilities', ['vulnerability_id'], unique=False)
    op.create_table('policies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('action', sa.Enum('ALLOW', 'WARN', 'BLOCK', 'REQUIRE_APPROVAL', name='policyaction'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('applicable_ecosystems', sa.JSON(), nullable=False),
    sa.Column('exceptions', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_index(op.f('ix_policies_action'), 'policies', ['action'], unique=False)
    op.create_index('ix_policies_active_priority', 'policies', ['is_active', 'priority'], unique=False)
    op.create_index(op.f('ix_policies_is_active'), 'policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_policies_is_deleted'), 'policies', ['is_deleted'], unique=False)
    op.create_index('ix_policies_organization_active', 'policies', ['organization_id', 'is_active'], unique=False)
    op.create_index('ix_policies_organization_type', 'policies', ['organization_id', 'policy_type'], unique=False)
    op.create_index(op.f('ix_policies_policy_type'), 'policies', ['policy_type'], unique=False)
    op.create_index(op.f('ix_policies_priority'), 'policies', ['priority'], unique=False)
    op.create_table('workflows',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('initiator_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'WAITING_FOR_APPROVAL', 'APPROVED', 'REJECTED', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('current_state', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approvals_required', sa.JSON(), nullable=False),
    sa.Column('approvals_received', sa.JSON(), nullable=False),
    sa.Column('checkpoints', sa.JSON(), nullable=False),
    sa.Column('related_entities', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workflows_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    op.create_index(op.f('ix_workflows_completed_at'), 'workflows', ['completed_at'], unique=False)
    op.create_index(op.f('ix_workflows_current_state'), 'workflows', ['current_state'], unique=False)
    op.create_index('ix_workflows_initiator_status', 'workflows', ['initiator_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflows_is_deleted'), 'workflows', ['is_deleted'], unique=False)
    op.create_index('ix_workflows_organization_status', 'workflows', ['organization_id', 'status'], unique=False)
    op.create_index('ix_workflows_organization_type', 'workflows', ['organization_id', 'workflow_type'], unique=False)
    op.create_index(op.f('ix_workflows_started_at'), 'workflows', ['started_at'], unique=False)
    op.create_index('ix_workflows_started_completed', 'workflows', ['started_at', 'completed_at'], unique=False)
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index('ix_workflows_type_status', 'workflows', ['workflow_type', 'status'], unique=False)
    op.create_index(op.f('ix_workflows_workflow_type'), 'workflows', ['workflow_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_workflow_type'), table_name='workflows')
    op.drop_index('ix_workflows_type_status', table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_index('ix_workflows_started_completed', table_name='workflows')
    op.drop_index(op.f('ix_workflows_started_at'), table_name='workflows')
    op.drop_index('ix_workflows_organization_type', table_name='workflows')
    op.drop_index('ix_workflows_organization_status', table_name='workflows')
    op.drop_index(op.f('ix_workflows_is_deleted'), table_name='workflows')
    op.drop_index('ix_workflows_initiator_status', table_name='workflows')
    op.drop_index(op.f('ix_workflows_current_state'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_completed_at'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_policies_priority'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_type'), table_name='policies')
    op.drop_index('ix_policies_organization_type', table_name='policies')
    op.drop_index('ix_policies_organization_active', table_name='policies')
    op.drop_index(op.f('ix_policies_is_deleted'), table_name='policies')
    op.drop_index(op.f('ix_policies_is_active'), table_name='policies')
    op.drop_index('ix_policies_active_priority', table_name='policies')
    op.drop_index(op.f('ix_policies_action'), table_name='policies')
    op.drop_table('policies')
    op.drop_index('ix_package_vulnerabilities_vulnerability', table_name='package_vulnerabilities')
    op.drop_index('ix_package_vulnerabilities_package', table_name='package_vulnerabilities')
    op.drop_index(op.f('ix_package_vulnerabilities_is_fixed'), table_name='package_vulnerabilities')
    op.drop_index(op.f('ix_package_vulnerabilities_is_deleted'), table_name='package_vulnerabilities')
    op.drop_index('ix_package_vulnerabilities_detected', table_name='package_vulnerabilities')
    op.drop_table('package_vulnerabilities')
    op.drop_index('ix_dependency_graphs_vulnerabilities_resolved', table_name='dependency_graphs')
    op.drop_index(op.f('ix_dependency_graphs_total_vulnerabilities'), table_name='dependency_graphs')
    op.drop_index('ix_dependency_graphs_root_org', table_name='dependency_graphs')
    op.drop_index(op.f('ix_dependency_graphs_risk_score'), table_name='dependency_graphs')
    op.drop_index('ix_dependency_graphs_organization_risk', table_name='dependency_graphs')
    op.drop_index(op.f('ix_dependency_graphs_is_resolved'), table_name='dependency_graphs')
    op.drop_index(op.f('ix_dependency_graphs_is_deleted'), table_name='dependency_graphs')
    op.drop_table('dependency_graphs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_success_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_organization_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vulnerabilities_source'), table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_severity_score', table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_published_at'), table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_published', table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_patch_available'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_is_deleted'), table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_exploit_patch', table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_exploit_available'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cvss_score'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_advisory_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index('ix_packages_published_at', table_name='packages')
    op.drop_index(op.f('ix_packages_namespace'), table_name='packages')
    op.drop_index(op.f('ix_packages_name'), table_name='packages')
    op.drop_index('ix_packages_license', table_name='packages')
    op.drop_index(op.f('ix_packages_is_deleted'), table_name='packages')
    op.drop_index('ix_packages_full_name', table_name='packages')
    op.drop_index('ix_packages_ecosystem_name', table_name='packages')
    op.drop_index(op.f('ix_packages_ecosystem'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index('ix_organizations_size', table_name='organizations')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_index('ix_organizations_industry', table_name='organizations')
    op.drop_index(op.f('ix_organizations_domain'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_licenses_type_osi', table_name='licenses')
    op.drop_index(op.f('ix_licenses_spdx_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_requires_source_disclosure'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_name'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_license_type'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_is_osi_approved'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_is_deleted'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_is_copyleft'), table_name='licenses')
    op.drop_index('ix_licenses_commercial_copyleft', table_name='licenses')
    op.drop_table('licenses')
    # ### end Alembic commands ###


