"""Add missing core tables: projects, users, dependencies, analysis, etc.

Revision ID: add_missing_core_tables
Revises: 220840b8ae8d
Create Date: 2025-10-29 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "add_missing_core_tables"
down_revision = "220840b8ae8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create users table
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)

    # Create projects table
    op.create_table(
        "projects",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("repository_url", sa.String(length=500), nullable=True),
        sa.Column("repository_branch", sa.String(length=100), nullable=False),
        sa.Column("primary_language", sa.String(length=50), nullable=True),
        sa.Column("ecosystem", sa.String(length=50), nullable=True),
        sa.Column("project_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("last_analysis_at", sa.String(length=50), nullable=True),
        sa.Column("last_analysis_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("analysis_frequency", sa.String(length=20), nullable=False),
        sa.Column("auto_scan_enabled", sa.Boolean(), nullable=False),
        sa.Column("policy_enforcement_enabled", sa.Boolean(), nullable=False),
        sa.Column("build_system", sa.String(length=50), nullable=True),
        sa.Column("deployment_pipeline", sa.JSON(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index("idx_projects_ecosystem", "projects", ["ecosystem"], unique=False)
    op.create_index(
        "idx_projects_last_analysis", "projects", ["last_analysis_at"], unique=False
    )
    op.create_index(
        "idx_projects_org_slug", "projects", ["organization_id", "slug"], unique=False
    )
    op.create_index(
        "idx_projects_status_type", "projects", ["status", "project_type"], unique=False
    )
    op.create_index(
        op.f("ix_projects_ecosystem"), "projects", ["ecosystem"], unique=False
    )
    op.create_index(
        op.f("ix_projects_last_analysis_at"),
        "projects",
        ["last_analysis_at"],
        unique=False,
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(
        op.f("ix_projects_organization_id"),
        "projects",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=False)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)

    # Create dependencies table
    op.create_table(
        "dependencies",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("framework", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("repository_url", sa.String(length=500), nullable=True),
        sa.Column("license", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("dependency_metadata", sa.JSON(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_dependencies_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dependencies")),
    )
    op.create_index(
        op.f("ix_dependencies_framework"), "dependencies", ["framework"], unique=False
    )
    op.create_index(
        op.f("ix_dependencies_is_active"), "dependencies", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_dependencies_language"), "dependencies", ["language"], unique=False
    )
    op.create_index(
        op.f("ix_dependencies_name"), "dependencies", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_dependencies_version"), "dependencies", ["version"], unique=False
    )

    # Create dependency_vulnerabilities table
    op.create_table(
        "dependency_vulnerabilities",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("dependency_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("vulnerability_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("cvss_score", sa.String(length=10), nullable=True),
        sa.Column("cve_id", sa.String(length=50), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("patched_versions", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dependency_id"],
            ["dependencies.id"],
            name=op.f("fk_dependency_vulnerabilities_dependency_id_dependencies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dependency_vulnerabilities")),
    )
    op.create_index(
        op.f("ix_dependency_vulnerabilities_cve_id"),
        "dependency_vulnerabilities",
        ["cve_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dependency_vulnerabilities_dependency_id"),
        "dependency_vulnerabilities",
        ["dependency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dependency_vulnerabilities_severity"),
        "dependency_vulnerabilities",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dependency_vulnerabilities_vulnerability_id"),
        "dependency_vulnerabilities",
        ["vulnerability_id"],
        unique=False,
    )

    # Create dependency_analyses table
    op.create_table(
        "dependency_analyses",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("dependency_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("vulnerabilities", sa.JSON(), nullable=False),
        sa.Column("compatibility_score", sa.String(length=10), nullable=False),
        sa.Column("maintenance_score", sa.String(length=10), nullable=False),
        sa.Column("popularity_score", sa.String(length=10), nullable=False),
        sa.Column("license_compatible", sa.Boolean(), nullable=False),
        sa.Column("recommendations", sa.JSON(), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dependency_id"],
            ["dependencies.id"],
            name=op.f("fk_dependency_analyses_dependency_id_dependencies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dependency_analyses")),
    )
    op.create_index(
        op.f("ix_dependency_analyses_dependency_id"),
        "dependency_analyses",
        ["dependency_id"],
        unique=False,
    )

    # Create analysis table (analysiss to avoid keyword conflict)
    op.create_table(
        "analysiss",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("analysis_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("analysis_type", sa.String(length=50), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("target_version", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.String(length=50), nullable=True),
        sa.Column("completed_at", sa.String(length=50), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("scanner_version", sa.String(length=50), nullable=True),
        sa.Column("total_issues", sa.Integer(), nullable=False),
        sa.Column("critical_issues", sa.Integer(), nullable=False),
        sa.Column("high_issues", sa.Integer(), nullable=False),
        sa.Column("medium_issues", sa.Integer(), nullable=False),
        sa.Column("low_issues", sa.Integer(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_stacktrace", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysiss")),
    )
    op.create_index(
        "idx_analysis_severity_counts",
        "analysiss",
        ["critical_issues", "high_issues"],
        unique=False,
    )
    op.create_index(
        "idx_analysis_target_id",
        "analysiss",
        ["target_type", "target_id"],
        unique=False,
    )
    op.create_index(
        "idx_analysis_type_status",
        "analysiss",
        ["analysis_type", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysiss_analysis_id"), "analysiss", ["analysis_id"], unique=True
    )
    op.create_index(
        op.f("ix_analysiss_analysis_type"), "analysiss", ["analysis_type"], unique=False
    )
    op.create_index(
        op.f("ix_analysiss_created_at"), "analysiss", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_analysiss_status"), "analysiss", ["status"], unique=False)
    op.create_index(
        op.f("ix_analysiss_target_id"), "analysiss", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysiss_target_type"), "analysiss", ["target_type"], unique=False
    )

    # Create analysis_results table
    op.create_table(
        "analysis_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("result_id", sa.String(length=100), nullable=False),
        sa.Column("analysis_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("issue_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=1000), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=True),
        sa.Column("end_line", sa.Integer(), nullable=True),
        sa.Column("component_name", sa.String(length=255), nullable=True),
        sa.Column("component_version", sa.String(length=100), nullable=True),
        sa.Column("component_type", sa.String(length=50), nullable=True),
        sa.Column("cve_id", sa.String(length=50), nullable=True),
        sa.Column("cwe_id", sa.String(length=50), nullable=True),
        sa.Column("owasp_category", sa.String(length=100), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("fix_available", sa.Boolean(), nullable=False),
        sa.Column("fixed_version", sa.String(length=100), nullable=True),
        sa.Column("references", sa.JSON(), nullable=False),
        sa.Column("result_metadata", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("assigned_to", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysiss.id"],
            name=op.f("fk_analysis_results_analysis_id_analysiss"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name=op.f("fk_analysis_results_assigned_to_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_results")),
    )
    op.create_index(
        "idx_analysis_results_cve", "analysis_results", ["cve_id"], unique=False
    )
    op.create_index(
        "idx_analysis_results_file",
        "analysis_results",
        ["file_path", "line_number"],
        unique=False,
    )
    op.create_index(
        "idx_analysis_results_severity",
        "analysis_results",
        ["severity", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_analysis_id"),
        "analysis_results",
        ["analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_assigned_to"),
        "analysis_results",
        ["assigned_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_cve_id"), "analysis_results", ["cve_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_results_file_path"),
        "analysis_results",
        ["file_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_issue_type"),
        "analysis_results",
        ["issue_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_result_id"),
        "analysis_results",
        ["result_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_analysis_results_severity"),
        "analysis_results",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_status"), "analysis_results", ["status"], unique=False
    )

    # Create sboms table
    op.create_table(
        "sboms",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sbom_id", sa.String(length=100), nullable=False),
        sa.Column("format", sa.String(length=50), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("target_name", sa.String(length=255), nullable=True),
        sa.Column("sbom_data", sa.JSON(), nullable=False),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("total_components", sa.Integer(), nullable=False),
        sa.Column("direct_dependencies", sa.Integer(), nullable=False),
        sa.Column("transitive_dependencies", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.String(length=50), nullable=False),
        sa.Column("generator", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sboms")),
    )
    op.create_index(
        "idx_sbom_format_version", "sboms", ["format", "version"], unique=False
    )
    op.create_index("idx_sbom_generated_at", "sboms", ["generated_at"], unique=False)
    op.create_index(
        "idx_sbom_target_id", "sboms", ["target_type", "target_id"], unique=False
    )
    op.create_index(op.f("ix_sboms_format"), "sboms", ["format"], unique=False)
    op.create_index(op.f("ix_sboms_sbom_id"), "sboms", ["sbom_id"], unique=True)
    op.create_index(op.f("ix_sboms_target_id"), "sboms", ["target_id"], unique=False)
    op.create_index(
        op.f("ix_sboms_target_type"), "sboms", ["target_type"], unique=False
    )

    # Create package_versions table
    op.create_table(
        "package_versions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("package_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("is_prerelease", sa.Boolean(), nullable=False),
        sa.Column("is_latest", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.String(length=50), nullable=True),
        sa.Column("release_notes", sa.Text(), nullable=True),
        sa.Column("download_url", sa.String(length=500), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("checksum_md5", sa.String(length=32), nullable=True),
        sa.Column("checksum_sha1", sa.String(length=40), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("dev_dependencies", sa.JSON(), nullable=False),
        sa.Column("python_requires", sa.String(length=100), nullable=True),
        sa.Column("java_version", sa.String(length=20), nullable=True),
        sa.Column("node_version", sa.String(length=20), nullable=True),
        sa.Column("version_metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_package_versions_package_id_packages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_versions")),
    )
    op.create_index(
        "idx_package_versions_latest",
        "package_versions",
        ["package_id", "is_latest"],
        unique=False,
    )
    op.create_index(
        "idx_package_versions_package_version",
        "package_versions",
        ["package_id", "version"],
        unique=False,
    )
    op.create_index(
        "idx_package_versions_published",
        "package_versions",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_package_versions_is_latest"),
        "package_versions",
        ["is_latest"],
        unique=False,
    )
    op.create_index(
        op.f("ix_package_versions_package_id"),
        "package_versions",
        ["package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_package_versions_version"),
        "package_versions",
        ["version"],
        unique=False,
    )

    # Create organization_memberships table
    op.create_table(
        "organization_memberships",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("invited_at", sa.String(length=50), nullable=False),
        sa.Column("joined_at", sa.String(length=50), nullable=True),
        sa.Column("left_at", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_organization_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_memberships")),
    )
    op.create_index(
        "idx_org_members_role_active",
        "organization_memberships",
        ["role", "is_active"],
        unique=False,
    )
    op.create_index(
        "idx_org_members_org_user",
        "organization_memberships",
        ["organization_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_memberships_is_active"),
        "organization_memberships",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_memberships_organization_id"),
        "organization_memberships",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_memberships_role"),
        "organization_memberships",
        ["role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_memberships_user_id"),
        "organization_memberships",
        ["user_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_organization_memberships_user_id"),
        table_name="organization_memberships",
    )
    op.drop_index(
        op.f("ix_organization_memberships_role"), table_name="organization_memberships"
    )
    op.drop_index(
        op.f("ix_organization_memberships_organization_id"),
        table_name="organization_memberships",
    )
    op.drop_index(
        op.f("ix_organization_memberships_is_active"),
        table_name="organization_memberships",
    )
    op.drop_index("idx_org_members_org_user", table_name="organization_memberships")
    op.drop_index("idx_org_members_role_active", table_name="organization_memberships")
    op.drop_table("organization_memberships")
    op.drop_index(op.f("ix_package_versions_version"), table_name="package_versions")
    op.drop_index(op.f("ix_package_versions_package_id"), table_name="package_versions")
    op.drop_index(op.f("ix_package_versions_is_latest"), table_name="package_versions")
    op.drop_index("idx_package_versions_published", table_name="package_versions")
    op.drop_index("idx_package_versions_package_version", table_name="package_versions")
    op.drop_index("idx_package_versions_latest", table_name="package_versions")
    op.drop_table("package_versions")
    op.drop_index(op.f("ix_sboms_target_type"), table_name="sboms")
    op.drop_index(op.f("ix_sboms_target_id"), table_name="sboms")
    op.drop_index(op.f("ix_sboms_sbom_id"), table_name="sboms")
    op.drop_index(op.f("ix_sboms_format"), table_name="sboms")
    op.drop_index("idx_sbom_target_id", table_name="sboms")
    op.drop_index("idx_sbom_generated_at", table_name="sboms")
    op.drop_index("idx_sbom_format_version", table_name="sboms")
    op.drop_table("sboms")
    op.drop_index(op.f("ix_analysis_results_status"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_severity"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_result_id"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_issue_type"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_file_path"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_cve_id"), table_name="analysis_results")
    op.drop_index(
        op.f("ix_analysis_results_assigned_to"), table_name="analysis_results"
    )
    op.drop_index(
        op.f("ix_analysis_results_analysis_id"), table_name="analysis_results"
    )
    op.drop_index(op.f("ix_analysis_results_severity"), table_name="analysis_results")
    op.drop_index("idx_analysis_results_severity", table_name="analysis_results")
    op.drop_index("idx_analysis_results_file", table_name="analysis_results")
    op.drop_index("idx_analysis_results_cve", table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_index(op.f("ix_analysiss_target_type"), table_name="analysiss")
    op.drop_index(op.f("ix_analysiss_target_id"), table_name="analysiss")
    op.drop_index(op.f("ix_analysiss_status"), table_name="analysiss")
    op.drop_index(op.f("ix_analysiss_created_at"), table_name="analysiss")
    op.drop_index(op.f("ix_analysiss_analysis_type"), table_name="analysiss")
    op.drop_index(op.f("ix_analysiss_analysis_id"), table_name="analysiss")
    op.drop_index("idx_analysis_type_status", table_name="analysiss")
    op.drop_index("idx_analysis_target_id", table_name="analysiss")
    op.drop_index("idx_analysis_severity_counts", table_name="analysiss")
    op.drop_table("analysiss")
    op.drop_index(
        op.f("ix_dependency_analyses_dependency_id"), table_name="dependency_analyses"
    )
    op.drop_table("dependency_analyses")
    op.drop_index(
        op.f("ix_dependency_vulnerabilities_vulnerability_id"),
        table_name="dependency_vulnerabilities",
    )
    op.drop_index(
        op.f("ix_dependency_vulnerabilities_severity"),
        table_name="dependency_vulnerabilities",
    )
    op.drop_index(
        op.f("ix_dependency_vulnerabilities_dependency_id"),
        table_name="dependency_vulnerabilities",
    )
    op.drop_index(
        op.f("ix_dependency_vulnerabilities_cve_id"),
        table_name="dependency_vulnerabilities",
    )
    op.drop_table("dependency_vulnerabilities")
    op.drop_index(op.f("ix_dependencies_version"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_name"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_language"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_is_active"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_framework"), table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_last_analysis_at"), table_name="projects")
    op.drop_index(op.f("ix_projects_ecosystem"), table_name="projects")
    op.drop_index("idx_projects_status_type", table_name="projects")
    op.drop_index("idx_projects_org_slug", table_name="projects")
    op.drop_index("idx_projects_last_analysis", table_name="projects")
    op.drop_index("idx_projects_ecosystem", table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
