// Package aicommit detects whether a git commit was authored by an AI
// coding assistant (Cursor, Claude Code, Copilot, Codex, etc).
//
// This powers the "ai_authored" tag on PipeWarden findings — the GTM
// headline that AI-generated code carries elevated risk (hallucinated
// deps, secret leaks at 2× baseline, prototype-pollution patterns).
package aicommit

import (
	"regexp"
	"strings"
)

// Tool is the recognised AI authoring tool.
type Tool string

const (
	ToolClaudeCode Tool = "claude-code"
	ToolCursor     Tool = "cursor"
	ToolCopilot    Tool = "copilot"
	ToolCodex      Tool = "codex"
	ToolAider      Tool = "aider"
	ToolWindsurf   Tool = "windsurf"
	ToolUnknown    Tool = "" // not AI authored
)

// Detection is the result of analyzing a commit.
type Detection struct {
	Tool       Tool
	Confidence float64 // 0.0 to 1.0
	Evidence   string  // human-readable reason; goes into the finding tag
}

// IsAI reports whether the commit was likely AI-authored.
func (d Detection) IsAI() bool { return d.Tool != ToolUnknown }

// Commit is the subset of git-commit metadata aicommit inspects.
// Populate from `git log --format="%an|%ae|%cn|%ce|%B"` or via go-git.
type Commit struct {
	AuthorName     string
	AuthorEmail    string
	CommitterName  string
	CommitterEmail string
	Message        string
}

// Heuristic signatures.
//
//   - Co-Authored-By trailers are the strongest signal: Claude Code
//     and Cursor both emit them by default.
//   - Author/committer email matches GitHub Copilot's bot identity
//     when commits are made via the Copilot Workspace UI.
//   - Message-body fingerprints are noisier but catch "🤖 Generated
//     with [Claude Code]" / "Co-generated by Cursor" lines.
//
// All matches are case-insensitive.
var (
	reCoAuthored = regexp.MustCompile(`(?im)^\s*co-authored-by:\s*(.+?)\s*<([^>]+)>\s*$`)
	reClaudeBody = regexp.MustCompile(`(?i)(claude\s*code|claude-code|noreply@anthropic\.com)`)
	reCursorBody = regexp.MustCompile(`(?i)(cursor\.ai|cursor\.so|generated\s+by\s+cursor)`)
	reCodexBody  = regexp.MustCompile(`(?i)(openai\s*codex|codex\s*cli|codex@openai)`)
	reAiderBody  = regexp.MustCompile(`(?i)(aider\.chat|generated\s+by\s+aider)`)
	reWindsurf   = regexp.MustCompile(`(?i)(windsurf\.codeium|codeium\.com)`)

	emailCopilot = []string{
		"@users.noreply.github.com",
		"copilot@github.com",
	}
)

// Detect inspects a single commit and returns a detection result.
// Returns Detection{Tool: ToolUnknown} when no AI signal is found.
func Detect(c Commit) Detection {
	body := c.Message

	// 1) Strongest signal: co-author trailer.
	for _, m := range reCoAuthored.FindAllStringSubmatch(body, -1) {
		name := strings.ToLower(strings.TrimSpace(m[1]))
		email := strings.ToLower(strings.TrimSpace(m[2]))
		switch {
		case strings.Contains(email, "noreply@anthropic.com") ||
			strings.Contains(name, "claude"):
			return Detection{
				Tool: ToolClaudeCode, Confidence: 0.98,
				Evidence: "Co-Authored-By trailer matches Claude Code",
			}
		case strings.Contains(name, "cursor") || strings.Contains(email, "cursor"):
			return Detection{
				Tool: ToolCursor, Confidence: 0.95,
				Evidence: "Co-Authored-By trailer matches Cursor",
			}
		case strings.Contains(name, "copilot") || strings.Contains(email, "copilot"):
			return Detection{
				Tool: ToolCopilot, Confidence: 0.95,
				Evidence: "Co-Authored-By trailer matches Copilot",
			}
		case strings.Contains(name, "codex") || strings.Contains(email, "codex"):
			return Detection{
				Tool: ToolCodex, Confidence: 0.9,
				Evidence: "Co-Authored-By trailer matches Codex",
			}
		case strings.Contains(name, "aider") || strings.Contains(email, "aider"):
			return Detection{
				Tool: ToolAider, Confidence: 0.9,
				Evidence: "Co-Authored-By trailer matches Aider",
			}
		}
	}

	// 2) Author/committer email matches a known bot.
	emails := []string{strings.ToLower(c.AuthorEmail), strings.ToLower(c.CommitterEmail)}
	for _, e := range emails {
		if e == "" {
			continue
		}
		if strings.Contains(e, "noreply@anthropic.com") {
			return Detection{Tool: ToolClaudeCode, Confidence: 0.9, Evidence: "Author email is Anthropic noreply"}
		}
		if strings.Contains(e, "cursor.sh") || strings.Contains(e, "cursor.ai") {
			return Detection{Tool: ToolCursor, Confidence: 0.9, Evidence: "Author email is Cursor"}
		}
		for _, c := range emailCopilot {
			if strings.HasSuffix(e, c) && (strings.Contains(e, "copilot") || strings.Contains(e, "github-copilot")) {
				return Detection{Tool: ToolCopilot, Confidence: 0.85, Evidence: "Author email is Copilot bot"}
			}
		}
	}

	// 3) Message-body fingerprints.
	if reClaudeBody.MatchString(body) {
		return Detection{Tool: ToolClaudeCode, Confidence: 0.7, Evidence: "Commit body mentions Claude Code"}
	}
	if reCursorBody.MatchString(body) {
		return Detection{Tool: ToolCursor, Confidence: 0.6, Evidence: "Commit body mentions Cursor"}
	}
	if reCodexBody.MatchString(body) {
		return Detection{Tool: ToolCodex, Confidence: 0.55, Evidence: "Commit body mentions Codex"}
	}
	if reAiderBody.MatchString(body) {
		return Detection{Tool: ToolAider, Confidence: 0.6, Evidence: "Commit body mentions Aider"}
	}
	if reWindsurf.MatchString(body) {
		return Detection{Tool: ToolWindsurf, Confidence: 0.6, Evidence: "Commit body mentions Windsurf"}
	}

	return Detection{Tool: ToolUnknown}
}
