/**
 * Init Command for Questro CLI
 * Interactive project initialization and configuration setup
 */

import { Command } from 'commander';
import inquirer from 'inquirer';
import chalk from 'chalk';
import ora from 'ora';
import { writeFileSync, existsSync } from 'fs';
import { api } from '../utils/api-client';
import { logger } from '../utils/logger';

interface InitConfig {
  projectName: string;
  apiUrl: string;
  apiKey: string;
  framework: 'playwright' | 'cypress';
  testDir: string;
  baseUrl?: string;
}

const createInitCommand = (): Command => {
  const initCmd = new Command('init')
    .description('Initialize a new Qestro project')
    .alias('initialize')
    .alias('i')
    .action(async () => {
      try {
        console.log(chalk.cyan('Welcome to Qestro! Let\'s set up your test project.\n'));

        const answers = await gatherProjectInfo() as InitConfig;

        const spinner = ora('Validating configuration...').start();
        try {
          await api.get('/api/v1/auth/validate', {
            headers: {
              'Authorization': `Bearer ${answers.apiKey}`,
            },
          });
          spinner.succeed('Configuration validated');
        } catch (err) {
          spinner.fail('Invalid API key or URL');
          logger.error('Validation failed:', {}, err as Error);
          process.exit(1);
        }

        generateConfigFile(answers);
        displayInitSummary(answers);
      } catch (error) {
        logger.error('Initialization failed:', {}, error as Error);
        process.exit(1);
      }
    });

  return initCmd;
};

async function gatherProjectInfo(): Promise<any> {
  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'projectName',
      message: 'Project name:',
      default: 'My Test Project',
      validate: (input: string) => input.length > 0 || 'Project name required',
    },
    {
      type: 'input',
      name: 'apiUrl',
      message: 'Qestro API URL:',
      default: 'https://api.qestro.io',
      validate: (input: string) => input.startsWith('http') || 'Must be valid URL',
    },
    {
      type: 'password',
      name: 'apiKey',
      message: 'API Key (from dashboard settings):',
      validate: (input: string) => input.length > 10 || 'API key too short',
    },
    {
      type: 'list',
      name: 'framework',
      message: 'Preferred test framework:',
      choices: ['playwright', 'cypress'],
      default: 'playwright',
    },
    {
      type: 'input',
      name: 'testDir',
      message: 'Test directory:',
      default: './tests',
    },
    {
      type: 'input',
      name: 'baseUrl',
      message: 'Application base URL (optional):',
      default: '',
    },
  ]);

  return answers;
}

function generateConfigFile(config: InitConfig): void {
  const configContent = `/**
 * Qestro Configuration
 * Auto-generated by \`qestro init\`
 */

export default {
  // Project metadata
  projectName: '${config.projectName}',

  // API Configuration
  api: {
    url: '${config.apiUrl}',
    key: process.env.QESTRO_API_KEY,
    timeout: 30000,
  },

  // Testing Framework
  framework: '${config.framework}',

  // Test directory
  testDir: '${config.testDir}',

  // Base URL for browser tests
  ${config.baseUrl ? `baseUrl: '${config.baseUrl}',` : '// baseUrl: "https://example.com",'}

  // Execution settings
  execution: {
    parallel: true,
    maxWorkers: 4,
    timeout: 60000,
    retries: 1,
  },

  // Report generation
  reports: {
    enabled: true,
    formats: ['html', 'junit', 'json'],
    outputDir: './test-results',
  },

  // Self-healing settings
  selfHealing: {
    enabled: true,
    autoApplyHighConfidence: false,
    minConfidenceThreshold: 0.8,
  },

  // CI/CD Integration
  cicd: {
    // GitHub Actions
    github: {
      enabled: false,
      token: process.env.GITHUB_TOKEN,
    },
    // GitLab CI
    gitlab: {
      enabled: false,
      token: process.env.GITLAB_TOKEN,
    },
  },
};
`;

  const configPath = 'qestro.config.ts';

  if (existsSync(configPath)) {
    logger.warn(`Config file already exists at ${configPath}`);
    return;
  }

  writeFileSync(configPath, configContent);
  logger.success(`Created ${chalk.cyan(configPath)}`);
}

function displayInitSummary(config: InitConfig): void {
  const summary = [
    `Project: ${chalk.cyan(config.projectName)}`,
    `Framework: ${chalk.yellow(config.framework)}`,
    `Test Directory: ${chalk.green(config.testDir)}`,
    config.baseUrl ? `Base URL: ${chalk.blue(config.baseUrl)}` : null,
    `API: ${chalk.gray(config.apiUrl)}`,
  ]
    .filter(Boolean)
    .join('\n');

  console.log(chalk.green('\n✓ Project Initialized\n'));
  console.log(summary);

  console.log(chalk.cyan('\nNext steps:'));
  console.log('  1. Set QESTRO_API_KEY environment variable');
  console.log('  2. Create tests with: qestro generate --url <url>');
  console.log('  3. Run tests with: qestro run');
  console.log('  4. View results with: qestro status --full');
}

export const initCommand = createInitCommand();
