#!/bin/bash
# Master Consolidation Script: Merge all database projects into QueryFlux

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   QueryFlux Database Projects Consolidation               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "This will consolidate:"
echo "  1. postgres-docker → Desktop, Mobile, Extensions, Themes"
echo "  2. querylens → NL→SQL Backend Service"
echo ""
echo "Into unified QueryFlux platform"
echo ""

# Ask for confirmation
read -p "Continue with consolidation? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Consolidation cancelled."
    exit 1
fi

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Step 1/2: Consolidating postgres-docker"
echo "═══════════════════════════════════════════════════════════"
echo ""

bash "$SCRIPT_DIR/consolidate-postgres-docker.sh"

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Step 2/2: Consolidating querylens"
echo "═══════════════════════════════════════════════════════════"
echo ""

bash "$SCRIPT_DIR/consolidate-querylens.sh"

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║   🎉 CONSOLIDATION COMPLETE!                               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 Summary:"
echo "  ✅ postgres-docker → desktop/, mobile/, extensions/, themes/"
echo "  ✅ querylens → backend/nlp-service/"
echo ""
echo "📁 New QueryFlux Structure:"
echo "  queryflux/"
echo "  ├── src/                    # React frontend (existing)"
echo "  ├── backend/"
echo "  │   ├── nlp-service/        # Java NL→SQL service (from querylens)"
echo "  │   └── python/             # Python AI components (from postgres-docker)"
echo "  ├── desktop/                # Desktop app (from postgres-docker)"
echo "  ├── mobile/                 # React Native app (from postgres-docker)"
echo "  ├── extensions/"
echo "  │   └── vscode/             # VS Code extension (from postgres-docker)"
echo "  ├── themes/                 # Premium themes (from postgres-docker)"
echo "  └── docs/                   # Combined documentation"
echo ""
echo "🔧 Next Steps:"
echo ""
echo "1. Review consolidated files:"
echo "   cd /Users/shaharsolomon/dev/projects/03_Enterprize_application/queryflux"
echo "   ls -la desktop/ mobile/ backend/ extensions/ themes/"
echo ""
echo "2. Initialize Git (if not already done):"
echo "   git add ."
echo "   git commit -m 'Consolidation: Merged postgres-docker and querylens into QueryFlux'"
echo ""
echo "3. Install dependencies:"
echo "   # Frontend"
echo "   npm install"
echo ""
echo "   # Desktop"
echo "   cd desktop && pip install -r requirements-desktop.txt"
echo ""
echo "   # Mobile"
echo "   cd mobile && npm install"
echo ""
echo "   # NL→SQL Service"
echo "   cd backend/nlp-service && mvn clean install"
echo ""
echo "4. Start development:"
echo "   # Frontend: npm run dev"
echo "   # Desktop: python desktop/launch_glass_db_manager.py"
echo "   # Mobile: cd mobile && npm run ios/android"
echo "   # NL→SQL: cd backend/nlp-service && mvn spring-boot:run"
echo ""
echo "📖 For detailed next steps, see:"
echo "   - README.md (updated platform documentation)"
echo "   - CONSOLIDATION_COMPLETE.md (consolidation summary)"
echo ""
echo "🚀 Ready to build the ultimate database management platform!"
echo ""
