server:
  port: 9098
logging:
  level:
    root: INFO
    sample:
      mybatis:
        mapper: TRACE
    org:
      hibernate: error
zapier_enabled: true
email_enabled: true
sms_enabled: false
envname: TEST7 NEO
message_subject: "Billpro Service Monitor alert"
email:
    sender_email: billpro2021@gmail.com
    sender_password: 2KUyhyKuj4PJdPXyxWn3/w==
    test_host: smtp.gmail.com
    host: localhost
    port: 587
    ssl: true
    auth: true
    recipients: "michael.son@teliacompany.com;shahar.solomon@teliacompany.com"
    zapier_recipients: "michael.son@billpro-software.com;shacharsol@gmail.com;shahar.solomon@billpro-software.com"
    starttlsenable: true
    testmode: true
    from: "Billpro Service Monitor"
twilio:
      sender: +16672223821
      sid: AC000d06ee5da99db13312a078a7bf71b7
      token: 34bd2f22429942c0f032f3019945cf0f
      recipients: ["+972545253534"]
sms:
  envname: AT
  service:
     name: mdwc
     url: "http://ninjadk-testsvr.han.telia.se:7082/NinjaMDWCInterface"
     requests: [ MDWC_SendMessage]
  recipients: "04528270376"
sanity-app:
  services:
   - { name: nsl_sta, type: nsl, url: "http://dk001neosta001.gad.teliasonera.net:7001/",  requests: [ GetAvailableTelephoneNumbers ]}
   - { name: nsl_at, type: nsl, url: "http://dk001neoat001.gad.teliasonera.net:7001/",  requests: [ GetAvailableTelephoneNumbers ] }
   - { name: nsl_stb, type: nsl, url: "http://dk001neostb001.gad.teliasonera.net:7001/",  requests: [ GetAvailableTelephoneNumbers ] }

time-based-monitoring:
  enabled: true
  default-timeout-seconds: 30
scheduler:
  period: PT30M
mybatis:
  type-aliases-package: com.bsl.service.monitor.sanity.db
  type-handlers-package: com.bsl.service.monitor.sanity.db
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
