server:
  port: 9098

logging:
  level:
    root: INFO
    com.bsl.service.monitor: DEBUG

spring:
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/05764a73-8c6f-4538-83cd-413f1e1b5665/v2.0

# Local development settings
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# CORS settings for local development
cors:
  allowed-origins: http://localhost:3000