#!/usr/bin/env bash
# tunnel-up.sh — expose the local sdlc-cc gateway at a real https URL
# via a Cloudflare Tunnel. Free, no VPS, real TLS at *.sdlc.cc.
#
# Prereqs (one-time, manual because they open a browser):
#   1. brew install cloudflared (already done if this script is here)
#   2. cloudflared tunnel login
#      → browser → pick the sdlc.cc zone → cert.pem written to
#        ~/.cloudflared/cert.pem
#
# After that, this script:
#   - creates the tunnel if absent
#   - writes ~/.cloudflared/config.yml binding HOSTNAME → localhost:8080
#   - routes the public DNS record at HOSTNAME via cloudflared
#   - launches the tunnel in the foreground (Ctrl-C to stop)
#
# Idempotent: re-runs reuse an existing tunnel + DNS record.

set -euo pipefail

HOSTNAME="${HOSTNAME:-api.sdlc.cc}"
TUNNEL_NAME="${TUNNEL_NAME:-sdlc-gateway}"
TARGET="${TARGET:-http://localhost:8080}"

if [[ -t 1 ]]; then
  C_BOLD=$'\e[1m'; C_RED=$'\e[31m'; C_GRN=$'\e[32m'; C_YEL=$'\e[33m'; C_RST=$'\e[0m'
else
  C_BOLD=; C_RED=; C_GRN=; C_YEL=; C_RST=
fi
ok()   { printf "${C_GRN}  ✓${C_RST} %s\n" "$*"; }
warn() { printf "${C_YEL}  ⚠${C_RST} %s\n" "$*"; }
fail() { printf "${C_RED}  ✗${C_RST} %s\n" "$*" >&2; exit 1; }
step() { printf "\n${C_BOLD}▸ %s${C_RST}\n" "$*"; }

# ─── preflight ────────────────────────────────────────────────────
step "Preflight"
command -v cloudflared >/dev/null || fail "cloudflared not found — brew install cloudflared"
[[ -f ~/.cloudflared/cert.pem ]] || fail "no cert.pem — run: cloudflared tunnel login (opens browser)"
curl -sSf "$TARGET/health" >/dev/null 2>&1 || fail "$TARGET unreachable — bring up the gateway first (./scripts/dev-up.sh)"
ok "cert.pem present"
ok "$TARGET reachable"

# ─── create or reuse tunnel ───────────────────────────────────────
step "Tunnel"
if cloudflared tunnel list 2>/dev/null | grep -q " $TUNNEL_NAME "; then
  TUNNEL_UUID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2==n {print $1}')"
  ok "reusing tunnel $TUNNEL_NAME ($TUNNEL_UUID)"
else
  cloudflared tunnel create "$TUNNEL_NAME"
  TUNNEL_UUID="$(cloudflared tunnel list | awk -v n="$TUNNEL_NAME" '$2==n {print $1}')"
  ok "created tunnel $TUNNEL_NAME ($TUNNEL_UUID)"
fi

CREDS_FILE="$HOME/.cloudflared/$TUNNEL_UUID.json"
[[ -f "$CREDS_FILE" ]] || fail "credentials missing at $CREDS_FILE"

# ─── config ───────────────────────────────────────────────────────
step "Config"
cat >"$HOME/.cloudflared/config.yml" <<EOF
# Generated by scripts/tunnel-up.sh — re-running this script overwrites.
tunnel: $TUNNEL_UUID
credentials-file: $CREDS_FILE

ingress:
  - hostname: $HOSTNAME
    service: $TARGET
  - service: http_status:404
EOF
ok "wrote ~/.cloudflared/config.yml"

# ─── DNS route ────────────────────────────────────────────────────
step "DNS route"
if cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" 2>&1 | tee /tmp/tunnel-dns-out | grep -q "already exists\|Added CNAME"; then
  ok "DNS for $HOSTNAME → tunnel $TUNNEL_UUID"
else
  cat /tmp/tunnel-dns-out
  warn "couldn't confirm DNS update — verify in Cloudflare dashboard"
fi

# ─── run ──────────────────────────────────────────────────────────
step "Starting tunnel (Ctrl-C to stop)"
printf "\n  Public URL: ${C_BOLD}https://%s${C_RST}\n" "$HOSTNAME"
printf "  Origin:     %s\n\n" "$TARGET"
exec cloudflared tunnel run "$TUNNEL_NAME"
