import { Navbar } from '../components/Navbar'
import { Footer } from '../components/Footer'
import { useDocumentMeta } from '../components/useDocumentMeta'
import { CodeBlock } from '../components/CodeBlock'

const yamlExample = `# pushci.yml — generated by \`pushci init\`
stages:
  - install:
      checks:
        - name: pnpm install --frozen-lockfile
  - test:
      parallel: true
      checks:
        - name: pnpm lint
        - name: pnpm typecheck
        - name: pnpm test
  - build:
      checks:
        - name: pnpm build
  - deploy:
      needs: [test, build]
      target: cloudflare-pages
      env: production`

const apiExample = `curl https://api.pushci.dev/v1/runs \\
  -H "Authorization: Bearer $PUSHCI_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{
    "repo": "acme/api",
    "branch": "main",
    "commit": "a3f1c2d"
  }'

# → 201 Created
# {
#   "id": "run_8f2a",
#   "status": "queued",
#   "dashboard": "https://app.pushci.dev/runs/run_8f2a"
# }`

const webhookExample = `// Webhook payload — POST to your endpoint on every run event
{
  "event": "run.completed",
  "run": {
    "id": "run_8f2a",
    "status": "success",
    "duration_ms": 105210,
    "stages": [ /* ... */ ]
  },
  "commit": "a3f1c2d",
  "repo": "acme/api"
}

// Verify via HMAC-SHA256 signature:
// X-PushCI-Signature: sha256=<hex>`

export default function DevelopersPage() {
  useDocumentMeta({
    title: 'Developers — PushCI',
    description: 'Quickstart, CLI, YAML reference, API, and webhooks.',
    canonical: 'https://pushci.dev/developers',
  })

  return (
    <div className="min-h-screen bg-root">
      <Navbar />
      <section className="pt-28 sm:pt-36 pb-12 px-6">
        <div className="mx-auto max-w-[920px]">
          <p className="text-body font-medium text-accent tracking-wide uppercase">Developers</p>
          <h1 className="mt-3 text-4xl sm:text-5xl font-extrabold tracking-tight text-t1">
            Ship in 60 seconds
          </h1>
          <p className="mt-5 text-lg text-t2 leading-relaxed max-w-xl">
            Install the CLI, run <code className="font-mono text-accent">pushci init</code>,
            push. No YAML to hand-write, no runner to provision.
          </p>
        </div>
      </section>

      <section className="pb-16 px-6">
        <div className="mx-auto max-w-[920px] space-y-16">
          <div>
            <h2 className="text-2xl font-bold text-t1 mb-3">1. Install</h2>
            <CodeBlock code="npm i -g pushci" language="bash" />
            <p className="mt-3 text-sm text-t3">
              Also available via <code className="font-mono text-t2">brew install pushci/tap/pushci</code>
              {' '}or <code className="font-mono text-t2">curl -sSf pushci.dev/install | sh</code>.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-t1 mb-3">2. Initialize</h2>
            <CodeBlock code="cd your-repo && pushci init" language="bash" />
            <p className="mt-3 text-sm text-t2">
              Detects your stack (35 languages, 39 frameworks), generates <code className="font-mono text-accent">pushci.yml</code>,
              wires a pre-push hook. Zero prompts if the stack is unambiguous.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-t1 mb-3">3. Example pipeline</h2>
            <CodeBlock code={yamlExample} language="yaml" />
            <p className="mt-3 text-sm text-t3">
              Full field reference at <a href="/docs/pushci-yaml" className="text-accent underline">/docs/pushci-yaml</a>.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-t1 mb-3">REST API</h2>
            <p className="text-t2 text-sm mb-4">
              Trigger runs, fetch status, stream logs. Token auth via
              {' '}<code className="font-mono text-accent">pushci auth login</code>.
            </p>
            <CodeBlock code={apiExample} language="bash" />
          </div>

          <div>
            <h2 className="text-2xl font-bold text-t1 mb-3">Webhooks</h2>
            <p className="text-t2 text-sm mb-4">
              Subscribe to run lifecycle events. HMAC-signed. Retry with exponential backoff.
            </p>
            <CodeBlock code={webhookExample} language="json" />
          </div>

          <div>
            <h2 className="text-2xl font-bold text-t1 mb-3">SDKs</h2>
            <ul className="text-t2 text-sm space-y-2">
              <li>• <code className="font-mono text-accent">@pushci/sdk</code> — TypeScript/Node.js</li>
              <li>• <code className="font-mono text-accent">pushci-go</code> — Go client</li>
              <li>• REST spec: <a href="/docs" className="underline">OpenAPI 3.1</a></li>
              <li>• MCP server: <code className="font-mono text-accent">npx @pushci/mcp</code> — exposes tools to Claude, Cursor, any MCP host</li>
            </ul>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
