import { lazy } from 'react'

export const Dashboard = lazy(() => import('../pages/Dashboard').then(m => ({ default: m.Dashboard })))
export const AlertQueue = lazy(() => import('../pages/AlertQueue').then(m => ({ default: m.AlertQueue })))
export const AlertDetailPage = lazy(() => import('../pages/AlertDetailPage').then(m => ({ default: m.AlertDetailPage })))
export const ScreenEntity = lazy(() => import('../pages/ScreenEntity').then(m => ({ default: m.ScreenEntity })))
export const Configuration = lazy(() => import('../pages/Configuration').then(m => ({ default: m.Configuration })))
export const Analytics = lazy(() => import('../pages/Analytics').then(m => ({ default: m.Analytics })))
export const AuditTrail = lazy(() => import('../pages/AuditTrail').then(m => ({ default: m.AuditTrail })))
export const Monitoring = lazy(() => import('../pages/Monitoring').then(m => ({ default: m.Monitoring })))
export const BatchJobs = lazy(() => import('../pages/BatchJobs').then(m => ({ default: m.BatchJobs })))
export const SanctionsLists = lazy(() => import('../pages/SanctionsLists').then(m => ({ default: m.SanctionsLists })))
export const SanctionsListsSettings = lazy(() => import('../pages/SanctionsListsSettings').then(m => ({ default: m.SanctionsListsSettings })))
export const Login = lazy(() => import('../pages/Login').then(m => ({ default: m.Login })))
export const Signup = lazy(() => import('../pages/Signup').then(m => ({ default: m.Signup })))
export const LandingPage = lazy(() => import('../pages/marketing/LandingPage'))
export const BillingPage = lazy(() => import('../pages/billing/BillingPage'))
export const Onboarding = lazy(() => import('../pages/Onboarding'))
export const AdminTenants = lazy(() => import('../pages/admin/Tenants'))
export const TenantDetail = lazy(() => import('../pages/admin/TenantDetail'))
export const SystemHealth = lazy(() => import('../pages/admin/SystemHealth'))
export const ListSyncHealth = lazy(() => import('../pages/admin/ListSyncHealth'))
export const DataSources = lazy(() => import('../pages/admin/DataSources'))
export const AdminOperations = lazy(() => import('../pages/admin/Operations'))
export const AdminScheduledTasks = lazy(() => import('../pages/admin/ScheduledTasks'))
export const AdminLeads = lazy(() => import('../pages/admin/Leads'))
export const Team = lazy(() => import('../pages/Team'))
export const TermsOfService = lazy(() => import('../pages/legal/TermsOfService'))
export const PrivacyPolicy = lazy(() => import('../pages/legal/PrivacyPolicy'))
export const ForgotPassword = lazy(() => import('../pages/ForgotPassword'))
export const ListsMarketplace = lazy(() => import('../pages/ListsMarketplace').then(m => ({ default: m.ListsMarketplace })))
export const APIKeysPage = lazy(() => import('../pages/APIKeys'))
export const WebhooksPage = lazy(() => import('../pages/Webhooks'))
export const CryptoScreening = lazy(() => import('../pages/CryptoScreening'))
export const TxnScreening = lazy(() => import('../pages/TxnScreening'))
export const MFASetup = lazy(() => import('../pages/MFASetup'))
export const ResetPassword = lazy(() => import('../pages/ResetPassword'))
export const TaskHistory = lazy(() => import('../pages/TaskHistory'))
export const DataCoverage = lazy(() => import('../pages/marketing/DataCoverage'))
export const SourceHealth = lazy(() => import('../pages/SourceHealth').then(m => ({ default: m.SourceHealth })))
export const SecurityPage = lazy(() => import('../pages/trust/SecurityPage'))
export const CompliancePage = lazy(() => import('../pages/trust/CompliancePage'))
export const AboutPage = lazy(() => import('../pages/trust/AboutPage'))
export const ProductPage = lazy(() => import('../pages/ProductPage'))
export const ContactPage = lazy(() => import('../pages/ContactPage'))
export const DocsPage = lazy(() => import('../pages/DocsPage'))
export const BlogPage = lazy(() => import('../pages/marketing/BlogPage'))
export const CareersPage = lazy(() => import('../pages/marketing/CareersPage'))
export const ChangelogPage = lazy(() => import('../pages/marketing/ChangelogPage'))
export const StatusPage = lazy(() => import('../pages/marketing/StatusPage'))
export const CompareWorldCheckPage = lazy(() => import('../pages/marketing/CompareWorldCheckPage'))
export const BenchmarksPage = lazy(() => import('../pages/marketing/BenchmarksPage'))
export const DPAPage = lazy(() => import('../pages/legal/DPAPage'))
export const NotFoundPage = lazy(() => import('../pages/NotFoundPage'))
export const CustomerImport = lazy(() => import('../pages/monitoring/CustomerImport'))
export const AutomationRules = lazy(() => import('../pages/automation/AutomationRules'))
export const SARFormPage = lazy(() => import('../pages/reporting/SARForm').then(m => ({ default: m.SARForm })))
