-- Seed: OpenSyber first-party marketplace skills
-- These are real, verified skills published by the OpenSyber team.
-- Status: approved (pre-verified as first-party)

INSERT OR IGNORE INTO skills (id, slug, name, description, category, author_id, current_version, verification_status, verified_at, install_count, rating_avg, rating_count, tier, price_cents, manifest, is_featured, is_certified, created_at)
VALUES
  -- Security Skills
  ('sk_secret_scanner', 'secret-scanner', 'Secret Scanner', 'Scans your codebase for hardcoded API keys, passwords, tokens, and credentials. Supports 120+ secret patterns including AWS, GCP, Azure, GitHub, Stripe, and database connection strings. Reports findings with file path, line number, and remediation guidance.', 'security', 'opensyber', '1.2.0', 'approved', datetime('now'), 4821, 4.8, 312, 'free', 0, '{"name":"Secret Scanner","slug":"secret-scanner","version":"1.2.0","description":"Scan codebase for hardcoded secrets","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./"],"env":[]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  ('sk_dep_audit', 'dependency-auditor', 'Dependency Auditor', 'Continuously monitors installed packages for known CVEs using the OSV and NVD databases. Generates SBOM (Software Bill of Materials) in CycloneDX format. Flags critical and high severity vulnerabilities with upgrade paths and patching recommendations.', 'security', 'opensyber', '2.0.1', 'approved', datetime('now'), 3654, 4.7, 248, 'free', 0, '{"name":"Dependency Auditor","slug":"dependency-auditor","version":"2.0.1","description":"Monitor dependencies for CVEs","entrypoint":"index.js","permissions":{"network":["osv.dev","services.nvd.nist.gov"],"filesystem":["./"],"env":[]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  ('sk_container_scan', 'container-hardening', 'Container Hardening', 'Audits Docker containers and Kubernetes pods for security misconfigurations. Checks for root user execution, excessive capabilities, missing seccomp profiles, writable filesystems, and exposed ports. Generates CIS Docker Benchmark compliance reports.', 'security', 'opensyber', '1.4.0', 'approved', datetime('now'), 2187, 4.6, 156, 'pro', 0, '{"name":"Container Hardening","slug":"container-hardening","version":"1.4.0","description":"Audit container security configs","entrypoint":"index.js","permissions":{"network":[],"filesystem":["/var/run/docker.sock","./"],"env":[]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  ('sk_network_monitor', 'network-sentinel', 'Network Sentinel', 'Real-time network traffic analysis for your agent environment. Detects suspicious outbound connections, DNS exfiltration attempts, port scanning, and lateral movement patterns. Integrates with the OpenSyber alert pipeline for instant notifications.', 'security', 'opensyber', '1.1.0', 'approved', datetime('now'), 1893, 4.5, 134, 'free', 0, '{"name":"Network Sentinel","slug":"network-sentinel","version":"1.1.0","description":"Monitor network traffic for threats","entrypoint":"index.js","permissions":{"network":[],"filesystem":["/proc/net/"],"env":[]},"author":"OpenSyber"}', 0, 1, datetime('now')),

  ('sk_iac_scanner', 'iac-scanner', 'IaC Security Scanner', 'Static analysis for Infrastructure as Code templates. Scans Terraform, CloudFormation, Pulumi, and Kubernetes manifests for security misconfigurations, overly permissive IAM policies, unencrypted storage, and public-facing resources before deployment.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 1456, 4.4, 98, 'free', 0, '{"name":"IaC Security Scanner","slug":"iac-scanner","version":"1.0.0","description":"Scan IaC templates for misconfigs","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./"],"env":[]},"author":"OpenSyber"}', 0, 1, datetime('now')),

  ('sk_supply_chain', 'supply-chain-guard', 'Supply Chain Guard', 'Monitors npm, PyPI, and Go module installations for supply chain attack indicators. Detects typosquatting, suspicious postinstall scripts, unexpected network calls, and known malicious packages using the Socket.dev threat feed and OpenSyber threat intelligence.', 'security', 'opensyber', '1.3.0', 'approved', datetime('now'), 2934, 4.9, 201, 'free', 0, '{"name":"Supply Chain Guard","slug":"supply-chain-guard","version":"1.3.0","description":"Detect supply chain attacks in dependencies","entrypoint":"index.js","permissions":{"network":["api.socket.dev"],"filesystem":["./"],"env":["SOCKET_API_KEY"]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  -- Developer Tools
  ('sk_git_guardian', 'git-guardian', 'Git Guardian', 'Pre-commit and pre-push hook enforcement for your repositories. Blocks commits containing secrets, large binary files, or force-pushes to protected branches. Validates commit message format and ensures branch naming conventions.', 'developer', 'opensyber', '1.5.0', 'approved', datetime('now'), 3201, 4.6, 187, 'free', 0, '{"name":"Git Guardian","slug":"git-guardian","version":"1.5.0","description":"Enforce git security policies","entrypoint":"index.js","permissions":{"network":[],"filesystem":[".git/"],"env":[]},"author":"OpenSyber"}', 0, 1, datetime('now')),

  ('sk_api_fuzzer', 'api-fuzzer', 'API Fuzzer', 'Automated API security testing that discovers vulnerabilities by sending malformed requests to your endpoints. Tests for injection flaws, authentication bypasses, rate limit evasion, and OWASP Top 10 API vulnerabilities. Generates detailed reports with proof-of-concept payloads.', 'developer', 'opensyber', '1.0.0', 'approved', datetime('now'), 987, 4.3, 64, 'pro', 0, '{"name":"API Fuzzer","slug":"api-fuzzer","version":"1.0.0","description":"Fuzz test APIs for vulnerabilities","entrypoint":"index.js","permissions":{"network":["localhost"],"filesystem":["./reports/"],"env":["TARGET_URL"]},"author":"OpenSyber"}', 0, 1, datetime('now')),

  ('sk_log_analyzer', 'log-analyzer', 'Log Analyzer', 'Intelligent log parsing and anomaly detection. Ingests syslog, JSON, and structured log formats. Uses statistical analysis to identify unusual patterns, failed authentication spikes, and potential intrusion indicators. Forwards critical findings to the OpenSyber alert pipeline.', 'developer', 'opensyber', '2.1.0', 'approved', datetime('now'), 2456, 4.5, 143, 'free', 0, '{"name":"Log Analyzer","slug":"log-analyzer","version":"2.1.0","description":"Parse and analyze logs for anomalies","entrypoint":"index.js","permissions":{"network":[],"filesystem":["/var/log/","./logs/"],"env":[]},"author":"OpenSyber"}', 0, 1, datetime('now')),

  -- Communication Skills
  ('sk_slack_alerts', 'slack-security-alerts', 'Slack Security Alerts', 'Forward OpenSyber security events to Slack channels with rich formatting. Supports severity-based routing, thread grouping for related incidents, and interactive buttons for quick acknowledgment and escalation. Configurable alert thresholds and quiet hours.', 'communication', 'opensyber', '1.2.0', 'approved', datetime('now'), 4102, 4.7, 289, 'free', 0, '{"name":"Slack Security Alerts","slug":"slack-security-alerts","version":"1.2.0","description":"Forward security alerts to Slack","entrypoint":"index.js","permissions":{"network":["hooks.slack.com"],"filesystem":[],"env":["SLACK_WEBHOOK_URL"]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  ('sk_pagerduty', 'pagerduty-escalation', 'PagerDuty Escalation', 'Automatic incident escalation to PagerDuty when critical security events are detected. Maps OpenSyber severity levels to PagerDuty urgency tiers. Supports incident deduplication, auto-resolution on remediation, and custom routing rules per alert type.', 'communication', 'opensyber', '1.0.0', 'approved', datetime('now'), 1234, 4.4, 78, 'pro', 0, '{"name":"PagerDuty Escalation","slug":"pagerduty-escalation","version":"1.0.0","description":"Escalate critical events to PagerDuty","entrypoint":"index.js","permissions":{"network":["events.pagerduty.com"],"filesystem":[],"env":["PAGERDUTY_ROUTING_KEY"]},"author":"OpenSyber"}', 0, 1, datetime('now')),

  -- Productivity Skills
  ('sk_compliance_report', 'compliance-reporter', 'Compliance Reporter', 'Automated compliance report generation for SOC 2, ISO 27001, HIPAA, and GDPR frameworks. Collects evidence from your OpenSyber agent, maps controls to framework requirements, and exports PDF reports with executive summaries suitable for auditor review.', 'productivity', 'opensyber', '1.1.0', 'approved', datetime('now'), 1876, 4.6, 112, 'pro', 0, '{"name":"Compliance Reporter","slug":"compliance-reporter","version":"1.1.0","description":"Generate compliance audit reports","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./reports/"],"env":[]},"author":"OpenSyber"}', 0, 1, datetime('now'));
