-- Sprint 27: Agent monitoring skills (cursor-monitor, secret-vault-bridge, siem-forwarder)
-- These are the 3 priority first-party skills for the ecosystem launch.

INSERT OR IGNORE INTO skills (id, slug, name, description, category, author_id, current_version, verification_status, verified_at, install_count, rating_avg, rating_count, tier, price_cents, manifest, is_featured, is_certified, created_at)
VALUES
  ('sk_cursor_monitor', 'cursor-monitor', 'Cursor Monitor', 'Cursor IDE-specific telemetry for AI agent security monitoring. Tracks file edits made by Cursor AI, AI completion acceptance rates, context window usage, and prompt injection attempts. Correlates Cursor activity with file sensitivity classifications to detect unauthorized access to credentials, configs, and production code.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 1847, 4.7, 142, 'free', 0, '{"name":"Cursor Monitor","slug":"cursor-monitor","version":"1.0.0","description":"Monitor Cursor AI agent file access and completions","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./"],"env":[]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  ('sk_vault_bridge', 'secret-vault-bridge', 'Secret Vault Bridge', 'Connects OpenSyber agent activity monitoring to HashiCorp Vault and AWS Secrets Manager. When an agent accesses a secret, the bridge checks if the secret was retrieved through the approved vault workflow or accessed directly from disk. Flags direct credential file access as policy violations and generates JIT access requests for vault-managed secrets.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 923, 4.5, 67, 'pro', 0, '{"name":"Secret Vault Bridge","slug":"secret-vault-bridge","version":"1.0.0","description":"Bridge agent activity to HashiCorp Vault and AWS Secrets Manager","entrypoint":"index.js","permissions":{"network":["vault.example.com","secretsmanager.us-east-1.amazonaws.com"],"filesystem":[],"env":["VAULT_ADDR","VAULT_TOKEN"]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  ('sk_siem_forwarder', 'siem-forwarder', 'SIEM Forwarder', 'Streams OpenSyber agent security events to your SIEM platform in real-time. Supports Splunk HEC, Datadog Logs, and Elastic Common Schema (ECS) formats. Maps OpenSyber event types to SIEM-native severity levels, adds enrichment fields (agent name, developer, workspace), and batches events for efficient delivery with configurable flush intervals.', 'security', 'opensyber', '1.1.0', 'approved', datetime('now'), 2156, 4.6, 178, 'pro', 0, '{"name":"SIEM Forwarder","slug":"siem-forwarder","version":"1.1.0","description":"Stream agent events to Splunk, Datadog, or Elastic","entrypoint":"index.js","permissions":{"network":["*.splunkcloud.com","http-intake.logs.datadoghq.com","*.elastic.co"],"filesystem":[],"env":["SIEM_ENDPOINT","SIEM_TOKEN","SIEM_FORMAT"]},"author":"OpenSyber"}', 1, 1, datetime('now'));
