-- Seed: OpenSyber new security skills (CI/CD & AI agent protection)
-- All new skills — install_count 0, rating_avg 0, rating_count 0

INSERT OR IGNORE INTO skills (id, slug, name, description, category, author_id, current_version, verification_status, verified_at, install_count, rating_avg, rating_count, tier, price_cents, manifest, is_featured, is_certified, created_at)
VALUES
  ('sk_prompt_guard', 'github-actions-ai-prompt-guard', 'GitHub Actions AI Prompt Guard', 'Scans workflow YAML for AI action integrations and detects when untrusted user input flows into AI agent prompts. Monitors for prompt injection in GitHub issues, PR descriptions, and comments targeting Claude Code Actions, Gemini CLI, and Codex. Scans CLAUDE.md and .cursor/rules for injection payloads in PR diffs.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 0, 0, 0, 'free', 0, '{"name":"GitHub Actions AI Prompt Guard","slug":"github-actions-ai-prompt-guard","version":"1.0.0","description":"Detect prompt injection in CI/CD AI actions","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./",".github/"],"env":[]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  ('sk_trigger_audit', 'workflow-trigger-auditor', 'Workflow Trigger Auditor', 'Scans all GitHub Actions workflow files for dangerous trigger configurations. Detects pull_request_target with checkout of PR head, workflow_run with elevated permissions, and issue/comment triggers with write access. Generates severity-scored findings with exact line numbers and auto-generates hardened workflow replacements.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 0, 0, 0, 'free', 0, '{"name":"Workflow Trigger Auditor","slug":"workflow-trigger-auditor","version":"1.0.0","description":"Audit workflow triggers for dangerous configs","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./",".github/"],"env":[]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  ('sk_perms_audit', 'workflow-permissions-auditor', 'Workflow Permissions Auditor', 'Audits GitHub Actions workflow permissions against the principle of least privilege. Identifies jobs with write-all or missing permissions blocks, recommends minimum permission sets based on actions used, and flags contents:write and id-token:write without explicit justification.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 0, 0, 0, 'free', 0, '{"name":"Workflow Permissions Auditor","slug":"workflow-permissions-auditor","version":"1.0.0","description":"Enforce least-privilege workflow permissions","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./",".github/"],"env":[]},"author":"OpenSyber"}', 0, 1, datetime('now')),

  ('sk_transitive_scan', 'transitive-action-scanner', 'Transitive Action Scanner', 'Resolves the full transitive dependency tree for every GitHub Action used in your workflows. Builds a complete dependency graph, SHA-pins the entire tree (not just top-level), and monitors all transitive dependencies against threat intelligence feeds. Catches supply chain attacks hiding in nested action references.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 0, 0, 0, 'free', 0, '{"name":"Transitive Action Scanner","slug":"transitive-action-scanner","version":"1.0.0","description":"Resolve and pin transitive action dependencies","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./",".github/"],"env":[]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  ('sk_instruction_guard', 'agent-instruction-guardian', 'Agent Instruction File Guardian', 'Monitors CLAUDE.md, .claude/, AGENTS.md, .cursor/rules, and .windsurfrules for changes in pull requests. Scans for prompt injection patterns including instructions to ignore previous context, exfiltrate secrets, modify permissions, or install software. Detects hidden text via HTML comments, zero-width characters, and invisible Unicode.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 0, 0, 0, 'free', 0, '{"name":"Agent Instruction File Guardian","slug":"agent-instruction-guardian","version":"1.0.0","description":"Guard agent instruction files from prompt injection","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./",".github/"],"env":[]},"author":"OpenSyber"}', 1, 1, datetime('now')),

  ('sk_ide_guard', 'ide-extension-guardian', 'IDE Extension Guardian', 'Monitors publish tokens for VS Code Marketplace, OpenVSX, and npm for token reuse across contexts. Detects when extension publish workflows use long-lived PATs instead of OIDC, alerts on off-hours version publishes, and scans extension bundles for postinstall scripts and unexpected binary payloads.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 0, 0, 0, 'free', 0, '{"name":"IDE Extension Guardian","slug":"ide-extension-guardian","version":"1.0.0","description":"Monitor IDE extension publish security","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./"],"env":[]},"author":"OpenSyber"}', 0, 1, datetime('now')),

  ('sk_oidc_monitor', 'oidc-trust-monitor', 'OIDC Trust Monitor', 'Audits GitHub Actions OIDC configurations for overprivileged cloud role assumptions. Validates that role assumption is scoped to specific repos and branches, flags wildcard conditions in AWS/GCP/Azure OIDC trust policies, and monitors cloud event logs for unexpected OIDC-sourced role assumptions.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 0, 0, 0, 'free', 0, '{"name":"OIDC Trust Monitor","slug":"oidc-trust-monitor","version":"1.0.0","description":"Audit OIDC trust policies for overprivileged roles","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./",".github/"],"env":[]},"author":"OpenSyber"}', 0, 1, datetime('now'));
