-- Seed: Self-hosted security skills (Superagent Guard, Ruflo AIDefence, Voicebox)
-- All run locally — zero external API calls, zero data leaving the VM

INSERT OR IGNORE INTO skills (id, slug, name, description, category, author_id, current_version, verification_status, verified_at, install_count, rating_avg, rating_count, tier, price_cents, manifest, is_featured, is_certified, created_at)
VALUES
  ('sk_prompt_guard_v2', 'prompt-guard', 'Prompt Guard', 'Self-hosted prompt injection detection using Superagent guard-1.7B model via local Ollama. Classifies every LLM input as pass/block with auto-chunking and parallel processing. Zero external API calls — all inference runs on your VM.', 'security', 'opensyber', '2.0.0', 'approved', datetime('now'), 0, 0, 0, 'free', 0, '{"name":"Prompt Guard","slug":"prompt-guard","version":"2.0.0","description":"Self-hosted prompt injection detection via Ollama","entrypoint":"index.js","permissions":{"network":["127.0.0.1"],"filesystem":["./data/"],"env":["OLLAMA_URL"]},"author":"opensyber","minAgentVersion":"0.2.0"}', 1, 1, datetime('now')),

  ('sk_ruflo_aidefence', 'ruflo-aidefence', 'Ruflo AIDefence', 'Agent input sanitization powered by Ruflo (claude-flow) AIDefence module. 27 regex patterns for prompt injection, path traversal, and command injection detection. Runs in under 1ms with zero network calls — pure local pattern matching.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 0, 0, 0, 'free', 0, '{"name":"Ruflo AIDefence","slug":"ruflo-aidefence","version":"1.0.0","description":"Local input sanitization — injection, traversal, command patterns","entrypoint":"index.js","permissions":{"network":[],"filesystem":["./data/"],"env":[]},"author":"opensyber","minAgentVersion":"0.2.0"}', 1, 1, datetime('now')),

  ('sk_voice_synthesis', 'voice-synthesis', 'Voice Synthesis', 'Self-hosted voice synthesis via Voicebox FastAPI over Tailscale mesh. Generates spoken security briefings, audio alerts, and incident narrations. Connects to a shared GPU instance — no external TTS API, all audio on your infrastructure.', 'security', 'opensyber', '1.0.0', 'approved', datetime('now'), 0, 0, 0, 'pro', 2900, '{"name":"Voice Synthesis","slug":"voice-synthesis","version":"1.0.0","description":"Self-hosted TTS for security briefings via Voicebox","entrypoint":"index.js","permissions":{"network":["voicebox.opensyber.ts.net"],"filesystem":["./data/","./audio/"],"env":["VOICEBOX_URL"]},"author":"opensyber","minAgentVersion":"0.2.0"}', 0, 1, datetime('now'));

-- Update existing prompt-guard to point to v2
UPDATE skills SET current_version = '2.0.0', manifest = '{"name":"Prompt Guard","slug":"prompt-guard","version":"2.0.0","description":"Self-hosted prompt injection detection via Ollama","entrypoint":"index.js","permissions":{"network":["127.0.0.1"],"filesystem":["./data/"],"env":["OLLAMA_URL"]},"author":"opensyber","minAgentVersion":"0.2.0"}' WHERE slug = 'prompt-guard' AND id != 'sk_prompt_guard_v2';
