package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

// FixPRRequest contains parameters for creating a fix PR via GitHub API.
type FixPRRequest struct {
	Owner       string `json:"owner"`
	Repo        string `json:"repo"`
	BaseBranch  string `json:"base_branch"`
	GitHubToken string `json:"github_token"`
}

// FixPRResponse describes the created pull request.
type FixPRResponse struct {
	PRURL    string `json:"pr_url"`
	PRNumber int    `json:"pr_number"`
	Branch   string `json:"branch"`
	Title    string `json:"title"`
}

// CreateFixPR handles POST /api/v1/findings/{id}/fix/pr.
func (h *Handlers) CreateFixPR(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonError(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	id, err := extractFindingIDFromPRPath(r.URL.Path)
	if err != nil {
		jsonError(w, "invalid finding ID", http.StatusBadRequest)
		return
	}

	var req FixPRRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, "invalid JSON", http.StatusBadRequest)
		return
	}

	if req.GitHubToken == "" {
		jsonError(w, "github_token is required", http.StatusBadRequest)
		return
	}
	if req.Owner == "" || req.Repo == "" {
		jsonError(w, "owner and repo are required", http.StatusBadRequest)
		return
	}
	if req.BaseBranch == "" {
		req.BaseBranch = "main"
	}

	findings, err := h.db.ListFindings("")
	if err != nil {
		jsonError(w, err.Error(), http.StatusInternalServerError)
		return
	}

	var finding *findingRef
	for _, f := range findings {
		if f.ID == id {
			finding = &findingRef{
				ID:       f.ID,
				Title:    f.Title,
				Category: f.Category,
			}
			break
		}
	}
	if finding == nil {
		jsonError(w, "finding not found", http.StatusNotFound)
		return
	}

	steps, autoFixable, _ := fixStepsForFinding(finding.Category, finding.Title)
	branch := fmt.Sprintf("pipewarden/fix-%s-%d", sanitizeBranchSegment(finding.Category), finding.ID)
	title := fmt.Sprintf("[PipeWarden] Fix: %s", finding.Title)
	body := buildPRBody(steps, finding.ID)

	_, baseSHA, err := getRepoDefaultBranch(req.Owner, req.Repo, req.BaseBranch, req.GitHubToken)
	if err != nil {
		jsonError(w, fmt.Sprintf("failed to get base branch: %s", err), http.StatusBadGateway)
		return
	}

	if err := createGitHubBranch(req.Owner, req.Repo, branch, baseSHA, req.GitHubToken); err != nil {
		jsonError(w, fmt.Sprintf("failed to create branch: %s", err), http.StatusBadGateway)
		return
	}

	if autoFixable && strings.Contains(strings.ToLower(finding.Category), "supply-chain") {
		_ = ensureDependabotConfig(req.Owner, req.Repo, branch, req.GitHubToken)
	}

	prNum, prURL, err := createGitHubPR(req.Owner, req.Repo, title, body, branch, req.BaseBranch, req.GitHubToken)
	if err != nil {
		jsonError(w, fmt.Sprintf("failed to create PR: %s", err), http.StatusBadGateway)
		return
	}

	jsonOK(w, FixPRResponse{
		PRURL:    prURL,
		PRNumber: prNum,
		Branch:   branch,
		Title:    title,
	})
}

// findingRef holds the minimal data needed to build a fix PR.
type findingRef struct {
	ID       int64
	Title    string
	Category string
}

func extractFindingIDFromPRPath(path string) (int64, error) {
	trimmed := strings.TrimPrefix(path, "/api/v1/findings/")
	trimmed = strings.TrimSuffix(trimmed, "/fix/pr")
	return strconv.ParseInt(trimmed, 10, 64)
}

func sanitizeBranchSegment(s string) string {
	return strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			return r
		}
		return '-'
	}, strings.ToLower(s))
}

func buildPRBody(steps []string, findingID int64) string {
	var sb strings.Builder
	sb.WriteString("## PipeWarden Automated Fix\n\n")
	sb.WriteString("### Remediation Checklist\n\n")
	for _, step := range steps {
		fmt.Fprintf(&sb, "- [ ] %s\n", step)
	}
	fmt.Fprintf(&sb, "\n---\nGenerated by [PipeWarden](https://pipewarden.com) for finding #%d\n", findingID)
	return sb.String()
}
