name = "quantumbeam-marketing"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[env.production]
name = "quantumbeam-marketing"
pages_build_output_dir = ".next"

[env.preview]
name = "quantumbeam-marketing-preview"
pages_build_output_dir = ".next"