name = "mcpoverflow-io"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "mcpoverflow-io"
routes = [
  { pattern = "mcpoverflow.io/*", zone_name = "mcpoverflow.io" },
  { pattern = "www.mcpoverflow.io/*", zone_name = "mcpoverflow.io" }
]