import type { WorkflowTemplate } from '../../../../../../packages/shared/src/types/workflow-dsl';

export const GOVERNANCE_TEMPLATES: WorkflowTemplate[] = [
	{
		id: 'empty-group-cleanup',
		name: 'Empty Group Cleanup',
		description: 'Find and remove security/distribution groups with zero members.',
		category: 'governance',
		triggerType: 'schedule',
		tags: ['groups', 'cleanup', 'hygiene'],
		estimatedDurationMinutes: 10,
		steps: [
			{ id: 'scan', type: 'action', name: 'Scan all groups', config: { graphAction: 'listGroups', includeMembers: true }, onSuccess: 'filter' },
			{ id: 'filter', type: 'condition', name: 'Filter empty groups', config: { memberCount: 0, excludeDynamic: true }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Admin approval to delete', config: { approverRole: 'admin' }, onSuccess: 'delete' },
			{ id: 'delete', type: 'action', name: 'Delete empty groups', config: { graphAction: 'deleteGroup' }, onSuccess: 'report' },
			{ id: 'report', type: 'notification', name: 'Cleanup summary', config: { channel: 'email' } },
		],
	},
	{
		id: 'guest-access-review',
		name: 'Guest Access Review',
		description: 'Quarterly review of all guest accounts: validate business need or remove.',
		category: 'governance',
		triggerType: 'schedule',
		tags: ['guest', 'access-review', 'compliance'],
		estimatedDurationMinutes: 30,
		steps: [
			{ id: 'list', type: 'action', name: 'List all guest users', config: { graphAction: 'listUsers', userType: 'guest' }, onSuccess: 'enrich' },
			{ id: 'enrich', type: 'action', name: 'Enrich with last activity', config: { graphAction: 'getSignInActivity' }, onSuccess: 'review' },
			{ id: 'review', type: 'approval', name: 'Sponsor reviews each guest', config: { approverRole: 'admin', perUser: true }, onSuccess: 'remove' },
			{ id: 'remove', type: 'action', name: 'Remove unapproved guests', config: { graphAction: 'deleteUser' }, onSuccess: 'audit' },
			{ id: 'audit', type: 'notification', name: 'Log review to audit trail', config: { channel: 'audit' } },
		],
	},
	{
		id: 'sharing-link-audit',
		name: 'Sharing Link Audit',
		description: 'Audit anonymous and org-wide sharing links in SharePoint and OneDrive.',
		category: 'governance',
		triggerType: 'schedule',
		tags: ['sharepoint', 'sharing', 'data-protection'],
		estimatedDurationMinutes: 25,
		steps: [
			{ id: 'scan', type: 'action', name: 'Scan sharing links', config: { graphAction: 'listSharingLinks', scope: 'anonymous' }, onSuccess: 'classify' },
			{ id: 'classify', type: 'condition', name: 'Classify link risk', config: { riskLevels: ['anonymous', 'org-wide'] }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Admin review risky links', config: { approverRole: 'admin' }, onSuccess: 'revoke' },
			{ id: 'revoke', type: 'action', name: 'Revoke flagged links', config: { graphAction: 'deleteSharingLink' }, onSuccess: 'report' },
			{ id: 'report', type: 'notification', name: 'Sharing audit report', config: { channel: 'email' } },
		],
	},
	{
		id: 'teams-policy-enforcement',
		name: 'Teams Policy Enforcement',
		description: 'Ensure all Teams comply with naming conventions, expiry, and guest policies.',
		category: 'governance',
		triggerType: 'schedule',
		tags: ['teams', 'policy', 'compliance'],
		estimatedDurationMinutes: 15,
		steps: [
			{ id: 'scan', type: 'action', name: 'Scan all Teams', config: { graphAction: 'listTeams' }, onSuccess: 'check' },
			{ id: 'check', type: 'condition', name: 'Check policy compliance', config: { namingRegex: '^[A-Z]{2,4}-', requireExpiry: true }, onSuccess: 'fix' },
			{ id: 'fix', type: 'action', name: 'Apply missing policies', config: { graphAction: 'updateGroup', setExpiry: true }, onSuccess: 'notify' },
			{ id: 'notify', type: 'notification', name: 'Policy enforcement report', config: { channel: 'teams' } },
		],
	},
	{
		id: 'spo-permission-audit',
		name: 'SharePoint Permission Audit',
		description: 'Audit unique permissions on SharePoint sites and flag over-shared content.',
		category: 'governance',
		triggerType: 'schedule',
		tags: ['sharepoint', 'permissions', 'audit'],
		estimatedDurationMinutes: 30,
		steps: [
			{ id: 'enumerate', type: 'action', name: 'Enumerate site permissions', config: { graphAction: 'listSitePermissions' }, onSuccess: 'analyze' },
			{ id: 'analyze', type: 'condition', name: 'Flag over-shared sites', config: { maxUniquePermissions: 50 }, onSuccess: 'report' },
			{ id: 'report', type: 'notification', name: 'Permission audit report', config: { channel: 'email', format: 'csv' } },
		],
	},
	{
		id: 'stale-site-archival',
		name: 'Stale Site Archival',
		description: 'Archive SharePoint sites with no activity for 180+ days.',
		category: 'governance',
		triggerType: 'schedule',
		tags: ['sharepoint', 'archival', 'cleanup'],
		estimatedDurationMinutes: 20,
		steps: [
			{ id: 'scan', type: 'action', name: 'Scan site activity', config: { graphAction: 'listSites', inactiveDays: 180 }, onSuccess: 'filter' },
			{ id: 'filter', type: 'condition', name: 'Exclude protected sites', config: { excludeLabels: ['legal-hold', 'compliance'] }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Site owner approval', config: { approverRole: 'admin', timeoutDays: 14 }, onSuccess: 'archive' },
			{ id: 'archive', type: 'action', name: 'Set site to read-only', config: { graphAction: 'updateSite', readOnly: true }, onSuccess: 'notify' },
			{ id: 'notify', type: 'notification', name: 'Archival confirmation', config: { channel: 'email' } },
		],
	},
];
