import type { WorkflowTemplate } from '../../../../../../packages/shared/src/types/workflow-dsl';

export const LICENSE_TEMPLATES: WorkflowTemplate[] = [
	{
		id: 'reclaim-unused-licenses',
		name: 'Reclaim Unused Licenses',
		description: 'Identify and reclaim licenses from users inactive for 30+ days.',
		category: 'license',
		triggerType: 'schedule',
		tags: ['cost-savings', 'license', 'automation'],
		estimatedDurationMinutes: 15,
		steps: [
			{ id: 'scan', type: 'action', name: 'Scan inactive users', config: { inactiveDays: 30 }, onSuccess: 'filter' },
			{ id: 'filter', type: 'condition', name: 'Filter reclaimable licenses', config: { minCost: 5 }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Manager approval', config: { approverRole: 'admin' }, onSuccess: 'revoke' },
			{ id: 'revoke', type: 'action', name: 'Revoke licenses via Graph', config: { graphAction: 'removeLicense' }, onSuccess: 'notify' },
			{ id: 'notify', type: 'notification', name: 'Send reclaim report', config: { channel: 'email' } },
		],
	},
	{
		id: 'downgrade-e5-to-e3',
		name: 'Downgrade E5 to E3',
		description: 'Detect E5 users not using premium features and downgrade to E3.',
		category: 'license',
		triggerType: 'schedule',
		tags: ['cost-savings', 'license', 'downgrade'],
		estimatedDurationMinutes: 20,
		steps: [
			{ id: 'audit', type: 'action', name: 'Audit E5 feature usage', config: { skuFilter: 'SPE_E5' }, onSuccess: 'check' },
			{ id: 'check', type: 'condition', name: 'Check premium feature adoption', config: { threshold: 0.1 }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Approve downgrade list', config: { approverRole: 'admin' }, onSuccess: 'swap' },
			{ id: 'swap', type: 'action', name: 'Swap E5 for E3', config: { removeSku: 'SPE_E5', addSku: 'SPE_E3' }, onSuccess: 'report' },
			{ id: 'report', type: 'notification', name: 'Downgrade summary', config: { channel: 'email' } },
		],
	},
	{
		id: 'remove-departed-user-licenses',
		name: 'Remove Departed User Licenses',
		description: 'Strip all licenses from users marked as departed in HR sync.',
		category: 'license',
		triggerType: 'event',
		tags: ['offboarding', 'license', 'hr-sync'],
		estimatedDurationMinutes: 5,
		steps: [
			{ id: 'detect', type: 'action', name: 'Detect departed users', config: { source: 'hrSync' }, onSuccess: 'strip' },
			{ id: 'strip', type: 'action', name: 'Remove all licenses', config: { graphAction: 'removeAllLicenses' }, onSuccess: 'log' },
			{ id: 'log', type: 'notification', name: 'Log removal to audit', config: { channel: 'audit' } },
		],
	},
	{
		id: 'bulk-assign-licenses',
		name: 'Bulk Assign Licenses',
		description: 'Assign licenses to a group of users based on department or role.',
		category: 'license',
		triggerType: 'manual',
		tags: ['provisioning', 'license', 'bulk'],
		estimatedDurationMinutes: 10,
		steps: [
			{ id: 'select', type: 'action', name: 'Select target users', config: { filterBy: 'department' }, onSuccess: 'validate' },
			{ id: 'validate', type: 'condition', name: 'Validate available licenses', config: { checkAvailability: true }, onSuccess: 'assign' },
			{ id: 'assign', type: 'action', name: 'Assign licenses via Graph', config: { graphAction: 'assignLicense' }, onSuccess: 'confirm' },
			{ id: 'confirm', type: 'notification', name: 'Assignment confirmation', config: { channel: 'email' } },
		],
	},
	{
		id: 'trial-expiry-alert',
		name: 'Trial Expiry Alert',
		description: 'Monitor trial licenses nearing expiration and alert admins.',
		category: 'license',
		triggerType: 'schedule',
		tags: ['trial', 'license', 'alert'],
		estimatedDurationMinutes: 5,
		steps: [
			{ id: 'scan', type: 'action', name: 'Scan trial subscriptions', config: { daysBeforeExpiry: 14 }, onSuccess: 'filter' },
			{ id: 'filter', type: 'condition', name: 'Filter expiring trials', config: { minUsers: 1 }, onSuccess: 'alert' },
			{ id: 'alert', type: 'notification', name: 'Send expiry alerts', config: { channel: 'email', urgency: 'high' } },
		],
	},
	{
		id: 'monthly-license-reconciliation',
		name: 'Monthly License Reconciliation',
		description: 'Reconcile assigned vs purchased licenses and flag discrepancies.',
		category: 'license',
		triggerType: 'schedule',
		tags: ['reconciliation', 'license', 'reporting'],
		estimatedDurationMinutes: 30,
		steps: [
			{ id: 'pull', type: 'action', name: 'Pull license inventory', config: { source: 'graphSubscriptions' }, onSuccess: 'compare' },
			{ id: 'compare', type: 'action', name: 'Compare assigned vs purchased', config: { tolerance: 0.05 }, onSuccess: 'check' },
			{ id: 'check', type: 'condition', name: 'Check for over-assignment', config: { maxOverage: 0 }, onSuccess: 'report' },
			{ id: 'report', type: 'notification', name: 'Reconciliation report', config: { channel: 'email' } },
		],
	},
	{
		id: 'license-cost-allocation',
		name: 'License Cost Allocation',
		description: 'Allocate license costs per department for internal chargeback.',
		category: 'license',
		triggerType: 'schedule',
		tags: ['cost-allocation', 'license', 'chargeback'],
		estimatedDurationMinutes: 20,
		steps: [
			{ id: 'gather', type: 'action', name: 'Gather license assignments', config: { groupBy: 'department' }, onSuccess: 'calculate' },
			{ id: 'calculate', type: 'action', name: 'Calculate cost per department', config: { includeTaxes: false }, onSuccess: 'export' },
			{ id: 'export', type: 'notification', name: 'Export allocation report', config: { channel: 'email', format: 'csv' } },
		],
	},
];
