import type { WorkflowTemplate } from '../../../../../../packages/shared/src/types/workflow-dsl';

export const LIFECYCLE_TEMPLATES: WorkflowTemplate[] = [
	{
		id: 'onboard-new-user',
		name: 'Onboard New User',
		description: 'Full onboarding: create account, assign licenses, add to groups, send welcome email.',
		category: 'lifecycle',
		triggerType: 'event',
		tags: ['onboarding', 'provisioning', 'hr-sync'],
		estimatedDurationMinutes: 10,
		steps: [
			{ id: 'create', type: 'action', name: 'Create user account', config: { graphAction: 'createUser', setPassword: true }, onSuccess: 'license' },
			{ id: 'license', type: 'action', name: 'Assign role-based licenses', config: { graphAction: 'assignLicense', mapping: 'departmentToSku' }, onSuccess: 'groups' },
			{ id: 'groups', type: 'action', name: 'Add to security groups', config: { graphAction: 'addGroupMember', mapping: 'departmentToGroups' }, onSuccess: 'welcome' },
			{ id: 'welcome', type: 'notification', name: 'Send welcome email', config: { channel: 'email', template: 'welcome-new-user' } },
		],
	},
	{
		id: 'offboard-departing-user',
		name: 'Offboard Departing User',
		description: 'Complete offboarding: revoke access, backup mailbox, remove licenses, disable account.',
		category: 'lifecycle',
		triggerType: 'event',
		tags: ['offboarding', 'deprovisioning', 'security'],
		estimatedDurationMinutes: 15,
		steps: [
			{ id: 'revoke', type: 'action', name: 'Revoke all sessions', config: { graphAction: 'revokeSignInSessions' }, onSuccess: 'backup' },
			{ id: 'backup', type: 'action', name: 'Export mailbox to PST', config: { graphAction: 'exportMailbox', format: 'pst' }, onSuccess: 'strip' },
			{ id: 'strip', type: 'action', name: 'Remove all licenses', config: { graphAction: 'removeAllLicenses' }, onSuccess: 'disable' },
			{ id: 'disable', type: 'action', name: 'Disable account', config: { graphAction: 'disableUser' }, onSuccess: 'notify' },
			{ id: 'notify', type: 'notification', name: 'Notify manager', config: { channel: 'email', template: 'offboard-complete' } },
		],
	},
	{
		id: 'convert-guest-to-member',
		name: 'Convert Guest to Member',
		description: 'Promote a guest user to a full member with appropriate licenses and groups.',
		category: 'lifecycle',
		triggerType: 'manual',
		tags: ['guest', 'conversion', 'provisioning'],
		estimatedDurationMinutes: 5,
		steps: [
			{ id: 'validate', type: 'condition', name: 'Validate guest exists', config: { userType: 'guest' }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Manager approval', config: { approverRole: 'admin' }, onSuccess: 'convert' },
			{ id: 'convert', type: 'action', name: 'Update user type to member', config: { graphAction: 'updateUser', userType: 'Member' }, onSuccess: 'license' },
			{ id: 'license', type: 'action', name: 'Assign standard licenses', config: { graphAction: 'assignLicense' }, onSuccess: 'notify' },
			{ id: 'notify', type: 'notification', name: 'Welcome as member', config: { channel: 'email', template: 'guest-converted' } },
		],
	},
	{
		id: 'bulk-password-reset',
		name: 'Bulk Password Reset',
		description: 'Reset passwords for a group of users after a security incident.',
		category: 'lifecycle',
		triggerType: 'manual',
		tags: ['password', 'security', 'bulk'],
		estimatedDurationMinutes: 10,
		steps: [
			{ id: 'select', type: 'action', name: 'Select affected users', config: { filterBy: 'group' }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Security team approval', config: { approverRole: 'admin' }, onSuccess: 'reset' },
			{ id: 'reset', type: 'action', name: 'Reset passwords', config: { graphAction: 'resetPassword', forceChange: true }, onSuccess: 'notify' },
			{ id: 'notify', type: 'notification', name: 'Notify users of reset', config: { channel: 'email', template: 'password-reset' } },
		],
	},
	{
		id: 'inactive-user-cleanup',
		name: 'Inactive User Cleanup',
		description: 'Disable accounts inactive for 90+ days and reclaim their licenses.',
		category: 'lifecycle',
		triggerType: 'schedule',
		tags: ['cleanup', 'inactive', 'cost-savings'],
		estimatedDurationMinutes: 20,
		steps: [
			{ id: 'scan', type: 'action', name: 'Scan for inactive users', config: { inactiveDays: 90 }, onSuccess: 'filter' },
			{ id: 'filter', type: 'condition', name: 'Exclude service accounts', config: { excludeServiceAccounts: true }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Admin approval', config: { approverRole: 'admin' }, onSuccess: 'disable' },
			{ id: 'disable', type: 'action', name: 'Disable and strip licenses', config: { graphAction: 'disableUser', removeLicenses: true }, onSuccess: 'report' },
			{ id: 'report', type: 'notification', name: 'Cleanup summary report', config: { channel: 'email' } },
		],
	},
	{
		id: 'contractor-access-expiry',
		name: 'Contractor Access Expiry',
		description: 'Monitor contractor accounts nearing access expiry and handle extensions or offboarding.',
		category: 'lifecycle',
		triggerType: 'schedule',
		tags: ['contractor', 'expiry', 'access-review'],
		estimatedDurationMinutes: 10,
		steps: [
			{ id: 'scan', type: 'action', name: 'Scan expiring contractors', config: { daysBeforeExpiry: 7, userType: 'guest' }, onSuccess: 'notify-manager' },
			{ id: 'notify-manager', type: 'notification', name: 'Alert hiring manager', config: { channel: 'email', template: 'contractor-expiring' }, onSuccess: 'wait' },
			{ id: 'wait', type: 'delay', name: 'Wait for decision', config: { delayMinutes: 4320 }, onSuccess: 'check' },
			{ id: 'check', type: 'condition', name: 'Check if extended', config: { checkExtension: true }, onSuccess: 'offboard', onFailure: 'offboard' },
			{ id: 'offboard', type: 'action', name: 'Disable expired accounts', config: { graphAction: 'disableUser' } },
		],
	},
];
