import type { WorkflowTemplate } from '../../../../../../packages/shared/src/types/workflow-dsl';

export const SECURITY_TEMPLATES: WorkflowTemplate[] = [
	{
		id: 'disable-risky-user',
		name: 'Disable Risky User',
		description: 'Automatically disable accounts flagged as high-risk by Identity Protection.',
		category: 'security',
		triggerType: 'event',
		tags: ['risk', 'identity-protection', 'automation'],
		estimatedDurationMinutes: 2,
		steps: [
			{ id: 'detect', type: 'action', name: 'Detect high-risk user', config: { riskLevel: 'high', source: 'identityProtection' }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Security team approval', config: { approverRole: 'admin', timeoutMinutes: 30 }, onSuccess: 'disable', onFailure: 'skip-notify' },
			{ id: 'disable', type: 'action', name: 'Disable account via Graph', config: { graphAction: 'disableUser' }, onSuccess: 'revoke' },
			{ id: 'revoke', type: 'action', name: 'Revoke active sessions', config: { graphAction: 'revokeSignInSessions' }, onSuccess: 'alert' },
			{ id: 'alert', type: 'notification', name: 'Alert security team', config: { channel: 'teams', urgency: 'critical' } },
			{ id: 'skip-notify', type: 'notification', name: 'Log skipped action', config: { channel: 'audit' } },
		],
	},
	{
		id: 'force-mfa-enrollment',
		name: 'Force MFA Enrollment',
		description: 'Identify users without MFA and enforce enrollment within 48 hours.',
		category: 'security',
		triggerType: 'schedule',
		tags: ['mfa', 'compliance', 'identity'],
		estimatedDurationMinutes: 10,
		steps: [
			{ id: 'scan', type: 'action', name: 'Scan MFA registration status', config: { graphAction: 'listAuthMethods' }, onSuccess: 'filter' },
			{ id: 'filter', type: 'condition', name: 'Filter non-MFA users', config: { excludeGuests: true }, onSuccess: 'notify-users' },
			{ id: 'notify-users', type: 'notification', name: 'Notify users to enroll', config: { channel: 'email', deadline: '48h' }, onSuccess: 'wait' },
			{ id: 'wait', type: 'delay', name: 'Wait for enrollment period', config: { delayMinutes: 2880 }, onSuccess: 'enforce' },
			{ id: 'enforce', type: 'action', name: 'Enable MFA requirement', config: { graphAction: 'requireMfa' } },
		],
	},
	{
		id: 'block-legacy-auth-users',
		name: 'Block Legacy Auth Users',
		description: 'Identify and block users still using legacy authentication protocols.',
		category: 'security',
		triggerType: 'schedule',
		tags: ['legacy-auth', 'conditional-access', 'security'],
		estimatedDurationMinutes: 15,
		steps: [
			{ id: 'scan', type: 'action', name: 'Scan sign-in logs for legacy auth', config: { lookbackDays: 30 }, onSuccess: 'check' },
			{ id: 'check', type: 'condition', name: 'Check affected user count', config: { maxUsers: 100 }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Admin approval to block', config: { approverRole: 'admin' }, onSuccess: 'block' },
			{ id: 'block', type: 'action', name: 'Apply conditional access policy', config: { graphAction: 'createConditionalAccessPolicy', blockLegacy: true } },
		],
	},
	{
		id: 'revoke-app-consent',
		name: 'Revoke App Consent',
		description: 'Revoke OAuth consents for unapproved or risky third-party applications.',
		category: 'security',
		triggerType: 'event',
		tags: ['oauth', 'app-consent', 'shadow-it'],
		estimatedDurationMinutes: 5,
		steps: [
			{ id: 'detect', type: 'action', name: 'Detect risky app consent', config: { riskThreshold: 'medium' }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'Approve revocation', config: { approverRole: 'admin' }, onSuccess: 'revoke' },
			{ id: 'revoke', type: 'action', name: 'Revoke consent via Graph', config: { graphAction: 'revokeOAuth2Grants' }, onSuccess: 'notify' },
			{ id: 'notify', type: 'notification', name: 'Notify affected users', config: { channel: 'email' } },
		],
	},
	{
		id: 'quarantine-compromised-mailbox',
		name: 'Quarantine Compromised Mailbox',
		description: 'Isolate a mailbox suspected of compromise: disable forwarding, reset password.',
		category: 'security',
		triggerType: 'event',
		tags: ['email', 'compromise', 'incident-response'],
		estimatedDurationMinutes: 3,
		steps: [
			{ id: 'lock', type: 'action', name: 'Disable mail forwarding', config: { graphAction: 'updateMailboxSettings', disableForwarding: true }, onSuccess: 'reset' },
			{ id: 'reset', type: 'action', name: 'Reset user password', config: { graphAction: 'resetPassword', forceChange: true }, onSuccess: 'revoke' },
			{ id: 'revoke', type: 'action', name: 'Revoke all sessions', config: { graphAction: 'revokeSignInSessions' }, onSuccess: 'alert' },
			{ id: 'alert', type: 'notification', name: 'Alert SOC team', config: { channel: 'teams', urgency: 'critical' } },
		],
	},
	{
		id: 'rotate-admin-credentials',
		name: 'Rotate Admin Credentials',
		description: 'Periodically rotate passwords for privileged admin accounts.',
		category: 'security',
		triggerType: 'schedule',
		tags: ['credential-rotation', 'admin', 'hygiene'],
		estimatedDurationMinutes: 10,
		steps: [
			{ id: 'list', type: 'action', name: 'List admin accounts', config: { roleFilter: 'Global Administrator' }, onSuccess: 'approve' },
			{ id: 'approve', type: 'approval', name: 'CISO approval', config: { approverRole: 'super_admin' }, onSuccess: 'rotate' },
			{ id: 'rotate', type: 'action', name: 'Rotate passwords', config: { graphAction: 'resetPassword', generateStrong: true }, onSuccess: 'notify' },
			{ id: 'notify', type: 'notification', name: 'Send new credentials securely', config: { channel: 'email', encrypted: true } },
		],
	},
];
