import type { Mode, ModeContext } from "lunaforge-core";
import { DreamClient, DreamClientOptions } from "./client";
import type { DreamIntent, DreamRunSummary } from "./types";
import { ensureLicense } from "lunaforge-core";

export interface DreamAPI {
  listRecent(): Promise<void>;
  schedule(intent: DreamIntent): Promise<DreamRunSummary | undefined>;
  checkStatus(id: string): Promise<DreamRunSummary | undefined>;
  waitFor(id: string): Promise<DreamRunSummary | undefined>;
}

export function createDreamMode(
  opts: DreamClientOptions
): Mode & DreamAPI {
  const client = new DreamClient(opts);
  let ctxRef: ModeContext | null = null;

  async function listRecent(): Promise<void> {
    const ctx = ctxRef;
    if (!ctx) return;

    ctx.emit("dream:status", { status: "loading" });

    try {
      const runs = await client.listRecent();
      ctx.emit("dream:runs", { runs });
    } catch (err: any) {
      ctx.emit("dream:error", { error: String(err) });
    }

    ctx.emit("dream:status", { status: "idle" });
  }

  async function schedule(intent: DreamIntent): Promise<DreamRunSummary | undefined> {
    const ctx = ctxRef;
    if (!ctx) return undefined;

    ctx.emit("dream:status", { status: "scheduled" });

    try {
      const summary = await client.schedule(intent);
      ctx.emit("dream:scheduled", { summary });
      ctx.emit("dream:status", { status: "idle" });
      return summary;
    } catch (err: any) {
      ctx.emit("dream:error", { error: String(err) });
      ctx.emit("dream:status", { status: "idle" });
      return undefined;
    }
  }

  async function checkStatus(id: string): Promise<DreamRunSummary | undefined> {
    const ctx = ctxRef;
    if (!ctx) return undefined;

    try {
      const summary: DreamRunSummary = await client.getStatus(id);
      ctx.emit("dream:runStatus", { summary });
      return summary;
    } catch (err: any) {
      ctx.emit("dream:error", { error: String(err) });
      return undefined;
    }
  }

  async function waitFor(id: string): Promise<DreamRunSummary | undefined> {
    try {
      const summary = await client.waitForCompletion(id);
      if (ctxRef) {
        ctxRef.emit("dream:runStatus", { summary });
      }
      return summary;
    } catch (err: any) {
      if (ctxRef) ctxRef.emit("dream:error", { error: String(err) });
      throw err;
    }
  }

  return {
    id: "dream",
    title: "Dream",
    description:
      "Nightly autonomous refactors, tests, and branches generated by the cloud AI backend.",
    requiredFeature: "dream",

    activate(ctx: ModeContext) {
      if (!ensureLicense(ctx, "dream")) return;

      ctxRef = ctx;
      ctx.emit("dream:ready", {});
    },

    deactivate() {
      ctxRef = null;
    },

    listRecent,
    schedule,
    checkStatus,
    waitFor
  };
}

export * from "./types";