
export interface LLMMessage {
    role: 'system' | 'user' | 'assistant';
    content: string;
}

export interface LLMResponse {
    content: string;
    usage?: {
        promptTokens: number;
        completionTokens: number;
    };
}

export interface LLMProvider {
    complete(messages: LLMMessage[]): Promise<LLMResponse>;
}

export class OpenAIProvider implements LLMProvider {
    private apiKey: string;
    private model: string;
    private baseUrl: string;

    constructor(apiKey: string, model: string = 'gpt-4-turbo-preview') {
        this.apiKey = apiKey;
        this.model = model;
        this.baseUrl = 'https://api.openai.com/v1/chat/completions';
    }

    async complete(messages: LLMMessage[]): Promise<LLMResponse> {
        if (!this.apiKey) {
            throw new Error('OpenAI API key not configured');
        }

        const response = await fetch(this.baseUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${this.apiKey}`
            },
            body: JSON.stringify({
                model: this.model,
                messages: messages,
                temperature: 0.7
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`OpenAI API Error ${response.status}: ${errorText}`);
        }

        const data: any = await response.json();
        return {
            content: data.choices[0].message.content,
            usage: {
                promptTokens: data.usage.prompt_tokens,
                completionTokens: data.usage.completion_tokens
            }
        };
    }
}

export class MockProvider implements LLMProvider {
    async complete(messages: LLMMessage[]): Promise<LLMResponse> {
        // Simulate thinking delay
        await new Promise(r => setTimeout(r, 2000));

        const lastUserMsg = messages.filter(m => m.role === 'user').pop()?.content || "unknown";

        return {
            content: JSON.stringify({
                summary: `[MOCK AI] I processed: "${lastUserMsg}". Check out the new README.`,
                files: [
                    {
                        path: "DREAM_RESULT.md",
                        content: `# Dream Result\n\nYou asked for: ${lastUserMsg}\n\nThis file was generated by the LunaForge Dream AI (Mock Mode).`
                    }
                ]
            }),
            usage: { promptTokens: 10, completionTokens: 50 }
        };
    }
}
