name = "opensyber-redirects"
main = "worker.js"
compatibility_date = "2025-02-18"

routes = [
  { pattern = "opensyber.dev/*", zone_name = "opensyber.dev" },
  { pattern = "www.opensyber.dev/*", zone_name = "opensyber.dev" },
  { pattern = "opensyber.com/*", zone_name = "opensyber.com" },
  { pattern = "www.opensyber.com/*", zone_name = "opensyber.com" },
  { pattern = "opensyber.io/*", zone_name = "opensyber.io" },
  { pattern = "www.opensyber.io/*", zone_name = "opensyber.io" },
]
