/**
 * Test Execution API Endpoints
 *
 * Comprehensive API for managing test executions including:
 * - Queue and execute test runs
 * - Real-time execution monitoring
 * - Test artifacts and results management
 * - Performance metrics and analytics
 * - Environment and schedule management
 */

import { Hono } from "hono";
import { z } from "zod";
import { zValidator } from "@hono/zod-validator";
import { HTTPException } from "hono/http-exception";
import { drizzle } from "drizzle-orm/d1";
import { eq, and, desc, gte, lte, inArray } from "drizzle-orm";
import * as schema from "../db/schema";
import {
  createTestExecutionEngine,
  TestExecutionEngine,
  TestExecutionRequest,
} from "../services/test-execution-engine";

// Validation schemas
const queueExecutionSchema = z.object({
  projectId: z.string().min(1, "Project ID is required"),
  testSuiteId: z.string().optional(),
  testIds: z.array(z.string()).min(1, "At least one test ID is required"),
  config: z.record(z.any()).optional().default({}),
  environment: z.string().optional().default("development"),
  metadata: z.record(z.any()).optional().default({}),
  scheduledFor: z.string().datetime().optional(),
});

const cancelExecutionSchema = z.object({
  reason: z.string().optional(),
});

const controlExecutionSchema = z.object({
  action: z.enum(["pause", "resume"]),
});

// Create Hono router
const testExecutionRoutes = new Hono<{
  Bindings: {
    DB: D1Database;
    SESSIONS: KVNamespace;
    CACHE: KVNamespace;
    REALTIME: KVNamespace;
    ARTIFACTS: R2Bucket;
    MEDIA: R2Bucket;
    BACKUPS: R2Bucket;
    COLLABORATION_DO: DurableObject;
    SESSION_DO: DurableObject;
    TEST_EXECUTION_DO: DurableObject;
    AI_QUEUE: Queue;
    TEST_QUEUE: Queue;
    BILLING_QUEUE: Queue;
    JWT_SECRET: string;
    OPENAI_API_KEY: string;
    HUGGINGFACE_API_KEY: string;
    LEMONSQUEEZY_API_KEY: string;
    RESEND_API_KEY: string;
    NODE_ENV: string;
    ENVIRONMENT: string;
    API_URL: string;
    FRONTEND_URL: string;
    LOG_LEVEL: string;
  };
}>();

export class TestExecutionAPI {
  private db: any;
  private executionEngine: TestExecutionEngine;

  constructor(d1Database: D1Database, webSocketService?: any) {
    this.db = drizzle(d1Database, { schema });
    this.executionEngine = createTestExecutionEngine(
      d1Database,
      {},
      webSocketService,
    );
  }

  /**
   * Queue test execution
   */
  async queueExecution(request: Request, env: any): Promise<Response> {
    try {
      const body = await request.json();
      const {
        projectId,
        testSuiteId,
        testIds,
        config = {},
        environment = "development",
        metadata = {},
        scheduledFor,
      } = body;

      // Validate required fields
      if (
        !projectId ||
        !testIds ||
        !Array.isArray(testIds) ||
        testIds.length === 0
      ) {
        return Response.json(
          {
            error: "Missing required fields: projectId, testIds",
          },
          { status: 400 },
        );
      }

      // Verify project exists and user has access
      const project = await this.db
        .select()
        .from(schema.projects)
        .where(eq(schema.projects.id, projectId))
        .first();

      if (!project) {
        return Response.json(
          {
            error: "Project not found",
          },
          { status: 404 },
        );
      }

      // Get user from request (would need authentication middleware)
      const userId = request.headers.get("x-user-id") || "system";

      // Create execution request
      const executionRequest: TestExecutionRequest = {
        id: "", // Will be generated by the engine
        projectId,
        testSuiteId,
        testIds,
        config,
        environment,
        metadata,
        scheduledFor: scheduledFor ? new Date(scheduledFor) : undefined,
        requestedBy: userId,
      };

      // Queue execution
      const executionId =
        await this.executionEngine.queueExecution(executionRequest);

      console.log(
        `🚀 Queued test execution ${executionId} for project ${projectId}`,
      );

      return Response.json({
        success: true,
        executionId,
        projectId,
        testCount: testIds.length,
        environment,
        status: "queued",
        queuedAt: new Date().toISOString(),
        scheduledFor: scheduledFor || null,
        metadata: {
          testSuiteId,
          config,
          requestedBy: userId,
        },
      });
    } catch (error) {
      console.error("Queue execution failed:", error);

      return Response.json(
        {
          error: "Failed to queue test execution",
          message: error instanceof Error ? error.message : "Unknown error",
        },
        { status: 500 },
      );
    }
  }

  /**
   * Get execution status and details
   */
  async getExecutionStatus(request: Request, env: any): Promise<Response> {
    try {
      const url = new URL(request.url);
      const executionId = url.pathname.split("/").pop();

      if (!executionId) {
        return Response.json(
          {
            error: "Missing execution ID",
          },
          { status: 400 },
        );
      }

      const status = await this.executionEngine.getExecutionStatus(executionId);

      // Get additional details
      const execution = status.execution;
      const results = status.results;
      const isActive = status.isActive;

      // Calculate progress
      const completedTests = results.filter((r) =>
        ["passed", "completed", "failed", "skipped", "error"].includes(r.status),
      ).length;
      const totalTests = results.length;
      const progress =
        totalTests > 0 ? Math.round((completedTests / totalTests) * 100) : 0;

      // Get artifacts count
      const artifacts = await this.db
        .select()
        .from(schema.testArtifacts)
        .where(eq(schema.testArtifacts.executionId, executionId));

      return Response.json({
        success: true,
        execution: {
          ...execution,
          isActive,
          progress: {
            completed: completedTests,
            total: totalTests,
            percentage: progress,
          },
          results: results.map((result) => ({
            id: result.id,
            testId: result.testId,
            status: result.status,
            duration: result.duration,
            startedAt: result.startedAt,
            completedAt: result.completedAt,
            error: result.error,
          })),
          artifacts: {
            count: artifacts.length,
            types: this.countArtifactTypes(artifacts),
          },
        },
      });
    } catch (error) {
      console.error("Get execution status failed:", error);

      return Response.json(
        {
          error: "Failed to get execution status",
          message: error instanceof Error ? error.message : "Unknown error",
        },
        { status: 500 },
      );
    }
  }

  /**
   * Get execution results with detailed information
   */
  async getExecutionResults(request: Request, env: any): Promise<Response> {
    try {
      const url = new URL(request.url);
      const executionId = url.pathname.split("/").pop();
      const includeArtifacts =
        url.searchParams.get("includeArtifacts") === "true";
      const includeSteps = url.searchParams.get("includeSteps") === "true";

      if (!executionId) {
        return Response.json(
          {
            error: "Missing execution ID",
          },
          { status: 400 },
        );
      }

      // Get execution details
      const execution = await this.db
        .select()
        .from(schema.testExecutions)
        .where(eq(schema.testExecutions.id, executionId))
        .first();

      if (!execution) {
        return Response.json(
          {
            error: "Execution not found",
          },
          { status: 404 },
        );
      }

      // Get test results
      const results = await this.db
        .select()
        .from(schema.testExecutionResults)
        .where(eq(schema.testExecutionResults.executionId, executionId));

      // Get artifacts if requested
      let artifacts = [];
      if (includeArtifacts) {
        artifacts = await this.db
          .select()
          .from(schema.testArtifacts)
          .where(eq(schema.testArtifacts.executionId, executionId));
      }

      // Get test details
      const testIds = results.map((r) => r.testId);
      const tests =
        testIds.length > 0
          ? await this.db
              .select()
              .from(schema.testCases)
              .where(inArray(schema.testCases.id, testIds))
          : [];

      // Combine results with test details
      const detailedResults = results.map((result) => {
        const test = tests.find((t) => t.id === result.testId);
        return {
          ...result,
          test: test
            ? {
                id: test.id,
                name: test.name,
                description: test.description,
                platform: test.platform,
                category: test.category,
              }
            : null,
          result: result.result ? JSON.parse(result.result) : null,
          artifacts: includeArtifacts
            ? artifacts.filter((a) => a.testResultId === result.id)
            : [],
          performance: result.performance
            ? JSON.parse(result.performance)
            : null,
        };
      });

      return Response.json({
        success: true,
        execution: {
          ...execution,
          summary: execution.summary ? JSON.parse(execution.summary) : null,
          config: execution.config ? JSON.parse(execution.config) : null,
          metadata: execution.metadata ? JSON.parse(execution.metadata) : null,
        },
        results: detailedResults,
        artifacts: includeArtifacts ? artifacts : [],
        statistics: this.calculateExecutionStatistics(detailedResults),
      });
    } catch (error) {
      console.error("Get execution results failed:", error);

      return Response.json(
        {
          error: "Failed to get execution results",
          message: error instanceof Error ? error.message : "Unknown error",
        },
        { status: 500 },
      );
    }
  }

  /**
   * Cancel execution
   */
  async cancelExecution(request: Request, env: any): Promise<Response> {
    try {
      const url = new URL(request.url);
      const executionId = url.pathname.split("/").pop();
      const body = await request.json();
      const reason = body.reason;

      if (!executionId) {
        return Response.json(
          {
            error: "Missing execution ID",
          },
          { status: 400 },
        );
      }

      await this.executionEngine.cancelExecution(executionId, reason);

      console.log(
        `⏹️ Cancelled execution ${executionId}${reason ? `: ${reason}` : ""}`,
      );

      return Response.json({
        success: true,
        executionId,
        status: "cancelled",
        cancelledAt: new Date().toISOString(),
        reason: reason || "Cancelled by user",
      });
    } catch (error) {
      console.error("Cancel execution failed:", error);

      return Response.json(
        {
          error: "Failed to cancel execution",
          message: error instanceof Error ? error.message : "Unknown error",
        },
        { status: 500 },
      );
    }
  }

  /**
   * Pause/Resume execution
   */
  async controlExecution(request: Request, env: any): Promise<Response> {
    try {
      const url = new URL(request.url);
      const executionId = url.pathname.split("/").pop();
      const body = await request.json();
      const action = body.action; // 'pause' or 'resume'

      if (!executionId) {
        return Response.json(
          {
            error: "Missing execution ID",
          },
          { status: 400 },
        );
      }

      if (!["pause", "resume"].includes(action)) {
        return Response.json(
          {
            error: 'Invalid action. Must be "pause" or "resume"',
          },
          { status: 400 },
        );
      }

      if (action === "pause") {
        await this.executionEngine.pauseExecution(executionId);
      } else {
        await this.executionEngine.resumeExecution(executionId);
      }

      console.log(
        `${action === "pause" ? "⏸️" : "▶️"} ${action.charAt(0).toUpperCase() + action.slice(1)}d execution ${executionId}`,
      );

      return Response.json({
        success: true,
        executionId,
        status: action,
        controlledAt: new Date().toISOString(),
      });
    } catch (error) {
      console.error("Control execution failed:", error);

      return Response.json(
        {
          error: `Failed to ${body.action} execution`,
          message: error instanceof Error ? error.message : "Unknown error",
        },
        { status: 500 },
      );
    }
  }

  /**
   * Get execution list for project
   */
  async getExecutions(request: Request, env: any): Promise<Response> {
    try {
      const url = new URL(request.url);
      const projectId = url.searchParams.get("projectId");
      const status = url.searchParams.get("status");
      const limit = parseInt(url.searchParams.get("limit") || "20");
      const offset = parseInt(url.searchParams.get("offset") || "0");

      if (!projectId) {
        return Response.json(
          {
            error: "Missing projectId parameter",
          },
          { status: 400 },
        );
      }

      // Build query
      let query = this.db
        .select()
        .from(schema.testExecutions)
        .where(eq(schema.testExecutions.projectId, projectId))
        .orderBy(desc(schema.testExecutions.createdAt))
        .limit(limit)
        .offset(offset);

      if (status) {
        query = query.where(
          and(
            eq(schema.testExecutions.projectId, projectId),
            eq(schema.testExecutions.status, status),
          ),
        );
      }

      const executions = await query;

      // Get summary statistics
      const stats = await this.getExecutionStatistics(projectId);

      return Response.json({
        success: true,
        executions: executions.map((exec) => ({
          ...exec,
          summary: exec.summary ? JSON.parse(exec.summary) : null,
          config: exec.config ? JSON.parse(exec.config) : null,
          metadata: exec.metadata ? JSON.parse(exec.metadata) : null,
        })),
        pagination: {
          limit,
          offset,
          total: stats.totalExecutions,
        },
        statistics: stats,
      });
    } catch (error) {
      console.error("Get executions failed:", error);

      return Response.json(
        {
          error: "Failed to get executions",
          message: error instanceof Error ? error.message : "Unknown error",
        },
        { status: 500 },
      );
    }
  }

  /**
   * Get test artifacts
   */
  async getArtifacts(request: Request, env: any): Promise<Response> {
    try {
      const url = new URL(request.url);
      const executionId = url.pathname.split("/").slice(-2, -1)[0]; // Get execution ID from path
      const artifactId = url.pathname.split("/").pop(); // Get artifact ID from path

      if (!executionId) {
        return Response.json(
          {
            error: "Missing execution ID",
          },
          { status: 400 },
        );
      }

      // If artifactId is provided, get specific artifact
      if (artifactId && artifactId !== "artifacts") {
        const artifact = await this.db
          .select()
          .from(schema.testArtifacts)
          .where(
            and(
              eq(schema.testArtifacts.executionId, executionId),
              eq(schema.testArtifacts.id, artifactId),
            ),
          )
          .first();

        if (!artifact) {
          return Response.json(
            {
              error: "Artifact not found",
            },
            { status: 404 },
          );
        }

        // If it's a file, serve it
        if (artifact.path && artifact.contentType) {
          // This would need to be implemented based on storage location
          return new Response("Artifact file serving not implemented", {
            status: 501,
          });
        }

        return Response.json({
          success: true,
          artifact: {
            ...artifact,
            metadata: artifact.metadata ? JSON.parse(artifact.metadata) : null,
          },
        });
      }

      // Otherwise, list all artifacts for execution
      const artifacts = await this.db
        .select()
        .from(schema.testArtifacts)
        .where(eq(schema.testArtifacts.executionId, executionId))
        .orderBy(desc(schema.testArtifacts.createdAt));

      return Response.json({
        success: true,
        executionId,
        artifacts: artifacts.map((artifact) => ({
          ...artifact,
          metadata: artifact.metadata ? JSON.parse(artifact.metadata) : null,
        })),
        statistics: {
          totalArtifacts: artifacts.length,
          totalSize: artifacts.reduce((sum, a) => sum + (a.size || 0), 0),
          types: this.countArtifactTypes(artifacts),
        },
      });
    } catch (error) {
      console.error("Get artifacts failed:", error);

      return Response.json(
        {
          error: "Failed to get artifacts",
          message: error instanceof Error ? error.message : "Unknown error",
        },
        { status: 500 },
      );
    }
  }

  /**
   * Get execution metrics and analytics
   */
  async getMetrics(request: Request, env: any): Promise<Response> {
    try {
      const url = new URL(request.url);
      const projectId = url.searchParams.get("projectId");
      const timeframe = {
        from:
          url.searchParams.get("from") ||
          new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        to: url.searchParams.get("to") || new Date().toISOString(),
      };

      if (!projectId) {
        return Response.json(
          {
            error: "Missing projectId parameter",
          },
          { status: 400 },
        );
      }

      // Get execution metrics
      const metrics = await this.db
        .select()
        .from(schema.testExecutionMetrics)
        .where(
          and(
            eq(schema.testExecutionMetrics.projectId, projectId),
            gte(
              schema.testExecutionMetrics.timestamp,
              new Date(timeframe.from).getTime(),
            ),
            lte(
              schema.testExecutionMetrics.timestamp,
              new Date(timeframe.to).getTime(),
            ),
          ),
        )
        .orderBy(desc(schema.testExecutionMetrics.timestamp));

      // Calculate trends and analytics
      const analytics = this.calculateExecutionAnalytics(metrics, timeframe);

      return Response.json({
        success: true,
        timeframe,
        analytics,
        metrics: metrics.map((metric) => ({
          ...metric,
          performanceMetrics: metric.performanceMetrics
            ? JSON.parse(metric.performanceMetrics)
            : null,
          resourceUtilization: metric.resourceUtilization
            ? JSON.parse(metric.resourceUtilization)
            : null,
        })),
      });
    } catch (error) {
      console.error("Get metrics failed:", error);

      return Response.json(
        {
          error: "Failed to get metrics",
          message: error instanceof Error ? error.message : "Unknown error",
        },
        { status: 500 },
      );
    }
  }

  /**
   * Helper methods
   */
  private countArtifactTypes(artifacts: any[]): Record<string, number> {
    const types: Record<string, number> = {};
    artifacts.forEach((artifact) => {
      types[artifact.type] = (types[artifact.type] || 0) + 1;
    });
    return types;
  }

  private calculateExecutionStatistics(results: any[]): any {
    const total = results.length;
    const passed = results.filter((r) => r.status === "passed").length;
    const failed = results.filter((r) => r.status === "failed").length;
    const skipped = results.filter((r) => r.status === "skipped").length;
    const errors = results.filter((r) => r.status === "error").length;

    const durations = results.filter((r) => r.duration).map((r) => r.duration);

    const averageDuration =
      durations.length > 0
        ? durations.reduce((sum, d) => sum + d, 0) / durations.length
        : 0;

    return {
      total,
      passed,
      failed,
      skipped,
      errors,
      successRate: total > 0 ? Math.round((passed / total) * 100) : 0,
      failureRate: total > 0 ? Math.round((failed / total) * 100) : 0,
      averageDuration: Math.round(averageDuration),
      totalDuration: Math.max(...durations, 0),
    };
  }

  private async getExecutionStatistics(projectId: string): Promise<any> {
    // Get total executions count
    const totalExecutions = await this.db
      .select()
      .from(schema.testExecutions)
      .where(eq(schema.testExecutions.projectId, projectId));

    // Get status distribution
    const statusCounts = totalExecutions.reduce(
      (acc, exec) => {
        acc[exec.status] = (acc[exec.status] || 0) + 1;
        return acc;
      },
      {} as Record<string, number>,
    );

    return {
      totalExecutions: totalExecutions.length,
      statusCounts,
      recentExecutions: totalExecutions.filter(
        (exec) => Date.now() - exec.createdAt < 7 * 24 * 60 * 60 * 1000,
      ).length,
    };
  }

  private calculateExecutionAnalytics(metrics: any[], timeframe: any): any {
    if (metrics.length === 0) {
      return {
        totalExecutions: 0,
        averageSuccessRate: 0,
        averageDuration: 0,
        trends: {
          successRate: "stable",
          duration: "stable",
          volume: "stable",
        },
        insights: [],
      };
    }

    const totalTests = metrics.reduce((sum, m) => sum + m.totalTests, 0);
    const totalPassed = metrics.reduce((sum, m) => sum + m.passedTests, 0);
    const averageSuccessRate =
      totalTests > 0 ? (totalPassed / totalTests) * 100 : 0;
    const averageDuration =
      metrics.reduce((sum, m) => sum + m.averageDuration, 0) / metrics.length;

    // Calculate trends (simplified)
    const recent = metrics.slice(0, 7); // Last 7 executions
    const older = metrics.slice(7, 14); // Previous 7 executions

    const recentSuccessRate =
      recent.reduce((sum, m) => sum + (m.successRate || 0), 0) / recent.length;
    const olderSuccessRate =
      older.length > 0
        ? older.reduce((sum, m) => sum + (m.successRate || 0), 0) / older.length
        : recentSuccessRate;

    const recentDuration =
      recent.reduce((sum, m) => sum + (m.averageDuration || 0), 0) /
      recent.length;
    const olderDuration =
      older.length > 0
        ? older.reduce((sum, m) => sum + (m.averageDuration || 0), 0) /
          older.length
        : recentDuration;

    return {
      totalExecutions: metrics.length,
      totalTests,
      totalPassed,
      averageSuccessRate: Math.round(averageSuccessRate),
      averageDuration: Math.round(averageDuration),
      trends: {
        successRate: this.calculateTrend(recentSuccessRate, olderSuccessRate),
        duration: this.calculateTrend(olderDuration, recentDuration), // Inverse for duration (lower is better)
        volume: this.calculateTrend(recent.length, older.length),
      },
      insights: this.generateInsights(
        metrics,
        recentSuccessRate,
        recentDuration,
      ),
    };
  }

  private calculateTrend(
    recent: number,
    older: number,
  ): "improving" | "stable" | "declining" {
    const threshold = 0.1; // 10% threshold
    const ratio = older > 0 ? recent / older : 1;

    if (ratio > 1 + threshold) return "improving";
    if (ratio < 1 - threshold) return "declining";
    return "stable";
  }

  private generateInsights(
    metrics: any[],
    recentSuccessRate: number,
    recentDuration: number,
  ): string[] {
    const insights: string[] = [];

    if (recentSuccessRate < 80) {
      insights.push(
        "Success rate is below 80%. Consider reviewing failing tests.",
      );
    }

    if (recentDuration > 60000) {
      // 1 minute
      insights.push(
        "Average test duration is high. Consider optimizing test performance.",
      );
    }

    const failureRate = 100 - recentSuccessRate;
    if (failureRate > 20) {
      insights.push(
        `Failure rate is ${Math.round(failureRate)}%. Investigate common failure patterns.`,
      );
    }

    if (metrics.length < 5) {
      insights.push(
        "Limited execution data. More executions will provide better insights.",
      );
    }

    return insights;
  }
}

// Error handling middleware
testExecutionRoutes.onError((err, c) => {
  console.error("Test Execution API Error:", err);

  if (err instanceof HTTPException) {
    return c.json(
      {
        error: err.message,
        status: err.status,
        timestamp: new Date().toISOString(),
        path: c.req.path,
      },
      err.status,
    );
  }

  return c.json(
    {
      error: "Internal server error",
      message: err.message || "Unknown error occurred",
      status: 500,
      timestamp: new Date().toISOString(),
      path: c.req.path,
    },
    500,
  );
});

/**
 * POST /api/test-execution/execute
 * Queue and execute test runs
 */
testExecutionRoutes.post(
  "/execute",
  zValidator("json", queueExecutionSchema),
  async (c) => {
    const api = new TestExecutionAPI(c.env.DB, c.env.webSocketService);
    const request = {
      ...c.req,
      json: async () => c.req.valid("json"),
      url: c.req.url,
      headers: {
        get: (name: string) => c.req.header(name),
      },
    };
    return api.queueExecution(request as Request, c.env);
  },
);

/**
 * GET /api/test-execution/session/:sessionId/status
 * Get real-time execution status
 */
testExecutionRoutes.get("/session/:sessionId/status", async (c) => {
  const api = new TestExecutionAPI(c.env.DB, c.env.webSocketService);
  const sessionId = c.req.param("sessionId");
  const request = {
    ...c.req,
    url: `${c.req.url.replace("/session/" + sessionId + "/status", "/status/" + sessionId)}`,
  };
  return api.getExecutionStatus(request as Request, c.env);
});

/**
 * GET /api/test-execution/session/:sessionId/results
 * Get comprehensive execution results
 */
testExecutionRoutes.get("/session/:sessionId/results", async (c) => {
  const api = new TestExecutionAPI(c.env.DB, c.env.webSocketService);
  const sessionId = c.req.param("sessionId");
  const request = {
    ...c.req,
    url: `${c.req.url.replace("/session/" + sessionId + "/results", "/results/" + sessionId)}${c.req.query ? "?" + c.req.query : ""}`,
  };
  return api.getExecutionResults(request as Request, c.env);
});

/**
 * POST /api/test-execution/session/:sessionId/cancel
 * Cancel running execution
 */
testExecutionRoutes.post(
  "/session/:sessionId/cancel",
  zValidator("json", cancelExecutionSchema),
  async (c) => {
    const api = new TestExecutionAPI(c.env.DB, c.env.webSocketService);
    const sessionId = c.req.param("sessionId");
    const request = {
      ...c.req,
      json: async () => c.req.valid("json"),
      url: `${c.req.url.replace("/session/" + sessionId + "/cancel", "/cancel/" + sessionId)}`,
    };
    return api.cancelExecution(request as Request, c.env);
  },
);

/**
 * POST /api/test-execution/session/:sessionId/control
 * Pause or resume execution
 */
testExecutionRoutes.post(
  "/session/:sessionId/control",
  zValidator("json", controlExecutionSchema),
  async (c) => {
    const api = new TestExecutionAPI(c.env.DB, c.env.webSocketService);
    const sessionId = c.req.param("sessionId");
    const request = {
      ...c.req,
      json: async () => c.req.valid("json"),
      url: `${c.req.url.replace("/session/" + sessionId + "/control", "/control/" + sessionId)}`,
    };
    return api.controlExecution(request as Request, c.env);
  },
);

/**
 * GET /api/test-execution/list
 * Get execution list for project
 */
testExecutionRoutes.get("/list", async (c) => {
  const api = new TestExecutionAPI(c.env.DB, c.env.webSocketService);
  const request = {
    ...c.req,
    url: `${c.req.url.replace("/list", "/executions")}`,
  };
  return api.getExecutions(request as Request, c.env);
});

/**
 * GET /api/test-execution/session/:sessionId/artifacts
 * Get test artifacts
 */
testExecutionRoutes.get("/session/:sessionId/artifacts", async (c) => {
  const api = new TestExecutionAPI(c.env.DB, c.env.webSocketService);
  const sessionId = c.req.param("sessionId");
  const request = {
    ...c.req,
    url: `${c.req.url.replace("/session/" + sessionId + "/artifacts", "/artifacts/" + sessionId)}`,
  };
  return api.getArtifacts(request as Request, c.env);
});

/**
 * GET /api/test-execution/session/:sessionId/artifacts/:artifactId
 * Get specific artifact
 */
testExecutionRoutes.get(
  "/session/:sessionId/artifacts/:artifactId",
  async (c) => {
    const api = new TestExecutionAPI(c.env.DB, c.env.webSocketService);
    const sessionId = c.req.param("sessionId");
    const artifactId = c.req.param("artifactId");
    const request = {
      ...c.req,
      url: `${c.req.url.replace("/session/" + sessionId + "/artifacts/" + artifactId, "/artifacts/" + sessionId + "/" + artifactId)}`,
    };
    return api.getArtifacts(request as Request, c.env);
  },
);

/**
 * GET /api/test-execution/metrics
 * Get execution metrics and analytics
 */
testExecutionRoutes.get("/metrics", async (c) => {
  const api = new TestExecutionAPI(c.env.DB, c.env.webSocketService);
  const request = {
    ...c.req,
    url: c.req.url,
  };
  return api.getMetrics(request as Request, c.env);
});

/**
 * WebSocket events for real-time execution updates
 * This is handled by the Durable Object in the main index.ts
 * But we can provide metadata about the WebSocket endpoints
 */
testExecutionRoutes.get("/ws-info", (c) => {
  return c.json({
    websocketEndpoints: {
      testExecution: {
        url: "/ws/test-execution/:testRunId",
        description: "Real-time test execution monitoring",
        events: [
          "test_started",
          "test_completed",
          "test_failed",
          "execution_progress",
          "device_status",
          "artifact_collected",
        ],
      },
    },
    usage: "Connect to the WebSocket endpoint using the test execution ID",
  });
});

export { testExecutionRoutes };

/**
 * Route handlers for the test execution API
 */
export async function handleQueueExecution(
  request: Request,
  env: any,
): Promise<Response> {
  const api = new TestExecutionAPI(env.DB, env.webSocketService);
  return api.queueExecution(request, env);
}

export async function handleGetExecutionStatus(
  request: Request,
  env: any,
): Promise<Response> {
  const api = new TestExecutionAPI(env.DB, env.webSocketService);
  return api.getExecutionStatus(request, env);
}

export async function handleGetExecutionResults(
  request: Request,
  env: any,
): Promise<Response> {
  const api = new TestExecutionAPI(env.DB, env.webSocketService);
  return api.getExecutionResults(request, env);
}

export async function handleCancelExecution(
  request: Request,
  env: any,
): Promise<Response> {
  const api = new TestExecutionAPI(env.DB, env.webSocketService);
  return api.cancelExecution(request, env);
}

export async function handleControlExecution(
  request: Request,
  env: any,
): Promise<Response> {
  const api = new TestExecutionAPI(env.DB, env.webSocketService);
  return api.controlExecution(request, env);
}

export async function handleGetExecutions(
  request: Request,
  env: any,
): Promise<Response> {
  const api = new TestExecutionAPI(env.DB, env.webSocketService);
  return api.getExecutions(request, env);
}

export async function handleGetArtifacts(
  request: Request,
  env: any,
): Promise<Response> {
  const api = new TestExecutionAPI(env.DB, env.webSocketService);
  return api.getArtifacts(request, env);
}

export async function handleGetExecutionMetrics(
  request: Request,
  env: any,
): Promise<Response> {
  const api = new TestExecutionAPI(env.DB, env.webSocketService);
  return api.getMetrics(request, env);
}
