import { Code, Terminal, Bot } from 'lucide-react';

export const ideClients = [
  {
    id: 'vscode',
    name: 'VS Code / Cursor / Windsurf',
    icon: Code,
    color: 'text-info',
    time: '2 min',
    steps: [
      'Open VS Code (or Cursor / Windsurf)',
      'Go to Extensions → Search "OpenSyber" → Install',
      'Press Cmd+Shift+P → "OpenSyber: Set Gateway Token"',
      'Paste your gateway token (from Settings page)',
      'Done! Activity syncs automatically every 5 minutes',
    ],
    note: 'Works identically in Cursor and Windsurf — the extension auto-detects which IDE and AI agents are active (Copilot, Cursor Composer, Cline, Continue, etc.)',
  },
  {
    id: 'jetbrains',
    name: 'JetBrains (IntelliJ, PyCharm, WebStorm)',
    icon: Code,
    color: 'text-red-400',
    time: '2 min',
    steps: [
      'Open your JetBrains IDE',
      'Go to Settings → Plugins → Marketplace → Search "OpenSyber"',
      'Install and restart the IDE',
      'Go to Settings → Tools → OpenSyber → Paste gateway token',
      'Terminal commands and AI Assistant interactions are now monitored',
    ],
    note: 'Supports all JetBrains IDEs: IntelliJ IDEA, PyCharm, WebStorm, GoLand, RubyMine, PHPStorm, CLion, Rider, and DataGrip.',
  },
  {
    id: 'neovim',
    name: 'Neovim',
    icon: Terminal,
    color: 'text-green-400',
    time: '1 min',
    steps: [
      "Add to your plugin manager: { 'opensyber/opensyber.nvim' }",
      "Add to init.lua: require('opensyber').setup({ token = 'YOUR_GATEWAY_TOKEN' })",
      'Restart Neovim',
      'Shell commands via :! and :terminal are now captured',
      'Copilot.lua and cmp-ai completions are tracked automatically',
    ],
    note: 'Ultra-lightweight Lua plugin. Zero measurable latency impact.',
  },
  {
    id: 'claude-code',
    name: 'Claude Code CLI',
    icon: Terminal,
    color: 'text-amber-400',
    time: '1 min',
    steps: [
      'Install the OpenSyber CLI: npm install -g @opensyber/cli',
      'Run: opensyber hook install claude-code',
      'The hook wraps Claude Code and forwards all events',
      'Every file edit, terminal command, and session is captured',
      'View in Dashboard → Agent Activity → filter "Claude Code"',
    ],
    note: 'The hook is non-invasive — it observes without modifying Claude Code behavior.',
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot (Chat + Code)',
    icon: Bot,
    color: 'text-purple-400',
    time: '2 min',
    steps: [
      'Install the OpenSyber extension in your IDE (VS Code, Cursor, etc.)',
      'The extension auto-detects GitHub Copilot by extension ID',
      'All chat conversations are logged with context',
      'Code suggestion acceptance/rejection is tracked',
      '@workspace agent commands are audited with risk scores',
    ],
    note: 'No additional configuration needed beyond the base extension — Copilot detection is automatic.',
  },
  {
    id: 'microsoft-copilot',
    name: 'Microsoft 365 Copilot',
    icon: Bot,
    color: 'text-info',
    time: '10 min',
    steps: [
      'Go to Integrations → Microsoft 365 Copilot → Connect',
      'Register an App in Microsoft Entra ID portal',
      'Grant Reports.Read.All and AuditLog.Read.All permissions',
      'Grant admin consent for your tenant',
      'Enter Tenant ID, Client ID, and Client Secret',
      'Copilot usage across Word, Excel, PowerPoint, Outlook, and Teams is monitored',
    ],
    note: 'Requires Entra ID admin consent. Data syncs hourly via Microsoft Graph API.',
  },
];
