import { Cloud, Shield, CheckCircle } from 'lucide-react';

export const cloudClients = [
  {
    id: 'aws',
    name: 'AWS (GuardDuty, CloudTrail, Bedrock, Security Hub)',
    icon: Cloud,
    color: 'text-orange-400',
    time: '15 min',
    steps: [
      'Go to Integrations → Choose your AWS service(s)',
      'Create an IAM user with the minimum required permissions listed on each integration page',
      'Generate an access key pair',
      'Enter credentials in the integration config',
      'OpenSyber polls findings every 5 minutes',
      'For Bedrock: enable model invocation logging in the Bedrock console first',
    ],
    note: 'Use a dedicated IAM user with least-privilege. We recommend GuardDuty + CloudTrail as the minimum AWS setup.',
  },
  {
    id: 'azure',
    name: 'Azure (Sentinel, Entra ID, Azure OpenAI)',
    icon: Cloud,
    color: 'text-cyan-400',
    time: '15 min',
    steps: [
      'Go to Integrations → Choose your Azure service(s)',
      'Register an App in Microsoft Entra ID',
      'Grant the API permissions listed on each integration page',
      'Create a client secret',
      'Enter Tenant ID, Client ID, and Client Secret',
      'For Sentinel: also provide your Log Analytics Workspace ID',
    ],
    note: 'All Azure integrations use the same App Registration — you only need one.',
  },
  {
    id: 'gcp',
    name: 'Google Cloud (SCC, Vertex AI)',
    icon: Cloud,
    color: 'text-info',
    time: '10 min',
    steps: [
      'Go to Integrations → Choose your GCP service',
      'Create a service account with the required IAM roles',
      'Download the JSON key file',
      'Paste the JSON contents into the config field',
      'Enter your Organization ID or Project ID',
    ],
    note: 'Use a dedicated service account. For SCC, organization-level access is required.',
  },
  {
    id: 'tenant-iq',
    name: 'Microsoft 365 Tenant IQ',
    icon: Shield,
    color: 'text-info',
    time: '15 min',
    steps: [
      'Go to Integrations → Microsoft 365 Tenant IQ → Connect',
      'Register an App with Office 365 Management APIs permissions',
      'Grant ActivityFeed.Read and ActivityFeed.ReadDlp',
      'Grant admin consent for tenant-wide access',
      'Enter Tenant ID, Client ID, and Client Secret',
      'OpenSyber ingests the unified audit log covering Outlook, SharePoint, OneDrive, Exchange, and Copilot',
    ],
    note: 'This is the most comprehensive M365 integration — it covers everything in one connection. Polls every 15 minutes.',
  },
  {
    id: 'slack-teams',
    name: 'Slack & Microsoft Teams Alerts',
    icon: Cloud,
    color: 'text-pink-400',
    time: '2 min',
    steps: [
      'Go to Integrations → Slack or Microsoft Teams',
      'Create an Incoming Webhook in your platform (Slack App settings or Teams channel connectors)',
      'Copy the webhook URL',
      'Paste it in the integration config',
      'Security alerts are delivered as rich messages to your channel',
    ],
    note: 'Both support interactive buttons for incident response directly from the chat.',
  },
  {
    id: 'siem',
    name: 'SIEM (Splunk, Datadog, Grafana, Syslog)',
    icon: Shield,
    color: 'text-yellow-400',
    time: '10 min',
    steps: [
      'Go to Integrations → Choose your SIEM platform',
      'For Splunk: enable HEC and create a token',
      'For Datadog: create an API key',
      'For Grafana: set up a Loki data source',
      'For generic SIEM: configure syslog receiver with CEF/LEEF format',
      'Enter connection details in the integration config',
    ],
    note: 'Events are formatted in CIM-compatible schemas for automatic field extraction.',
  },
  {
    id: 'ticketing',
    name: 'Jira & Linear (Auto-Ticketing)',
    icon: CheckCircle,
    color: 'text-info',
    time: '5 min',
    steps: [
      'Go to Integrations → Jira or Linear',
      'For Jira: create an API token and choose a project',
      'For Linear: generate an API key and select a team',
      'Enter credentials in the integration config',
      'Critical findings auto-create tickets with severity mapping',
      'Ticket status syncs back when issues are resolved',
    ],
    note: 'Bi-directional sync means closing a Jira ticket marks the finding as remediated in OpenSyber.',
  },
];
