// Stream M — gerrit-callback tests.
//
// Mocks env.RUNNERS (KV) and global fetch to exercise the notify path
// end to end without touching a real Gerrit or a real KV binding.

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { notifyGerritOnRunComplete, readCorrelation } from "./gerrit-callback";
import type { Env } from "./types";

// --- tiny in-memory KV mock -------------------------------------------------

function makeKv(initial: Record<string, string> = {}) {
  const store = new Map<string, string>(Object.entries(initial));
  return {
    get: vi.fn(async (key: string) => store.get(key) ?? null),
    put: vi.fn(async (key: string, value: string) => {
      store.set(key, value);
    }),
    delete: vi.fn(async (key: string) => {
      store.delete(key);
    }),
    _store: store,
  };
}

function makeEnv(kv: ReturnType<typeof makeKv>): Env {
  return { RUNNERS: kv as unknown as KVNamespace } as unknown as Env;
}

// Seed a correlation + project registration in KV.
function seed(kv: ReturnType<typeof makeKv>, opts: {
  runId: string;
  projectId: string;
  changeId: string;
  revision: string;
  host?: string;
  user?: string;
  password?: string;
  skipProject?: boolean;
}) {
  kv._store.set(
    `run:${opts.runId}:gerrit`,
    JSON.stringify({
      projectId: opts.projectId,
      changeId: opts.changeId,
      revision: opts.revision,
    })
  );
  if (!opts.skipProject) {
    kv._store.set(
      `gerrit:project:${opts.projectId}`,
      JSON.stringify({
        id: opts.projectId,
        ownerSub: "user_1",
        host: opts.host ?? "https://gerrit.example.com",
        project: "norlys/metering",
        httpUser: opts.user ?? "pushci-bot",
        httpPassword: opts.password ?? "plaintext-pw",
        httpPasswordEnc: false,
        webhookSecret: "secret",
        createdAt: new Date().toISOString(),
      })
    );
  }
}

const originalFetch = globalThis.fetch;

describe("notifyGerritOnRunComplete", () => {
  beforeEach(() => {
    globalThis.fetch = vi.fn();
  });

  afterEach(() => {
    globalThis.fetch = originalFetch;
    vi.restoreAllMocks();
  });

  it("no correlation record → posted=false", async () => {
    const kv = makeKv();
    const env = makeEnv(kv);
    const result = await notifyGerritOnRunComplete(env, "run-404", "passed");
    expect(result).toEqual({ ok: true, posted: false });
    expect(globalThis.fetch).not.toHaveBeenCalled();
  });

  it("passed → posts Verified +1 and deletes correlation", async () => {
    const kv = makeKv();
    seed(kv, { runId: "r1", projectId: "p1", changeId: "Iabc", revision: "deadbeef" });
    const env = makeEnv(kv);

    (globalThis.fetch as ReturnType<typeof vi.fn>).mockResolvedValue(
      new Response(")]}'\n{}", { status: 200 })
    );

    const result = await notifyGerritOnRunComplete(env, "r1", "passed");
    expect(result).toEqual({ ok: true, posted: true });

    const fetchMock = globalThis.fetch as ReturnType<typeof vi.fn>;
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const [url, init] = fetchMock.mock.calls[0] as [string, RequestInit];
    expect(url).toContain("/a/changes/Iabc/revisions/deadbeef/review");
    const body = JSON.parse(String(init.body));
    expect(body.labels).toEqual({ Verified: 1 });
    expect(body.tag).toBe("autogenerated:pushci");

    // Correlation was deleted.
    expect(kv._store.has("run:r1:gerrit")).toBe(false);
  });

  it("failed → posts Verified -1", async () => {
    const kv = makeKv();
    seed(kv, { runId: "r2", projectId: "p1", changeId: "Ixyz", revision: "cafe" });
    const env = makeEnv(kv);

    (globalThis.fetch as ReturnType<typeof vi.fn>).mockResolvedValue(
      new Response(")]}'\n{}", { status: 200 })
    );

    const result = await notifyGerritOnRunComplete(env, "r2", "failed");
    expect(result).toEqual({ ok: true, posted: true });

    const fetchMock = globalThis.fetch as ReturnType<typeof vi.fn>;
    const [, init] = fetchMock.mock.calls[0] as [string, RequestInit];
    const body = JSON.parse(String(init.body));
    expect(body.labels).toEqual({ Verified: -1 });
  });

  it("cancelled → posted=false, no Gerrit call", async () => {
    const kv = makeKv();
    seed(kv, { runId: "r3", projectId: "p1", changeId: "Ixyz", revision: "abc" });
    const env = makeEnv(kv);

    const result = await notifyGerritOnRunComplete(env, "r3", "cancelled");
    expect(result).toEqual({ ok: true, posted: false });
    expect(globalThis.fetch).not.toHaveBeenCalled();

    // Correlation NOT deleted — a future re-run can still post a real result.
    expect(kv._store.has("run:r3:gerrit")).toBe(true);
  });

  it("project config missing → ok:false with error", async () => {
    const kv = makeKv();
    seed(kv, {
      runId: "r4",
      projectId: "p-gone",
      changeId: "Ixyz",
      revision: "abc",
      skipProject: true,
    });
    const env = makeEnv(kv);

    const result = await notifyGerritOnRunComplete(env, "r4", "passed");
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.error).toMatch(/not found/i);
    expect(globalThis.fetch).not.toHaveBeenCalled();
  });

  it("gerrit API 404 → ok:false with error", async () => {
    const kv = makeKv();
    seed(kv, { runId: "r5", projectId: "p1", changeId: "Iabc", revision: "deadbeef" });
    const env = makeEnv(kv);

    (globalThis.fetch as ReturnType<typeof vi.fn>).mockResolvedValue(
      new Response("not found", { status: 404 })
    );

    const result = await notifyGerritOnRunComplete(env, "r5", "passed");
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.error).toMatch(/404/);

    // Correlation NOT deleted on failure — next re-run gets a chance.
    expect(kv._store.has("run:r5:gerrit")).toBe(true);
  });

  it("never throws — fetch that throws is captured as structured error", async () => {
    const kv = makeKv();
    seed(kv, { runId: "r6", projectId: "p1", changeId: "Iabc", revision: "deadbeef" });
    const env = makeEnv(kv);

    (globalThis.fetch as ReturnType<typeof vi.fn>).mockRejectedValue(
      new TypeError("network unreachable")
    );

    const result = await notifyGerritOnRunComplete(env, "r6", "passed");
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.error).toMatch(/network unreachable/);
  });

  it("garbage correlation JSON → treated as no correlation", async () => {
    const kv = makeKv();
    kv._store.set("run:r7:gerrit", "{not-json");
    const env = makeEnv(kv);

    const result = await notifyGerritOnRunComplete(env, "r7", "passed");
    expect(result).toEqual({ ok: true, posted: false });
  });

  it("uses basic auth header derived from stored credentials", async () => {
    const kv = makeKv();
    seed(kv, {
      runId: "r8",
      projectId: "p1",
      changeId: "Iabc",
      revision: "deadbeef",
      user: "alice",
      password: "topsecret",
    });
    const env = makeEnv(kv);

    (globalThis.fetch as ReturnType<typeof vi.fn>).mockResolvedValue(
      new Response(")]}'\n{}", { status: 200 })
    );

    await notifyGerritOnRunComplete(env, "r8", "passed");

    const fetchMock = globalThis.fetch as ReturnType<typeof vi.fn>;
    const [, init] = fetchMock.mock.calls[0] as [string, RequestInit];
    const headers = new Headers(init.headers);
    const auth = headers.get("authorization") ?? "";
    expect(auth.startsWith("Basic ")).toBe(true);
    const decoded = atob(auth.slice("Basic ".length));
    expect(decoded).toBe("alice:topsecret");
  });
});

describe("readCorrelation", () => {
  it("returns null for unknown key", async () => {
    const kv = makeKv();
    const env = makeEnv(kv);
    expect(await readCorrelation(env, "missing")).toBeNull();
  });

  it("parses a well-formed correlation", async () => {
    const kv = makeKv();
    kv._store.set(
      "run:rX:gerrit",
      JSON.stringify({ projectId: "pid", changeId: "cid", revision: "rev" })
    );
    const env = makeEnv(kv);
    expect(await readCorrelation(env, "rX")).toEqual({
      projectId: "pid",
      changeId: "cid",
      revision: "rev",
    });
  });

  it("returns null for incomplete correlation", async () => {
    const kv = makeKv();
    kv._store.set("run:rY:gerrit", JSON.stringify({ projectId: "pid" }));
    const env = makeEnv(kv);
    expect(await readCorrelation(env, "rY")).toBeNull();
  });
});
