// Gradle HTTP routes — mounted at /api/gradle by index.ts.
//
// Three endpoints, mirroring the Maven router shape:
//
//   POST /api/gradle/parse     → parse a build.gradle[.kts]
//   POST /api/gradle/settings  → generate a ~/.gradle/init.d/ script
//   POST /api/gradle/pipeline  → generate a `.pushci.yml` tuned for Gradle
//
// All endpoints are pure JSON in / JSON (or text) out. No persistence.
// Designed for the Norlys pilot where Java + Kotlin teams want to
// bring their existing build.gradle file and see PushCI produce a
// working pipeline in one click.

import { Hono } from "hono";
import type { Env } from "./types";
import {
  parseGradle,
  parseGradlePlugins,
  parseSettingsGradle,
  type ParsedGradle,
  type GradlePlugin,
} from "./gradle";
import {
  generateGradleInitScript,
  defaultPropertiesTemplate,
  looksLikePlaintextGradleSecret,
  type GradleRepository,
} from "./gradle-settings";

export const gradleRoutes = new Hono<{ Bindings: Env }>();

// --- POST /api/gradle/parse ------------------------------------------------

gradleRoutes.post("/parse", async (c) => {
  let body: { buildGradle?: string; isKotlinDsl?: boolean; settingsGradle?: string };
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid_json" }, 400);
  }
  if (!body.buildGradle || typeof body.buildGradle !== "string") {
    return c.json({ error: "buildGradle required" }, 400);
  }
  try {
    const parsed = parseGradle(body.buildGradle, body.isKotlinDsl);
    const subprojects = body.settingsGradle
      ? parseSettingsGradle(body.settingsGradle)
      : [];
    const structuredPlugins = parseGradlePlugins(body.buildGradle);
    return c.json({
      gradle: { ...parsed, subprojects },
      isMultiProject: subprojects.length > 0,
      structuredPlugins,
    });
  } catch (e) {
    return c.json({ error: "parse_failed", detail: String(e) }, 400);
  }
});

// --- POST /api/gradle/settings ---------------------------------------------

gradleRoutes.post("/settings", async (c) => {
  let body: { repositories?: GradleRepository[] };
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid_json" }, 400);
  }
  if (!Array.isArray(body.repositories)) {
    return c.json({ error: "repositories required" }, 400);
  }
  const warnings: string[] = [];
  for (const r of body.repositories) {
    if (!r.name || !r.url) {
      return c.json({ error: "repository name/url required" }, 400);
    }
    if (r.password && looksLikePlaintextGradleSecret(r.password)) {
      warnings.push(
        `repo '${r.name}' password looks plaintext — prefer an env-var name`,
      );
    }
  }
  const initScript = generateGradleInitScript({ repositories: body.repositories });
  const properties = defaultPropertiesTemplate();
  return c.json({ initScript, properties, warnings });
});

// --- POST /api/gradle/pipeline ---------------------------------------------

interface PipelineOptions {
  javaVersion?: string;
  spotbugs?: boolean;
  detekt?: boolean;
  multiProject?: boolean;
  subprojects?: string[];
  withTests?: boolean;
  deploy?: boolean;
  isKotlinDsl?: boolean;
}

/**
 * Translate a parsed gradle build and user options into a recommended
 * `.pushci.yml`. Kept as a pure string builder so it can be unit
 * tested without spinning up Hono. Output always uses
 * `./gradlew --no-daemon --parallel build` and caches
 * `~/.gradle/caches/modules-2`, `~/.gradle/caches/jars-9`, and
 * `~/.gradle/wrapper/dists` (the three dir the Gradle docs explicitly
 * call out as safe to share across runs).
 */
export function buildGradlePipeline(
  gradle: ParsedGradle,
  plugins: GradlePlugin[],
  options: PipelineOptions = {},
): string {
  const java = options.javaVersion ?? gradle.javaVersion ?? "17";
  const subprojects = options.subprojects ?? gradle.subprojects ?? [];
  const isMulti = options.multiProject ?? subprojects.length > 0;
  const withTests = options.withTests ?? true;

  const pluginIds = new Set(plugins.map((p) => p.id));
  const springBoot = plugins.find((p) => p.id === "org.springframework.boot");
  const hasSpotBugs = options.spotbugs ?? pluginIds.has("com.github.spotbugs");
  const hasDetekt = options.detekt ?? pluginIds.has("io.gitlab.arturbosch.detekt");

  const coord =
    gradle.group && gradle.version
      ? `${gradle.group}:${gradle.version}`
      : gradle.group ?? "gradle-project";

  const lines: string[] = [];
  lines.push(`# Generated by PushCI for ${coord}`);
  lines.push(`# DSL: ${gradle.isKotlinDsl ? "Kotlin" : "Groovy"}`);
  if (springBoot) {
    lines.push(`# Spring Boot ${springBoot.version ?? "(version unknown)"} detected`);
  }
  lines.push(`# Recommendation: check \`gradlew\` wrapper into git so PushCI can run it`);
  lines.push(`version: 1`);
  lines.push(`language: java`);
  lines.push(`build_tool: gradle`);
  lines.push(`java: "${java}"`);
  lines.push(`cache:`);
  lines.push(`  - path: ~/.gradle/caches/modules-2`);
  lines.push(`    key: gradle-modules-\${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}`);
  lines.push(`  - path: ~/.gradle/caches/jars-9`);
  lines.push(`    key: gradle-jars`);
  lines.push(`  - path: ~/.gradle/wrapper/dists`);
  lines.push(`    key: gradle-wrapper-\${{ hashFiles('**/gradle-wrapper.properties') }}`);

  lines.push(`stages:`);

  // Build stage — main check.
  lines.push(`  - name: build`);
  if (isMulti && subprojects.length > 0) {
    const hints = subprojects.map((s) => `:${s}:build`).join(" ");
    lines.push(`    run: ./gradlew --no-daemon --parallel ${hints}`);
  } else {
    lines.push(`    run: ./gradlew --no-daemon --parallel build -x test`);
  }

  // Test stage.
  if (withTests) {
    lines.push(`  - name: test`);
    lines.push(`    depends_on: [build]`);
    lines.push(`    run: ./gradlew test`);
    lines.push(`    reports:`);
    lines.push(`      - junit: "**/build/test-results/test/*.xml"`);
    lines.push(`      - surefire: "**/build/reports/surefire/*.xml"`);
    lines.push(`      - testng: "**/build/reports/testng/*.xml"`);
  }

  if (hasSpotBugs) {
    lines.push(`  - name: spotbugs`);
    lines.push(`    depends_on: [build]`);
    lines.push(`    run: ./gradlew spotbugsMain`);
    lines.push(`    optional: true`);
  }
  if (hasDetekt) {
    lines.push(`  - name: detekt`);
    lines.push(`    depends_on: [build]`);
    lines.push(`    run: ./gradlew detekt`);
    lines.push(`    optional: true`);
  }

  if (options.deploy) {
    lines.push(`  - name: publish`);
    lines.push(`    depends_on: [test]`);
    lines.push(`    run: ./gradlew publish`);
    lines.push(`    env:`);
    lines.push(`      GRADLE_OPTS: "-Dorg.gradle.internal.http.connectionTimeout=120000"`);
  }
  return lines.join("\n") + "\n";
}

gradleRoutes.post("/pipeline", async (c) => {
  let body: {
    buildGradle?: string;
    settingsGradle?: string;
    options?: PipelineOptions;
  };
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid_json" }, 400);
  }
  if (!body.buildGradle || typeof body.buildGradle !== "string") {
    return c.json({ error: "buildGradle required" }, 400);
  }
  try {
    const opts = body.options ?? {};
    const gradle = parseGradle(body.buildGradle, opts.isKotlinDsl);
    const plugins = parseGradlePlugins(body.buildGradle);
    const subprojects = body.settingsGradle
      ? parseSettingsGradle(body.settingsGradle)
      : opts.subprojects ?? [];
    const enriched: ParsedGradle = { ...gradle, subprojects };
    const yaml = buildGradlePipeline(enriched, plugins, {
      ...opts,
      subprojects,
    });
    return c.json({
      yaml,
      coordinates:
        gradle.group && gradle.version ? `${gradle.group}:${gradle.version}` : undefined,
      isMultiProject: subprojects.length > 0,
      subprojects,
    });
  } catch (e) {
    return c.json({ error: "pipeline_failed", detail: String(e) }, 400);
  }
});
