// Gradle init script + gradle.properties generator.
//
// Produces a `~/.gradle/init.d/pushci.init.gradle` that registers
// private repositories (Nexus, Artifactory, GitHub Packages) with
// environment-variable credential placeholders. No secret is ever
// hard-coded — the output always calls `System.getenv(...)` so the
// build picks up credentials at runtime.
//
// Also produces a minimal `gradle.properties` from a key/value map
// for users who prefer props-file credentials (we still require the
// actual secret to live outside the file).

export interface GradleRepository {
  name: string;
  url: string;
  /**
   * Optional env var holding the username. Defaults to
   * `<NAME>_USERNAME` (upper-cased, non-alnum → `_`).
   */
  username?: string;
  /**
   * Optional env var holding the password. Defaults to
   * `<NAME>_PASSWORD`.
   */
  password?: string;
}

export interface InitScriptOptions {
  repositories: GradleRepository[];
}

export interface PropertiesOptions {
  props: Record<string, string>;
}

/** Escape a string for safe embedding inside a Groovy double-quoted literal. */
function groovyEscape(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Derive a stable env-var name from a repository name. */
function envVarName(base: string, suffix: string): string {
  const cleaned = base
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return `${cleaned || "REPO"}_${suffix}`;
}

/** Detect a plaintext secret — mirrors maven-settings for consistency. */
export function looksLikePlaintextGradleSecret(value: string): boolean {
  const trimmed = value.trim();
  if (trimmed === "") return false;
  if (trimmed.startsWith("System.getenv(")) return false;
  if (trimmed.startsWith("${env.") && trimmed.endsWith("}")) return false;
  if (/^[A-Z][A-Z0-9_]*$/.test(trimmed)) return false; // looks like an env var name
  return true;
}

/**
 * Generate a Gradle init script that injects private repositories
 * into every project. The script uses Groovy DSL (not Kotlin) because
 * init scripts still default to Groovy in every Gradle version and
 * Kotlin init scripts require an opt-in `.init.gradle.kts` name which
 * not every toolchain reliably picks up.
 */
export function generateGradleInitScript(opts: InitScriptOptions): string {
  const lines: string[] = [];
  lines.push(`// Generated by PushCI. Credentials resolved from env vars at runtime.`);
  lines.push(`// Never commit secrets to this file — the templated values below`);
  lines.push(`// call System.getenv() so the build picks up credentials safely.`);
  lines.push(`allprojects {`);
  lines.push(`    repositories {`);
  for (const repo of opts.repositories) {
    const userEnv = repo.username ?? envVarName(repo.name, "USERNAME");
    const passEnv = repo.password ?? envVarName(repo.name, "PASSWORD");
    lines.push(`        maven {`);
    lines.push(`            name = "${groovyEscape(repo.name)}"`);
    lines.push(`            url = uri("${groovyEscape(repo.url)}")`);
    lines.push(`            credentials {`);
    lines.push(`                username = System.getenv("${userEnv}")`);
    lines.push(`                password = System.getenv("${passEnv}")`);
    lines.push(`            }`);
    lines.push(`        }`);
  }
  lines.push(`        mavenCentral()`);
  lines.push(`    }`);
  lines.push(`}`);
  return lines.join("\n") + "\n";
}

/**
 * Generate a deterministic `gradle.properties` string from a plain
 * key/value map. Keys are written in the order provided so snapshot
 * tests stay stable across runs.
 */
export function generateGradleProperties(opts: PropertiesOptions): string {
  const lines: string[] = [
    `# Generated by PushCI. Do not commit secrets to this file.`,
  ];
  for (const [k, v] of Object.entries(opts.props)) {
    lines.push(`${k}=${v}`);
  }
  return lines.join("\n") + "\n";
}

/**
 * Convenience helper returning a small template gradle.properties
 * users can fill in with their own env-var pointers. Used by the
 * `/api/gradle/settings` route alongside the init script.
 */
export function defaultPropertiesTemplate(): string {
  return generateGradleProperties({
    props: {
      "org.gradle.parallel": "true",
      "org.gradle.caching": "true",
      "org.gradle.daemon": "false",
      "org.gradle.jvmargs": "-Xmx2g -XX:MaxMetaspaceSize=512m",
    },
  });
}
