// Maven HTTP routes — mounted at /api/maven by index.ts.
//
// Three endpoints:
//
//   POST /api/maven/parse     → parse a pom.xml
//   POST /api/maven/settings  → generate a settings.xml
//   POST /api/maven/pipeline  → generate a `.pushci.yml` tuned for Maven
//
// All endpoints are pure JSON in, JSON (or text for settings/pipeline)
// out. No persistence. Designed for the Norlys pilot onboarding flow
// where enterprise teams want to bring their existing pom.xml and see
// PushCI produce a working pipeline in one click.

import { Hono } from "hono";
import type { Env } from "./types";
import { parsePom, parseMultiModule, type ParsedPom } from "./maven";
import {
  generateSettingsXml,
  looksLikePlaintextSecret,
  type SettingsOptions,
} from "./maven-settings";

export const mavenRoutes = new Hono<{ Bindings: Env }>();

// --- POST /api/maven/parse -------------------------------------------------

mavenRoutes.post("/parse", async (c) => {
  let body: { pomXml?: string; children?: Record<string, string> };
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid_json" }, 400);
  }
  if (!body.pomXml || typeof body.pomXml !== "string") {
    return c.json({ error: "pomXml required" }, 400);
  }
  try {
    const parsed = parsePom(body.pomXml);
    const multi = body.children
      ? parseMultiModule(body.pomXml, body.children)
      : undefined;
    return c.json({
      pom: parsed,
      isMultiModule: parsed.modules.length > 0,
      moduleGraph: multi,
    });
  } catch (e) {
    return c.json({ error: "parse_failed", detail: String(e) }, 400);
  }
});

// --- POST /api/maven/settings ----------------------------------------------

mavenRoutes.post("/settings", async (c) => {
  let body: Partial<SettingsOptions>;
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid_json" }, 400);
  }
  if (!Array.isArray(body.servers)) {
    return c.json({ error: "servers required" }, 400);
  }
  const warnings: string[] = [];
  for (const s of body.servers) {
    if (!s.id || !s.username) {
      return c.json({ error: "server id/username required" }, 400);
    }
    if (looksLikePlaintextSecret(s.password ?? "")) {
      warnings.push(
        `server '${s.id}' appears to use a plaintext password — prefer \${env.VAR} placeholder`,
      );
    }
  }
  const xml = generateSettingsXml({
    servers: body.servers,
    mirrors: body.mirrors,
    profiles: body.profiles,
    localRepository: body.localRepository,
  });
  return c.json({ xml, warnings });
});

// --- POST /api/maven/pipeline ----------------------------------------------

interface PipelineOptions {
  javaVersion?: string;
  spotbugs?: boolean;
  multiModule?: boolean;
  deploy?: boolean;
}

/**
 * Translate a parsed pom and user options into a recommended
 * `.pushci.yml`. Kept as a pure string builder so it can be unit
 * tested without spinning up Hono. Output uses `mvn -B -T 1C verify`
 * (batch, 1 thread per core) and caches `~/.m2/repository`.
 */
export function buildMavenPipeline(
  pom: ParsedPom,
  options: PipelineOptions = {},
): string {
  const java = options.javaVersion ?? detectJavaVersion(pom) ?? "17";
  const isMulti = options.multiModule ?? pom.modules.length > 0;
  const lines: string[] = [];
  lines.push(`# Generated by PushCI for ${pom.groupId}:${pom.artifactId}`);
  lines.push(`version: 1`);
  lines.push(`language: java`);
  lines.push(`build_tool: maven`);
  lines.push(`java: "${java}"`);
  lines.push(`cache:`);
  lines.push(`  - path: ~/.m2/repository`);
  lines.push(`    key: maven-\${{ hashFiles('**/pom.xml') }}`);
  lines.push(`stages:`);
  lines.push(`  - name: install`);
  lines.push(`    run: mvn -B -q dependency:go-offline`);
  lines.push(`  - name: build`);
  lines.push(`    depends_on: [install]`);
  if (isMulti) {
    lines.push(`    run: mvn -B -T 1C -DskipTests verify`);
  } else {
    lines.push(`    run: mvn -B -DskipTests package`);
  }
  lines.push(`  - name: test`);
  lines.push(`    depends_on: [install]`);
  lines.push(`    run: mvn -B -T 1C verify`);
  lines.push(`    reports:`);
  lines.push(`      - surefire: "**/target/surefire-reports/*.xml"`);
  lines.push(`      - failsafe: "**/target/failsafe-reports/*.xml"`);
  if (options.spotbugs) {
    lines.push(`  - name: spotbugs`);
    lines.push(`    depends_on: [build]`);
    lines.push(`    run: mvn -B com.github.spotbugs:spotbugs-maven-plugin:check`);
    lines.push(`    optional: true`);
  }
  if (options.deploy) {
    lines.push(`  - name: deploy`);
    lines.push(`    depends_on: [test]`);
    lines.push(`    run: mvn -B -DskipTests deploy`);
    lines.push(`    env:`);
    lines.push(`      MAVEN_OPTS: "-Dmaven.wagon.http.retryHandler.count=3"`);
  }
  return lines.join("\n") + "\n";
}

function detectJavaVersion(pom: ParsedPom): string | undefined {
  const p = pom.properties;
  return (
    p["maven.compiler.release"] ||
    p["maven.compiler.target"] ||
    p["java.version"] ||
    undefined
  );
}

mavenRoutes.post("/pipeline", async (c) => {
  let body: { pomXml?: string; options?: PipelineOptions };
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid_json" }, 400);
  }
  if (!body.pomXml || typeof body.pomXml !== "string") {
    return c.json({ error: "pomXml required" }, 400);
  }
  try {
    const pom = parsePom(body.pomXml);
    const yaml = buildMavenPipeline(pom, body.options ?? {});
    return c.json({
      yaml,
      coordinates: `${pom.groupId}:${pom.artifactId}:${pom.version}`,
      isMultiModule: pom.modules.length > 0,
      modules: pom.modules,
    });
  } catch (e) {
    return c.json({ error: "pipeline_failed", detail: String(e) }, 400);
  }
});
