// Maven settings.xml generator.
//
// Produces a Maven `~/.m2/settings.xml` pointing at private Nexus or
// Artifactory with environment-variable placeholders for credentials.
// Pure string builder — no secrets are baked into the output; callers
// inject `${env.NEXUS_PASSWORD}` style references which Maven resolves
// at build time.

export interface MavenServer {
  id: string;
  username: string;
  /**
   * Password. Strongly recommended to pass an env-var placeholder such
   * as `${env.NEXUS_PASSWORD}` rather than a literal secret.
   */
  password: string;
}

export interface MavenMirror {
  id: string;
  url: string;
  mirrorOf: string;
  name?: string;
}

export interface MavenProfile {
  id: string;
  active?: boolean;
  properties?: Record<string, string>;
  repositories?: Array<{ id: string; url: string }>;
}

export interface SettingsOptions {
  servers: MavenServer[];
  mirrors?: MavenMirror[];
  profiles?: MavenProfile[];
  /** Override the local Maven repository path. Defaults to `~/.m2/repository`. */
  localRepository?: string;
}

/** XML-escape a value. Keeps `${...}` placeholders intact. */
function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function indent(level: number): string {
  return "  ".repeat(level);
}

/**
 * Detect whether a password looks like a plaintext secret. We
 * intentionally err on the side of false-positives — the result feeds
 * a warning, not a blocker.
 */
export function looksLikePlaintextSecret(password: string): boolean {
  if (password.startsWith("${") && password.endsWith("}")) return false;
  if (password.trim() === "") return false;
  return true;
}

/** Render a single `<server>` block. */
function renderServer(s: MavenServer, level: number): string {
  const i = indent(level);
  const i1 = indent(level + 1);
  return [
    `${i}<server>`,
    `${i1}<id>${xmlEscape(s.id)}</id>`,
    `${i1}<username>${xmlEscape(s.username)}</username>`,
    `${i1}<password>${xmlEscape(s.password)}</password>`,
    `${i}</server>`,
  ].join("\n");
}

function renderMirror(m: MavenMirror, level: number): string {
  const i = indent(level);
  const i1 = indent(level + 1);
  const parts = [
    `${i}<mirror>`,
    `${i1}<id>${xmlEscape(m.id)}</id>`,
    `${i1}<url>${xmlEscape(m.url)}</url>`,
    `${i1}<mirrorOf>${xmlEscape(m.mirrorOf)}</mirrorOf>`,
  ];
  if (m.name) parts.push(`${i1}<name>${xmlEscape(m.name)}</name>`);
  parts.push(`${i}</mirror>`);
  return parts.join("\n");
}

function renderProfile(p: MavenProfile, level: number): string {
  const i = indent(level);
  const i1 = indent(level + 1);
  const i2 = indent(level + 2);
  const i3 = indent(level + 3);
  const parts = [`${i}<profile>`, `${i1}<id>${xmlEscape(p.id)}</id>`];
  if (p.properties && Object.keys(p.properties).length > 0) {
    parts.push(`${i1}<properties>`);
    for (const [k, v] of Object.entries(p.properties)) {
      parts.push(`${i2}<${k}>${xmlEscape(v)}</${k}>`);
    }
    parts.push(`${i1}</properties>`);
  }
  if (p.repositories && p.repositories.length > 0) {
    parts.push(`${i1}<repositories>`);
    for (const r of p.repositories) {
      parts.push(
        `${i2}<repository>`,
        `${i3}<id>${xmlEscape(r.id)}</id>`,
        `${i3}<url>${xmlEscape(r.url)}</url>`,
        `${i2}</repository>`,
      );
    }
    parts.push(`${i1}</repositories>`);
  }
  parts.push(`${i}</profile>`);
  return parts.join("\n");
}

/**
 * Generate a Maven `settings.xml` string for the given config. Output
 * is deterministic — easy to snapshot-test and safe to write to disk.
 */
export function generateSettingsXml(opts: SettingsOptions): string {
  const lines: string[] = [];
  lines.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  lines.push(
    `<!-- Generated by PushCI. Never hard-code credentials — use ${"\\${env.VAR}"} placeholders. -->`,
  );
  lines.push(
    `<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"`,
  );
  lines.push(`          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"`);
  lines.push(
    `          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">`,
  );
  if (opts.localRepository) {
    lines.push(`  <localRepository>${xmlEscape(opts.localRepository)}</localRepository>`);
  }
  if (opts.servers.length > 0) {
    lines.push(`  <servers>`);
    for (const s of opts.servers) lines.push(renderServer(s, 2));
    lines.push(`  </servers>`);
  }
  if (opts.mirrors && opts.mirrors.length > 0) {
    lines.push(`  <mirrors>`);
    for (const m of opts.mirrors) lines.push(renderMirror(m, 2));
    lines.push(`  </mirrors>`);
  }
  if (opts.profiles && opts.profiles.length > 0) {
    lines.push(`  <profiles>`);
    for (const p of opts.profiles) lines.push(renderProfile(p, 2));
    lines.push(`  </profiles>`);
    const active = opts.profiles.filter((p) => p.active).map((p) => p.id);
    if (active.length > 0) {
      lines.push(`  <activeProfiles>`);
      for (const id of active) lines.push(`    <activeProfile>${xmlEscape(id)}</activeProfile>`);
      lines.push(`  </activeProfiles>`);
    }
  }
  lines.push(`</settings>`);
  return lines.join("\n") + "\n";
}
