// Terraform HTTP routes — mounted at /api/terraform by index.ts.
//
// Two endpoints:
//
//   POST /api/terraform/scan      → parse a set of .tf files
//   POST /api/terraform/pipeline  → generate a `.pushci.yml` for Terraform
//
// Pure JSON in, JSON out. No persistence. Designed for the enterprise
// onboarding flow where teams want PushCI to absorb their existing
// Terraform project and produce a working pipeline in one click.

import { Hono } from "hono";
import type { Env } from "./types";
import {
  scanTerraformFiles,
  type TerraformFile,
  type TerraformScan,
} from "./terraform";

export const terraformRoutes = new Hono<{ Bindings: Env }>();

// --- POST /api/terraform/scan ---------------------------------------------

terraformRoutes.post("/scan", async (c) => {
  let body: { files?: TerraformFile[] };
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid_json" }, 400);
  }
  if (!Array.isArray(body.files)) {
    return c.json({ error: "files required" }, 400);
  }
  for (const f of body.files) {
    if (typeof f?.path !== "string" || typeof f?.content !== "string") {
      return c.json({ error: "each file requires path + content strings" }, 400);
    }
  }
  try {
    const scan = scanTerraformFiles(body.files);
    return c.json({ scan });
  } catch (e) {
    return c.json({ error: "scan_failed", detail: String(e) }, 400);
  }
});

// --- POST /api/terraform/pipeline -----------------------------------------

export interface TerraformPipelineOptions {
  skipSecurity?: boolean;
  backend?: "none" | "configured";
  workspaces?: string[];
  varFile?: string;
}

export interface TerraformPipelineResult {
  yaml: string;
  explanation: {
    stages: string[];
    cachePaths: string[];
    notes: string[];
    securityEnabled: boolean;
  };
}

/**
 * Translate a parsed Terraform scan and user options into a
 * recommended `.pushci.yml`. Pure string builder so it can be unit
 * tested without spinning up Hono. Output caches `.terraform/` and
 * `~/.terraform.d/plugin-cache/` and publishes `tfplan` as an
 * artifact so a later approval job can `terraform apply tfplan`.
 */
export function buildTerraformPipeline(
  scan: TerraformScan,
  options: TerraformPipelineOptions = {},
): TerraformPipelineResult {
  const skipSecurity = options.skipSecurity ?? false;
  const backendMode = options.backend ?? "none";
  const workspaces = options.workspaces ?? [];
  const varFile = options.varFile ?? "";
  const notes: string[] = [];
  const stageNames: string[] = [];

  const lines: string[] = [];
  lines.push(`# Generated by PushCI for Terraform`);
  if (scan.requiredVersion) {
    lines.push(`# required_version: ${scan.requiredVersion}`);
  }
  if (scan.backend) {
    lines.push(`# backend: ${scan.backend.type}`);
  }
  lines.push(`version: 1`);
  lines.push(`language: terraform`);
  lines.push(`cache:`);
  lines.push(`  - path: .terraform/`);
  lines.push(`    key: terraform-\${{ hashFiles('**/.terraform.lock.hcl') }}`);
  lines.push(`  - path: ~/.terraform.d/plugin-cache/`);
  lines.push(`    key: terraform-plugins-\${{ hashFiles('**/*.tf') }}`);
  lines.push(`stages:`);

  // fmt check — fails fast on formatting drift.
  lines.push(`  - name: fmt`);
  lines.push(`    run: terraform fmt -check -recursive`);
  stageNames.push("fmt");

  // init — skip remote state when backend=none.
  const initCmd =
    backendMode === "none"
      ? "terraform init -backend=false -input=false"
      : "terraform init -input=false";
  lines.push(`  - name: init`);
  lines.push(`    depends_on: [fmt]`);
  lines.push(`    run: ${initCmd}`);
  stageNames.push("init");
  if (backendMode === "none") {
    notes.push("init runs with -backend=false — no remote state access");
  }

  // validate
  lines.push(`  - name: validate`);
  lines.push(`    depends_on: [init]`);
  lines.push(`    run: terraform validate`);
  stageNames.push("validate");

  // tflint (optional, recursive)
  lines.push(`  - name: tflint`);
  lines.push(`    depends_on: [init]`);
  lines.push(`    run: tflint --recursive`);
  lines.push(`    optional: true`);
  stageNames.push("tflint");
  notes.push("install tflint in your runner to enable lint checks");

  // plan
  const planParts = ["terraform plan -out=tfplan -lock=false -input=false"];
  if (varFile) planParts.push(`-var-file=${varFile}`);
  lines.push(`  - name: plan`);
  lines.push(`    depends_on: [validate]`);
  lines.push(`    run: ${planParts.join(" ")}`);
  lines.push(`    artifacts:`);
  lines.push(`      - tfplan`);
  stageNames.push("plan");

  // Security scans
  if (!skipSecurity) {
    lines.push(`  - name: tfsec`);
    lines.push(`    depends_on: [validate]`);
    lines.push(`    run: tfsec .`);
    lines.push(`    parallel: true`);
    stageNames.push("tfsec");

    lines.push(`  - name: checkov`);
    lines.push(`    depends_on: [validate]`);
    lines.push(`    run: checkov -d .`);
    lines.push(`    parallel: true`);
    stageNames.push("checkov");
    notes.push("install tfsec/checkov in your runner to enable security scanning");
  }

  if (workspaces.length > 0) {
    lines.push(`env:`);
    lines.push(`  TF_WORKSPACES: "${workspaces.join(",")}"`);
    notes.push(`workspaces hinted: ${workspaces.join(", ")}`);
  }

  return {
    yaml: lines.join("\n") + "\n",
    explanation: {
      stages: stageNames,
      cachePaths: [".terraform/", "~/.terraform.d/plugin-cache/"],
      notes,
      securityEnabled: !skipSecurity,
    },
  };
}

terraformRoutes.post("/pipeline", async (c) => {
  let body: { files?: TerraformFile[]; options?: TerraformPipelineOptions };
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid_json" }, 400);
  }
  if (!Array.isArray(body.files)) {
    return c.json({ error: "files required" }, 400);
  }
  try {
    const scan = scanTerraformFiles(body.files);
    const result = buildTerraformPipeline(scan, body.options ?? {});
    return c.json({
      yaml: result.yaml,
      explanation: result.explanation,
      scan,
    });
  } catch (e) {
    return c.json({ error: "pipeline_failed", detail: String(e) }, 400);
  }
});
