import { Browser, Page } from 'puppeteer';

export interface RecordedAction {
  id: string;
  type: 'click' | 'input' | 'navigation' | 'scroll' | 'wait' | 'assert' | 'submit' | 'keyboard' | 'tap' | 'swipe' | 'screenshot';
  timestamp: number;
  selector?: string | SelectorInfo;
  text?: string;
  url?: string;
  coordinates?: { x: number; y: number };
  element?: string | ElementInfo;
  scrollX?: number;
  scrollY?: number;
  duration?: number;
  assertion?: AssertionInfo;
  reason?: string;
  screenshot?: string;
  metadata?: Record<string, any>;
}

export interface SelectorInfo {
  primary: string;
  fallbacks: string[];
  confidence?: number;
  strategy?: 'id' | 'testid' | 'aria' | 'text' | 'css' | 'xpath' | 'ai';
  stability?: number;
  aiGenerated?: boolean;
  visualHash?: string;
}

export interface ElementInfo {
  tagName: string;
  type?: string;
  text?: string;
  value?: string;
  placeholder?: string;
  href?: string;
  src?: string;
  alt?: string;
  title?: string;
  className?: string;
  attributes?: Record<string, string>;
}

export interface AssertionInfo {
  type: 'visible' | 'hidden' | 'text_contains' | 'text_equals' | 'url_contains' | 'url_equals' | 'exists';
  value: any;
}

export interface WebRecordingConfig {
  url?: string;
  viewport?: { width: number; height: number };
  browser?: 'chrome' | 'firefox' | 'safari' | 'edge';
  browserType?: 'chrome' | 'firefox' | 'safari' | 'edge';
  userAgent?: string;
  locale?: string;
  timezone?: string;
  geolocation?: { latitude: number; longitude: number };
  permissions?: string[];

  // Enhanced features
  cloudProvider?: 'browserstack' | 'saucelabs' | 'lambdatest' | 'local';
  cloudCredentials?: CloudCredentials;
  aiFeatures?: {
    smartSelectors?: boolean;
    assertionSuggestions?: boolean;
    elementHealing?: boolean;
    parameterDetection?: boolean;
  };
  visualTesting?: {
    enableBaselines?: boolean;
    threshold?: number;
    ignoreRegions?: Array<{ x: number; y: number; width: number; height: number }>;
  };
  performance?: {
    collectMetrics?: boolean;
    thresholds?: {
      loadTime?: number;
      firstContentfulPaint?: number;
      largestContentfulPaint?: number;
    };
  };
}

export interface CloudCredentials {
  browserstack?: {
    username: string;
    accessKey: string;
    project?: string;
    build?: string;
  };
  saucelabs?: {
    username: string;
    accessKey: string;
    tunnelIdentifier?: string;
  };
  lambdatest?: {
    username: string;
    accessKey: string;
    tunnel?: boolean;
    tunnelName?: string;
  };
}

export interface SmartSelector {
  primary: string;
  fallbacks: string[];
  confidence: number;
  strategy: 'id' | 'testid' | 'aria' | 'text' | 'css' | 'xpath' | 'ai';
  stability: number;
  aiGenerated?: boolean;
  visualHash?: string;
}

export interface AIAssertion {
  type: 'visual' | 'text' | 'attribute' | 'performance' | 'accessibility';
  selector: string;
  expected: any;
  confidence: number;
  reasoning: string;
  autoGenerated: boolean;
}

export interface ParameterCandidate {
  selector: string;
  element: ElementInfo;
  parameterType: 'input' | 'select' | 'checkbox' | 'radio' | 'text';
  suggestedName: string;
  defaultValue: any;
  confidence: number;
  dataPattern?: string;
}

export interface WebRecordingSession {
  id: string;
  sessionId?: string;
  type: 'web';
  platform: string;
  status: 'idle' | 'recording' | 'processing' | 'completed' | 'failed';
  startTime: number;
  endTime?: number;
  duration?: number;
  createdAt?: number;
  actions: RecordedAction[];
  config: WebRecordingConfig;
  browser?: Browser;
  page?: Page;
  metadata?: Record<string, any>;

  // Enhanced features
  aiSuggestions?: AIAssertion[];
  parameters?: ParameterCandidate[];
  visualBaselines?: Array<{
    actionId: string;
    baseline: string;
    timestamp: number;
  }>;
  performanceMetrics?: Array<{
    timestamp: number;
    metrics: {
      loadTime?: number;
      firstContentfulPaint?: number;
      largestContentfulPaint?: number;
      cumulativeLayoutShift?: number;
      firstInputDelay?: number;
    };
  }>;
  cloudSession?: {
    provider: string;
    sessionId: string;
    sessionUrl?: string;
    videoUrl?: string;
  };
}

export interface MobileRecordingConfig {
  deviceId: string;
  platform: 'ios' | 'android';
  appId?: string;
  simulator?: boolean;
  deviceName?: string;
  osVersion?: string;
}

export interface MobileRecordingSession {
  id: string;
  type: 'mobile';
  platform: 'ios' | 'android';
  status: 'idle' | 'recording' | 'processing' | 'completed' | 'failed';
  startTime: number;
  endTime?: number;
  duration?: number;
  updatedAt?: number;
  actions: RecordedAction[];
  config: MobileRecordingConfig;
  metadata?: Record<string, any>;
}

export type RecordingSession = WebRecordingSession | MobileRecordingSession;

export interface RecordingStartRequest {
  type: 'web' | 'mobile';
  config: WebRecordingConfig | MobileRecordingConfig;
  projectId?: string;
  name?: string;
}

export interface RecordingStopRequest {
  sessionId: string;
}

export interface RecordingExportRequest {
  sessionId: string;
  format: 'puppeteer' | 'playwright' | 'cypress' | 'selenium' | 'yaml' | 'workflow-use' | 'maestro';
  options?: {
    name?: string;
    waitStrategy?: 'fixed' | 'smart' | 'none';
    includeAssertions?: boolean;
    optimizeActions?: boolean;
  };
}

export interface TestSuite {
  id: string;
  name: string;
  description?: string;
  projectId: string;
  testCases: TestCase[];
  createdAt: number;
  updatedAt: number;
}

export interface TestCase {
  id: string;
  name: string;
  description?: string;
  type: 'web' | 'mobile';
  actions: RecordedAction[];
  config: WebRecordingConfig | MobileRecordingConfig;
  createdAt: number;
  updatedAt: number;
}

export interface TestExecution {
  id: string;
  testCaseId: string;
  status: 'pending' | 'running' | 'passed' | 'failed' | 'cancelled';
  startTime: number;
  endTime?: number;
  duration?: number;
  results: TestResult[];
  environment: string;
  logs: string[];
  screenshots: string[];
  error?: string;
}

export interface TestResult {
  actionId: string;
  status: 'passed' | 'failed' | 'skipped';
  duration: number;
  error?: string;
  screenshot?: string;
  timestamp: number;
}

export interface BrowserExtensionMessage {
  type: 'START_RECORDING' | 'STOP_RECORDING' | 'ACTION_RECORDED' | 'STATUS_UPDATE';
  sessionId?: string;
  action?: RecordedAction;
  status?: string;
  data?: any;
}

export interface AgentMessage {
  type: 'DEVICE_CONNECTED' | 'DEVICE_DISCONNECTED' | 'RECORDING_STARTED' | 'RECORDING_STOPPED' | 'ACTION_RECORDED';
  deviceId?: string;
  sessionId?: string;
  action?: RecordedAction;
  data?: any;
}