package main

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/finsavvyai/pushci/internal/cli"
	"github.com/finsavvyai/pushci/internal/config"
	"github.com/finsavvyai/pushci/internal/detect"
)

// tryShellOnlyFallback handles "shell-only" repos — top-level `*.sh`
// scripts, no recognized build tool. Emits a shellcheck lint stage
// per script plus an explicit "no automated test" stub so the user
// ends up with a runnable pushci.yml instead of "no supported stack."
//
// Returns nil when the repo is NOT shell-only — callers drop to the
// generic "no supported stack detected" warning.
func tryShellOnlyFallback(root string) *config.Pipeline {
	p := detect.ScanShellOnly(root)
	if p == nil {
		return nil
	}
	scripts := splitShellCSV(p.ConfigFile)
	cli.Warn(fmt.Sprintf("Shell-only project detected — %d script(s): %s",
		len(scripts), strings.Join(scripts, ", ")))
	cli.Info("pushci provides shellcheck lint + a manual test stub. Edit pushci.yml to add real test / deploy steps.")
	return parseShellOnlyPipeline(shellOnlyYAML(scripts))
}

// shellOnlyYAML returns the generated pushci.yml body: one lint
// stage running `shellcheck` against every top-level `.sh`, plus a
// clearly-labeled test stub that echoes a reminder and exits
// successfully so CI stays green until the user fills it in.
func shellOnlyYAML(scripts []string) string {
	var b strings.Builder
	b.WriteString("\"on\":\n  - push\n  - pull_request\n\nstages:\n")
	b.WriteString("  - name: lint\n")
	b.WriteString("    checks:\n")
	for _, s := range scripts {
		fmt.Fprintf(&b, "      - name: shellcheck %s\n", s)
	}
	b.WriteString("  - name: test\n")
	b.WriteString("    checks:\n")
	b.WriteString("      - name: test-stub\n")
	b.WriteString("        run: echo 'No automated test — add your own command here and commit pushci.yml'\n")
	return b.String()
}

// splitShellCSV turns the comma-joined ConfigFile back into a slice.
// ScanShellOnly packs the script list into ConfigFile to keep the
// CIProvider type one-field-per-role without introducing a second
// slice field.
func splitShellCSV(csv string) []string {
	if csv == "" {
		return nil
	}
	parts := strings.Split(csv, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

// parseShellOnlyPipeline unmarshals the generated YAML. Returns nil
// on parse error so callers can drop to the generic warning.
func parseShellOnlyPipeline(raw string) *config.Pipeline {
	var pipe config.Pipeline
	if err := yaml.Unmarshal([]byte(raw), &pipe); err != nil {
		cli.Warn("Shell-only fallback pushci.yml failed to parse: " + err.Error())
		return nil
	}
	return &pipe
}

// shellHeaderLines is the comment prefix for the generated file when
// the shell-only fallback fires.
func shellHeaderLines(scripts []string, version string) string {
	var b strings.Builder
	b.WriteString("# Generated by pushci init (" + version + ") for shell-only project\n")
	b.WriteString("# Detected scripts: " + strings.Join(scripts, ", ") + "\n")
	b.WriteString("# Lint-only pipeline — replace the test-stub with real test/deploy steps.\n")
	return b.String()
}
