package main

import (
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/finsavvyai/pushci/internal/cli"
	"github.com/finsavvyai/pushci/internal/config"
)

// parseAntPipeline unmarshals the generated YAML into a config.Pipeline.
// Returns nil (not an error) so callers can fall back cleanly.
func parseAntPipeline(raw, src string) *config.Pipeline {
	var pipe config.Pipeline
	if err := yaml.Unmarshal([]byte(raw), &pipe); err != nil {
		cli.Warn("Generated pushci.yml from " + src + " failed to parse: " + err.Error())
		return nil
	}
	return &pipe
}

// antHeaderLines returns the comment block prepended to the generated
// pushci.yml so future readers know the source was an Ant build.xml.
func antHeaderLines(src string, targets []string, version string) string {
	var b strings.Builder
	b.WriteString("# Generated by pushci init from " + src + " (" + version + ")\n")
	if len(targets) > 0 {
		b.WriteString("# Detected Ant targets: " + strings.Join(targets, ", ") + "\n")
	}
	return b.String()
}
