package main

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/finsavvyai/pushci/internal/cli"
	"github.com/finsavvyai/pushci/internal/config"
	"github.com/finsavvyai/pushci/internal/detect"
	"github.com/finsavvyai/pushci/internal/migrate"
)

// tryChefMigrate looks for Chef cookbook structure in root and returns
// a config.Pipeline derived from the cookbook layout. Returns nil when
// no Chef signals are present or the migrator produces no importable
// cookbooks — callers fall back to the framework-heuristic path.
//
// Prints a header line plus env-var hints (rare for Chef, but possible
// when kitchen drivers reference cloud credentials) before returning so
// the user sees exactly what was imported.
func tryChefMigrate(root string) *config.Pipeline {
	providers := detect.ScanCIProviders(root)
	var rel string
	for _, p := range providers {
		if p.Marker == "ci:chef" {
			rel = p.ConfigFile
			break
		}
	}
	if rel == "" {
		return nil
	}
	cli.Info("Found Chef cookbook layout at " + cli.Bold(rel))
	r := migrate.ConvertChef(root)
	if len(r.Cookbooks) == 0 && !r.HasBerksfile && !r.HasPolicyfile && !r.HasKitchen {
		return nil
	}
	for _, w := range r.Warnings {
		cli.Warn(w)
	}
	if len(r.EnvVarsNeeded) > 0 {
		printMigrationEnvVars(r.EnvVarsNeeded)
	}
	if len(r.Cookbooks) > 0 {
		cli.Success(fmt.Sprintf("Detected %d cookbook(s): %s", len(r.Cookbooks), strings.Join(r.Cookbooks, ", ")))
	}
	return parseChefPipeline(r.PushCIYAML)
}

// parseChefPipeline unmarshals the generated YAML into a
// config.Pipeline. Returns nil (not an error) so callers can fall back
// cleanly; the migrator already warned the user via r.Warnings.
func parseChefPipeline(raw string) *config.Pipeline {
	if strings.TrimSpace(raw) == "" {
		return nil
	}
	var pipe config.Pipeline
	if err := yaml.Unmarshal([]byte(raw), &pipe); err != nil {
		cli.Warn("Generated pushci.yml from Chef cookbook layout failed to parse: " + err.Error())
		return nil
	}
	return &pipe
}

// chefHeaderLines returns the comment block we prepend to the generated
// pushci.yml so future readers know the source was a Chef cookbook
// repo and which cookbooks shaped the pipeline.
func chefHeaderLines(cookbooks []string, version string) string {
	var b strings.Builder
	b.WriteString("# Generated by pushci init from Chef cookbook layout (" + version + ")\n")
	if len(cookbooks) > 0 {
		b.WriteString("# Detected cookbooks: " + strings.Join(cookbooks, ", ") + "\n")
	}
	return b.String()
}
