package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/finsavvyai/pushci/internal/cli"
	"github.com/finsavvyai/pushci/internal/config"
	"github.com/finsavvyai/pushci/internal/detect"
	"github.com/finsavvyai/pushci/internal/migrate"
)

// tryJenkinsfileMigrate looks for a Jenkinsfile in root and returns a
// config.Pipeline whose stages mirror the declarative (or best-effort
// scripted) pipeline. Returns nil when no Jenkinsfile is present or
// the migrator produces no importable stages — callers fall back to
// the framework-heuristic path.
//
// Precedence sits after buildspec.yml and Chef so repos migrating from
// AWS CodeBuild or Chef still win; Jenkins wins over generic gitlab/
// github/circleci migration because Jenkinsfiles are the canonical
// telltale for a Java/Maven shop.
func tryJenkinsfileMigrate(root string) *config.Pipeline {
	providers := detect.ScanJenkins(root)
	if len(providers) == 0 {
		return nil
	}
	// Prefer a root-level Jenkinsfile when multiple exist.
	rel := providers[0].ConfigFile
	for _, p := range providers {
		if p.ConfigFile == "Jenkinsfile" {
			rel = p.ConfigFile
			break
		}
	}
	full := filepath.Join(root, rel)
	data, err := os.ReadFile(full)
	if err != nil {
		cli.Warn("Found " + rel + " but could not read: " + err.Error())
		return nil
	}
	cli.Info("Found Jenkins pipeline at " + cli.Bold(rel))
	r := migrate.ConvertJenkinsfile(string(data))
	if r.StagesConverted == 0 {
		for _, w := range r.Warnings {
			cli.Warn(w)
		}
		cli.Warn(rel + " had no importable stages — falling back to framework detection")
		return nil
	}
	for _, w := range r.Warnings {
		if w != "" {
			cli.Warn(w)
		}
	}
	if len(r.EnvVarsNeeded) > 0 {
		printMigrationEnvVars(r.EnvVarsNeeded)
	}
	cli.Success(fmt.Sprintf("Imported %d stages, %d sh commands from %s", r.StagesConverted, r.StepsKept, rel))
	return parseJenkinsfilePipeline(r.PushCIYAML, rel)
}

// parseJenkinsfilePipeline unmarshals generated YAML into a Pipeline.
// Returns nil (not an error) so callers can fall back cleanly; the
// migrator already warned the user via r.Warnings.
func parseJenkinsfilePipeline(raw, src string) *config.Pipeline {
	if strings.TrimSpace(raw) == "" {
		return nil
	}
	var pipe config.Pipeline
	if err := yaml.Unmarshal([]byte(raw), &pipe); err != nil {
		cli.Warn("Generated pushci.yml from " + src + " failed to parse: " + err.Error())
		return nil
	}
	return &pipe
}

// jenkinsfileHeaderLines returns the comment block we prepend to the
// generated pushci.yml so future readers know the source was a
// Jenkinsfile and which credentials/secrets need to be set.
func jenkinsfileHeaderLines(src, version string) string {
	var b strings.Builder
	b.WriteString("# Generated by pushci init from " + src + " (" + version + ")\n")
	b.WriteString("# Review: pushci secret set <NAME> <value> for Jenkins credentials / withCredentials bindings\n")
	return b.String()
}
