package main

import (
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/finsavvyai/pushci/internal/cli"
	"github.com/finsavvyai/pushci/internal/config"
	"github.com/finsavvyai/pushci/internal/detect"
)

// tryWARFallback handles legacy Servlet WAR projects — repos with a
// `WEB-INF/web.xml` descriptor but no pom.xml / build.gradle /
// build.xml. Returns a placeholder pipeline with zero stages and a
// commented-out `javac + jar cvf` template so users start from
// something concrete instead of "no supported stack detected."
//
// Returns nil when the repo is NOT a legacy WAR project — callers
// fall through to the shell-only fallback or the generic warning.
func tryWARFallback(root string) *config.Pipeline {
	p := detect.ScanLegacyWAR(root)
	if p == nil {
		return nil
	}
	cli.Warn("Legacy Servlet WAR project detected at " + cli.Bold(p.ConfigFile))
	cli.Info("No recognized build tool — add a build.xml or pom.xml, or edit pushci.yml manually.")
	return parseWARFallbackPipeline(warFallbackYAML())
}

// warFallbackYAML returns the placeholder pushci.yml body for legacy
// WAR projects. Empty stages list + commented-out javac/jar template
// keeps pushci.yml valid while pointing the user at what to fill in.
func warFallbackYAML() string {
	var b strings.Builder
	b.WriteString("\"on\":\n  - push\n  - pull_request\n\n")
	b.WriteString("stages: []\n\n")
	b.WriteString("# Legacy Servlet WAR project — no build tool detected.\n")
	b.WriteString("# Uncomment and customize one of the templates below, or\n")
	b.WriteString("# add a pom.xml / build.xml to your repo and re-run `pushci init`.\n")
	b.WriteString("#\n")
	b.WriteString("# stages:\n")
	b.WriteString("#   - name: compile\n")
	b.WriteString("#     checks:\n")
	b.WriteString("#       - name: javac\n")
	b.WriteString("#         run: javac -d build/classes -cp \"external-jars/*\" $(find src -name '*.java')\n")
	b.WriteString("#   - name: package\n")
	b.WriteString("#     checks:\n")
	b.WriteString("#       - name: jar\n")
	b.WriteString("#         run: jar cvf app.war -C web/ . -C build/classes .\n")
	return b.String()
}

// parseWARFallbackPipeline unmarshals the placeholder YAML. Returns
// nil on parse error so callers can drop to the generic warning.
func parseWARFallbackPipeline(raw string) *config.Pipeline {
	var pipe config.Pipeline
	if err := yaml.Unmarshal([]byte(raw), &pipe); err != nil {
		cli.Warn("WAR fallback pushci.yml failed to parse: " + err.Error())
		return nil
	}
	return &pipe
}

// warHeaderLines is the comment prefix for the generated file when
// the WAR fallback fires. Kept separate from the YAML body so the
// version string can be injected by the init flow.
func warHeaderLines(descriptor, version string) string {
	var b strings.Builder
	b.WriteString("# Generated by pushci init (" + version + ") for legacy Servlet WAR project\n")
	b.WriteString("# Detected descriptor: " + descriptor + "\n")
	b.WriteString("# No build tool found — review the commented template below.\n")
	return b.String()
}
