package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/finsavvyai/pushci/internal/cli"
	"github.com/finsavvyai/pushci/internal/config"
	"github.com/finsavvyai/pushci/internal/detect"
	"github.com/finsavvyai/pushci/internal/migrate"
)

// tryBuildspecMigrate looks for an AWS CodeBuild buildspec.yml in root
// and returns a config.Pipeline whose stages mirror the buildspec
// phases. Returns nil when no buildspec is present or the file fails
// to parse — callers fall back to the framework-heuristic path.
//
// Prints a multi-line header (file found, command count kept,
// warnings, secret hints) before returning so the user sees exactly
// what was imported.
func tryBuildspecMigrate(root string) *config.Pipeline {
	providers := detect.ScanCIProviders(root)
	var rel string
	// Only accept a root-level buildspec.yml — AWS CodeBuild's
	// canonical layout. A buildspec hidden inside a subdirectory
	// (e.g. cloudformation/code-build-antivirus/buildspec.yml) is
	// a leaf service's spec, NOT the repo-wide CI; letting it
	// pre-empt a root .gitlab-ci.yml / Jenkinsfile is the wrong
	// signal for monorepo dogfood (global-remit/cloudformation).
	for _, p := range providers {
		if p.Marker == "ci:aws-codebuild" && p.ConfigFile == "buildspec.yml" {
			rel = p.ConfigFile
			break
		}
	}
	if rel == "" {
		return nil
	}
	full := filepath.Join(root, rel)
	data, err := os.ReadFile(full)
	if err != nil {
		cli.Warn("Found " + rel + " but could not read: " + err.Error())
		return nil
	}
	cli.Info("Found AWS CodeBuild buildspec at " + cli.Bold(rel))
	r := migrate.ConvertBuildspec(string(data))
	if r.StagesConverted == 0 {
		for _, w := range r.Warnings {
			cli.Warn(w)
		}
		cli.Warn("buildspec.yml had no importable phases — falling back to framework detection")
		return nil
	}
	for _, w := range r.Warnings {
		cli.Warn(w)
	}
	if len(r.EnvVarsNeeded) > 0 {
		printMigrationEnvVars(r.EnvVarsNeeded)
	}
	cli.Success(fmt.Sprintf("Imported %d stages, %d commands from buildspec.yml", r.StagesConverted, r.StepsConverted))
	return parseBuildspecPipeline(r.PushCIYAML, rel)
}

// parseBuildspecPipeline unmarshals the generated YAML into a
// config.Pipeline. Returns nil (not an error) so callers can fall back
// cleanly; the migrator already warned the user via r.Warnings.
func parseBuildspecPipeline(raw, src string) *config.Pipeline {
	var pipe config.Pipeline
	if err := yaml.Unmarshal([]byte(raw), &pipe); err != nil {
		cli.Warn("Generated pushci.yml from " + src + " failed to parse: " + err.Error())
		return nil
	}
	return &pipe
}

// buildspecHeaderLines returns the comment block we prepend to the
// generated pushci.yml so future readers know where the stages came
// from and how to resolve AWS Secrets Manager references. Matches the
// marker style used by `pushci migrate` for gitlab/circle imports.
func buildspecHeaderLines(src, version string) string {
	var b strings.Builder
	b.WriteString("# Generated by pushci init from " + src + " (" + version + ")\n")
	b.WriteString("# Review: pushci secret set <NAME> <value> for AWS Secrets Manager refs\n")
	return b.String()
}
