package main

import (
	"github.com/finsavvyai/pushci/internal/config"
	"github.com/finsavvyai/pushci/internal/detect"
)

// mergeSecondaryHeuristic appends framework-heuristic stages to a
// migrated pipeline when the migration source explicitly supports
// secondary merging (buildspec, Chef, Jenkins, or generic foreign
// CI with governance-only stages). GitHub Actions migration normally
// produces its own heuristic stages so skip there — except when the
// importer mapped zero stages, in which case the migrated pipe is
// empty and we must fall through to language heuristics. Ant
// migration is deliberately left out — an Ant repo with also a
// pom.xml would produce duplicate compile/test stages otherwise.
//
// The Global-Remit v1.6.4 dogfood exposed the gap: a GitLab CI
// pipeline with approve/audit/release governance stages (no
// install/build/test/lint) migrated cleanly but dropped the Node
// language-level stages even though package.json sat in the root.
// Merging heuristic stages from generic CI migrations restores
// them, prefixed as `heur-install`/`heur-build`/... so the
// governance stages still win on name collision.
//
// The Norlys pos-dk dogfood (2026-05-02) exposed a related gap:
// a turborepo with a custom GitHub Actions workflow whose steps
// the importer couldn't map yielded "Migrated 0 steps" + an empty
// pipe. Heuristic merge is now allowed when the GH Actions migration
// produced zero stages, restoring turbo install/lint/test/build.
func mergeSecondaryHeuristic(pipe *config.Pipeline, src initMigrationSource, root string, projects []detect.Project, deployTargets []detect.DeployTarget) {
	ghaEmpty := src.FromGenericCI && src.GenericCIKind == "github" && len(pipe.Stages) == 0
	eligible := src.FromBuildspec || src.FromChef || src.FromJenkins ||
		(src.FromGenericCI && src.GenericCIKind != "github") || ghaEmpty
	if !eligible || len(projects) == 0 {
		return
	}
	heur := generatePipeline(root, projects, deployTargets)
	pipe.Stages = appendSecondaryStages(pipe.Stages, heur.Stages)
}

// prependMigrationHeader returns out prefixed with the appropriate
// "# Generated by pushci init from …" comment block. Order matches
// pickMigrationSource precedence.
func prependMigrationHeader(out []byte, src initMigrationSource, version string) []byte {
	if src.FromBuildspec {
		return append([]byte(buildspecHeaderLines("buildspec.yml", "v"+version)), out...)
	}
	if src.FromChef {
		return append([]byte(chefHeaderLines(src.ChefCookbooks, "v"+version)), out...)
	}
	if src.FromJenkins {
		return append([]byte(jenkinsfileHeaderLines(src.JenkinsfileRel, "v"+version)), out...)
	}
	if src.FromAnt {
		return append([]byte(antHeaderLines(src.AntSource, src.AntTargets, "v"+version)), out...)
	}
	if src.FromWAR {
		return append([]byte(warHeaderLines(src.WARDescriptor, "v"+version)), out...)
	}
	if src.FromShellOnly {
		return append([]byte(shellHeaderLines(src.ShellScripts, "v"+version)), out...)
	}
	return out
}
