package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/finsavvyai/pushci/internal/migrate"
)

// convertActionsFiles reads each workflow, runs it through
// migrate.ConvertActions, and concatenates the resulting pushci.yml
// fragments under a single document. Per-workflow stage names are
// preserved; if two workflows define a job with the same name the
// duplicate is emitted with a "# UNRESOLVED: duplicate stage" hint
// so the user can rename rather than silently shadow.
func convertActionsFiles(files []string) (string, []string, []migrate.EnvVarRef) {
	var b strings.Builder
	var warnings []string
	var envVars []migrate.EnvVarRef
	seen := map[string]string{}

	b.WriteString("# Generated by `pushci import actions` from .github/workflows/\n\n")

	for _, f := range files {
		raw, err := os.ReadFile(f) // #nosec G304 -- user-supplied workflow path
		if err != nil {
			warnings = append(warnings, fmt.Sprintf("read %s: %v", f, err))
			continue
		}
		res := migrate.ConvertActions(migrate.ActionsWorkflow{RawYAML: string(raw)})

		fmt.Fprintf(&b, "# --- WORKFLOW: %s ---\n", filepath.Base(f))
		body := stripActionsHeader(res.PushCIYAML)
		annotateDuplicateStages(&b, body, f, seen, &warnings)
		warnings = append(warnings, res.Warnings...)
		envVars = append(envVars, res.EnvVarsNeeded...)
	}
	return b.String(), warnings, envVars
}

// stripActionsHeader removes the duplicated "on:" block from
// subsequent workflows so the combined output isn't full of repeated
// trigger declarations. We keep the trigger block from the first
// workflow only.
func stripActionsHeader(yaml string) string {
	const marker = "\nstages:\n"
	if idx := strings.Index(yaml, marker); idx > 0 {
		return yaml[idx+1:]
	}
	return yaml
}

// annotateDuplicateStages appends body to b, prefixing any stage
// whose name already appeared in `seen` with an UNRESOLVED comment.
func annotateDuplicateStages(b *strings.Builder, body, file string, seen map[string]string, warnings *[]string) {
	for _, line := range strings.Split(body, "\n") {
		if name, ok := stageNameFrom(line); ok {
			if prev, exists := seen[name]; exists {
				fmt.Fprintf(b, "  # UNRESOLVED: stage %q duplicated (also in %s)\n", name, filepath.Base(prev))
				*warnings = append(*warnings, fmt.Sprintf("duplicate stage %q in %s (also in %s)", name, file, prev))
			} else {
				seen[name] = file
			}
		}
		b.WriteString(line)
		b.WriteByte('\n')
	}
}

func stageNameFrom(line string) (string, bool) {
	t := strings.TrimSpace(line)
	if !strings.HasPrefix(t, "- name:") {
		return "", false
	}
	return strings.TrimSpace(strings.TrimPrefix(t, "- name:")), true
}

// writeActionsOutput writes the combined YAML to disk (or stdout).
// Refuses to overwrite an existing file without --force.
func writeActionsOutput(output, content string, force bool) error {
	if output == "-" {
		_, err := os.Stdout.WriteString(content)
		return err
	}
	if !force {
		if _, err := os.Stat(output); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", output)
		}
	}
	return os.WriteFile(output, []byte(content), 0o644) // #nosec G306 -- yaml is non-secret config
}
