import type { Hono } from 'hono';
import { AI } from '../lib/constants';
import { aiRoutes } from '../routes/ai';
import { aiStreamingRoutes } from '../routes/ai-streaming';
import { aiExportRoutes } from '../routes/ai-export';
import { aiEngineRoutes } from '../routes/ai-engine';
import alertAnalytics from '../routes/alert-analytics';
import { licenseRoutes } from '../routes/licenses';
import alerts from '../routes/alerts';
import anomalyDetection from '../routes/anomaly-detection';
import { cisBenchmarkRoutes as cisBenchmark } from '../routes/cis-benchmark';
import { configSnapshotRoutes as configSnapshots } from '../routes/config-snapshots';
import { configDriftRoutes as configDrifts } from '../routes/config-drifts';
import { governanceRoutes as governance } from '../routes/governance';
import { governanceAiRoutes } from '../routes/governance-ai';
import { copilotReadinessRoutes as copilotReadiness } from '../routes/copilot-readiness';
import { lifecycleRoutes as lifecycle } from '../routes/lifecycle';
import { teamRoutes } from '../routes/team';
import { webhookConfigRoutes } from '../routes/webhook-config';
import { mspBenchmarkRoutes } from '../routes/msp-benchmark';
import { storageAnalyticsRoutes } from '../routes/storage-analytics';
import { copilotUsageRoutes } from '../routes/copilot-usage';
import { reportBuilderRoutes } from '../routes/report-builder';
import { guestReviewRoutes } from '../routes/guest-review';
import { groupCleanupRoutes } from '../routes/group-cleanup';
import { approvalRoutes } from '../routes/approvals';
import { backupHealthRoutes } from '../routes/backup-health';
import { backupDataRoutes } from '../routes/backup-data';
import { pushNotificationRoutes } from '../routes/push-notifications';
import purviewDlpRoutes from '../routes/purview';
import zeroTrustRoutes from '../routes/zero-trust';
import { userDelegationRoutes } from '../routes/user-delegation';
import { userBulkRoutes } from '../routes/user-bulk';
import { portalRoutes } from '../routes/portal';
import { migrationRoutes } from '../routes/migration';
import { eventTriggers } from '../routes/event-triggers';
import { eventLog } from '../routes/event-log';
import { mspProfitRoutes } from '../routes/msp-profit';
import { savingsReportRoutes } from '../routes/savings-report';
import { marketplaceRoutes } from '../routes/marketplace';
import { billingRoutes } from '../routes/billing';
import { brandingRoutes } from '../routes/branding';
import { configExportRoutes } from '../routes/config-export';
import { federatedIdentityRoutes } from '../routes/federated-identity';
import { afterHoursRoutes } from '../routes/after-hours-escalation';
import { credentialRotationRoutes } from '../routes/credential-rotation';
import { copilotSecurityRoutes } from '../routes/copilot-security';
import { driftSuppressionRoutes } from '../routes/drift-suppression';
import { copilotReadinessPdfRoutes } from '../routes/copilot-readiness-pdf';
import { snapshotScheduleRoutes } from '../routes/snapshot-schedule';
import { snapshotExportRoutes } from '../routes/snapshot-export';
import { ssoRoutes } from '../routes/sso';
import { websocketRoutes } from '../routes/websocket';
import { graphSubscriptionRoutes } from '../routes/graph-subscriptions';
import { graphWebhookRoutes } from '../routes/graph-webhook';
import { storageComplianceRoutes } from '../routes/storage-compliance';
import { selfTestRoutes } from '../routes/self-test';
import audit from '../routes/audit';
import { authRoutes } from '../routes/auth';
import { jwksRoutes } from '../routes/auth-jwks';
import compliancePosture from '../routes/compliance-posture';
import costOptimization from '../routes/cost-optimization';
import executiveReport from '../routes/executive-report';
import executiveReportPdf from '../routes/executive-report-pdf';
import { healthRoutes } from '../routes/health';
import { healthDetailedRoutes } from '../routes/health-detailed';
import healthScore from '../routes/health-score';
import { metricsRoutes } from '../routes/metrics';
import openclawIntegrationRoutes from '../routes/integrations/openclaw';
import intelligence from '../routes/intelligence';
import licenseAutopilot from '../routes/license-autopilot';
import { mspRoutes } from '../routes/msp';
import { mspBackupRoutes } from '../routes/msp/backups';
import { intuneRoutes } from '../routes/intune';
import { pimRoutes } from '../routes/pim';
import { defenderRoutes } from '../routes/defender';
import { mcpRoutes } from '../routes/mcp';
import { mcpKeyRoutes } from '../routes/mcp-keys';
import { mcpPublicRoutes } from '../routes/mcp-public';
import { statsPublicRoutes } from '../routes/stats-public';
import { findingDebateRoutes } from '../routes/finding-debate';
import { agentActionsRoutes } from '../routes/agent-actions';
import { agentApprovalRoutes } from '../routes/agent-approval';
import { mcpExternalRoutes } from '../routes/mcp-external';
import { timewarpRoutes } from '../routes/timewarp';
import onboarding from '../routes/onboarding';
import onboardingTracking from '../routes/onboarding-tracking';
import platform from '../routes/platform';
import remediations from '../routes/remediations';
import remediationsDryRun from '../routes/remediations-dryrun';
import savingsLeaderboard from '../routes/savings-leaderboard';
import security from '../routes/security';
import securityCompliance from '../routes/security-compliance';
import tenantComparison from '../routes/tenant-comparison';
import { tenantRoutes } from '../routes/tenants';
import { tenantSettingsRoutes } from '../routes/tenant-settings';
import tenantProfileRoutes from '../routes/tenants/profile';
import purviewRoutes from '../routes/tenants/purview';
import { promoRoutes } from '../routes/tenants/promo';
import tenantWebhookRoutes from '../routes/tenants/webhooks';
import usageHeatmap from '../routes/usage-heatmap';
import users from '../routes/users';
import webhooks from '../routes/webhooks';
import openclawWebhookRoutes from '../routes/webhooks/openclaw';
import workflows from '../routes/workflows';
import { workflowTemplateRoutes } from '../routes/workflow-templates';
import { connectwiseRoutes } from '../routes/integrations-connectwise';
import { connectwiseWebhookRoutes } from '../routes/webhooks-connectwise';
import { dattoRoutes } from '../routes/integrations-datto';
import { kaseyaRoutes } from '../routes/integrations-kaseya';
import { partnerRoutes } from '../routes/partners';
import { gdapRoutes } from '../routes/gdap';
import { siteLifecycleRoutes } from '../routes/site-lifecycle';
import { unifiedSearchRoutes } from '../routes/unified-search';
import { aiSeoRoutes } from '../routes/ai-seo';
import { prospectScanRoutes } from '../routes/prospect-scan';
import { prospectRoutes } from '../routes/prospect';
import { scimUsersRoutes } from '../routes/scim/users';
import { scimGroupsRoutes } from '../routes/scim/groups';
import { scimTokensRoutes } from '../routes/scim-tokens';
import { ssoLoginRoutes } from '../routes/sso-login';
import { ssoCallbackRoutes } from '../routes/sso-callback';
import { webauthnRegisterRoutes } from '../routes/auth-webauthn-register';
import { webauthnAuthRoutes } from '../routes/auth-webauthn-auth';
import { shareRoutes } from '../routes/share';
import { openapiRoutes } from '../routes/openapi';
import type { AppEnv } from './types';

export function registerRoutes(app: Hono<AppEnv>) {
	app.route('/health', healthRoutes);
	app.route('/health', healthDetailedRoutes);
	app.route('/api/health', healthRoutes);
	app.route('/api/health', healthDetailedRoutes);
	app.route('/api/metrics', metricsRoutes);
	app.route('/api/auth', authRoutes);
	app.route('/api/auth/webauthn/register', webauthnRegisterRoutes);
	app.route('/api/auth/webauthn/auth', webauthnAuthRoutes);
	app.route('/api/.well-known/jwks.json', jwksRoutes);
	app.route('/scim/v2/Users', scimUsersRoutes);
	app.route('/scim/v2/Groups', scimGroupsRoutes);
	app.route('/api/sso/scim-tokens', scimTokensRoutes);
	app.route('/api/sso', ssoLoginRoutes);
	app.route('/api/sso', ssoCallbackRoutes);
	app.route('/api/share', shareRoutes);
	app.route('/api', openapiRoutes);
	app.route('/api/tenants', tenantRoutes);
	app.route('/api/tenants', tenantSettingsRoutes);
	app.route('/platform', platform);
	app.route('/api/intelligence', intelligence);
	app.route('/api/alerts', alerts);
	app.route('/api/alert-analytics', alertAnalytics);
	app.route('/api/remediations', remediations);
	app.route('/api/remediations', remediationsDryRun);
	app.route('/api/workflows', workflows);
	app.route('/api/workflow-templates', workflowTemplateRoutes);
	app.route('/api/users', users);
	app.route('/api/security', security);
	app.route('/api/security', securityCompliance);
	app.route('/api/audit', audit);
	app.route('/api/webhooks', webhooks);
	app.route('/api/cost-optimization', costOptimization);
	app.route('/api/onboarding', onboarding);
	app.route('/api/onboarding', onboardingTracking);
	app.route('/api/health-score', healthScore);
	app.route('/api/executive-report', executiveReport);
	app.route('/api/executive-report', executiveReportPdf);
	app.route('/api/savings', savingsLeaderboard);
	app.route('/api/anomaly-detection', anomalyDetection);
	app.route('/api/license-autopilot', licenseAutopilot);
	app.route('/api/compliance-posture', compliancePosture);
	app.route('/api/tenant-comparison', tenantComparison);
	app.route('/api/usage-heatmap', usageHeatmap);
	app.route('/api/tenants/:tenantId/ai', aiRoutes);
	app.route('/api/tenants/:tenantId/ai', aiStreamingRoutes);
	app.route('/', aiExportRoutes);
	app.route('/api/tenants/:tenantId', tenantProfileRoutes);
	app.route('/api/tenants/:tenantId/purview', purviewRoutes);
	app.route('/api/tenants', promoRoutes);
	app.route('/api/tenants/:tenantId/webhooks', tenantWebhookRoutes);
	app.route('/api/msp', mspRoutes);
	app.route('/api/msp/backups', mspBackupRoutes);
	app.route('/api/intune', intuneRoutes);
	app.route('/api/pim', pimRoutes);
	app.route('/api/defender', defenderRoutes);
	app.route('/api/mcp', mcpRoutes);
	app.route('/api/mcp-keys', mcpKeyRoutes);
	app.route('/api/mcp-public', mcpPublicRoutes);
	app.route('/api/stats/public', statsPublicRoutes);
	app.route('/api/finding-debate', findingDebateRoutes);
	app.route('/api/agent-actions', agentActionsRoutes);
	app.route('/api/agent-actions', agentApprovalRoutes);
	app.route('/api/mcp-external', mcpExternalRoutes);
	app.route('/api/timewarp', timewarpRoutes);
	app.route('/api/webhooks/openclaw', openclawWebhookRoutes);
	app.route('/api/integrations/openclaw', openclawIntegrationRoutes);
	app.route('/api/ai', aiEngineRoutes);

	// CIS Benchmark Scanner
	app.route('/api/cis-benchmark', cisBenchmark);
	app.route('/api/config-snapshots', configSnapshots);
	app.route('/api/config-drifts', configDrifts);
	app.route('/api/governance', governance);
	app.route('/api/governance', governanceAiRoutes);
	app.route('/api/copilot-readiness', copilotReadiness);
	app.route('/api/lifecycle', lifecycle);
	app.route('/api/team', teamRoutes);
	app.route('/api/webhook-config', webhookConfigRoutes);
	app.route('/api/msp-benchmark', mspBenchmarkRoutes);
	app.route('/api/storage-analytics', storageAnalyticsRoutes);
	app.route('/api/copilot-usage', copilotUsageRoutes);
	app.route('/api/report-builder', reportBuilderRoutes);
	app.route('/api/guest-review', guestReviewRoutes);
	app.route('/api/group-cleanup', groupCleanupRoutes);
	app.route('/api/approvals', approvalRoutes);
	app.route('/api/backup-health', backupHealthRoutes);
	app.route('/api/backups', backupDataRoutes);
	app.route('/api/push', pushNotificationRoutes);
	app.route('/api/users', userDelegationRoutes);
	app.route('/api/users', userBulkRoutes);
	app.route('/api/delegations', userDelegationRoutes);
	app.route('/api/portal', portalRoutes);
	app.route('/api/migration', migrationRoutes);
	app.route('/api/purview', purviewDlpRoutes);
	app.route('/api/zero-trust', zeroTrustRoutes);
	app.route('/api/tenants/:tenantId/licenses', licenseRoutes);
	app.route('/api/event-triggers', eventTriggers);
	app.route('/api/events', eventLog);
	app.route('/api/msp-profit', mspProfitRoutes);
	app.route('/api/savings-report', savingsReportRoutes);
	app.route('/api/marketplace', marketplaceRoutes);
	app.route('/api/billing', billingRoutes);
	app.route('/api/federated-identity', federatedIdentityRoutes);
	app.route('/api/after-hours', afterHoursRoutes);
	app.route('/api/credential-rotation', credentialRotationRoutes);
	app.route('/api/copilot-security', copilotSecurityRoutes);
	app.route('/api/config-drifts/suppression-rules', driftSuppressionRoutes);
	app.route('/api/copilot-readiness', copilotReadinessPdfRoutes);
	app.route('/api/config-snapshots', snapshotScheduleRoutes);
	app.route('/api/config-snapshots', snapshotExportRoutes);
	app.route('/api/sso', ssoRoutes);
	app.route('/api', websocketRoutes);

	app.route('/api/tenants/:tenantId/graph-subscriptions', graphSubscriptionRoutes);
	app.route('/api/graph', graphWebhookRoutes);
	app.route('/api/tenants/:tenantId/storage', storageComplianceRoutes);

	// Self-test (post-deploy verification)
	app.route('/api/self-test', selfTestRoutes);

	// PSA/RMM Integrations
	app.route('/api/integrations/connectwise', connectwiseRoutes);
	app.route('/api/integrations/datto', dattoRoutes);
	app.route('/api/integrations/kaseya', kaseyaRoutes);
	app.route('/api/webhooks/connectwise', connectwiseWebhookRoutes);

	// Partner Marketplace, GDAP & Site Lifecycle
	app.route('/api/partners', partnerRoutes);
	app.route('/api/gdap', gdapRoutes);
	app.route('/api/governance/sites', siteLifecycleRoutes);

	// White-Label Branding & Config-as-Code Export
	app.route('/api/branding', brandingRoutes);
	app.route('/api/config', configExportRoutes);

	// Unified Search
	app.route('/api/search', unifiedSearchRoutes);

	// AI SEO Optimizer & Publisher
	app.route('/api/ai-seo', aiSeoRoutes);

	// Prospect Scan — unauthenticated MSP sales tool (legacy + new shareable scan)
	app.route('/api/prospect-scan', prospectScanRoutes);
	app.route('/api/prospect', prospectRoutes);

	// API Versioning — /api/v1/* aliases /api/* for forward compatibility
	app.all('/api/v1/*', async (c) => {
		const url = new URL(c.req.url);
		url.pathname = url.pathname.replace('/api/v1/', '/api/');
		const rewritten = new Request(url.toString(), c.req.raw);
		return app.fetch(rewritten, c.env, c.executionCtx);
	});

	// Settings endpoints — require auth
	app.get('/api/settings/ai-provider', async (c, next) => {
		const auth = c.req.header('Authorization');
		if (!auth?.startsWith('Bearer ')) return c.json({ error: 'Unauthorized' }, 401);
		await next();
	}, (c) => c.json({ provider: 'anthropic', model: AI.MODEL, status: c.env.ANTHROPIC_API_KEY ? 'configured' : 'not_configured' }));
	app.post('/api/settings/ai-provider', async (c) => {
		const auth = c.req.header('Authorization');
		if (!auth?.startsWith('Bearer ')) return c.json({ error: 'Unauthorized' }, 401);
		return c.json({ success: true });
	});
}
