import type { Hono } from 'hono';
import alerts from '../routes/alerts';
import alertAnalytics from '../routes/alert-analytics';
import { approvalRoutes } from '../routes/approvals';
import intelligence from '../routes/intelligence';
import remediations from '../routes/remediations';
import remediationsDryRun from '../routes/remediations-dryrun';
import workflows from '../routes/workflows';
import { workflowTemplateRoutes } from '../routes/workflow-templates';
import { lifecycleRoutes as lifecycle } from '../routes/lifecycle';
import users from '../routes/users';
import { userDelegationRoutes } from '../routes/user-delegation';
import { userBulkRoutes } from '../routes/user-bulk';
import audit from '../routes/audit';
import { teamRoutes } from '../routes/team';
import { webhookConfigRoutes } from '../routes/webhook-config';
import { eventTriggers } from '../routes/event-triggers';
import { eventLog } from '../routes/event-log';
import { pushNotificationRoutes } from '../routes/push-notifications';
import { afterHoursRoutes } from '../routes/after-hours-escalation';
import { credentialRotationRoutes } from '../routes/credential-rotation';
import { portalRoutes } from '../routes/portal';
import { migrationRoutes } from '../routes/migration';
import type { AppEnv } from './types';

export function registerOperationsRoutes(app: Hono<AppEnv>) {
	app.route('/api/alerts', alerts);
	app.route('/api/alert-analytics', alertAnalytics);
	app.route('/api/approvals', approvalRoutes);
	app.route('/api/intelligence', intelligence);
	app.route('/api/remediations', remediations);
	app.route('/api/remediations', remediationsDryRun);
	app.route('/api/workflows', workflows);
	app.route('/api/workflow-templates', workflowTemplateRoutes);
	app.route('/api/lifecycle', lifecycle);
	app.route('/api/users', users);
	app.route('/api/users', userDelegationRoutes);
	app.route('/api/users', userBulkRoutes);
	app.route('/api/delegations', userDelegationRoutes);
	app.route('/api/audit', audit);
	app.route('/api/team', teamRoutes);
	app.route('/api/webhook-config', webhookConfigRoutes);
	app.route('/api/event-triggers', eventTriggers);
	app.route('/api/events', eventLog);
	app.route('/api/push', pushNotificationRoutes);
	app.route('/api/after-hours', afterHoursRoutes);
	app.route('/api/credential-rotation', credentialRotationRoutes);
	app.route('/api/portal', portalRoutes);
	app.route('/api/migration', migrationRoutes);
}
