import type { AIProvider, AIProviderConfig } from './aiProviders';
import { OpenHandsProvider, OpenClawProvider } from './aiProviders';
import { formatSchemaForPrompt, getSchema } from './schemaService';
import { executeQuery } from './queryService';
import { AppError } from '../middleware/errorHandler';
import type { NLQueryInput, NLQueryResult } from '../types';

let providers: AIProvider[] = [];

export function initializeAIProviders(config: AIProviderConfig): void {
  providers = [];

  if (config.openHandsURL) {
    providers.push(new OpenHandsProvider(config.openHandsURL, config.openHandsAPIKey));
  }

  if (config.openClawURL) {
    providers.push(new OpenClawProvider(config.openClawURL, config.openClawAPIKey));
  }

  if (providers.length === 0) {
    console.warn('[NLP] No AI providers configured. NL-to-SQL will be unavailable.');
  }
}

export function getProviderCount(): number {
  return providers.length;
}

async function getHealthyProvider(): Promise<AIProvider> {
  for (const provider of providers) {
    try {
      const healthy = await provider.isHealthy();
      if (healthy) return provider;
    } catch {
      continue;
    }
  }
  throw new AppError(503, 'No healthy AI provider available', 'AI_UNAVAILABLE');
}

export async function convertNLToSQL(input: NLQueryInput): Promise<NLQueryResult> {
  const provider = await getHealthyProvider();
  const schema = await getSchema(input.connectionId);
  const schemaText = formatSchemaForPrompt(schema);

  const sql = await provider.convertNLToSQL(input.prompt, schemaText);
  const explanation = `Generated by ${provider.name}: Converted natural language to SQL`;

  let result;
  if (input.execute) {
    result = await executeQuery({ connectionId: input.connectionId, sql });
  }

  return { sql, explanation, result };
}

export async function convertNLToSQLWithContext(
  prompt: string,
  schemaText: string,
): Promise<NLQueryResult> {
  const provider = await getHealthyProvider();
  const sql = await provider.convertNLToSQL(prompt, schemaText);
  const explanation = `Generated by ${provider.name}: Converted natural language to SQL`;
  return { sql, explanation };
}

export async function optimizeSQL(connectionId: string, sql: string) {
  const provider = await getHealthyProvider();
  const schema = await getSchema(connectionId);
  const schemaText = formatSchemaForPrompt(schema);
  return provider.optimizeQuery(sql, schemaText);
}

export async function explainSQL(sql: string): Promise<string> {
  const provider = await getHealthyProvider();
  return provider.explainQuery(sql);
}

export async function getAIStatus(): Promise<{ providers: Array<{ name: string; healthy: boolean }> }> {
  const statuses = await Promise.all(
    providers.map(async (p) => ({
      name: p.name,
      healthy: await p.isHealthy().catch(() => false),
    })),
  );
  return { providers: statuses };
}
