package generator

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/mcpoverflow/api-service/internal/parser"
)

// PythonLambdaGenerator generates Python code for AWS Lambda MCP
type PythonLambdaGenerator struct {
	*BaseGenerator
}

// NewPythonLambdaGenerator creates a new Python Lambda generator
func NewPythonLambdaGenerator() *PythonLambdaGenerator {
	features := []Feature{
		FeatureBasicGeneration,
		FeatureTypeGeneration,
		FeatureAuthGeneration,
		FeatureValidation,
		FeatureErrorHandling,
		FeatureRetryLogic,
		FeatureLogging,
		FeatureAWSLambda,
		FeatureRESTSupport,
		FeatureInlineDocs,
		FeatureExamples,
	}

	gen := &PythonLambdaGenerator{
		BaseGenerator: NewBaseGenerator("python", "aws-lambda", "1.0.0", features),
	}

	return gen
}

// Generate generates Python code for AWS Lambda
func (g *PythonLambdaGenerator) Generate(ctx context.Context, ir *parser.IntermediateRepresentation, opts GenerateOptions) (*GeneratedCode, error) {
	startTime := time.Now()

	// Validate IR
	result, err := g.Validate(ir)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, fmt.Errorf("IR validation failed: %d errors", len(result.Errors))
	}

	files := []GeneratedFile{}

	// Generate main handler file
	handlerFile, err := g.generateHandlerFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate handler file: %w", err)
	}
	files = append(files, handlerFile)

	// Generate types/models file
	modelsFile, err := g.generateModelsFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate models file: %w", err)
	}
	files = append(files, modelsFile)

	// Generate tools file
	toolsFile, err := g.generateToolsFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate tools file: %w", err)
	}
	files = append(files, toolsFile)

	// Generate client file
	clientFile, err := g.generateClientFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate client file: %w", err)
	}
	files = append(files, clientFile)

	// Generate requirements.txt
	requirementsFile, err := g.generateRequirements(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate requirements.txt: %w", err)
	}
	files = append(files, requirementsFile)

	// Generate SAM template
	samFile, err := g.generateSAMTemplate(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate SAM template: %w", err)
	}
	files = append(files, samFile)

	// Generate README
	if opts.IncludeDocs {
		readmeFile, err := g.generateReadme(ir, opts)
		if err != nil {
			return nil, fmt.Errorf("failed to generate README: %w", err)
		}
		files = append(files, readmeFile)
	}

	// Generate tests
	if opts.IncludeTests {
		testFile, err := g.generateTestFile(ir, opts)
		if err != nil {
			return nil, fmt.Errorf("failed to generate tests: %w", err)
		}
		files = append(files, testFile)
	}

	// Create dependencies
	deps := g.generateDependencies(ir, opts)

	// Calculate statistics
	stats := GenerationStatistics{
		TotalFiles:     len(files),
		TotalLines:     g.CountLines(files),
		TotalEndpoints: len(ir.Endpoints),
		TotalTypes:     len(ir.Types),
		GenerationTime: time.Since(startTime),
	}

	return g.CreateGeneratedCode(files, deps, stats), nil
}

// generateHandlerFile generates the main Lambda handler
func (g *PythonLambdaGenerator) generateHandlerFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	// Header
	sb.WriteString("\"\"\"Generated by MCPOverflow Python Generator\n")
	sb.WriteString(fmt.Sprintf("API: %s v%s\n", ir.Metadata.Title, ir.Metadata.Version))
	sb.WriteString(fmt.Sprintf("Generated: %s\n\"\"\"\n\n", time.Now().Format(time.RFC3339)))

	// Imports
	sb.WriteString("import json\n")
	sb.WriteString("import logging\n")
	sb.WriteString("from typing import Dict, Any, Optional\n\n")
	sb.WriteString("from tools import get_tools\n")
	sb.WriteString("from client import APIClient\n\n")

	// Logger setup
	sb.WriteString("logger = logging.getLogger()\n")
	sb.WriteString("logger.setLevel(logging.INFO)\n\n")

	// Main handler
	sb.WriteString("def lambda_handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:\n")
	sb.WriteString("    \"\"\"Main Lambda handler for MCP tools.\"\"\"\n")
	sb.WriteString("    try:\n")
	sb.WriteString("        # Parse request\n")
	sb.WriteString("        path = event.get('path', '')\n")
	sb.WriteString("        method = event.get('httpMethod', 'GET')\n")
	sb.WriteString("        body = event.get('body', '{}')\n\n")

	sb.WriteString("        # CORS headers\n")
	sb.WriteString("        headers = {\n")
	sb.WriteString("            'Content-Type': 'application/json',\n")
	sb.WriteString("            'Access-Control-Allow-Origin': '*',\n")
	sb.WriteString("            'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',\n")
	sb.WriteString("            'Access-Control-Allow-Headers': 'Content-Type',\n")
	sb.WriteString("        }\n\n")

	sb.WriteString("        # Handle OPTIONS for CORS\n")
	sb.WriteString("        if method == 'OPTIONS':\n")
	sb.WriteString("            return {'statusCode': 200, 'headers': headers, 'body': ''}\n\n")

	sb.WriteString("        # MCP manifest endpoint\n")
	sb.WriteString("        if path == '/.well-known/mcp.json':\n")
	sb.WriteString("            manifest = {\n")
	sb.WriteString(fmt.Sprintf("                'name': '%s',\n", ir.Metadata.Name))
	sb.WriteString(fmt.Sprintf("                'version': '%s',\n", ir.Metadata.Version))
	sb.WriteString(fmt.Sprintf("                'description': '%s',\n", escapeString(ir.Metadata.Description)))
	sb.WriteString("                'tools': get_tools(),\n")
	sb.WriteString("            }\n")
	sb.WriteString("            return {\n")
	sb.WriteString("                'statusCode': 200,\n")
	sb.WriteString("                'headers': headers,\n")
	sb.WriteString("                'body': json.dumps(manifest, indent=2),\n")
	sb.WriteString("            }\n\n")

	sb.WriteString("        # MCP tool execution endpoint\n")
	sb.WriteString("        if path == '/mcp/execute' and method == 'POST':\n")
	sb.WriteString("            request = json.loads(body) if isinstance(body, str) else body\n")
	sb.WriteString("            tool_name = request.get('tool')\n")
	sb.WriteString("            arguments = request.get('arguments', {})\n\n")

	sb.WriteString("            result = execute_tool(tool_name, arguments, context)\n")
	sb.WriteString("            return {\n")
	sb.WriteString("                'statusCode': 200,\n")
	sb.WriteString("                'headers': headers,\n")
	sb.WriteString("                'body': json.dumps(result),\n")
	sb.WriteString("            }\n\n")

	sb.WriteString("        # Default 404\n")
	sb.WriteString("        return {\n")
	sb.WriteString("            'statusCode': 404,\n")
	sb.WriteString("            'headers': headers,\n")
	sb.WriteString("            'body': json.dumps({'error': 'Not Found'}),\n")
	sb.WriteString("        }\n\n")

	sb.WriteString("    except Exception as e:\n")
	sb.WriteString("        logger.error(f'Error processing request: {str(e)}')\n")
	sb.WriteString("        return {\n")
	sb.WriteString("            'statusCode': 500,\n")
	sb.WriteString("            'headers': headers,\n")
	sb.WriteString("            'body': json.dumps({'error': str(e)}),\n")
	sb.WriteString("        }\n\n\n")

	// Tool executor function
	sb.WriteString("def execute_tool(tool_name: str, arguments: Dict[str, Any], context: Any) -> Any:\n")
	sb.WriteString("    \"\"\"Execute a specific MCP tool.\"\"\"\n")
	sb.WriteString("    import os\n")
	sb.WriteString("    \n")
	sb.WriteString("    # Get configuration from environment\n")
	sb.WriteString("    api_base_url = os.environ.get('API_BASE_URL', '" + GetPrimaryServer(ir) + "')\n")

	if NeedsAuthentication(ir) {
		sb.WriteString("    api_key = os.environ.get('API_KEY')\n")
		sb.WriteString("    if not api_key:\n")
		sb.WriteString("        raise ValueError('API_KEY environment variable is required')\n\n")
	}

	sb.WriteString("    # Create API client\n")
	sb.WriteString("    client = APIClient(api_base_url")
	if NeedsAuthentication(ir) {
		sb.WriteString(", api_key=api_key")
	}
	sb.WriteString(")\n\n")

	sb.WriteString("    # Route to appropriate tool\n")

	// Generate tool routing
	for i, endpoint := range ir.Endpoints {
		toolName := g.getToolName(endpoint)
		if i == 0 {
			sb.WriteString(fmt.Sprintf("    if tool_name == '%s':\n", toolName))
		} else {
			sb.WriteString(fmt.Sprintf("    elif tool_name == '%s':\n", toolName))
		}
		sb.WriteString(fmt.Sprintf("        return client.%s(**arguments)\n", sanitizeIdentifier(toolName)))
	}

	sb.WriteString("    else:\n")
	sb.WriteString("        raise ValueError(f'Unknown tool: {tool_name}')\n")

	return GeneratedFile{
		Path:     "handler.py",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "python",
	}, nil
}

// generateModelsFile generates Python type definitions
func (g *PythonLambdaGenerator) generateModelsFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("\"\"\"Generated Python type definitions.\"\"\"\n\n")
	sb.WriteString("from typing import TypedDict, List, Optional, Any, Dict\n\n")

	// Generate models from IR types
	for _, typeDef := range ir.Types {
		sb.WriteString(g.generateTypeDefinition(typeDef))
		sb.WriteString("\n\n")
	}

	// Generate request/response models for endpoints
	for _, endpoint := range ir.Endpoints {
		// Request model
		if endpoint.RequestBody != nil {
			className := toPascalCase(endpoint.ID) + "Request"
			sb.WriteString(fmt.Sprintf("class %s(TypedDict):\n", className))
			sb.WriteString("    \"\"\"Request model.\"\"\"\n")
			if endpoint.RequestBody.Schema != nil && endpoint.RequestBody.Schema.Type != "" {
				sb.WriteString(fmt.Sprintf("    body: %s\n", typeToPython(endpoint.RequestBody.Schema.Type)))
			} else {
				sb.WriteString("    body: Dict[str, Any]\n")
			}
			sb.WriteString("\n\n")
		}

		// Response models
		for _, response := range endpoint.Responses {
			className := toPascalCase(endpoint.ID) + "Response" + response.StatusCode
			sb.WriteString(fmt.Sprintf("class %s(TypedDict):\n", className))
			sb.WriteString(fmt.Sprintf("    \"\"\"Response model for %s.\"\"\"\n", response.StatusCode))
			if response.Schema != nil && response.Schema.Type != "" {
				sb.WriteString(fmt.Sprintf("    data: %s\n", typeToPython(response.Schema.Type)))
			} else {
				sb.WriteString("    data: Dict[str, Any]\n")
			}
			sb.WriteString("\n\n")
		}
	}

	return GeneratedFile{
		Path:     "models.py",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "python",
	}, nil
}

// generateToolsFile generates the tools manifest
func (g *PythonLambdaGenerator) generateToolsFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("\"\"\"Generated MCP tools manifest.\"\"\"\n\n")
	sb.WriteString("from typing import List, Dict, Any\n\n\n")

	sb.WriteString("def get_tools() -> List[Dict[str, Any]]:\n")
	sb.WriteString("    \"\"\"Return list of available MCP tools.\"\"\"\n")
	sb.WriteString("    return [\n")

	for i, endpoint := range ir.Endpoints {
		toolName := g.getToolName(endpoint)
		sb.WriteString("        {\n")
		sb.WriteString(fmt.Sprintf("            'name': '%s',\n", toolName))
		sb.WriteString(fmt.Sprintf("            'description': '%s',\n", escapeString(endpoint.Description)))
		sb.WriteString("            'parameters': {\n")
		sb.WriteString("                'type': 'object',\n")
		sb.WriteString("                'properties': {\n")

		// Add parameters
		for _, param := range endpoint.Parameters {
			sb.WriteString(fmt.Sprintf("                    '%s': {\n", param.Name))
			sb.WriteString(fmt.Sprintf("                        'type': '%s',\n", typeToPython(param.Schema.Type)))
			if param.Description != "" {
				sb.WriteString(fmt.Sprintf("                        'description': '%s',\n", escapeString(param.Description)))
			}
			sb.WriteString("                    },\n")
		}

		sb.WriteString("                },\n")

		// Required parameters
		requiredParams := []string{}
		for _, param := range endpoint.Parameters {
			if param.Required {
				requiredParams = append(requiredParams, param.Name)
			}
		}
		if len(requiredParams) > 0 {
			sb.WriteString("                'required': [")
			for j, req := range requiredParams {
				if j > 0 {
					sb.WriteString(", ")
				}
				sb.WriteString(fmt.Sprintf("'%s'", req))
			}
			sb.WriteString("],\n")
		}

		sb.WriteString("            },\n")
		sb.WriteString("        }")

		if i < len(ir.Endpoints)-1 {
			sb.WriteString(",")
		}
		sb.WriteString("\n")
	}

	sb.WriteString("    ]\n")

	return GeneratedFile{
		Path:     "tools.py",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "python",
	}, nil
}

// generateClientFile generates the API client
func (g *PythonLambdaGenerator) generateClientFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("\"\"\"Generated API client.\"\"\"\n\n")
	sb.WriteString("import requests\n")
	sb.WriteString("from typing import Dict, Any, Optional\n")
	sb.WriteString("import logging\n\n")

	sb.WriteString("logger = logging.getLogger(__name__)\n\n\n")

	sb.WriteString("class APIClient:\n")
	sb.WriteString("    \"\"\"Client for making API requests.\"\"\"\n\n")

	sb.WriteString("    def __init__(self, base_url: str, api_key: Optional[str] = None):\n")
	sb.WriteString("        self.base_url = base_url.rstrip('/')\n")
	sb.WriteString("        self.api_key = api_key\n")
	sb.WriteString("        self.session = requests.Session()\n")
	if NeedsAuthentication(ir) {
		sb.WriteString("        if api_key:\n")
		sb.WriteString("            self.session.headers.update({'Authorization': f'Bearer {api_key}'})\n")
	}
	sb.WriteString("\n")

	// Generate method for each endpoint
	for _, endpoint := range ir.Endpoints {
		sb.WriteString(g.generateClientMethod(endpoint, ir))
		sb.WriteString("\n")
	}

	return GeneratedFile{
		Path:     "client.py",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "python",
	}, nil
}

// Helper functions

func (g *PythonLambdaGenerator) getToolName(endpoint parser.UnifiedEndpoint) string {
	if endpoint.Name != "" {
		return toSnakeCase(endpoint.Name)
	}
	return toSnakeCase(endpoint.ID)
}

func (g *PythonLambdaGenerator) generateTypeDefinition(typeDef parser.TypeDefinition) string {
	var sb strings.Builder

	className := toPascalCase(typeDef.Name)
	sb.WriteString(fmt.Sprintf("class %s(TypedDict):\n", className))
	if typeDef.Description != "" {
		sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", typeDef.Description))
	} else {
		sb.WriteString(fmt.Sprintf("    \"\"\"Type definition for %s.\"\"\"\n", typeDef.Name))
	}

	if len(typeDef.Properties) == 0 {
		sb.WriteString("    pass\n")
	} else {
		for propName, propDef := range typeDef.Properties {
			pyType := typeToPython(propDef.Type)
			if propDef.Ref != "" {
				// Extract type name from $ref
				parts := strings.Split(propDef.Ref, "/")
				pyType = toPascalCase(parts[len(parts)-1])
			}

			// Check if optional
			optional := !contains(typeDef.Required, propName)
			if optional {
				pyType = fmt.Sprintf("Optional[%s]", pyType)
			}

			sb.WriteString(fmt.Sprintf("    %s: %s\n", propName, pyType))
		}
	}

	return sb.String()
}

func (g *PythonLambdaGenerator) generateClientMethod(endpoint parser.UnifiedEndpoint, ir *parser.IntermediateRepresentation) string {
	var sb strings.Builder

	methodName := sanitizeIdentifier(g.getToolName(endpoint))
	sb.WriteString(fmt.Sprintf("    def %s(self, **kwargs) -> Dict[str, Any]:\n", methodName))
	sb.WriteString(fmt.Sprintf("        \"\"\"%s\"\"\"\n", endpoint.Description))

	// Build URL with path parameters
	path := endpoint.Path
	pathParams := []string{}
	for _, param := range endpoint.Parameters {
		if param.In == "path" {
			pathParams = append(pathParams, param.Name)
			path = strings.ReplaceAll(path, "{"+param.Name+"}", "{"+param.Name+"}")
		}
	}

	if len(pathParams) > 0 {
		sb.WriteString("        # Extract path parameters\n")
		for _, pp := range pathParams {
			sb.WriteString(fmt.Sprintf("        %s = kwargs.get('%s')\n", pp, pp))
		}
		sb.WriteString(fmt.Sprintf("        url = f'{self.base_url}%s'\n\n", path))
	} else {
		sb.WriteString(fmt.Sprintf("        url = f'{self.base_url}%s'\n\n", path))
	}

	// Build query parameters
	queryParams := []string{}
	for _, param := range endpoint.Parameters {
		if param.In == "query" {
			queryParams = append(queryParams, param.Name)
		}
	}

	if len(queryParams) > 0 {
		sb.WriteString("        # Build query parameters\n")
		sb.WriteString("        params = {}\n")
		for _, qp := range queryParams {
			sb.WriteString(fmt.Sprintf("        if '%s' in kwargs:\n", qp))
			sb.WriteString(fmt.Sprintf("            params['%s'] = kwargs['%s']\n", qp, qp))
		}
		sb.WriteString("\n")
	}

	// Make request
	sb.WriteString("        try:\n")
	sb.WriteString(fmt.Sprintf("            response = self.session.%s(\n", strings.ToLower(endpoint.Method)))
	sb.WriteString("                url,\n")

	if len(queryParams) > 0 {
		sb.WriteString("                params=params,\n")
	}

	if endpoint.RequestBody != nil && (endpoint.Method == "POST" || endpoint.Method == "PUT" || endpoint.Method == "PATCH") {
		sb.WriteString("                json=kwargs.get('body'),\n")
	}

	sb.WriteString("            )\n")
	sb.WriteString("            response.raise_for_status()\n")
	sb.WriteString("            return response.json()\n")
	sb.WriteString("        except requests.exceptions.RequestException as e:\n")
	sb.WriteString("            logger.error(f'API request failed: {str(e)}')\n")
	sb.WriteString("            raise\n\n")

	return sb.String()
}

func (g *PythonLambdaGenerator) generateRequirements(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	content := `requests>=2.31.0
boto3>=1.28.0
`
	if opts.IncludeTests {
		content += `pytest>=7.4.0
pytest-cov>=4.1.0
moto>=4.2.0
`
	}

	return GeneratedFile{
		Path:     "requirements.txt",
		Content:  content,
		Type:     FileTypeConfig,
		Language: "text",
	}, nil
}

func (g *PythonLambdaGenerator) generateSAMTemplate(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	functionName := opts.PackageName
	if functionName == "" {
		functionName = toKebabCase(ir.Metadata.Name)
	}

	content := fmt.Sprintf(`AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: %s MCP Lambda Function

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11

Resources:
  MCPFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.lambda_handler
      Description: %s
      Environment:
        Variables:
          API_BASE_URL: %s
      Events:
        MCPManifest:
          Type: Api
          Properties:
            Path: /.well-known/mcp.json
            Method: get
        MCPExecute:
          Type: Api
          Properties:
            Path: /mcp/execute
            Method: post
        CORSOptions:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: options

Outputs:
  MCPApi:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  MCPFunction:
    Description: Lambda Function ARN
    Value: !GetAtt MCPFunction.Arn
`, ir.Metadata.Title, ir.Metadata.Description, GetPrimaryServer(ir))

	return GeneratedFile{
		Path:     "template.yaml",
		Content:  content,
		Type:     FileTypeConfig,
		Language: "yaml",
	}, nil
}

func (g *PythonLambdaGenerator) generateReadme(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# %s\n\n", ir.Metadata.Title))
	sb.WriteString(fmt.Sprintf("%s\n\n", ir.Metadata.Description))
	sb.WriteString(fmt.Sprintf("**Version:** %s\n\n", ir.Metadata.Version))

	sb.WriteString("## Installation\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("pip install -r requirements.txt\n")
	sb.WriteString("```\n\n")

	sb.WriteString("## Deployment\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("sam build\n")
	sb.WriteString("sam deploy --guided\n")
	sb.WriteString("```\n\n")

	sb.WriteString("## Environment Variables\n\n")
	sb.WriteString("- `API_BASE_URL` - Base URL for API calls\n")
	if NeedsAuthentication(ir) {
		sb.WriteString("- `API_KEY` - API authentication key\n")
	}
	sb.WriteString("\n")

	sb.WriteString("## Available Tools\n\n")
	for _, endpoint := range ir.Endpoints {
		toolName := g.getToolName(endpoint)
		sb.WriteString(fmt.Sprintf("### %s\n\n", toolName))
		sb.WriteString(fmt.Sprintf("%s\n\n", endpoint.Description))
		sb.WriteString(fmt.Sprintf("**Method:** `%s %s`\n\n", endpoint.Method, endpoint.Path))
	}

	sb.WriteString("\n---\n")
	sb.WriteString("Generated by MCPOverflow Python Generator\n")

	return GeneratedFile{
		Path:     "README.md",
		Content:  sb.String(),
		Type:     FileTypeDocs,
		Language: "markdown",
	}, nil
}

func (g *PythonLambdaGenerator) generateTestFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("\"\"\"Tests for MCP Lambda function.\"\"\"\n\n")
	sb.WriteString("import json\n")
	sb.WriteString("import pytest\n")
	sb.WriteString("from handler import lambda_handler\n\n\n")

	sb.WriteString("def test_mcp_manifest():\n")
	sb.WriteString("    \"\"\"Test MCP manifest endpoint.\"\"\"\n")
	sb.WriteString("    event = {\n")
	sb.WriteString("        'path': '/.well-known/mcp.json',\n")
	sb.WriteString("        'httpMethod': 'GET',\n")
	sb.WriteString("    }\n")
	sb.WriteString("    response = lambda_handler(event, None)\n")
	sb.WriteString("    assert response['statusCode'] == 200\n")
	sb.WriteString("    body = json.loads(response['body'])\n")
	sb.WriteString(fmt.Sprintf("    assert body['name'] == '%s'\n", ir.Metadata.Name))
	sb.WriteString("    assert 'tools' in body\n\n\n")

	sb.WriteString("def test_cors_preflight():\n")
	sb.WriteString("    \"\"\"Test CORS preflight handling.\"\"\"\n")
	sb.WriteString("    event = {\n")
	sb.WriteString("        'path': '/mcp/execute',\n")
	sb.WriteString("        'httpMethod': 'OPTIONS',\n")
	sb.WriteString("    }\n")
	sb.WriteString("    response = lambda_handler(event, None)\n")
	sb.WriteString("    assert response['statusCode'] == 200\n")
	sb.WriteString("    assert 'Access-Control-Allow-Origin' in response['headers']\n")

	return GeneratedFile{
		Path:     "test_handler.py",
		Content:  sb.String(),
		Type:     FileTypeTest,
		Language: "python",
	}, nil
}

func (g *PythonLambdaGenerator) generateDependencies(ir *parser.IntermediateRepresentation, opts GenerateOptions) []Dependency {
	deps := []Dependency{
		{
			Name:     "requests",
			Version:  ">=2.31.0",
			Type:     DependencyTypeRuntime,
			Source:   "pypi",
			Required: true,
		},
		{
			Name:     "boto3",
			Version:  ">=1.28.0",
			Type:     DependencyTypeRuntime,
			Source:   "pypi",
			Required: true,
		},
	}

	if opts.IncludeTests {
		deps = append(deps, Dependency{
			Name:     "pytest",
			Version:  ">=7.4.0",
			Type:     DependencyTypeDev,
			Source:   "pypi",
			Required: false,
		})
	}

	return deps
}
