package generator

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/mcpoverflow/api-service/internal/parser"
)

// RustWasmGenerator generates Rust code for WASM/native MCP functions
type RustWasmGenerator struct {
	*BaseGenerator
}

// NewRustWasmGenerator creates a new Rust WASM generator
func NewRustWasmGenerator() *RustWasmGenerator {
	features := []Feature{
		FeatureBasicGeneration,
		FeatureTypeGeneration,
		FeatureAuthGeneration,
		FeatureValidation,
		FeatureErrorHandling,
		FeatureRetryLogic,
		FeatureLogging,
		FeatureWASM,
		FeatureRESTSupport,
		FeatureInlineDocs,
		FeatureExamples,
		FeatureAsyncAwait,
	}

	gen := &RustWasmGenerator{
		BaseGenerator: NewBaseGenerator("rust", "wasm", "1.0.0", features),
	}

	return gen
}

// Generate generates Rust code from the intermediate representation
func (g *RustWasmGenerator) Generate(ctx context.Context, ir *parser.IntermediateRepresentation, opts GenerateOptions) (*GeneratedCode, error) {
	startTime := time.Now()

	// Validate IR
	result, err := g.Validate(ir)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}

	if !result.Valid {
		return nil, fmt.Errorf("IR validation failed: %v", result.Errors)
	}

	files := []GeneratedFile{}

	// Generate main lib.rs file with request handler
	mainFile, err := g.generateMainFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate main file: %w", err)
	}
	files = append(files, mainFile)

	// Generate types module
	typesFile, err := g.generateTypesFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate types file: %w", err)
	}
	files = append(files, typesFile)

	// Generate tools module
	toolsFile, err := g.generateToolsFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate tools file: %w", err)
	}
	files = append(files, toolsFile)

	// Generate client module
	clientFile, err := g.generateClientFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate client file: %w", err)
	}
	files = append(files, clientFile)

	// Generate Cargo.toml
	cargoFile, err := g.generateCargoToml(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate Cargo.toml: %w", err)
	}
	files = append(files, cargoFile)

	// Generate README
	if opts.IncludeDocs {
		readmeFile, err := g.generateReadme(ir, opts)
		if err != nil {
			return nil, fmt.Errorf("failed to generate README: %w", err)
		}
		files = append(files, readmeFile)
	}

	// Generate tests
	if opts.IncludeTests {
		testsFile, err := g.generateTestFile(ir, opts)
		if err != nil {
			return nil, fmt.Errorf("failed to generate tests: %w", err)
		}
		files = append(files, testsFile)
	}

	// Calculate dependencies
	deps := g.generateDependencies(ir, opts)

	// Calculate statistics
	stats := GenerationStatistics{
		TotalFiles:     len(files),
		TotalLines:     g.CountLines(files),
		TotalEndpoints: len(ir.Endpoints),
		TotalTypes:     len(ir.Types),
		GenerationTime: time.Since(startTime),
	}

	return g.CreateGeneratedCode(files, deps, stats), nil
}

// generateMainFile generates the main lib.rs file
func (g *RustWasmGenerator) generateMainFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	// File header
	sb.WriteString("//! MCP Server for " + ir.Metadata.Title + "\n")
	sb.WriteString("//!\n")
	if ir.Metadata.Description != "" {
		sb.WriteString("//! " + ir.Metadata.Description + "\n")
		sb.WriteString("//!\n")
	}
	sb.WriteString("//! Auto-generated by MCPOverflow\n\n")

	// Imports
	sb.WriteString("use serde::{Deserialize, Serialize};\n")
	sb.WriteString("use serde_json::{json, Value};\n")
	sb.WriteString("use std::collections::HashMap;\n")
	sb.WriteString("use wasm_bindgen::prelude::*;\n\n")

	// Module declarations
	sb.WriteString("pub mod types;\n")
	sb.WriteString("pub mod tools;\n")
	sb.WriteString("pub mod client;\n\n")

	sb.WriteString("use types::*;\n")
	sb.WriteString("use tools::*;\n")
	sb.WriteString("use client::ApiClient;\n\n")

	// Request/Response types
	sb.WriteString("/// HTTP Request structure\n")
	sb.WriteString("#[derive(Debug, Deserialize)]\n")
	sb.WriteString("pub struct Request {\n")
	sb.WriteString("    pub path: String,\n")
	sb.WriteString("    pub method: String,\n")
	sb.WriteString("    #[serde(default)]\n")
	sb.WriteString("    pub headers: HashMap<String, String>,\n")
	sb.WriteString("    #[serde(default)]\n")
	sb.WriteString("    pub body: Option<String>,\n")
	sb.WriteString("}\n\n")

	sb.WriteString("/// HTTP Response structure\n")
	sb.WriteString("#[derive(Debug, Serialize)]\n")
	sb.WriteString("pub struct Response {\n")
	sb.WriteString("    pub status: u16,\n")
	sb.WriteString("    pub headers: HashMap<String, String>,\n")
	sb.WriteString("    pub body: String,\n")
	sb.WriteString("}\n\n")

	sb.WriteString("impl Response {\n")
	sb.WriteString("    fn json(status: u16, data: Value) -> Self {\n")
	sb.WriteString("        let mut headers = HashMap::new();\n")
	sb.WriteString("        headers.insert(\"Content-Type\".to_string(), \"application/json\".to_string());\n")
	sb.WriteString("        headers.insert(\"Access-Control-Allow-Origin\".to_string(), \"*\".to_string());\n")
	sb.WriteString("        \n")
	sb.WriteString("        Response {\n")
	sb.WriteString("            status,\n")
	sb.WriteString("            headers,\n")
	sb.WriteString("            body: data.to_string(),\n")
	sb.WriteString("        }\n")
	sb.WriteString("    }\n\n")

	sb.WriteString("    fn error(status: u16, message: &str) -> Self {\n")
	sb.WriteString("        Self::json(status, json!({ \"error\": message }))\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n\n")

	// Main handler function
	sb.WriteString("/// Main request handler\n")
	sb.WriteString("#[wasm_bindgen]\n")
	sb.WriteString("pub fn handle_request(request_json: &str) -> String {\n")
	sb.WriteString("    let request: Request = match serde_json::from_str(request_json) {\n")
	sb.WriteString("        Ok(req) => req,\n")
	sb.WriteString("        Err(e) => {\n")
	sb.WriteString("            let err_resp = Response::error(400, &format!(\"Invalid request: {}\", e));\n")
	sb.WriteString("            return serde_json::to_string(&err_resp).unwrap();\n")
	sb.WriteString("        }\n")
	sb.WriteString("    };\n\n")

	sb.WriteString("    let response = match request.path.as_str() {\n")
	sb.WriteString("        \"/.well-known/mcp.json\" => handle_manifest(),\n")
	sb.WriteString("        \"/mcp/execute\" => handle_execute(&request),\n")
	sb.WriteString("        _ => Response::error(404, \"Not Found\"),\n")
	sb.WriteString("    };\n\n")

	sb.WriteString("    serde_json::to_string(&response).unwrap()\n")
	sb.WriteString("}\n\n")

	// Manifest handler
	sb.WriteString("/// Handle MCP manifest request\n")
	sb.WriteString("fn handle_manifest() -> Response {\n")
	sb.WriteString("    let manifest = json!({\n")
	sb.WriteString(fmt.Sprintf("        \"name\": \"%s\",\n", ir.Metadata.Name))
	sb.WriteString(fmt.Sprintf("        \"version\": \"%s\",\n", ir.Metadata.Version))
	if ir.Metadata.Description != "" {
		sb.WriteString(fmt.Sprintf("        \"description\": \"%s\",\n", escapeString(ir.Metadata.Description)))
	}
	sb.WriteString("        \"tools\": get_tools(),\n")
	sb.WriteString("    });\n\n")
	sb.WriteString("    Response::json(200, manifest)\n")
	sb.WriteString("}\n\n")

	// Execute handler
	sb.WriteString("/// Handle tool execution request\n")
	sb.WriteString("fn handle_execute(request: &Request) -> Response {\n")
	sb.WriteString("    let body = match &request.body {\n")
	sb.WriteString("        Some(b) => b,\n")
	sb.WriteString("        None => return Response::error(400, \"Missing request body\"),\n")
	sb.WriteString("    };\n\n")

	sb.WriteString("    let exec_request: ExecuteRequest = match serde_json::from_str(body) {\n")
	sb.WriteString("        Ok(req) => req,\n")
	sb.WriteString("        Err(e) => return Response::error(400, &format!(\"Invalid execute request: {}\", e)),\n")
	sb.WriteString("    };\n\n")

	// Get environment variables
	if NeedsAuthentication(ir) {
		sb.WriteString("    // Get configuration from environment or request\n")
		sb.WriteString("    let api_base_url = std::env::var(\"API_BASE_URL\")\n")
		sb.WriteString(fmt.Sprintf("        .unwrap_or_else(|_| \"%s\".to_string());\n", GetPrimaryServer(ir)))
		sb.WriteString("    let api_key = std::env::var(\"API_KEY\").ok();\n\n")
		sb.WriteString("    let client = ApiClient::new(api_base_url, api_key);\n\n")
	} else {
		sb.WriteString("    let api_base_url = std::env::var(\"API_BASE_URL\")\n")
		sb.WriteString(fmt.Sprintf("        .unwrap_or_else(|_| \"%s\".to_string());\n", GetPrimaryServer(ir)))
		sb.WriteString("    let client = ApiClient::new(api_base_url, None);\n\n")
	}

	// Tool routing
	sb.WriteString("    match exec_request.tool.as_str() {\n")
	for _, endpoint := range ir.Endpoints {
		toolName := g.getToolName(endpoint)
		methodName := toSnakeCase(sanitizeIdentifier(toolName))

		sb.WriteString(fmt.Sprintf("        \"%s\" => {\n", toolName))
		sb.WriteString(fmt.Sprintf("            match client.%s(&exec_request.arguments) {\n", methodName))
		sb.WriteString("                Ok(result) => Response::json(200, result),\n")
		sb.WriteString("                Err(e) => Response::error(500, &format!(\"Tool execution failed: {}\", e)),\n")
		sb.WriteString("            }\n")
		sb.WriteString("        }\n")
	}
	sb.WriteString("        _ => Response::error(404, &format!(\"Unknown tool: {}\", exec_request.tool)),\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n\n")

	// ExecuteRequest type
	sb.WriteString("/// Tool execution request\n")
	sb.WriteString("#[derive(Debug, Deserialize)]\n")
	sb.WriteString("struct ExecuteRequest {\n")
	sb.WriteString("    tool: String,\n")
	sb.WriteString("    arguments: Value,\n")
	sb.WriteString("}\n")

	return GeneratedFile{
		Path:     "src/lib.rs",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "rust",
	}, nil
}

// generateTypesFile generates the types module
func (g *RustWasmGenerator) generateTypesFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("//! Type definitions for " + ir.Metadata.Title + "\n")
	sb.WriteString("//!\n")
	sb.WriteString("//! Auto-generated by MCPOverflow\n\n")

	sb.WriteString("use serde::{Deserialize, Serialize};\n")
	sb.WriteString("use serde_json::Value;\n\n")

	// Generate type definitions
	for _, typeDef := range ir.Types {
		typeCode := g.generateTypeDefinition(typeDef)
		sb.WriteString(typeCode)
		sb.WriteString("\n")
	}

	// If no types defined, add a placeholder comment
	if len(ir.Types) == 0 {
		sb.WriteString("// No custom types defined\n")
	}

	return GeneratedFile{
		Path:     "src/types.rs",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "rust",
	}, nil
}

// generateTypeDefinition generates a Rust struct from a type definition
func (g *RustWasmGenerator) generateTypeDefinition(typeDef parser.TypeDefinition) string {
	var sb strings.Builder

	structName := toPascalCase(typeDef.Name)

	// Add documentation
	if typeDef.Description != "" {
		sb.WriteString(fmt.Sprintf("/// %s\n", typeDef.Description))
	}

	// Add derives
	sb.WriteString("#[derive(Debug, Clone, Serialize, Deserialize)]\n")

	// Struct definition
	sb.WriteString(fmt.Sprintf("pub struct %s {\n", structName))

	// Add fields
	for propName, propDef := range typeDef.Properties {
		rustType := typeToRust(propDef.Type)

		// Check if field is optional (not in required list)
		isRequired := contains(typeDef.Required, propName)

		if propDef.Description != "" {
			sb.WriteString(fmt.Sprintf("    /// %s\n", propDef.Description))
		}

		if !isRequired {
			sb.WriteString("    #[serde(skip_serializing_if = \"Option::is_none\")]\n")
			rustType = fmt.Sprintf("Option<%s>", rustType)
		}

		sb.WriteString(fmt.Sprintf("    pub %s: %s,\n", toSnakeCase(propName), rustType))
	}

	sb.WriteString("}\n")

	return sb.String()
}

// generateToolsFile generates the tools module
func (g *RustWasmGenerator) generateToolsFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("//! MCP Tools definitions\n")
	sb.WriteString("//!\n")
	sb.WriteString("//! Auto-generated by MCPOverflow\n\n")

	sb.WriteString("use serde_json::{json, Value};\n\n")

	sb.WriteString("/// Get all available MCP tools\n")
	sb.WriteString("pub fn get_tools() -> Vec<Value> {\n")
	sb.WriteString("    vec![\n")

	for _, endpoint := range ir.Endpoints {
		toolName := g.getToolName(endpoint)
		description := endpoint.Description
		if description == "" {
			description = fmt.Sprintf("%s %s", endpoint.Method, endpoint.Path)
		}

		sb.WriteString("        json!({\n")
		sb.WriteString(fmt.Sprintf("            \"name\": \"%s\",\n", toolName))
		sb.WriteString(fmt.Sprintf("            \"description\": \"%s\",\n", escapeString(description)))
		sb.WriteString("            \"inputSchema\": {\n")
		sb.WriteString("                \"type\": \"object\",\n")
		sb.WriteString("                \"properties\": {\n")

		// Add path parameters
		for _, param := range endpoint.Parameters {
			if param.In == "path" {
				sb.WriteString(fmt.Sprintf("                    \"%s\": {\n", param.Name))
				sb.WriteString(fmt.Sprintf("                        \"type\": \"%s\",\n", param.Schema.Type))
				if param.Description != "" {
					sb.WriteString(fmt.Sprintf("                        \"description\": \"%s\",\n", escapeString(param.Description)))
				}
				sb.WriteString("                    },\n")
			}
		}

		// Add query parameters
		for _, param := range endpoint.Parameters {
			if param.In == "query" {
				sb.WriteString(fmt.Sprintf("                    \"%s\": {\n", param.Name))
				sb.WriteString(fmt.Sprintf("                        \"type\": \"%s\",\n", param.Schema.Type))
				if param.Description != "" {
					sb.WriteString(fmt.Sprintf("                        \"description\": \"%s\",\n", escapeString(param.Description)))
				}
				sb.WriteString("                    },\n")
			}
		}

		// Add request body if present
		if endpoint.RequestBody != nil && endpoint.Method != "GET" && endpoint.Method != "DELETE" {
			sb.WriteString("                    \"body\": {\n")
			sb.WriteString("                        \"type\": \"object\",\n")
			if endpoint.RequestBody.Description != "" {
				sb.WriteString(fmt.Sprintf("                        \"description\": \"%s\",\n", escapeString(endpoint.RequestBody.Description)))
			}
			sb.WriteString("                    },\n")
		}

		sb.WriteString("                },\n")

		// Required parameters
		var required []string
		for _, param := range endpoint.Parameters {
			if param.Required && param.In == "path" {
				required = append(required, param.Name)
			}
		}
		if len(required) > 0 {
			sb.WriteString("                \"required\": [")
			for i, r := range required {
				if i > 0 {
					sb.WriteString(", ")
				}
				sb.WriteString(fmt.Sprintf("\"%s\"", r))
			}
			sb.WriteString("],\n")
		}

		sb.WriteString("            },\n")
		sb.WriteString("        }),\n")
	}

	sb.WriteString("    ]\n")
	sb.WriteString("}\n")

	return GeneratedFile{
		Path:     "src/tools.rs",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "rust",
	}, nil
}

// generateClientFile generates the API client module
func (g *RustWasmGenerator) generateClientFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("//! API Client for " + ir.Metadata.Title + "\n")
	sb.WriteString("//!\n")
	sb.WriteString("//! Auto-generated by MCPOverflow\n\n")

	sb.WriteString("use serde_json::Value;\n")
	sb.WriteString("use std::collections::HashMap;\n\n")

	// Client struct
	sb.WriteString("/// API Client for making HTTP requests\n")
	sb.WriteString("#[derive(Debug, Clone)]\n")
	sb.WriteString("pub struct ApiClient {\n")
	sb.WriteString("    base_url: String,\n")
	sb.WriteString("    api_key: Option<String>,\n")
	sb.WriteString("}\n\n")

	sb.WriteString("impl ApiClient {\n")
	sb.WriteString("    /// Create a new API client\n")
	sb.WriteString("    pub fn new(base_url: String, api_key: Option<String>) -> Self {\n")
	sb.WriteString("        Self { base_url, api_key }\n")
	sb.WriteString("    }\n\n")

	// Generate method for each endpoint
	for _, endpoint := range ir.Endpoints {
		methodCode := g.generateClientMethod(endpoint, ir)
		sb.WriteString(methodCode)
		sb.WriteString("\n")
	}

	// Helper method to make HTTP requests
	sb.WriteString("    /// Make HTTP request (placeholder - needs async runtime)\n")
	sb.WriteString("    fn request(\n")
	sb.WriteString("        &self,\n")
	sb.WriteString("        method: &str,\n")
	sb.WriteString("        url: &str,\n")
	sb.WriteString("        _params: &HashMap<String, String>,\n")
	sb.WriteString("        _body: Option<&Value>,\n")
	sb.WriteString("    ) -> Result<Value, String> {\n")
	sb.WriteString("        // Note: This is a placeholder. In a real WASM environment,\n")
	sb.WriteString("        // you would use web_sys or reqwest-wasm to make HTTP requests\n")
	sb.WriteString("        Err(format!(\"HTTP {} to {} not implemented in WASM\", method, url))\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n")

	return GeneratedFile{
		Path:     "src/client.rs",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "rust",
	}, nil
}

// generateClientMethod generates a client method for an endpoint
func (g *RustWasmGenerator) generateClientMethod(endpoint parser.UnifiedEndpoint, ir *parser.IntermediateRepresentation) string {
	var sb strings.Builder

	toolName := g.getToolName(endpoint)
	methodName := toSnakeCase(sanitizeIdentifier(toolName))

	// Documentation
	if endpoint.Description != "" {
		sb.WriteString(fmt.Sprintf("    /// %s\n", endpoint.Description))
	}
	sb.WriteString(fmt.Sprintf("    /// %s %s\n", endpoint.Method, endpoint.Path))

	// Method signature
	sb.WriteString(fmt.Sprintf("    pub fn %s(&self, args: &Value) -> Result<Value, String> {\n", methodName))

	// Build URL with path parameters
	path := endpoint.Path
	for _, param := range endpoint.Parameters {
		if param.In == "path" {
			sb.WriteString(fmt.Sprintf("        let %s = args[\"%s\"].as_str().unwrap_or_default();\n",
				toSnakeCase(param.Name), param.Name))
			path = strings.ReplaceAll(path, "{"+param.Name+"}", fmt.Sprintf("{}", toSnakeCase(param.Name)))
		}
	}

	// Format URL
	pathFormatted := strings.ReplaceAll(path, "{}", "{}")
	var pathArgs []string
	for _, param := range endpoint.Parameters {
		if param.In == "path" {
			pathArgs = append(pathArgs, toSnakeCase(param.Name))
		}
	}

	if len(pathArgs) > 0 {
		sb.WriteString(fmt.Sprintf("        let url = format!(\"{}{}\", self.base_url, format!(\"%s\", %s));\n\n",
			pathFormatted, strings.Join(pathArgs, ", ")))
	} else {
		sb.WriteString(fmt.Sprintf("        let url = format!(\"{}{}\", self.base_url, \"%s\");\n\n", path))
	}

	// Build query parameters
	sb.WriteString("        let mut params = HashMap::new();\n")
	for _, param := range endpoint.Parameters {
		if param.In == "query" {
			sb.WriteString(fmt.Sprintf("        if let Some(val) = args[\"%s\"].as_str() {\n", param.Name))
			sb.WriteString(fmt.Sprintf("            params.insert(\"%s\".to_string(), val.to_string());\n", param.Name))
			sb.WriteString("        }\n")
		}
	}
	sb.WriteString("\n")

	// Request body
	if endpoint.Method == "POST" || endpoint.Method == "PUT" || endpoint.Method == "PATCH" {
		sb.WriteString("        let body = args.get(\"body\");\n\n")
		sb.WriteString(fmt.Sprintf("        self.request(\"%s\", &url, &params, body)\n", endpoint.Method))
	} else {
		sb.WriteString(fmt.Sprintf("        self.request(\"%s\", &url, &params, None)\n", endpoint.Method))
	}

	sb.WriteString("    }\n")

	return sb.String()
}

// generateCargoToml generates the Cargo.toml file
func (g *RustWasmGenerator) generateCargoToml(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	packageName := toKebabCase(ir.Metadata.Name)

	sb.WriteString("[package]\n")
	sb.WriteString(fmt.Sprintf("name = \"%s\"\n", packageName))
	sb.WriteString(fmt.Sprintf("version = \"%s\"\n", ir.Metadata.Version))
	sb.WriteString("edition = \"2021\"\n\n")

	sb.WriteString("[lib]\n")
	sb.WriteString("crate-type = [\"cdylib\", \"rlib\"]\n\n")

	sb.WriteString("[dependencies]\n")
	sb.WriteString("serde = { version = \"1.0\", features = [\"derive\"] }\n")
	sb.WriteString("serde_json = \"1.0\"\n")
	sb.WriteString("wasm-bindgen = \"0.2\"\n\n")

	sb.WriteString("[dev-dependencies]\n")
	sb.WriteString("wasm-bindgen-test = \"0.3\"\n\n")

	sb.WriteString("[profile.release]\n")
	sb.WriteString("opt-level = \"z\"\n")
	sb.WriteString("lto = true\n")
	sb.WriteString("codegen-units = 1\n")

	return GeneratedFile{
		Path:     "Cargo.toml",
		Content:  sb.String(),
		Type:     FileTypeConfig,
		Language: "toml",
	}, nil
}

// generateReadme generates README documentation
func (g *RustWasmGenerator) generateReadme(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# %s - Rust WASM MCP Server\n\n", ir.Metadata.Title))

	if ir.Metadata.Description != "" {
		sb.WriteString(ir.Metadata.Description + "\n\n")
	}

	sb.WriteString("Auto-generated Rust WASM MCP server by MCPOverflow.\n\n")

	sb.WriteString("## Installation\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("# Install wasm-pack\n")
	sb.WriteString("curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh\n\n")
	sb.WriteString("# Build the WASM module\n")
	sb.WriteString("wasm-pack build --target web\n")
	sb.WriteString("```\n\n")

	sb.WriteString("## Usage\n\n")
	sb.WriteString("```rust\n")
	sb.WriteString("use " + toSnakeCase(ir.Metadata.Name) + "::handle_request;\n\n")
	sb.WriteString("let request = r#\"{\n")
	sb.WriteString("    \"path\": \"/.well-known/mcp.json\",\n")
	sb.WriteString("    \"method\": \"GET\",\n")
	sb.WriteString("    \"headers\": {},\n")
	sb.WriteString("    \"body\": null\n")
	sb.WriteString("}\"#;\n\n")
	sb.WriteString("let response = handle_request(request);\n")
	sb.WriteString("```\n\n")

	sb.WriteString("## Environment Variables\n\n")
	sb.WriteString("- `API_BASE_URL` - Base URL for the API\n")
	if NeedsAuthentication(ir) {
		sb.WriteString("- `API_KEY` - API key for authentication\n")
	}
	sb.WriteString("\n")

	sb.WriteString("## Available Tools\n\n")
	for _, endpoint := range ir.Endpoints {
		toolName := g.getToolName(endpoint)
		description := endpoint.Description
		if description == "" {
			description = fmt.Sprintf("%s %s", endpoint.Method, endpoint.Path)
		}
		sb.WriteString(fmt.Sprintf("- `%s` - %s\n", toolName, description))
	}
	sb.WriteString("\n")

	sb.WriteString("## Development\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("# Run tests\n")
	sb.WriteString("wasm-pack test --headless --firefox\n\n")
	sb.WriteString("# Build for production\n")
	sb.WriteString("wasm-pack build --target web --release\n")
	sb.WriteString("```\n")

	return GeneratedFile{
		Path:     "README.md",
		Content:  sb.String(),
		Type:     FileTypeDocs,
		Language: "markdown",
	}, nil
}

// generateTestFile generates test cases
func (g *RustWasmGenerator) generateTestFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("//! Tests for " + ir.Metadata.Title + "\n")
	sb.WriteString("//!\n")
	sb.WriteString("//! Auto-generated by MCPOverflow\n\n")

	sb.WriteString("use wasm_bindgen_test::*;\n")
	sb.WriteString("use super::*;\n\n")

	sb.WriteString("#[wasm_bindgen_test]\n")
	sb.WriteString("fn test_manifest() {\n")
	sb.WriteString("    let request = r#\"{\n")
	sb.WriteString("        \"path\": \"/.well-known/mcp.json\",\n")
	sb.WriteString("        \"method\": \"GET\",\n")
	sb.WriteString("        \"headers\": {},\n")
	sb.WriteString("        \"body\": null\n")
	sb.WriteString("    }\"#;\n\n")
	sb.WriteString("    let response = handle_request(request);\n")
	sb.WriteString("    assert!(response.contains(\"tools\"));\n")
	sb.WriteString("}\n\n")

	sb.WriteString("#[wasm_bindgen_test]\n")
	sb.WriteString("fn test_invalid_path() {\n")
	sb.WriteString("    let request = r#\"{\n")
	sb.WriteString("        \"path\": \"/invalid\",\n")
	sb.WriteString("        \"method\": \"GET\",\n")
	sb.WriteString("        \"headers\": {},\n")
	sb.WriteString("        \"body\": null\n")
	sb.WriteString("    }\"#;\n\n")
	sb.WriteString("    let response = handle_request(request);\n")
	sb.WriteString("    assert!(response.contains(\"404\"));\n")
	sb.WriteString("}\n")

	return GeneratedFile{
		Path:     "tests/lib.rs",
		Content:  sb.String(),
		Type:     FileTypeTest,
		Language: "rust",
	}, nil
}

// generateDependencies returns the list of dependencies
func (g *RustWasmGenerator) generateDependencies(ir *parser.IntermediateRepresentation, opts GenerateOptions) []Dependency {
	deps := []Dependency{
		{
			Name:    "serde",
			Version: "1.0",
			Type:    DependencyTypeRuntime,
		},
		{
			Name:    "serde_json",
			Version: "1.0",
			Type:    DependencyTypeRuntime,
		},
		{
			Name:    "wasm-bindgen",
			Version: "0.2",
			Type:    DependencyTypeRuntime,
		},
		{
			Name:    "wasm-bindgen-test",
			Version: "0.3",
			Type:    DependencyTypeDev,
		},
	}

	return deps
}

// getToolName generates a tool name from an endpoint
func (g *RustWasmGenerator) getToolName(endpoint parser.UnifiedEndpoint) string {
	if endpoint.Name != "" {
		return toSnakeCase(endpoint.Name)
	}

	// Use operationId if available
	if endpoint.ID != "" {
		return toSnakeCase(endpoint.ID)
	}

	// Generate from method and path
	method := strings.ToLower(endpoint.Method)
	path := strings.Trim(endpoint.Path, "/")
	path = strings.ReplaceAll(path, "/", "_")
	path = strings.ReplaceAll(path, "{", "")
	path = strings.ReplaceAll(path, "}", "")

	return fmt.Sprintf("%s_%s", method, path)
}
