package generator

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/mcpoverflow/api-service/internal/parser"
)

// TypeScriptCloudflareGenerator generates TypeScript code for Cloudflare Workers MCP
type TypeScriptCloudflareGenerator struct {
	*BaseGenerator
}

// NewTypeScriptCloudflareGenerator creates a new TypeScript Cloudflare Worker generator
func NewTypeScriptCloudflareGenerator() *TypeScriptCloudflareGenerator {
	features := []Feature{
		FeatureBasicGeneration,
		FeatureTypeGeneration,
		FeatureAuthGeneration,
		FeatureValidation,
		FeatureErrorHandling,
		FeatureRetryLogic,
		FeatureCaching,
		FeatureLogging,
		FeatureCloudflareWorker,
		FeatureRESTSupport,
		FeatureInlineDocs,
		FeatureExamples,
	}

	gen := &TypeScriptCloudflareGenerator{
		BaseGenerator: NewBaseGenerator("typescript", "cloudflare-worker", "1.0.0", features),
	}

	gen.registerTemplates()
	return gen
}

// Generate generates TypeScript code for Cloudflare Workers
func (g *TypeScriptCloudflareGenerator) Generate(ctx context.Context, ir *parser.IntermediateRepresentation, opts GenerateOptions) (*GeneratedCode, error) {
	startTime := time.Now()

	// Validate IR
	result, err := g.Validate(ir)
	if err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if !result.Valid {
		return nil, fmt.Errorf("IR validation failed: %d errors", len(result.Errors))
	}

	files := []GeneratedFile{}

	// Generate main worker file
	mainFile, err := g.generateMainFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate main file: %w", err)
	}
	files = append(files, mainFile)

	// Generate types file
	typesFile, err := g.generateTypesFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate types file: %w", err)
	}
	files = append(files, typesFile)

	// Generate tools file
	toolsFile, err := g.generateToolsFile(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate tools file: %w", err)
	}
	files = append(files, toolsFile)

	// Generate package.json
	packageFile, err := g.generatePackageJSON(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate package.json: %w", err)
	}
	files = append(files, packageFile)

	// Generate wrangler.toml
	wranglerFile, err := g.generateWranglerConfig(ir, opts)
	if err != nil {
		return nil, fmt.Errorf("failed to generate wrangler.toml: %w", err)
	}
	files = append(files, wranglerFile)

	// Generate README
	if opts.IncludeDocs {
		readmeFile, err := g.generateReadme(ir, opts)
		if err != nil {
			return nil, fmt.Errorf("failed to generate README: %w", err)
		}
		files = append(files, readmeFile)
	}

	// Generate tests
	if opts.IncludeTests {
		testFile, err := g.generateTestFile(ir, opts)
		if err != nil {
			return nil, fmt.Errorf("failed to generate tests: %w", err)
		}
		files = append(files, testFile)
	}

	// Create dependencies
	deps := g.generateDependencies(ir, opts)

	// Calculate statistics
	stats := GenerationStatistics{
		TotalFiles:     len(files),
		TotalLines:     g.CountLines(files),
		TotalEndpoints: len(ir.Endpoints),
		TotalTypes:     len(ir.Types),
		GenerationTime: time.Since(startTime),
	}

	return g.CreateGeneratedCode(files, deps, stats), nil
}

// registerTemplates registers all TypeScript templates
func (g *TypeScriptCloudflareGenerator) registerTemplates() {
	// Main worker template will be defined inline for now
	// Future: move to external template files
}

// generateMainFile generates the main worker entry point
func (g *TypeScriptCloudflareGenerator) generateMainFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	// Header
	sb.WriteString("// Generated by MCPOverflow TypeScript Generator\n")
	sb.WriteString(fmt.Sprintf("// API: %s v%s\n", ir.Metadata.Title, ir.Metadata.Version))
	sb.WriteString(fmt.Sprintf("// Generated: %s\n\n", time.Now().Format(time.RFC3339)))

	// Imports
	sb.WriteString("import { MCPServer } from './types';\n")
	sb.WriteString("import { tools } from './tools';\n\n")

	// Worker handler
	sb.WriteString("export default {\n")
	sb.WriteString("  async fetch(request: Request, env: Env): Promise<Response> {\n")
	sb.WriteString("    // CORS headers\n")
	sb.WriteString("    const corsHeaders = {\n")
	sb.WriteString("      'Access-Control-Allow-Origin': '*',\n")
	sb.WriteString("      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',\n")
	sb.WriteString("      'Access-Control-Allow-Headers': 'Content-Type',\n")
	sb.WriteString("    };\n\n")

	sb.WriteString("    // Handle CORS preflight\n")
	sb.WriteString("    if (request.method === 'OPTIONS') {\n")
	sb.WriteString("      return new Response(null, { headers: corsHeaders });\n")
	sb.WriteString("    }\n\n")

	sb.WriteString("    try {\n")
	sb.WriteString("      const url = new URL(request.url);\n\n")

	sb.WriteString("      // MCP manifest endpoint\n")
	sb.WriteString("      if (url.pathname === '/.well-known/mcp.json') {\n")
	sb.WriteString("        const manifest: MCPServer = {\n")
	sb.WriteString(fmt.Sprintf("          name: '%s',\n", ir.Metadata.Name))
	sb.WriteString(fmt.Sprintf("          version: '%s',\n", ir.Metadata.Version))
	sb.WriteString(fmt.Sprintf("          description: '%s',\n", escapeString(ir.Metadata.Description)))
	sb.WriteString("          tools,\n")
	sb.WriteString("        };\n")
	sb.WriteString("        return new Response(JSON.stringify(manifest, null, 2), {\n")
	sb.WriteString("          headers: { ...corsHeaders, 'Content-Type': 'application/json' },\n")
	sb.WriteString("        });\n")
	sb.WriteString("      }\n\n")

	sb.WriteString("      // MCP tool execution endpoint\n")
	sb.WriteString("      if (url.pathname === '/mcp/execute' && request.method === 'POST') {\n")
	sb.WriteString("        const body = await request.json() as { tool: string; arguments: Record<string, any> };\n")
	sb.WriteString("        const result = await executeTool(body.tool, body.arguments, env);\n")
	sb.WriteString("        return new Response(JSON.stringify(result), {\n")
	sb.WriteString("          headers: { ...corsHeaders, 'Content-Type': 'application/json' },\n")
	sb.WriteString("        });\n")
	sb.WriteString("      }\n\n")

	sb.WriteString("      return new Response('Not Found', { status: 404, headers: corsHeaders });\n")
	sb.WriteString("    } catch (error) {\n")
	sb.WriteString("      return new Response(\n")
	sb.WriteString("        JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),\n")
	sb.WriteString("        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }\n")
	sb.WriteString("      );\n")
	sb.WriteString("    }\n")
	sb.WriteString("  },\n")
	sb.WriteString("};\n\n")

	// Tool executor function
	sb.WriteString("async function executeTool(\n")
	sb.WriteString("  toolName: string,\n")
	sb.WriteString("  args: Record<string, any>,\n")
	sb.WriteString("  env: Env\n")
	sb.WriteString("): Promise<any> {\n")
	sb.WriteString("  const baseUrl = env.API_BASE_URL || '" + GetPrimaryServer(ir) + "';\n")

	if NeedsAuthentication(ir) {
		sb.WriteString("  const apiKey = env.API_KEY;\n")
		sb.WriteString("  if (!apiKey) {\n")
		sb.WriteString("    throw new Error('API_KEY environment variable is required');\n")
		sb.WriteString("  }\n\n")
	}

	sb.WriteString("  switch (toolName) {\n")

	// Generate cases for each endpoint
	for _, endpoint := range ir.Endpoints {
		toolName := g.getToolName(endpoint)
		sb.WriteString(fmt.Sprintf("    case '%s':\n", toolName))
		sb.WriteString(fmt.Sprintf("      return await execute_%s(baseUrl, args, env);\n", sanitizeIdentifier(toolName)))
	}

	sb.WriteString("    default:\n")
	sb.WriteString("      throw new Error(`Unknown tool: ${toolName}`);\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n\n")

	// Generate executor functions for each endpoint
	for _, endpoint := range ir.Endpoints {
		executorFunc := g.generateExecutorFunction(endpoint, ir, opts)
		sb.WriteString(executorFunc)
		sb.WriteString("\n")
	}

	// Environment interface
	sb.WriteString("interface Env {\n")
	sb.WriteString("  API_BASE_URL?: string;\n")
	if NeedsAuthentication(ir) {
		sb.WriteString("  API_KEY?: string;\n")
	}
	sb.WriteString("}\n")

	return GeneratedFile{
		Path:     "src/index.ts",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "typescript",
	}, nil
}

// generateTypesFile generates TypeScript type definitions
func (g *TypeScriptCloudflareGenerator) generateTypesFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("// Generated TypeScript types\n\n")

	// MCP types
	sb.WriteString("export interface MCPServer {\n")
	sb.WriteString("  name: string;\n")
	sb.WriteString("  version: string;\n")
	sb.WriteString("  description: string;\n")
	sb.WriteString("  tools: MCPTool[];\n")
	sb.WriteString("}\n\n")

	sb.WriteString("export interface MCPTool {\n")
	sb.WriteString("  name: string;\n")
	sb.WriteString("  description: string;\n")
	sb.WriteString("  parameters: {\n")
	sb.WriteString("    type: 'object';\n")
	sb.WriteString("    properties: Record<string, any>;\n")
	sb.WriteString("    required?: string[];\n")
	sb.WriteString("  };\n")
	sb.WriteString("}\n\n")

	// Generate types from IR
	for _, typeDef := range ir.Types {
		sb.WriteString(g.generateTypeDefinition(typeDef))
		sb.WriteString("\n")
	}

	// Generate request/response types for endpoints
	for _, endpoint := range ir.Endpoints {
		// Request type
		if endpoint.RequestBody != nil {
			sb.WriteString(fmt.Sprintf("export interface %sRequest {\n", toPascalCase(endpoint.ID)))
			if endpoint.RequestBody.Schema != nil && endpoint.RequestBody.Schema.Type != "" {
				sb.WriteString("  // Request body type\n")
				sb.WriteString(fmt.Sprintf("  body: %s;\n", typeToTypeScript(endpoint.RequestBody.Schema.Type)))
			}
			sb.WriteString("}\n\n")
		}

		// Response types
		for _, response := range endpoint.Responses {
			sb.WriteString(fmt.Sprintf("export interface %sResponse%s {\n", toPascalCase(endpoint.ID), response.StatusCode))
			if response.Schema != nil && response.Schema.Type != "" {
				sb.WriteString(fmt.Sprintf("  data: %s;\n", typeToTypeScript(response.Schema.Type)))
			}
			sb.WriteString("}\n\n")
		}
	}

	return GeneratedFile{
		Path:     "src/types.ts",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "typescript",
	}, nil
}

// generateToolsFile generates the MCP tools manifest
func (g *TypeScriptCloudflareGenerator) generateToolsFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("// Generated MCP Tools\n")
	sb.WriteString("import { MCPTool } from './types';\n\n")

	sb.WriteString("export const tools: MCPTool[] = [\n")

	for i, endpoint := range ir.Endpoints {
		toolName := g.getToolName(endpoint)
		sb.WriteString("  {\n")
		sb.WriteString(fmt.Sprintf("    name: '%s',\n", toolName))
		sb.WriteString(fmt.Sprintf("    description: '%s',\n", escapeString(endpoint.Description)))
		sb.WriteString("    parameters: {\n")
		sb.WriteString("      type: 'object',\n")
		sb.WriteString("      properties: {\n")

		// Add parameters
		for _, param := range endpoint.Parameters {
			sb.WriteString(fmt.Sprintf("        %s: {\n", param.Name))
			sb.WriteString(fmt.Sprintf("          type: '%s',\n", typeToTypeScript(param.Schema.Type)))
			if param.Description != "" {
				sb.WriteString(fmt.Sprintf("          description: '%s',\n", escapeString(param.Description)))
			}
			sb.WriteString("        },\n")
		}

		sb.WriteString("      },\n")

		// Required parameters
		requiredParams := []string{}
		for _, param := range endpoint.Parameters {
			if param.Required {
				requiredParams = append(requiredParams, param.Name)
			}
		}
		if len(requiredParams) > 0 {
			sb.WriteString("      required: [")
			for j, req := range requiredParams {
				if j > 0 {
					sb.WriteString(", ")
				}
				sb.WriteString(fmt.Sprintf("'%s'", req))
			}
			sb.WriteString("],\n")
		}

		sb.WriteString("    },\n")
		sb.WriteString("  }")

		if i < len(ir.Endpoints)-1 {
			sb.WriteString(",")
		}
		sb.WriteString("\n")
	}

	sb.WriteString("];\n")

	return GeneratedFile{
		Path:     "src/tools.ts",
		Content:  sb.String(),
		Type:     FileTypeSource,
		Language: "typescript",
	}, nil
}

// Helper functions

func (g *TypeScriptCloudflareGenerator) getToolName(endpoint parser.UnifiedEndpoint) string {
	if endpoint.Name != "" {
		return toSnakeCase(endpoint.Name)
	}
	return toSnakeCase(endpoint.ID)
}

func (g *TypeScriptCloudflareGenerator) generateTypeDefinition(typeDef parser.TypeDefinition) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("export interface %s {\n", toPascalCase(typeDef.Name)))

	for propName, propDef := range typeDef.Properties {
		optional := ""
		if !contains(typeDef.Required, propName) {
			optional = "?"
		}

		tsType := typeToTypeScript(propDef.Type)
		if propDef.Ref != "" {
			// Extract type name from $ref
			parts := strings.Split(propDef.Ref, "/")
			tsType = toPascalCase(parts[len(parts)-1])
		}

		if propDef.Description != "" {
			sb.WriteString(fmt.Sprintf("  /** %s */\n", propDef.Description))
		}
		sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", propName, optional, tsType))
	}

	sb.WriteString("}\n")
	return sb.String()
}

func (g *TypeScriptCloudflareGenerator) generateExecutorFunction(endpoint parser.UnifiedEndpoint, ir *parser.IntermediateRepresentation, opts GenerateOptions) string {
	var sb strings.Builder

	toolName := sanitizeIdentifier(g.getToolName(endpoint))
	sb.WriteString(fmt.Sprintf("async function execute_%s(\n", toolName))
	sb.WriteString("  baseUrl: string,\n")
	sb.WriteString("  args: Record<string, any>,\n")
	sb.WriteString("  env: Env\n")
	sb.WriteString("): Promise<any> {\n")

	// Build URL with path parameters
	path := endpoint.Path
	for _, param := range endpoint.Parameters {
		if param.In == "path" {
			path = strings.ReplaceAll(path, "{"+param.Name+"}", "${args."+param.Name+"}")
		}
	}
	sb.WriteString(fmt.Sprintf("  const url = `${baseUrl}%s`;\n\n", path))

	// Build query parameters
	queryParams := []string{}
	for _, param := range endpoint.Parameters {
		if param.In == "query" {
			queryParams = append(queryParams, param.Name)
		}
	}

	if len(queryParams) > 0 {
		sb.WriteString("  const params = new URLSearchParams();\n")
		for _, qp := range queryParams {
			sb.WriteString(fmt.Sprintf("  if (args.%s !== undefined) params.append('%s', String(args.%s));\n", qp, qp, qp))
		}
		sb.WriteString("  const urlWithParams = url + (params.toString() ? '?' + params.toString() : '');\n\n")
	} else {
		sb.WriteString("  const urlWithParams = url;\n\n")
	}

	// Build headers
	sb.WriteString("  const headers: Record<string, string> = {\n")
	sb.WriteString("    'Content-Type': 'application/json',\n")

	if NeedsAuthentication(ir) {
		sb.WriteString("    'Authorization': `Bearer ${env.API_KEY}`,\n")
	}

	sb.WriteString("  };\n\n")

	// Make request
	sb.WriteString("  const response = await fetch(urlWithParams, {\n")
	sb.WriteString(fmt.Sprintf("    method: '%s',\n", endpoint.Method))
	sb.WriteString("    headers,\n")

	if endpoint.RequestBody != nil && (endpoint.Method == "POST" || endpoint.Method == "PUT" || endpoint.Method == "PATCH") {
		sb.WriteString("    body: JSON.stringify(args.body),\n")
	}

	sb.WriteString("  });\n\n")

	// Handle response
	sb.WriteString("  if (!response.ok) {\n")
	sb.WriteString("    throw new Error(`API error: ${response.status} ${response.statusText}`);\n")
	sb.WriteString("  }\n\n")

	sb.WriteString("  return await response.json();\n")
	sb.WriteString("}\n")

	return sb.String()
}

func (g *TypeScriptCloudflareGenerator) generatePackageJSON(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	packageName := opts.PackageName
	if packageName == "" {
		packageName = toKebabCase(ir.Metadata.Name)
	}

	content := fmt.Sprintf(`{
  "name": "%s",
  "version": "%s",
  "description": "%s",
  "main": "src/index.ts",
  "scripts": {
    "dev": "wrangler dev",
    "deploy": "wrangler deploy",
    "test": "vitest"
  },
  "dependencies": {},
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20240512.0",
    "typescript": "^5.0.0",
    "wrangler": "^3.0.0",
    "vitest": "^1.0.0"
  }
}
`, packageName, ir.Metadata.Version, escapeString(ir.Metadata.Description))

	return GeneratedFile{
		Path:     "package.json",
		Content:  content,
		Type:     FileTypeConfig,
		Language: "json",
	}, nil
}

func (g *TypeScriptCloudflareGenerator) generateWranglerConfig(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	workerName := opts.PackageName
	if workerName == "" {
		workerName = toKebabCase(ir.Metadata.Name)
	}

	content := fmt.Sprintf(`name = "%s"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "%s"
`, workerName, workerName)

	return GeneratedFile{
		Path:     "wrangler.toml",
		Content:  content,
		Type:     FileTypeConfig,
		Language: "toml",
	}, nil
}

func (g *TypeScriptCloudflareGenerator) generateReadme(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# %s\n\n", ir.Metadata.Title))
	sb.WriteString(fmt.Sprintf("%s\n\n", ir.Metadata.Description))
	sb.WriteString(fmt.Sprintf("**Version:** %s\n\n", ir.Metadata.Version))

	sb.WriteString("## Installation\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("npm install\n")
	sb.WriteString("```\n\n")

	sb.WriteString("## Development\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("npm run dev\n")
	sb.WriteString("```\n\n")

	sb.WriteString("## Deployment\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("npm run deploy\n")
	sb.WriteString("```\n\n")

	sb.WriteString("## Available Tools\n\n")
	for _, endpoint := range ir.Endpoints {
		toolName := g.getToolName(endpoint)
		sb.WriteString(fmt.Sprintf("### %s\n\n", toolName))
		sb.WriteString(fmt.Sprintf("%s\n\n", endpoint.Description))
		sb.WriteString(fmt.Sprintf("**Method:** `%s %s`\n\n", endpoint.Method, endpoint.Path))
	}

	sb.WriteString("\n---\n")
	sb.WriteString("Generated by MCPOverflow TypeScript Generator\n")

	return GeneratedFile{
		Path:     "README.md",
		Content:  sb.String(),
		Type:     FileTypeDocs,
		Language: "markdown",
	}, nil
}

func (g *TypeScriptCloudflareGenerator) generateTestFile(ir *parser.IntermediateRepresentation, opts GenerateOptions) (GeneratedFile, error) {
	var sb strings.Builder

	sb.WriteString("import { describe, it, expect } from 'vitest';\n\n")

	sb.WriteString("describe('MCP Worker', () => {\n")
	sb.WriteString("  it('should return manifest', async () => {\n")
	sb.WriteString("    // Add test implementation\n")
	sb.WriteString("    expect(true).toBe(true);\n")
	sb.WriteString("  });\n")
	sb.WriteString("});\n")

	return GeneratedFile{
		Path:     "src/index.test.ts",
		Content:  sb.String(),
		Type:     FileTypeTest,
		Language: "typescript",
	}, nil
}

func (g *TypeScriptCloudflareGenerator) generateDependencies(ir *parser.IntermediateRepresentation, opts GenerateOptions) []Dependency {
	return []Dependency{
		{
			Name:     "@cloudflare/workers-types",
			Version:  "^4.20240512.0",
			Type:     DependencyTypeDev,
			Source:   "npm",
			Required: true,
		},
		{
			Name:     "typescript",
			Version:  "^5.0.0",
			Type:     DependencyTypeDev,
			Source:   "npm",
			Required: true,
		},
		{
			Name:     "wrangler",
			Version:  "^3.0.0",
			Type:     DependencyTypeDev,
			Source:   "npm",
			Required: true,
		},
	}
}

// Helper functions are now in base.go for reuse across all generators
