package migrate

import (
	"fmt"
	"strings"
)

// buildChefPushCIYAML assembles the pushci.yml for a parsed Chef layout.
// Order: validate (optional) → lint → unit-test → deps → integration.
// Each helper returns the stage name it emitted (or "") so the
// caller can wire depends_on between them without hardcoding order.
func buildChefPushCIYAML(l chefLayout, _ *ChefConvertResult) string {
	var b strings.Builder
	b.WriteString("# Generated by pushci init from Chef cookbook (v1.6.x)\n")
	b.WriteString("\"on\":\n  - push\n  - pull_request\n\nstages:\n")
	prev := emitChefValidate(&b, l)
	prev = emitChefLint(&b, l, prev)
	prev = emitChefUnitTest(&b, l, prev)
	prev = emitChefDeps(&b, l, prev)
	emitChefIntegration(&b, l, prev)
	return b.String()
}

func emitChefValidate(b *strings.Builder, l chefLayout) string {
	if len(l.validateScripts) == 0 {
		return ""
	}
	b.WriteString("  - name: validate\n    checks:\n")
	for _, s := range l.validateScripts {
		name := sanitizeName(strings.TrimSuffix(strings.TrimSuffix(s, ".sh"), ".py"))
		fmt.Fprintf(b, "      - name: %s\n        run: %s\n", name, chefRunScript(s))
	}
	return "validate"
}

func emitChefLint(b *strings.Builder, l chefLayout, prev string) string {
	b.WriteString("  - name: lint\n    checks:\n")
	b.WriteString("      - name: cookstyle\n        run: cookstyle cookbooks/\n")
	if l.foodcritic {
		b.WriteString("      # foodcritic is deprecated; cookstyle above replaces it.\n")
	}
	writeChefDepends(b, prev)
	return "lint"
}

func emitChefUnitTest(b *strings.Builder, l chefLayout, prev string) string {
	var withSpec []chefCookbook
	for _, c := range l.cookbooks {
		if c.HasSpec {
			withSpec = append(withSpec, c)
		}
	}
	if len(withSpec) == 0 {
		return prev
	}
	b.WriteString("  - name: unit-test\n    checks:\n")
	for _, c := range withSpec {
		fmt.Fprintf(b, "      - name: chefspec-%s\n        run: rspec cookbooks/%s/spec/\n", sanitizeName(c.Name), c.Name)
	}
	writeChefDepends(b, prev)
	return "unit-test"
}

func emitChefDeps(b *strings.Builder, l chefLayout, prev string) string {
	if !l.berksfile && !l.policyfile {
		return prev
	}
	b.WriteString("  - name: deps\n    checks:\n")
	if l.berksfile {
		b.WriteString("      - name: berks-install\n        run: berks install\n")
		b.WriteString("      - name: berks-verify\n        run: berks verify\n")
	}
	if l.policyfile {
		b.WriteString("      - name: policy-install\n        run: chef install Policyfile.rb\n")
	}
	writeChefDepends(b, prev)
	return "deps"
}

func emitChefIntegration(b *strings.Builder, l chefLayout, prev string) string {
	if l.kitchenYAML == "" {
		return prev
	}
	b.WriteString("  - name: integration\n    checks:\n")
	b.WriteString("      - name: kitchen-test\n        run: kitchen test\n")
	writeChefDepends(b, prev)
	return "integration"
}

func writeChefDepends(b *strings.Builder, prev string) {
	if prev == "" {
		return
	}
	fmt.Fprintf(b, "    depends_on:\n      - %s\n", prev)
}
