"""Py4J bridge template for Python-Java interoperability."""

from __future__ import annotations

import textwrap
from typing import List, Optional

from .base import (
    BridgeConfig,
    BridgeTemplate,
    BridgeType,
    InterfaceDefinition,
    Language,
)


class Py4JTemplate(BridgeTemplate):
    """Generate Py4J bridge code for Python-Java interoperability."""

    def __init__(self, config: BridgeConfig) -> None:
        # Override config to ensure proper settings for Py4J
        config.bridge_type = BridgeType.PY4J
        super().__init__(config)

    def generate_server_code(self, interface: InterfaceDefinition) -> str:
        """Generate Python server code using Py4J GatewayServer."""
        methods = self._generate_python_methods(interface)
        imports = self._generate_python_imports(interface)

        host = self.config.host
        port = self.config.base_port
        name = interface.name
        name_lower = interface.name.lower()

        return textwrap.dedent(f"""\
            # Auto-generated by UPM Bridge Generator - Py4J Template
            # DO NOT EDIT MANUALLY

            {imports}

            import structlog

            try:
                from py4j.java_gateway import GatewayServer
            except ImportError:
                raise ImportError(
                    "py4j is required for Py4J bridge. Install with: pip install py4j"
                )

            logger = structlog.get_logger(__name__)


            class {name}EntryPoint:
                '''Py4J entry point for {name} interface.

                This class exposes Python methods to Java via Py4J.
                '''

                def __init__(self):
                    self._gateway = None

                def setGateway(self, gateway):
                    '''Set the Py4J gateway reference (called automatically).'''
                    self._gateway = gateway
                    return self

            {methods}

            def start_{name_lower}_bridge(
                host: str = "{host}",
                port: int = {port},
                auto_start: bool = True,
            ) -> GatewayServer:
                '''Start the Py4J gateway server for {name}.

                Args:
                    host: Host to bind to
                    port: Port to listen on
                    auto_start: Start the server immediately

                Returns:
                    GatewayServer instance
                '''
                entry_point = {name}EntryPoint()
                server = GatewayServer(
                    entry_point=entry_point,
                    address=host,
                    port=port,
                    auto_convert=True,
                )

                if auto_start:
                    server.start()
                    logger.info(
                        "Started {name} Py4J bridge",
                        host=host,
                        port=server.get_listening_port(),
                    )

                return server


            def main():
                '''Entry point for running the bridge server directly.'''
                server = start_{name_lower}_bridge()
                try:
                    server.server.serve_forever()
                except KeyboardInterrupt:
                    logger.info("Shutting down {name} bridge server")
                    server.shutdown()


            if __name__ == "__main__":
                main()
        """)

    def generate_client_code(self, interface: InterfaceDefinition) -> str:
        """Generate Java client code using Py4J."""
        methods = self._generate_java_client_methods(interface)
        imports = self._generate_java_imports(interface)

        namespace = self.config.namespace
        name = interface.name
        name_lower = interface.name.lower()

        # Build the Java class without using f-string for the body
        java_body = f"""// Auto-generated by UPM Bridge Generator - Py4J Template
// DO NOT EDIT MANUALLY

package {namespace}.{name_lower};

{imports}

/**
 * Py4J client for accessing {name} Python bridge.
 *
 * <p>This class provides a type-safe Java interface to Python
 * functionality exposed via Py4J.</p>
 */
public class {name}Client implements AutoCloseable {{

    private final Gateway gateway;
    private final {name}EntryPoint entryPoint;

    /**
     * Create a new {name} client.
     *
     * @param host Python bridge host
     * @param port Python bridge port
     */
    public {name}Client(String host, int port) {{
        this.gateway = new Gateway(host, port);
        this.entryPoint = new {name}EntryPoint(this.gateway);
    }}

    /**
     * Create a new {name} client with custom gateway settings.
     *
     * @param gateway Configured Py4J Gateway instance
     */
    public {name}Client(Gateway gateway) {{
        this.gateway = gateway;
        this.entryPoint = new {name}EntryPoint(this.gateway);
    }}

    /**
     * Get the underlying Py4J gateway.
     *
     * @return Gateway instance
     */
    public Gateway getGateway() {{
        return this.gateway;
    }}

    /**
     * Check if the connection to the Python bridge is alive.
     *
     * @return true if connected, false otherwise
     */
    public boolean isConnected() {{
        try {{
            return entryPoint != null && gateway != null;
        }} catch (Exception e) {{
            return false;
        }}
    }}

{methods}

    @Override
    public void close() {{
        if (gateway != null) {{
            gateway.shutdown();
        }}
    }}

    /**
     * Entry point wrapper for Py4J communication.
     */
    public static class {name}EntryPoint {{
        private final Gateway gateway;

        public {name}EntryPoint(Gateway gateway) {{
            this.gateway = gateway;
        }}

{methods}
    }}
}}
"""
        return java_body

    def generate_build_config(self) -> str:
        """Generate Maven pom.xml for Py4J client."""
        namespace = self.config.namespace
        package_name = self.config.package_name

        return textwrap.dedent(f"""\
            <!-- Auto-generated by UPM Bridge Generator - Py4J Template -->
            <project>
                <modelVersion>4.0.0</modelVersion>

                <groupId>{namespace}</groupId>
                <artifactId>{package_name}-py4j-client</artifactId>
                <version>1.0.0</version>
                <packaging>jar</packaging>

                <name>UPM Py4J Bridge Client</name>
                <description>Auto-generated Py4J client for UPM bridge</description>

                <properties>
                    <maven.compiler.source>17</maven.compiler.source>
                    <maven.compiler.target>17</maven.compiler.target>
                    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                    <py4j.version>0.10.9.7</py4j.version>
                </properties>

                <dependencies>
                    <!-- Py4J for Python-Java interoperability -->
                    <dependency>
                        <groupId>net.sf.py4j</groupId>
                        <artifactId>py4j</artifactId>
                        <version>${{py4j.version}}</version>
                    </dependency>

                    <!-- Logging -->
                    <dependency>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                        <version>2.0.9</version>
                    </dependency>
                </dependencies>

                <build>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-compiler-plugin</artifactId>
                            <version>3.11.0</version>
                        </plugin>
                    </plugins>
                </build>
            </project>
        """)

    def _generate_python_methods(self, interface: InterfaceDefinition) -> str:
        """Generate Python method implementations."""
        methods = []

        for method in interface.methods:
            python_name = self.format_method_name(method.name, Language.PYTHON)

            # Build parameter list
            params = ["self"]
            for param in method.parameters:
                param_type = self.map_type(param.type)
                params.append(f"{param.name}: {param_type}")

            param_str = ", ".join(params)

            # Build method body
            docstring = (
                f'"""{method.docstring or method.name}"""' if method.docstring else ""
            )
            method_code = f"    def {python_name}({param_str}) -> {self.map_type(method.return_type)}:\n"

            if docstring:
                method_code += f"        {docstring}\n"

            # Add implementation placeholder
            method_code += "        # TODO: Implement method logic\n"
            method_code += f'        raise NotImplementedError("{python_name} not yet implemented")\n'

            methods.append(method_code)

        return "\n\n".join(methods)

    def _generate_python_imports(self, interface: InterfaceDefinition) -> str:
        """Generate Python import statements."""
        imports = set()

        for method in interface.methods:
            for param in method.parameters:
                self._collect_python_type_imports(param.type, imports)
            self._collect_python_type_imports(method.return_type, imports)

        if imports:
            return "from __future__ import annotations\n\n" + "\n".join(
                f"import {imp}" for imp in sorted(imports)
            )

        return "from __future__ import annotations"

    def _collect_python_type_imports(self, type_str: str, imports: set[str]) -> None:
        """Collect Python imports needed for a type."""
        base_type = type_str.split("<")[0].strip()

        python_imports = {
            "datetime": "datetime",
            "uuid": "uuid",
            "List": "typing.List",
            "Dict": "typing.Dict",
            "Any": "typing.Any",
            "Optional": "typing.Optional",
        }

        if base_type in python_imports:
            imports.add(python_imports[base_type])

    def _generate_java_client_methods(self, interface: InterfaceDefinition) -> str:
        """Generate Java client method implementations."""
        methods = []

        for method in interface.methods:
            java_name = self.format_method_name(method.name, Language.JAVA)

            # Build parameter list
            params = []
            for param in method.parameters:
                param_type = self.map_type(param.type)
                params.append(f"{param_type} {param.name}")

            param_str = ", ".join(params)
            return_type = self.map_type(method.return_type)

            # Generate public method
            method_code = f"        /**\n"
            if method.docstring:
                method_code += f"         * {method.docstring}\n"
            method_code += f"         */\n"
            method_code += f"        public {return_type} {java_name}({param_str}) {{\n"

            # Call through entry point
            entry_point_call = f"entryPoint.{java_name}("
            entry_point_call += ", ".join(p.name for p in method.parameters)
            entry_point_call += ")"

            if return_type == "void":
                method_code += f"            {entry_point_call};\n"
            else:
                method_code += f"            return {entry_point_call};\n"

            method_code += "        }\n\n"

            methods.append(method_code)

        return "\n".join(methods)

    def _generate_java_imports(self, interface: InterfaceDefinition) -> str:
        """Generate Java import statements."""
        imports = set(
            [
                "import py4j.Gateway;",
            ]
        )

        # Add standard Java imports
        for method in interface.methods:
            for param in method.parameters:
                self._collect_java_type_imports(param.type, imports)
            self._collect_java_type_imports(method.return_type, imports)

        return "\n".join(sorted(imports))

    def _collect_java_type_imports(self, type_str: str, imports: set[str]) -> None:
        """Collect Java imports needed for a type."""
        base_type = type_str.split("<")[0].strip()

        java_imports = {
            "List": "import java.util.List;",
            "Map": "import java.util.Map;",
            "ArrayList": "import java.util.ArrayList;",
            "HashMap": "import java.util.HashMap;",
            "UUID": "import java.util.UUID;",
            "Instant": "import java.time.Instant;",
        }

        if base_type in java_imports:
            imports.add(java_imports[base_type])
