"""REST API bridge template for cross-language REST interoperability."""

from __future__ import annotations

import textwrap
from typing import List

from .base import (
    BridgeConfig,
    BridgeTemplate,
    BridgeType,
    InterfaceDefinition,
    Language,
)


class RestApiTemplate(BridgeTemplate):
    """Generate REST API bridge code for cross-language interoperability."""

    def __init__(self, config: BridgeConfig) -> None:
        config.bridge_type = BridgeType.REST_API
        super().__init__(config)

    def generate_server_code(self, interface: InterfaceDefinition) -> str:
        """Generate REST API server code."""
        if self.config.target_language == Language.PYTHON:
            return self._generate_python_fastapi_server(interface)
        elif self.config.target_language == Language.JAVA:
            return self._generate_java_spring_server(interface)
        elif self.config.target_language == Language.TYPESCRIPT:
            return self._generate_typescript_express_server(interface)
        raise ValueError(f"Unsupported target language: {self.config.target_language}")

    def generate_client_code(self, interface: InterfaceDefinition) -> str:
        """Generate REST API client code."""
        if self.config.source_language == Language.PYTHON:
            return self._generate_python_client(interface)
        elif self.config.source_language == Language.JAVA:
            return self._generate_java_client(interface)
        elif self.config.source_language == Language.TYPESCRIPT:
            return self._generate_typescript_client(interface)
        raise ValueError(f"Unsupported source language: {self.config.source_language}")

    def generate_build_config(self) -> str:
        """Generate build configuration for REST API bridge."""
        if self.config.target_language == Language.JAVA:
            return self._generate_maven_config()
        elif self.config.target_language == Language.TYPESCRIPT:
            return self._generate_npm_config()
        return "# No build configuration needed for Python FastAPI"

    def generate_openapi_spec(self, interface: InterfaceDefinition) -> str:
        """Generate OpenAPI specification for the REST API."""
        paths = {}

        for method in interface.methods:
            path = f"/{interface.name.lower()}/{method.name}"
            paths[path] = {
                "post": {
                    "summary": method.docstring or method.name,
                    "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        p.name: {"type": self._map_openapi_type(p.type)}
                                        for p in method.parameters
                                    },
                                }
                            }
                        }
                    },
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": f"#/components/schemas/{method.name}Response"
                                    }
                                }
                            }
                        }
                    },
                }
            }

        import json

        return json.dumps(
            {
                "openapi": "3.0.0",
                "info": {"title": f"{interface.name} REST API", "version": "1.0.0"},
                "paths": paths,
            },
            indent=2,
        )

    def _generate_python_fastapi_server(self, interface: InterfaceDefinition) -> str:
        """Generate Python FastAPI server."""
        endpoints = self._generate_fastapi_endpoints(interface)

        return textwrap.dedent(f"""\
            # Auto-generated by UPM Bridge Generator - REST API Template
            # DO NOT EDIT MANUALLY

            from __future__ import annotations

            from typing import Any, Dict

            from fastapi import FastAPI, HTTPException
            from pydantic import BaseModel
            import structlog

            logger = structlog.get_logger(__name__)

            app = FastAPI(
                title="{interface.name} API",
                description="Auto-generated REST API for {interface.name}",
                version="1.0.0",
            )

            # Request/Response Models
            {self._generate_pydantic_models(interface)}

            # API Endpoints
            {endpoints}

            @app.get("/health")
            async def health_check() -> Dict[str, str]:
                '''Health check endpoint.'''
                return {{"status": "healthy"}}

            @app.get("/")
            async def root() -> Dict[str, Any]:
                '''Root endpoint with API information.'''
                return {{
                    "name": "{interface.name} API",
                    "version": "1.0.0",
                    "endpoints": ["/health", "/{interface.name.lower()}/<method>"],
                }}
        """)

    def _generate_java_spring_server(self, interface: InterfaceDefinition) -> str:
        """Generate Java Spring Boot server."""
        endpoints = self._generate_spring_endpoints(interface)

        return textwrap.dedent(f"""\
            // Auto-generated by UPM Bridge Generator - REST API Template
            // DO NOT EDIT MANUALLY

            package {self.config.namespace}.{interface.name.lower()};

            import org.springframework.boot.SpringApplication;
            import org.springframework.boot.autoconfigure.SpringBootApplication;
            import org.springframework.web.bind.annotation.*;
            import org.springframework.http.ResponseEntity;
            import org.springframework.http.HttpStatus;

            import java.util.Map;
            import java.util.HashMap;

            /**
             * Spring Boot application for {interface.name} REST API.
             */
            @SpringBootApplication
            public class {interface.name}Application {{

                public static void main(String[] args) {{
                    SpringApplication.run({interface.name}Application.class, args);
                }}
            }}

            /**
             * REST controller for {interface.name} operations.
             */
            @RestController
            @RequestMapping("/api/v1/{interface.name.lower()}")
            public class {interface.name}Controller {{

            {endpoints}

                @GetMapping("/health")
                public ResponseEntity<Map<String, String>> healthCheck() {{
                    Map<String, String> response = new HashMap<>();
                    response.put("status", "healthy");
                    return ResponseEntity.ok(response);
                }}
            }}
        """)

    def _generate_typescript_express_server(
        self, interface: InterfaceDefinition
    ) -> str:
        """Generate TypeScript Express server."""
        endpoints = self._generate_express_endpoints(interface)

        return textwrap.dedent(f"""\
            // Auto-generated by UPM Bridge Generator - REST API Template
            // DO NOT EDIT MANUALLY

            import express from 'express';
            import {{ Router, Request, Response }} from 'express';

            const app = express();
            const router = Router();

            // Middleware
            app.use(express.json());

            // Types
            {self._generate_typescript_types(interface)}

            // Endpoints
            {endpoints}

            // Health check
            router.get('/health', (req: Request, res: Response) => {{
                res.json({{ status: 'healthy' }});
            }});

            app.use('/api/v1/{interface.name.lower()}', router);

            const PORT = process.env.PORT || 8040;

            app.listen(PORT, () => {{
                console.log(`{interface.name} API running on port ${{PORT}}`);
            }});
        """)

    def _generate_python_client(self, interface: InterfaceDefinition) -> str:
        """Generate Python HTTP client."""
        methods = self._generate_client_methods(interface)

        return textwrap.dedent(f"""\
            # Auto-generated by UPM Bridge Generator - REST API Client
            # DO NOT EDIT MANUALLY

            from __future__ import annotations

            import aiohttp
            from typing import Any, Dict, Optional
            import structlog

            logger = structlog.get_logger(__name__)


            class {interface.name}Client:
                '''REST API client for {interface.name}.'''

                def __init__(
                    self,
                    base_url: str = "http://localhost:8040",
                    api_version: str = "v1",
                ) -> None:
                    self.base_url = f"{{base_url}}/api/{{api_version}}/{interface.name.lower()}"
                    self._session: Optional[aiohttp.ClientSession] = None

                async def __aenter__(self) -> "{interface.name}Client":
                    self._session = aiohttp.ClientSession()
                    return self

                async def __aexit__(self, *args: Any) -> None:
                    if self._session:
                        await self._session.close()

                async def _request(
                    self,
                    method: str,
                    endpoint: str,
                    **kwargs: Any,
                ) -> Any:
                    '''Make an HTTP request.'''
                    if self._session is None:
                        raise RuntimeError("Client not initialized. Use async context manager.")

                    url = f"{{self.base_url}}/{{endpoint}}"

                    try:
                        async with self._session.request(method, url, **kwargs) as response:
                            response.raise_for_status()
                            return await response.json()
                    except aiohttp.ClientError as e:
                        logger.error("HTTP request failed", url=url, error=str(e))
                        raise

            {methods}

                async def health_check(self) -> Dict[str, str]:
                    '''Check API health.'''
                    return await self._request("GET", "../health")
        """)

    def _generate_java_client(self, interface: InterfaceDefinition) -> str:
        """Generate Java HTTP client using Spring WebClient."""
        namespace = self.config.namespace
        name = interface.name
        name_lower = interface.name.lower()

        return f"""// Auto-generated by UPM Bridge Generator - REST API Client
// DO NOT EDIT MANUALLY

package {namespace}.{name_lower}.client;

import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.time.Duration;
import java.util.Map;

/**
 * Reactive REST client for {name} API.
 */
public class {name}Client {{

    private final WebClient webClient;
    private final String baseUrl;

    public {name}Client(String baseUrl) {{
        this.baseUrl = baseUrl;
        this.webClient = WebClient.builder()
            .baseUrl(baseUrl)
            .build();
    }}

    public Mono<Map<String, Object>> healthCheck() {{
        return webClient.get()
            .uri("/health")
            .retrieve()
            .bodyToMono(Map.class);
    }}
}}
"""

    def _generate_typescript_client(self, interface: InterfaceDefinition) -> str:
        """Generate TypeScript/JavaScript HTTP client."""
        return textwrap.dedent(f"""\
            // Auto-generated by UPM Bridge Generator - REST API Client
            // DO NOT EDIT MANUALLY

            import axios, {{ AxiosInstance }} from 'axios';

            export interface {interface.name}ClientConfig {{
                baseURL?: string;
                timeout?: number;
            }}

            export class {interface.name}Client {{
                private client: AxiosInstance;

                constructor(config: {interface.name}ClientConfig = {{}}) {{
                    const defaultConfig = {{
                        baseURL: config.baseURL || 'http://localhost:8040/api/v1/{interface.name.lower()}',
                        timeout: config.timeout || 30000,
                    }};

                    this.client = axios.create(defaultConfig);
                }}

                async healthCheck(): Promise<any> {{
                    const response = await this.client.get('/health');
                    return response.data;
                }}
            }}
        """)

    def _generate_pydantic_models(self, interface: InterfaceDefinition) -> str:
        """Generate Pydantic models for requests/responses."""
        models = []

        for method in interface.methods:
            model_name = f"{method.name.capitalize()}Request"
            fields = []

            for param in method.parameters:
                optional = " | None" if param.is_optional else ""
                fields.append(
                    f"    {param.name}: {self.map_type(param.type)}{optional}"
                )

            if fields:
                models.append(
                    f'\nclass {model_name}(BaseModel):\n    """Request model for {method.name}."""\n'
                    + "\n".join(fields)
                )

        return "\n".join(models)

    def _generate_fastapi_endpoints(self, interface: InterfaceDefinition) -> str:
        """Generate FastAPI endpoint implementations."""
        endpoints = []

        for method in interface.methods:
            endpoint_name = method.name
            params = ", ".join(
                f"{p.name}: {self.map_type(p.type)}" for p in method.parameters
            )

            endpoint = f'''@app.post("/{endpoint_name}")
async def {endpoint_name}({params}) -> dict:
    """{method.docstring or endpoint_name}."""
    # TODO: Implement {endpoint_name} logic
    raise HTTPException(status_code=501, detail="Not implemented")
'''
            endpoints.append(endpoint)

        return "\n\n".join(endpoints)

    def _generate_spring_endpoints(self, interface: InterfaceDefinition) -> str:
        """Generate Spring endpoint implementations."""
        endpoints = []

        for method in interface.methods:
            endpoint_name = self.format_method_name(method.name, Language.JAVA)
            params = ", ".join(
                f"@RequestParam {self.map_type(p.type)} {p.name}"
                for p in method.parameters
            )

            endpoint = f"""    @PostMapping("/{method.name}")
    public ResponseEntity<{self.map_type(method.return_type)}> {endpoint_name}({params}) {{
        // TODO: Implement {method.name} logic
        return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).build();
    }}

"""
            endpoints.append(endpoint)

        return "\n".join(endpoints)

    def _generate_express_endpoints(self, interface: InterfaceDefinition) -> str:
        """Generate Express endpoint implementations."""
        endpoints = []

        for method in interface.methods:
            endpoint = f"""router.post('/{method.name}', async (req: Request, res: Response) => {{
    // TODO: Implement {method.name} logic
    res.status(501).json({{ error: 'Not implemented' }});
}});

"""
            endpoints.append(endpoint)

        return "\n".join(endpoints)

    def _generate_client_methods(self, interface: InterfaceDefinition) -> str:
        """Generate client method implementations."""
        methods = []

        for method in interface.methods:
            params = ", ".join(
                f"{p.name}: {self.map_type(p.type)}" for p in method.parameters
            )

            client_method = f'''    async def {method.name}({params}) -> Any:
        """{method.docstring or method.name}."""
        return await self._request("POST", "{method.name}", json={{
            {", ".join(f'"{p.name}": {p.name}' for p in method.parameters)}
        }})
'''
            methods.append(client_method)

        return "\n\n".join(methods)

    def _generate_typescript_types(self, interface: InterfaceDefinition) -> str:
        """Generate TypeScript type definitions."""
        types = []

        for method in interface.methods:
            type_name = f"{method.name.capitalize()}Request"
            fields = []

            for param in method.parameters:
                optional = "?" if param.is_optional else ""
                fields.append(f"  {param.name}{optional}: {self.map_type(param.type)};")

            if fields:
                types.append(
                    f"export interface {type_name} {{\n" + "\n".join(fields) + "\n}"
                )

        return "\n\n".join(types)

    def _generate_maven_config(self) -> str:
        """Generate Maven pom.xml for Spring Boot."""
        return textwrap.dedent(f"""\
            <project>
                <modelVersion>4.0.0</modelVersion>

                <groupId>{self.config.namespace}</groupId>
                <artifactId>{self.config.package_name}-rest-api</artifactId>
                <version>1.0.0</version>

                <parent>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-parent</artifactId>
                    <version>3.2.0</version>
                </parent>

                <properties>
                    <java.version>17</java.version>
                </properties>

                <dependencies>
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-webflux</artifactId>
                    </dependency>
                </dependencies>
            </project>
        """)

    def _generate_npm_config(self) -> str:
        """Generate npm package.json for Express."""
        return textwrap.dedent(f"""\
            {{
                "name": "{self.config.package_name}-rest-api",
                "version": "1.0.0",
                "type": "module",
                "scripts": {{
                    "start": "node dist/index.js",
                    "build": "tsc",
                    "dev": "tsx src/index.ts"
                }},
                "dependencies": {{
                    "express": "^4.18.2",
                    "axios": "^1.6.0"
                }},
                "devDependencies": {{
                    "@types/express": "^4.17.21",
                    "@types/node": "^20.0.0",
                    "typescript": "^5.3.0",
                    "tsx": "^4.0.0"
                }}
            }}
        """)

    def _map_openapi_type(self, type_str: str) -> str:
        """Map type to OpenAPI schema type."""
        type_mapping = {
            "str": "string",
            "int": "integer",
            "float": "number",
            "bool": "boolean",
            "list": "array",
            "dict": "object",
            "Any": "object",
        }
        return type_mapping.get(type_str, "string")
