#!/usr/bin/env bash
# update-llamafile-pins.sh
#
# Auto-populates scripts/airgap/llamafile-pins.txt by:
#   1. Querying GitHub Releases for Mozilla-Ocho/llamafile.
#   2. Picking assets that match expected linux-amd64 / linux-arm64
#      filename patterns.
#   3. Downloading each asset, computing SHA256, and emitting one
#      `<arch>\t<filename>\t<sha256>\t<url>` row per match.
#
# The downloaded binaries are streamed to /dev/null after hashing so
# the script does not balloon the working tree. To stage the actual
# binaries for goreleaser, run `make airgap-stage` afterwards.
#
# Usage:
#   scripts/onboard/update-llamafile-pins.sh           # uses latest release
#   scripts/onboard/update-llamafile-pins.sh v0.10.1   # pin a specific tag

set -euo pipefail

REPO="Mozilla-Ocho/llamafile"
TAG="${1:-latest}"
OUT="scripts/airgap/llamafile-pins.txt"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq required" >&2
  exit 127
fi
if command -v sha256sum >/dev/null 2>&1; then
  HASHER=(sha256sum)
elif command -v shasum >/dev/null 2>&1; then
  HASHER=(shasum -a 256)
else
  echo "sha256sum or shasum required" >&2
  exit 127
fi

if [ "$TAG" = "latest" ]; then
  api="https://api.github.com/repos/${REPO}/releases/latest"
else
  api="https://api.github.com/repos/${REPO}/releases/tags/${TAG}"
fi

echo "[onboard-pins] fetching $api" >&2
release_json="$(curl -fsSL "$api")"
resolved_tag="$(printf '%s' "$release_json" | jq -r .tag_name)"
echo "[onboard-pins] resolved tag: $resolved_tag" >&2

# Match the canonical linux executables. llamafile ships a single
# multi-arch Cosmopolitan binary plus per-arch convenience builds
# named e.g. llamafile-0.10.1-linux-x86_64. We pin both arches.
mapfile -t rows < <(printf '%s' "$release_json" \
  | jq -r '.assets[]
           | select(.name | test("(?i)linux.*(x86_64|amd64|aarch64|arm64)"))
           | "\(.name)\t\(.browser_download_url)"')

if [ "${#rows[@]}" -eq 0 ]; then
  echo "[onboard-pins] no matching linux assets in $resolved_tag — pinning the multi-arch binary instead" >&2
  mapfile -t rows < <(printf '%s' "$release_json" \
    | jq -r '.assets[]
             | select(.name | test("^llamafile(-[0-9]+\\.[0-9]+(\\.[0-9]+)?)?$"))
             | "\(.name)\t\(.browser_download_url)"')
fi

if [ "${#rows[@]}" -eq 0 ]; then
  echo "[onboard-pins] no llamafile assets found in $resolved_tag" >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  printf '# Auto-generated by scripts/onboard/update-llamafile-pins.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '# Source: %s\n' "$api"
  printf '# Tag:    %s\n' "$resolved_tag"
  printf '# Format: <arch>\\t<filename>\\t<sha256>\\t<url>\n'
  printf '\n'
  for row in "${rows[@]}"; do
    name="${row%%	*}"
    url="${row#*	}"
    case "$name" in
      *x86_64*|*amd64*) arch="amd64" ;;
      *aarch64*|*arm64*) arch="arm64" ;;
      *) arch="amd64" ;;  # multi-arch cosmo binary lands under amd64 by default
    esac
    echo "[onboard-pins] hashing $name ($arch)..." >&2
    sha="$(curl -fsSL "$url" | "${HASHER[@]}" - | awk '{print $1}')"
    printf '%s\t%s\t%s\t%s\n' "$arch" "$name" "$sha" "$url"
  done
} > "$tmp"

mv "$tmp" "$OUT"
trap - EXIT
echo "[onboard-pins] wrote $OUT" >&2
echo "[onboard-pins] next step: make airgap-stage" >&2
