apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
      queryTimeout: 60s
      httpMethod: POST

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogsV2:
        customQuery: true
        query: 'method="${__span.tags.method}"'
        spanName: '${__span.name}'
        spanStartTimeDelta: '1m'
        tags: ['job', 'instance', 'pod', 'namespace']
        tagsField: 'resource.tags'
        startTime: '${__span.startTime}'
        traceId: '${__span.traceId}'
      tracesToMetrics:
        datasourceUid: 'prometheus'
        queries:
          - name: Sample Query
            query: 'rate(total_requests[5m])'
      spanBar:
        type: tags
        width: 0.6