export const plans = [
  {
    name: 'Free',
    price: '$0',
    period: 'forever',
    desc: 'Perfect for solo developers and open source projects.',
    features: [
      'Unlimited local runs',
      'AI stack detection',
      '2 deploy targets',
      'GitHub, GitLab, Bitbucket',
      'Community support',
    ],
  },
  {
    name: 'Pro',
    price: '$9',
    period: '/mo',
    desc: 'For developers shipping across multiple projects.',
    features: [
      'Unlimited repositories',
      'AI diagnosis (100/mo)',
      '500 cloud minutes',
      '22 deploy targets',
      'Web dashboard + analytics',
      'Slack & Discord alerts',
      'Priority support',
    ],
    highlight: true,
  },
  {
    name: 'Team',
    price: '$29',
    period: '/seat/mo',
    desc: 'For teams that need shared infrastructure.',
    features: [
      'Everything in Pro',
      '2000 cloud minutes',
      'Up to 25 members',
      'SSO / SAML',
      'Audit logs',
      'Governance workflows',
      'SLA guarantee',
    ],
  },
  {
    name: 'Enterprise',
    price: 'from $25',
    period: '/user/mo',
    desc: 'For regulated industries. Cloud or Dedicated tenant.',
    features: [
      'Everything in Team',
      'Unlimited cloud minutes · $0.01/min overage',
      'Self-hosted runner pool included',
      'Gerrit, Jenkins, AWS CodePipeline bridges',
      'SCIM provisioning · SSO enforcement',
      '7-year audit retention · SIEM export',
      'Policy-as-code + AI pipeline scan',
      'Dedicated tenant: from $8k/mo (optional)',
      'EU, US, or APAC data residency (Dedicated)',
      '24/7 incident response · 99.9% SLA',
    ],
    enterprise: true,
  },
]
