/**
 * CIS M365 Audit, Logging & Monitoring Controls
 * Levels per CIS M365 Foundations Benchmark v3.1 §5.
 */
import type { CisControl } from './control-definitions';

const COMPLIANCE = 'https://compliance.microsoft.com';
const DEFENDER = 'https://security.microsoft.com';
const ENTRA = 'https://portal.azure.com/#view/Microsoft_AAD_IAM';

export const AUDIT_CONTROLS: CisControl[] = [
	{ id: '5.1.1', section: 'Audit', title: 'Unified audit logging enabled', description: 'Audit logging enabled across all workloads', severity: 'critical', level: 'L1', graphCheck: 'audit_logging', expectedValue: 'Audit logging enabled', remediationHint: 'Enable unified audit logging in compliance center', portalUrl: `${COMPLIANCE}/auditlogsearch`, autoRemediable: false },
	{ id: '5.2.1', section: 'Audit', title: 'Alert policies for admins', description: 'Alerts for privilege escalation and suspicious activity', severity: 'high', level: 'L1', graphCheck: 'admin_alert_policies', expectedValue: 'Alert policies configured', remediationHint: 'Configure alert policies for role changes and suspicious sign-ins', portalUrl: `${DEFENDER}/alertpoliciesv2`, autoRemediable: false },
	{ id: '5.1.2', section: 'Audit', title: 'Advanced audit enabled', description: 'Microsoft 365 Advanced Audit for extended log retention', severity: 'medium', level: 'L2', graphCheck: 'advanced_audit', expectedValue: 'Advanced Audit enabled', remediationHint: 'Enable Advanced Audit for 1-year log retention', portalUrl: `${COMPLIANCE}/auditlogsearch`, autoRemediable: false },
	{ id: '5.1.3', section: 'Audit', title: 'Sign-in log retention (30+ days)', description: 'Azure AD sign-in logs retained for at least 30 days', severity: 'high', level: 'L1', graphCheck: 'signin_log_retention', expectedValue: '≥30 days retention', remediationHint: 'Configure Azure AD diagnostic settings with 30+ day retention', portalUrl: `${ENTRA}/DiagnosticSettingsMenuBlade`, autoRemediable: false },
	{ id: '5.1.4', section: 'Audit', title: 'Audit logs exported to SIEM', description: 'Audit logs streamed to external SIEM or storage', severity: 'medium', level: 'L2', graphCheck: 'audit_export_siem', expectedValue: 'Logs exported to SIEM', remediationHint: 'Configure diagnostic settings to stream logs to Sentinel or third-party SIEM', autoRemediable: false },
	{ id: '5.2.2', section: 'Audit', title: 'Alert for new admin role assignment', description: 'Alert triggers when admin role is assigned', severity: 'critical', level: 'L1', graphCheck: 'alert_admin_assignment', expectedValue: 'Alert configured', remediationHint: 'Create alert for "Elevation of Exchange admin privilege" and "Add member to role"', portalUrl: `${DEFENDER}/alertpoliciesv2`, autoRemediable: false },
	{ id: '5.2.3', section: 'Audit', title: 'Alert for malware detection', description: 'Alert triggers on malware in email or SharePoint', severity: 'high', level: 'L1', graphCheck: 'alert_malware', expectedValue: 'Malware alert configured', remediationHint: 'Enable default malware alert policy in Defender', portalUrl: `${DEFENDER}/alertpoliciesv2`, autoRemediable: false },
	{ id: '5.2.4', section: 'Audit', title: 'Alert for unusual volume of file deletion', description: 'Alert on mass file deletion events', severity: 'high', level: 'L1', graphCheck: 'alert_mass_delete', expectedValue: 'File deletion alert configured', remediationHint: 'Create alert for unusual volume of file deletions in SharePoint/OneDrive', portalUrl: `${DEFENDER}/alertpoliciesv2`, autoRemediable: false },
	{ id: '5.2.5', section: 'Audit', title: 'Alert for impossible travel', description: 'Alert on sign-ins from geographically distant locations', severity: 'medium', level: 'L2', graphCheck: 'alert_impossible_travel', expectedValue: 'Impossible travel alert active', remediationHint: 'Enable Identity Protection impossible travel detection', portalUrl: `${ENTRA}/IdentityProtection`, autoRemediable: false },
	{ id: '5.3.1', section: 'Audit', title: 'Security information events monitoring', description: 'SIEM integration for security event correlation', severity: 'medium', level: 'L2', graphCheck: 'siem_integration', expectedValue: 'SIEM connected', remediationHint: 'Connect Microsoft Sentinel or third-party SIEM', autoRemediable: false },
	{ id: '5.3.2', section: 'Audit', title: 'Threat detection policies enabled', description: 'Microsoft Defender threat detection active', severity: 'high', level: 'L1', graphCheck: 'threat_detection', expectedValue: 'Threat detection enabled', remediationHint: 'Enable all threat detection policies in Microsoft Defender', portalUrl: `${DEFENDER}/threatpolicy`, autoRemediable: false },
	{ id: '5.4.1', section: 'Audit', title: 'Activity alerts for user actions', description: 'Custom alerts for suspicious user behavior patterns', severity: 'medium', level: 'L2', graphCheck: 'user_activity_alerts', expectedValue: 'Activity alerts configured', remediationHint: 'Create activity alerts for suspicious behaviors (mass downloads, unusual access)', portalUrl: `${DEFENDER}/alertpoliciesv2`, autoRemediable: false },
];
