/** CIS M365 Benchmark v3.1 — Identity & Access Management (25 controls)
 *  Levels per CIS M365 Foundations Benchmark v3.1 §1. */
import type { CisControl } from './control-definitions';

const P = 'https://portal.azure.com/#view/Microsoft_AAD_ConditionalAccess';
const E = 'https://portal.azure.com/#view/Microsoft_AAD_IAM';

export const IDENTITY_CONTROLS: CisControl[] = [
	{
		id: '1.1.1', section: 'Identity', title: 'MFA enabled for all users',
		description: 'Ensure MFA is enforced for all users via Conditional Access',
		severity: 'critical', level: 'L1', graphCheck: 'mfa_all_users', expectedValue: 'Enforced via CA policy',
		remediationHint: 'Create a CA policy requiring MFA for all users',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: true,
	},
	{
		id: '1.1.2', section: 'Identity', title: 'MFA for guest accounts',
		description: 'Guest and external users must complete MFA via CA policy',
		severity: 'high', level: 'L1', graphCheck: 'mfa_guest_users', expectedValue: 'CA policy targets guest users',
		remediationHint: 'Create a CA policy targeting guest/external users requiring MFA',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: true,
	},
	{
		id: '1.1.3', section: 'Identity', title: 'MFA for admin accounts',
		description: 'All accounts with admin roles must have MFA',
		severity: 'critical', level: 'L1', graphCheck: 'mfa_admins', expectedValue: 'All admins MFA-registered',
		remediationHint: 'Verify all Global/Exchange/Security admins have MFA registered',
		portalUrl: `${E}/AuthenticationMethodsMenuBlade/~/AdminAuthMethods`, autoRemediable: false,
	},
	{
		id: '1.1.4', section: 'Identity', title: 'FIDO2 security keys for admins',
		description: 'Admin accounts should use phishing-resistant FIDO2 keys',
		severity: 'high', level: 'L2', graphCheck: 'fido2_admins', expectedValue: 'FIDO2 enabled for admin roles',
		remediationHint: 'Enable FIDO2 security keys as auth method and require for admins',
		portalUrl: `${E}/AuthenticationMethodsMenuBlade/~/Fido2`, autoRemediable: false,
	},
	{
		id: '1.1.5', section: 'Identity', title: 'Number matching for MFA push',
		description: 'MFA push must require number matching to prevent fatigue attacks',
		severity: 'high', level: 'L1', graphCheck: 'mfa_number_matching',
		expectedValue: 'Number matching enabled for Authenticator',
		remediationHint: 'Enable number matching in Authenticator settings',
		portalUrl: `${E}/AuthenticationMethodsMenuBlade/~/MicrosoftAuthenticator`, autoRemediable: true,
	},
	{
		id: '1.1.6', section: 'Identity', title: 'Block legacy authentication',
		description: 'Legacy auth protocols should be blocked via Conditional Access',
		severity: 'high', level: 'L1', graphCheck: 'block_legacy_auth', expectedValue: 'CA policy blocking legacy auth',
		remediationHint: 'Create CA policy blocking legacy authentication protocols',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: true,
	},
	{
		id: '1.2.1', section: 'Identity', title: 'Security defaults or CA policies',
		description: 'Either security defaults or Conditional Access must be configured',
		severity: 'critical', level: 'L1', graphCheck: 'security_defaults_or_ca',
		expectedValue: 'CA policies or security defaults enabled',
		remediationHint: 'Enable security defaults or configure CA policies',
		portalUrl: `${E}/SecurityDefaultsBlade`, autoRemediable: true,
	},
	{
		id: '1.2.2', section: 'Identity', title: 'Sign-in risk policy (medium+)',
		description: 'CA policy should block or require MFA for medium+ sign-in risk',
		severity: 'high', level: 'L2', graphCheck: 'signin_risk_policy',
		expectedValue: 'CA policy targets medium+ sign-in risk',
		remediationHint: 'Create CA policy requiring MFA at medium or high sign-in risk (requires Entra P2)',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: true,
	},
	{
		id: '1.2.3', section: 'Identity', title: 'User risk policy (high)',
		description: 'CA policy should require password change for high user risk',
		severity: 'high', level: 'L2', graphCheck: 'user_risk_policy',
		expectedValue: 'CA policy targets high user risk with password change',
		remediationHint: 'Create CA policy requiring secure password change at high user risk (requires Entra P2)',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: true,
	},
	{
		id: '1.3.1', section: 'Identity', title: 'Limit Global Administrators',
		description: 'No more than 4 Global Admins, minimum 2 for break-glass',
		severity: 'high', level: 'L1', graphCheck: 'global_admin_count', expectedValue: '2-4 Global Admins',
		remediationHint: 'Reduce Global Admin count to 2-4. Use PIM for just-in-time access',
		portalUrl: `${E}/RolesManagementMenuBlade/~/AllRoles`, autoRemediable: false,
	},
	{
		id: '1.3.2', section: 'Identity', title: 'PIM enabled for admin roles',
		description: 'PIM must be used for all admin role assignments',
		severity: 'high', level: 'L2', graphCheck: 'pim_enabled', expectedValue: 'PIM active for directory roles',
		remediationHint: 'Enable PIM and convert permanent assignments to eligible (requires Entra P2)',
		portalUrl: `${E}/PrivilegedIdentityManagement`, autoRemediable: false,
	},
	{
		id: '1.3.3', section: 'Identity', title: 'No permanent eligible assignments',
		description: 'Admin roles must not have permanent eligible assignments without expiry',
		severity: 'medium', level: 'L2', graphCheck: 'pim_no_permanent',
		expectedValue: 'All eligible assignments expire within 12 months',
		remediationHint: 'Set max eligible assignment duration in PIM role settings',
		portalUrl: `${E}/PrivilegedIdentityManagement`, autoRemediable: false,
	},
	{
		id: '1.3.4', section: 'Identity', title: 'Break-glass accounts excluded from CA',
		description: 'Emergency access accounts must be excluded from Conditional Access',
		severity: 'critical', level: 'L1', graphCheck: 'breakglass_ca_exclusion',
		expectedValue: 'Break-glass accounts in CA exclusion group',
		remediationHint: 'Add break-glass accounts to a CA exclusion group on all policies',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: false,
	},
	{
		id: '1.3.5', section: 'Identity', title: 'Named locations configured',
		description: 'Trusted named locations should be defined for CA policies',
		severity: 'medium', level: 'L1', graphCheck: 'named_locations',
		expectedValue: 'At least one named location configured',
		remediationHint: 'Define trusted IP ranges and countries as named locations',
		portalUrl: `${P}/ConditionalAccessBlade/~/NamedLocations`, autoRemediable: false,
	},
	{
		id: '1.3.6', section: 'Identity', title: 'Password expiration policy',
		description: 'Passwords should not expire per NIST 800-63B',
		severity: 'medium', level: 'L1', graphCheck: 'password_expiration',
		expectedValue: 'No forced password expiration',
		remediationHint: 'Set password expiration to "never" per NIST 800-63B guidance',
		portalUrl: `${E}/AuthenticationMethodsMenuBlade/~/PasswordProtection`, autoRemediable: false,
	},
	{
		id: '1.3.7', section: 'Identity', title: 'Banned password list',
		description: 'Custom banned password list should be configured in Entra ID',
		severity: 'medium', level: 'L1', graphCheck: 'banned_password_list',
		expectedValue: 'Custom banned password list enabled with entries',
		remediationHint: 'Enable custom banned passwords and add org-specific terms',
		portalUrl: `${E}/AuthenticationMethodsMenuBlade/~/PasswordProtection`, autoRemediable: false,
	},
	{
		id: '1.4.1', section: 'Identity', title: 'Self-service password reset',
		description: 'SSPR should be enabled for all users',
		severity: 'medium', level: 'L1', graphCheck: 'sspr_enabled', expectedValue: 'Enabled for all users',
		remediationHint: 'Enable self-service password reset in Azure AD',
		portalUrl: `${E}/PasswordResetMenuBlade/~/Properties`, autoRemediable: false,
	},
	{
		id: '1.4.2', section: 'Identity', title: 'SSPR requires 2 methods',
		description: 'SSPR must require at least 2 authentication methods to reset',
		severity: 'medium', level: 'L1', graphCheck: 'sspr_two_methods',
		expectedValue: 'Number of methods required = 2',
		remediationHint: 'Set SSPR to require 2 authentication methods for reset',
		portalUrl: `${E}/PasswordResetMenuBlade/~/AuthenticationMethods`, autoRemediable: false,
	},
	{
		id: '1.4.3', section: 'Identity', title: 'On-premises password writeback',
		description: 'Password writeback should be enabled for hybrid environments',
		severity: 'medium', level: 'L2', graphCheck: 'password_writeback',
		expectedValue: 'Password writeback enabled via Azure AD Connect',
		remediationHint: 'Enable password writeback in Azure AD Connect configuration',
		portalUrl: `${E}/PasswordResetMenuBlade/~/OnPremisesIntegration`, autoRemediable: false,
	},
	{
		id: '1.5.1', section: 'Identity', title: 'Session timeout policy',
		description: 'Idle sessions must time out to prevent unauthorized reuse',
		severity: 'medium', level: 'L1', graphCheck: 'session_timeout',
		expectedValue: 'CA policy enforces session lifetime ≤ 8 hours',
		remediationHint: 'Configure CA policy with sign-in frequency and persistent browser controls',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: true,
	},
	{
		id: '1.5.2', section: 'Identity', title: 'Persistent browser sessions disabled',
		description: 'Persistent browser sessions should be disabled for unmanaged devices',
		severity: 'medium', level: 'L1', graphCheck: 'persistent_browser_disabled',
		expectedValue: 'Persistent browser session = Never for unmanaged',
		remediationHint: 'Set persistent browser session to "Never" in CA session controls',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: true,
	},
	{
		id: '1.5.3', section: 'Identity', title: 'Sign-in frequency (max 24h)',
		description: 'Sensitive apps should enforce sign-in frequency of 24 hours max',
		severity: 'medium', level: 'L2', graphCheck: 'signin_frequency_24h',
		expectedValue: 'Sign-in frequency ≤ 24 hours for sensitive apps',
		remediationHint: 'Set sign-in frequency to 24 hours in CA policy for sensitive apps',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: true,
	},
	{
		id: '1.6.1', section: 'Identity', title: 'Device compliance as CA grant',
		description: 'CA policies should require compliant devices for access',
		severity: 'high', level: 'L2', graphCheck: 'device_compliance_grant',
		expectedValue: 'CA policy requires compliant device',
		remediationHint: 'Add "Require device to be marked as compliant" to CA grant controls',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: true,
	},
	{
		id: '1.6.2', section: 'Identity', title: 'Require hybrid Azure AD join',
		description: 'Corporate devices should be hybrid Azure AD joined for access',
		severity: 'medium', level: 'L2', graphCheck: 'hybrid_aad_join',
		expectedValue: 'CA policy requires hybrid Azure AD joined device',
		remediationHint: 'Add "Require hybrid Azure AD joined device" to CA grant controls',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: true,
	},
	{
		id: '1.7.1', section: 'Identity', title: 'Token protection enabled',
		description: 'Token protection (token binding) should be enabled to prevent token theft',
		severity: 'high', level: 'L2', graphCheck: 'token_protection',
		expectedValue: 'Token protection enforced via CA policy',
		remediationHint: 'Enable token protection in CA session controls for sensitive apps',
		portalUrl: `${P}/ConditionalAccessBlade/~/Policies`, autoRemediable: false,
	},
];
