/**
 * CIS M365 Email & Collaboration Security Controls
 * Covers anti-phishing, email authentication, transport rules, Teams policies.
 * Levels per CIS M365 Foundations Benchmark v3.1 §4.
 */
import type { CisControl } from './control-definitions';

const DEFENDER = 'https://security.microsoft.com';
const EXCHANGE = 'https://admin.exchange.microsoft.com';

export const EMAIL_CONTROLS: CisControl[] = [
	{ id: '4.1.1', section: 'Email', title: 'Anti-phishing policy', description: 'Custom anti-phishing policy with impersonation protection', severity: 'high', level: 'L1', graphCheck: 'anti_phishing', expectedValue: 'Custom policy with impersonation protection', remediationHint: 'Configure Defender anti-phishing with impersonation protection', portalUrl: `${DEFENDER}/antiphishing`, autoRemediable: false },
	{ id: '4.2.1', section: 'Email', title: 'DMARC record configured', description: 'DMARC DNS record with reject or quarantine policy', severity: 'medium', level: 'L1', graphCheck: 'dmarc_configured', expectedValue: 'DMARC p=quarantine or p=reject', remediationHint: 'Add DMARC DNS TXT record with at least p=quarantine', autoRemediable: false },
	{ id: '4.3.1', section: 'Email', title: 'External email tagging', description: 'External emails tagged with [EXTERNAL]', severity: 'low', level: 'L1', graphCheck: 'external_tagging', expectedValue: 'Transport rule tags external mail', remediationHint: 'Create mail flow rule to prepend [EXTERNAL]', portalUrl: `${EXCHANGE}/#/transportrules`, autoRemediable: false },
	{ id: '4.1.2', section: 'Email', title: 'Safe Attachments policy', description: 'Defender Safe Attachments enabled for all users', severity: 'high', level: 'L2', graphCheck: 'safe_attachments', expectedValue: 'Safe Attachments enabled', remediationHint: 'Enable Safe Attachments in Defender for Office 365', portalUrl: `${DEFENDER}/safeattachmentv2`, autoRemediable: false },
	{ id: '4.1.3', section: 'Email', title: 'Safe Links policy', description: 'Defender Safe Links enabled for all users', severity: 'high', level: 'L2', graphCheck: 'safe_links', expectedValue: 'Safe Links enabled', remediationHint: 'Enable Safe Links in Defender for Office 365', portalUrl: `${DEFENDER}/safelinksv2`, autoRemediable: false },
	{ id: '4.1.4', section: 'Email', title: 'Anti-spam inbound policy', description: 'Custom inbound anti-spam policy with high confidence thresholds', severity: 'medium', level: 'L1', graphCheck: 'anti_spam_inbound', expectedValue: 'Custom policy active', remediationHint: 'Configure inbound anti-spam with aggressive filtering', portalUrl: `${DEFENDER}/antispam`, autoRemediable: false },
	{ id: '4.1.5', section: 'Email', title: 'Anti-spam outbound policy', description: 'Outbound sending limits and notifications configured', severity: 'medium', level: 'L1', graphCheck: 'anti_spam_outbound', expectedValue: 'Sending limits enforced', remediationHint: 'Set outbound message limits and admin notifications', portalUrl: `${DEFENDER}/antispam`, autoRemediable: false },
	{ id: '4.2.2', section: 'Email', title: 'SPF record configured', description: 'SPF DNS record published for all sending domains', severity: 'high', level: 'L1', graphCheck: 'spf_configured', expectedValue: 'SPF record with -all or ~all', remediationHint: 'Add SPF TXT record: v=spf1 include:spf.protection.outlook.com -all', autoRemediable: false },
	{ id: '4.2.3', section: 'Email', title: 'DKIM signing enabled', description: 'DKIM signing enabled for all custom domains', severity: 'medium', level: 'L1', graphCheck: 'dkim_enabled', expectedValue: 'DKIM enabled per domain', remediationHint: 'Enable DKIM signing in Exchange Online for each domain', portalUrl: `${DEFENDER}/dkimv2`, autoRemediable: false },
	{ id: '4.3.2', section: 'Email', title: 'External forwarding blocked', description: 'Automatic forwarding to external addresses disabled', severity: 'high', level: 'L1', graphCheck: 'block_external_forwarding', expectedValue: 'Auto-forwarding blocked', remediationHint: 'Create transport rule to block auto-forwarding to external domains', portalUrl: `${EXCHANGE}/#/transportrules`, autoRemediable: true },
	{ id: '4.3.3', section: 'Email', title: 'Mailbox audit logging enabled', description: 'Audit logging enabled for all mailboxes', severity: 'high', level: 'L1', graphCheck: 'mailbox_auditing', expectedValue: 'Auditing enabled org-wide', remediationHint: 'Enable mailbox auditing globally via Set-OrganizationConfig', autoRemediable: false },
	{ id: '4.4.1', section: 'Email', title: 'Teams external access restricted', description: 'External messaging limited to allowed domains', severity: 'medium', level: 'L1', graphCheck: 'teams_external_access', expectedValue: 'External access limited', remediationHint: 'Restrict Teams external access to specific allowed domains', portalUrl: 'https://admin.teams.microsoft.com/company-wide-settings/external-communications', autoRemediable: false },
	{ id: '4.4.2', section: 'Email', title: 'Teams guest access controlled', description: 'Guest access in Teams with appropriate restrictions', severity: 'medium', level: 'L1', graphCheck: 'teams_guest_access', expectedValue: 'Guest access controlled', remediationHint: 'Review and restrict guest permissions in Teams admin center', portalUrl: 'https://admin.teams.microsoft.com/company-wide-settings/guest-configuration', autoRemediable: false },
	{ id: '4.4.3', section: 'Email', title: 'Teams meeting recording policy', description: 'Meeting recordings stored in OneDrive with retention', severity: 'low', level: 'L2', graphCheck: 'teams_recording_policy', expectedValue: 'Recordings to OneDrive with retention', remediationHint: 'Configure Teams meeting recording storage and retention', autoRemediable: false },
];
