/**
 * CIS M365 Device Management Controls
 * Levels per CIS M365 Foundations Benchmark v3.1 §6.
 */
import type { CisControl } from './control-definitions';

const INTUNE = 'https://intune.microsoft.com';
const ENTRA = 'https://portal.azure.com/#view/Microsoft_AAD_IAM';

export const DEVICE_CONTROLS: CisControl[] = [
	{ id: '6.1.1', section: 'Device', title: 'Intune enrollment required', description: 'All corporate devices must be enrolled in Microsoft Intune', severity: 'high', level: 'L1', graphCheck: 'intune_enrollment_required', expectedValue: 'Enrollment policy active', remediationHint: 'Configure automatic enrollment for corporate devices in Intune', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/DevicesEnrollmentMenu/~/windowsEnrollment`, autoRemediable: false },
	{ id: '6.1.2', section: 'Device', title: 'MDM authority set to Intune', description: 'Mobile device management authority must be set to Microsoft Intune', severity: 'high', level: 'L1', graphCheck: 'mdm_authority_intune', expectedValue: 'MDM authority = Intune', remediationHint: 'Set MDM authority to Intune in tenant settings', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/TenantAdminMenu/~/connectorStatus`, autoRemediable: false },
	{ id: '6.1.3', section: 'Device', title: 'Device compliance policy active', description: 'At least one device compliance policy enforced per platform', severity: 'high', level: 'L1', graphCheck: 'device_compliance_policy', expectedValue: 'Compliance policies active per platform', remediationHint: 'Create compliance policies for Windows, macOS, iOS, and Android', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/DevicesComplianceMenu/~/policies`, autoRemediable: false },
	{ id: '6.2.1', section: 'Device', title: 'BitLocker encryption required', description: 'BitLocker drive encryption enforced on all Windows devices', severity: 'high', level: 'L1', graphCheck: 'bitlocker_required', expectedValue: 'BitLocker policy enforced', remediationHint: 'Create endpoint protection profile requiring BitLocker encryption', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/DevicesConfigurationMenu/~/policies`, autoRemediable: false },
	{ id: '6.2.2', section: 'Device', title: 'Windows Hello for Business enabled', description: 'Windows Hello for Business configured as authentication method', severity: 'medium', level: 'L1', graphCheck: 'windows_hello_enabled', expectedValue: 'WHfB policy enabled', remediationHint: 'Enable Windows Hello for Business in Intune device configuration', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/DevicesWindowsMenu/~/windowsHelloForBusiness`, autoRemediable: false },
	{ id: '6.2.3', section: 'Device', title: 'Disk encryption for macOS (FileVault)', description: 'FileVault disk encryption enforced on all macOS devices', severity: 'high', level: 'L1', graphCheck: 'filevault_required', expectedValue: 'FileVault policy enforced', remediationHint: 'Create macOS endpoint protection profile requiring FileVault', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/DevicesConfigurationMenu/~/policies`, autoRemediable: false },
	{ id: '6.3.1', section: 'Device', title: 'Windows Update rings configured', description: 'Windows Update for Business rings with defined deferral periods', severity: 'medium', level: 'L1', graphCheck: 'update_rings_configured', expectedValue: 'Update rings with deferral set', remediationHint: 'Configure Windows Update rings with quality and feature update deferrals', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/DevicesWindowsMenu/~/windowsUpdateRings`, autoRemediable: false },
	{ id: '6.3.2', section: 'Device', title: 'Security baselines applied', description: 'Microsoft security baselines deployed to all managed devices', severity: 'high', level: 'L2', graphCheck: 'security_baselines_applied', expectedValue: 'Baselines assigned to device groups', remediationHint: 'Deploy Windows security baseline profiles to all managed device groups', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/DevicesConfigurationMenu/~/securityBaselines`, autoRemediable: false },
	{ id: '6.3.3', section: 'Device', title: 'App protection policies for mobile', description: 'MAM app protection policies for iOS and Android', severity: 'high', level: 'L1', graphCheck: 'app_protection_policies', expectedValue: 'APP policies active for iOS and Android', remediationHint: 'Create app protection policies for managed apps on iOS and Android', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/DevicesAppProtectionMenu/~/policies`, autoRemediable: false },
	{ id: '6.4.1', section: 'Device', title: 'Conditional Access requires compliant device', description: 'CA policy requiring device to be marked as compliant', severity: 'high', level: 'L2', graphCheck: 'ca_require_compliant_device', expectedValue: 'CA policy with compliant device grant', remediationHint: 'Create Conditional Access policy with "Require device to be marked as compliant" grant', portalUrl: `${ENTRA}/ConditionalAccessBlade/~/Policies`, autoRemediable: true },
	{ id: '6.4.2', section: 'Device', title: 'Block enrollment of personal devices', description: 'Personal device enrollment restricted or blocked', severity: 'medium', level: 'L2', graphCheck: 'block_personal_enrollment', expectedValue: 'Personal enrollment blocked', remediationHint: 'Set enrollment restrictions to block personally owned devices', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/DevicesEnrollmentMenu/~/enrollmentRestrictions`, autoRemediable: false },
	{ id: '6.4.3', section: 'Device', title: 'Remote wipe capability enabled', description: 'Admins can remotely wipe or retire lost/stolen devices', severity: 'medium', level: 'L1', graphCheck: 'remote_wipe_enabled', expectedValue: 'Remote wipe available', remediationHint: 'Verify remote wipe and retire actions are available for all enrolled devices', portalUrl: INTUNE, autoRemediable: false },
	{ id: '6.5.1', section: 'Device', title: 'Device inventory reviewed monthly', description: 'Stale and non-compliant devices reviewed on a monthly cadence', severity: 'medium', level: 'L1', graphCheck: 'device_inventory_review', expectedValue: 'Monthly review process documented', remediationHint: 'Establish monthly device inventory review to remove stale and non-compliant devices', portalUrl: `${INTUNE}/#view/Microsoft_Intune_DeviceSettings/DevicesMenu/~/mDMDevicesPreview`, autoRemediable: false },
];
