/**
 * CIS M365 Cloud Application Security Controls
 * Levels per CIS M365 Foundations Benchmark v3.1 §7.
 */
import type { CisControl } from './control-definitions';

const ENTRA = 'https://portal.azure.com/#view/Microsoft_AAD_IAM';
const DEFENDER = 'https://security.microsoft.com';

export const APP_CONTROLS: CisControl[] = [
	{ id: '7.1.1', section: 'Apps', title: 'App registrations restricted to admins', description: 'Only admins can register new applications in Azure AD', severity: 'high', level: 'L1', graphCheck: 'app_registration_restricted', expectedValue: 'Users cannot register apps', remediationHint: 'Set "Users can register applications" to No in Azure AD user settings', portalUrl: `${ENTRA}/UsersManagementMenuBlade/~/UserSettings`, autoRemediable: true },
	{ id: '7.1.2', section: 'Apps', title: 'Service principal credential expiry tracked', description: 'All service principal secrets and certificates have tracked expiry dates', severity: 'high', level: 'L1', graphCheck: 'sp_credential_expiry_tracked', expectedValue: 'Expiry alerts configured', remediationHint: 'Set up alerts for service principal credentials approaching expiry', portalUrl: `${ENTRA}/AppRegistrationsPreview`, autoRemediable: false },
	{ id: '7.1.3', section: 'Apps', title: 'No application secrets > 1 year', description: 'Application credentials must expire within 1 year or less', severity: 'high', level: 'L1', graphCheck: 'app_secret_max_lifetime', expectedValue: 'All secrets ≤ 1 year', remediationHint: 'Rotate all app secrets with expiry > 1 year and set policy for max lifetime', portalUrl: `${ENTRA}/AppRegistrationsPreview`, autoRemediable: false },
	{ id: '7.2.1', section: 'Apps', title: 'OAuth app consent limited', description: 'User consent for OAuth apps restricted to verified publishers or disabled', severity: 'high', level: 'L1', graphCheck: 'oauth_consent_limited', expectedValue: 'Consent restricted or disabled', remediationHint: 'Restrict user consent to apps from verified publishers only', portalUrl: `${ENTRA}/ConsentPoliciesMenuBlade/~/UserSettings`, autoRemediable: true },
	{ id: '7.2.2', section: 'Apps', title: 'Admin consent workflow enabled', description: 'Users can request admin consent for apps they cannot self-consent to', severity: 'medium', level: 'L1', graphCheck: 'admin_consent_workflow', expectedValue: 'Admin consent workflow enabled', remediationHint: 'Enable admin consent request workflow in Enterprise Applications settings', portalUrl: `${ENTRA}/ConsentPoliciesMenuBlade/~/AdminConsentSettings`, autoRemediable: true },
	{ id: '7.2.3', section: 'Apps', title: 'Enterprise app user assignment required', description: 'Enterprise apps require user or group assignment before access', severity: 'medium', level: 'L1', graphCheck: 'enterprise_app_assignment_required', expectedValue: 'Assignment required = Yes', remediationHint: 'Set "User assignment required" to Yes on all enterprise applications', portalUrl: `${ENTRA}/StartboardApplicationsMenu`, autoRemediable: false },
	{ id: '7.3.1', section: 'Apps', title: 'App proxy configured for legacy apps', description: 'Azure AD Application Proxy used for secure remote access to legacy apps', severity: 'medium', level: 'L2', graphCheck: 'app_proxy_configured', expectedValue: 'App Proxy active for legacy apps', remediationHint: 'Configure Azure AD Application Proxy for on-premises legacy applications', portalUrl: `${ENTRA}/ApplicationProxyMenu`, autoRemediable: false },
	{ id: '7.3.2', section: 'Apps', title: 'API permissions review quarterly', description: 'App API permissions reviewed and pruned on a quarterly schedule', severity: 'medium', level: 'L1', graphCheck: 'api_permissions_review', expectedValue: 'Quarterly review documented', remediationHint: 'Establish quarterly review of app registrations and remove unnecessary API permissions', portalUrl: `${ENTRA}/AppRegistrationsPreview`, autoRemediable: false },
	{ id: '7.3.3', section: 'Apps', title: 'Managed identities preferred over secrets', description: 'Azure resources use managed identities instead of stored credentials', severity: 'high', level: 'L2', graphCheck: 'managed_identities_preferred', expectedValue: 'Managed identities used where possible', remediationHint: 'Migrate workloads from app secrets to system-assigned or user-assigned managed identities', autoRemediable: false },
	{ id: '7.4.1', section: 'Apps', title: 'Microsoft Defender for Cloud Apps enabled', description: 'Defender for Cloud Apps activated for shadow IT discovery and app governance', severity: 'high', level: 'L2', graphCheck: 'defender_cloud_apps_enabled', expectedValue: 'MDCA enabled', remediationHint: 'Enable Microsoft Defender for Cloud Apps and connect data sources', portalUrl: `${DEFENDER}/cloudapps`, autoRemediable: false },
	{ id: '7.4.2', section: 'Apps', title: 'Shadow IT discovery active', description: 'Cloud Discovery enabled to detect unsanctioned cloud app usage', severity: 'medium', level: 'L2', graphCheck: 'shadow_it_discovery', expectedValue: 'Cloud Discovery active', remediationHint: 'Enable Cloud Discovery in Defender for Cloud Apps with log collector', portalUrl: `${DEFENDER}/cloudapps/discovery`, autoRemediable: false },
	{ id: '7.4.3', section: 'Apps', title: 'Sanctioned/unsanctioned app classification', description: 'Discovered apps classified as sanctioned or unsanctioned with policies', severity: 'medium', level: 'L2', graphCheck: 'app_classification', expectedValue: 'Apps classified with policies', remediationHint: 'Review discovered apps and tag as sanctioned or unsanctioned in MDCA', portalUrl: `${DEFENDER}/cloudapps/discovery`, autoRemediable: false },
	{ id: '7.5.1', section: 'Apps', title: 'Workload identities protection', description: 'Workload identity federation and conditional access for non-human identities', severity: 'high', level: 'L2', graphCheck: 'workload_identity_protection', expectedValue: 'Workload identity policies active', remediationHint: 'Configure Conditional Access policies for workload identities and enable identity protection', portalUrl: `${ENTRA}/WorkloadIdentitiesBlade`, autoRemediable: false },
];
