/**
 * CIS Microsoft 365 Foundations Benchmark v3.1 — Data Protection Controls
 * 25 controls: sharing, DLP, labels, retention, barriers, eDiscovery, encryption, insider risk.
 * Levels per CIS M365 Foundations Benchmark v3.1 §2-3.
 */
import type { CisControl } from './control-definitions';

const C = 'https://compliance.microsoft.com';
const P = 'https://purview.microsoft.com';
const S = 'https://admin.microsoft.com/sharepoint?page=sharing';
const E = 'https://portal.azure.com/#view/Microsoft_AAD_IAM';
const DLP = `${C}/datalossprevention/policies`;
const RET = `${C}/datalifecycle/retention`;
const LBL = `${C}/informationprotection/labels`;
const ADM = 'https://admin.microsoft.com/#/Settings/SecurityPrivacy';

const d = (o: Omit<CisControl, 'section'>): CisControl => ({ ...o, section: 'Data' });

export const DATA_CONTROLS: CisControl[] = [
	d({ id: '2.1.1', title: 'User consent to apps restricted',
		description: 'Users should not consent to apps accessing org data', severity: 'high', level: 'L1',
		graphCheck: 'user_consent_disabled', expectedValue: 'User consent disabled or limited',
		remediationHint: 'Set user consent to "Do not allow" or approved publishers only',
		portalUrl: `${E}/ConsentPoliciesMenuBlade`, autoRemediable: true }),
	d({ id: '2.1.2', title: 'Guest invite restrictions',
		description: 'Only admins should invite external guests', severity: 'medium', level: 'L1',
		graphCheck: 'guest_invite_restricted', expectedValue: 'Only admins can invite guests',
		remediationHint: 'Restrict guest invitations to admins in External Identities',
		portalUrl: `${E}/ExternalIdentitiesBlade`, autoRemediable: true }),
	d({ id: '3.1.1', title: 'SharePoint external sharing restricted',
		description: 'External sharing limited to authenticated guests', severity: 'high', level: 'L1',
		graphCheck: 'sharepoint_sharing', expectedValue: 'Existing guests only or less permissive',
		remediationHint: 'Restrict SharePoint sharing to existing guests or org-only',
		portalUrl: S, autoRemediable: false }),
	d({ id: '3.1.2', title: 'OneDrive sharing limited to org',
		description: 'OneDrive sharing should default to internal users only', severity: 'high', level: 'L1',
		graphCheck: 'onedrive_sharing_org_only', expectedValue: 'Sharing restricted to organization',
		remediationHint: 'Set OneDrive sharing to "Only people in your organization"',
		portalUrl: S, autoRemediable: false }),
	d({ id: '3.1.3', title: 'Anonymous sharing links disabled',
		description: 'Anyone-with-the-link sharing must be disabled', severity: 'high', level: 'L1',
		graphCheck: 'anonymous_links_disabled', expectedValue: 'Anonymous links disabled',
		remediationHint: 'Disable "Anyone" link type in SharePoint sharing settings',
		portalUrl: S, autoRemediable: false }),
	d({ id: '3.1.4', title: 'Sharing links default to org-only',
		description: 'Default sharing link type must be organization-scoped', severity: 'high', level: 'L1',
		graphCheck: 'sharing_link_default_org', expectedValue: 'Default link: People in org',
		remediationHint: 'Set default sharing link to "People in your organization"',
		portalUrl: S, autoRemediable: false }),
	d({ id: '3.2.1', title: 'DLP policies configured',
		description: 'At least one DLP policy should protect sensitive data', severity: 'high', level: 'L2',
		graphCheck: 'dlp_policies_exist', expectedValue: 'At least 1 active DLP policy',
		remediationHint: 'Create DLP policies for PII, financial, and health info (requires E5/EMS E5)',
		portalUrl: DLP, autoRemediable: false }),
	d({ id: '3.2.2', title: 'DLP for Teams chat/messages',
		description: 'DLP policies must cover Teams chat and channel messages', severity: 'high', level: 'L2',
		graphCheck: 'dlp_teams_enabled', expectedValue: 'DLP policy includes Teams locations',
		remediationHint: 'Add Teams chat and channel locations to DLP policy scope',
		portalUrl: DLP, autoRemediable: false }),
	d({ id: '3.2.3', title: 'DLP notifications configured',
		description: 'Users and admins notified on DLP policy matches', severity: 'high', level: 'L2',
		graphCheck: 'dlp_notifications_on', expectedValue: 'User and admin notifications enabled',
		remediationHint: 'Enable policy tips and admin alerts in DLP settings',
		portalUrl: DLP, autoRemediable: false }),
	d({ id: '3.2.4', title: 'DLP endpoint enforcement',
		description: 'DLP policies should enforce on endpoint devices', severity: 'high', level: 'L2',
		graphCheck: 'dlp_endpoint_enforcement', expectedValue: 'Endpoint DLP enabled and enforcing',
		remediationHint: 'Enable endpoint DLP in Purview and onboard devices',
		portalUrl: `${P}/datalossprevention/policies`, autoRemediable: false }),
	d({ id: '3.3.1', title: 'Sensitivity labels published',
		description: 'Sensitivity labels published for classification', severity: 'medium', level: 'L1',
		graphCheck: 'sensitivity_labels', expectedValue: 'Labels published to users',
		remediationHint: 'Create and publish labels (Public, Internal, Confidential)',
		portalUrl: LBL, autoRemediable: false }),
	d({ id: '3.3.2', title: 'Auto-labeling policies configured',
		description: 'Auto-labeling classifies documents with sensitive content', severity: 'medium', level: 'L2',
		graphCheck: 'auto_labeling_policies', expectedValue: 'At least 1 auto-labeling policy active',
		remediationHint: 'Create auto-labeling policies for PII and financial content',
		portalUrl: `${C}/informationprotection/autolabeling`, autoRemediable: false }),
	d({ id: '3.3.3', title: 'Default sensitivity label for documents',
		description: 'A default label should apply to all new documents', severity: 'medium', level: 'L1',
		graphCheck: 'default_sensitivity_label', expectedValue: 'Default label configured in policy',
		remediationHint: 'Set a default label (e.g., Internal) in the label policy',
		portalUrl: LBL, autoRemediable: false }),
	d({ id: '3.4.1', title: 'Retention policies for Exchange',
		description: 'Email retention policy must be configured', severity: 'high', level: 'L1',
		graphCheck: 'retention_exchange', expectedValue: 'Retention policy covers Exchange',
		remediationHint: 'Create a retention policy targeting Exchange mailboxes',
		portalUrl: RET, autoRemediable: false }),
	d({ id: '3.4.2', title: 'Retention policies for SharePoint',
		description: 'SharePoint site retention policy must be configured', severity: 'high', level: 'L1',
		graphCheck: 'retention_sharepoint', expectedValue: 'Retention policy covers SharePoint',
		remediationHint: 'Create a retention policy targeting SharePoint sites',
		portalUrl: RET, autoRemediable: false }),
	d({ id: '3.4.3', title: 'Retention policies for Teams',
		description: 'Teams messages retention policy must be configured', severity: 'high', level: 'L1',
		graphCheck: 'retention_teams', expectedValue: 'Retention policy covers Teams messages',
		remediationHint: 'Create a retention policy targeting Teams chat and channels',
		portalUrl: RET, autoRemediable: false }),
	d({ id: '3.5.1', title: 'Information barriers configured',
		description: 'Information barriers prevent unauthorized communication', severity: 'medium', level: 'L2',
		graphCheck: 'information_barriers', expectedValue: 'At least 1 barrier policy active',
		remediationHint: 'Define barrier segments and policies in Purview',
		portalUrl: `${P}/informationbarriers`, autoRemediable: false }),
	d({ id: '3.5.2', title: 'Communication compliance active',
		description: 'Communication compliance monitors policy violations', severity: 'medium', level: 'L2',
		graphCheck: 'communication_compliance', expectedValue: 'At least 1 compliance policy active',
		remediationHint: 'Create communication compliance policy in Purview',
		portalUrl: `${P}/communicationcompliance`, autoRemediable: false }),
	d({ id: '3.6.1', title: 'eDiscovery case management',
		description: 'eDiscovery available for legal investigations', severity: 'medium', level: 'L1',
		graphCheck: 'ediscovery_available', expectedValue: 'eDiscovery roles assigned',
		remediationHint: 'Assign eDiscovery Manager role to compliance team',
		portalUrl: `${P}/ediscovery`, autoRemediable: false }),
	d({ id: '3.6.2', title: 'Legal hold capability',
		description: 'Legal hold preserves content for litigation', severity: 'medium', level: 'L1',
		graphCheck: 'legal_hold_capable', expectedValue: 'Legal hold capability verified',
		remediationHint: 'Verify eDiscovery Premium license and test hold creation',
		portalUrl: `${P}/ediscovery`, autoRemediable: false }),
	d({ id: '3.7.1', title: 'Customer Lockbox enabled',
		description: 'Customer Lockbox requires approval for Microsoft access', severity: 'medium', level: 'L2',
		graphCheck: 'customer_lockbox', expectedValue: 'Customer Lockbox enabled',
		remediationHint: 'Enable Customer Lockbox in M365 admin center',
		portalUrl: ADM, autoRemediable: false }),
	d({ id: '3.7.2', title: 'Encryption for emails (OME)',
		description: 'Office Message Encryption protects email content', severity: 'medium', level: 'L1',
		graphCheck: 'ome_configured', expectedValue: 'OME mail flow rules configured',
		remediationHint: 'Configure OME transport rules for sensitive email',
		portalUrl: 'https://admin.exchange.microsoft.com/#/transportrules',
		autoRemediable: false }),
	d({ id: '3.8.1', title: 'Insider risk management policy',
		description: 'Insider risk policies detect data theft and leaks', severity: 'medium', level: 'L2',
		graphCheck: 'insider_risk_policy', expectedValue: 'At least 1 insider risk policy active',
		remediationHint: 'Create insider risk policy for data theft indicators',
		portalUrl: `${P}/insiderriskmanagement`, autoRemediable: false }),
	d({ id: '3.8.2', title: 'Privileged access management',
		description: 'PAM enforces just-in-time approval for admin tasks', severity: 'medium', level: 'L2',
		graphCheck: 'privileged_access_mgmt', expectedValue: 'PAM enabled with approval policies',
		remediationHint: 'Enable privileged access management in M365 admin center',
		portalUrl: ADM, autoRemediable: false }),
	d({ id: '3.9.1', title: 'Azure Information Protection integration',
		description: 'AIP unified labeling integrates with Purview', severity: 'medium', level: 'L2',
		graphCheck: 'aip_unified_labeling', expectedValue: 'AIP unified labeling activated',
		remediationHint: 'Activate unified labeling in Purview information protection',
		portalUrl: `${C}/informationprotection`, autoRemediable: false }),
];
