export const posts = [
  {
    slug: 'pushci-launch',
    title: 'Show HN: PushCI — Catch broken AI-generated code before production',
    description: 'Cursor PRs, Claude-generated migrations, hallucinated infra changes — PushCI catches them before production. Semantic validation, dependency safety, and infrastructure drift detection in a GitHub Action.',
    date: '2026-05-23',
    author: 'OpenSyber Team',
    readingTime: '6 min read',
    category: 'Product',
  },
  {
    slug: 'ai-code-reviewer-hacked',
    title: 'Your AI Code Reviewer Can Be Hacked With a GitHub Issue',
    description: 'Clinejection exposed npm tokens via a poisoned GitHub issue. PromptPwnd hit 5 Fortune 500 companies through Gemini CLI. The fix: validate AI action configs and scan instruction files.',
    date: '2026-03-28',
    author: 'OpenSyber Team',
    readingTime: '8 min read',
    category: 'Threat Intel',
  },
  {
    slug: 'supply-chain-attack-in-auditor',
    title: 'The Supply Chain Attack Hiding in Your Supply Chain Auditor',
    description: 'The Trivy attack spread transitively through setup-trivy. No existing tool scans the full dependency tree of GitHub Actions. SHA pinning the top-level action is not enough.',
    date: '2026-03-28',
    author: 'OpenSyber Team',
    readingTime: '6 min read',
    category: 'Security',
  },
  {
    slug: 'ai-agents-attacking-ai-agents',
    title: 'AI Agents Are Now Attacking Other AI Agents',
    description: 'An autonomous AI bot powered by Claude Opus spent 10 days scanning GitHub for vulnerable workflows, hitting Microsoft, DataDog, CNCF, and Aqua Security.',
    date: '2026-03-28',
    author: 'OpenSyber Team',
    readingTime: '7 min read',
    category: 'Threat Intel',
  },
  {
    slug: 'github-actions-misconfiguration',
    title: 'The One GitHub Actions Misconfiguration Behind Every Major Supply Chain Attack',
    description: 'Six incidents analyzed: Trivy, tj-actions, Ultralytics, Cline, Checkmarx, ambient-code. The common pattern: pull_request_target running fork code with parent repo secrets.',
    date: '2026-03-28',
    author: 'OpenSyber Team',
    readingTime: '8 min read',
    category: 'Security',
  },
  {
    slug: 'trivy-attack-inevitable',
    title: 'The Trivy Attack Was Inevitable',
    description: 'On March 19, 2026, TeamPCP force-pushed a malicious commit to Trivy GitHub Action. 12-hour blast radius, transitive spread, and stolen VS Code tokens. Mutable tags are broken by design.',
    date: '2026-03-27',
    author: 'OpenSyber Team',
    readingTime: '7 min read',
    category: 'Threat Intel',
  },
  {
    slug: 'github-mutable-tags-broken',
    title: 'GitHub Finally Admits Mutable Tags Are Broken',
    description: 'GitHub announced lockfiles, immutable releases, and egress policy for Actions. But it is a roadmap, not shipped. OpenSyber ships SHA pinning today.',
    date: '2026-03-28',
    author: 'OpenSyber Team',
    readingTime: '6 min read',
    category: 'Security',
  },
  {
    slug: 'gartner-guardian-agents',
    title: 'Gartner Named Our Category: Guardian Agents',
    description: 'The first-ever Gartner Market Guide for Guardian Agents validates the category. OpenSyber is a pure-play provider with full agent security coverage.',
    date: '2026-03-28',
    author: 'OpenSyber Team',
    readingTime: '7 min read',
    category: 'Product',
  },
  {
    slug: 'secure-ai-coding-agents',
    title: 'How to Secure AI Coding Agents: The Complete 2026 Guide',
    description: 'To secure AI coding agents, you need 4 things: runtime isolation, credential encryption, behavior monitoring, and supply chain verification.',
    date: '2026-03-21',
    author: 'OpenSyber Team',
    readingTime: '9 min read',
    category: 'Security',
  },
  {
    slug: 'ai-agent-kill-chain',
    title: 'The AI Agent Kill Chain: How MCP Server Attacks Work in 7 Stages',
    description: 'The 7-stage attack sequence targeting MCP servers — from AI-powered phishing to credential exfiltration. OpenSyber detects 5 of 7 stages today.',
    date: '2026-03-21',
    author: 'OpenSyber Team',
    readingTime: '8 min read',
    category: 'Threat Intel',
  },
  {
    slug: 'slopsquatting-npm-attacks',
    title: 'Slopsquatting: How AI Hallucinated Packages Become npm Attack Vectors',
    description: 'Slopsquatting is an attack where adversaries register npm package names that AI models hallucinate. 4,600 weaponized packages found on npm.',
    date: '2026-03-21',
    author: 'OpenSyber Research',
    readingTime: '7 min read',
    category: 'Threat Intel',
  },
  {
    slug: 'eu-ai-act-compliance-for-agent-platforms',
    title: 'EU AI Act Compliance for Agent Platforms',
    description: 'What the EU AI Act means for teams deploying autonomous AI agents in production.',
    date: '2026-03-19',
    author: 'OpenSyber Team',
    readingTime: '5 min read',
    category: 'Compliance',
  },
  {
    slug: 'mcp-security-best-practices',
    title: 'MCP Security Best Practices for Production Deployments',
    description: 'How to harden Model Context Protocol servers against prompt injection and data exfiltration.',
    date: '2026-03-12',
    author: 'OpenSyber Team',
    readingTime: '7 min read',
    category: 'Engineering',
  },
  {
    slug: 'supply-chain-attacks-targeting-ai-agents',
    title: 'Supply Chain Attacks Targeting AI Agents in 2026',
    description: 'From UNC6426 to CursorJack — how threat actors are exploiting the AI agent ecosystem.',
    date: '2026-03-05',
    author: 'OpenSyber Research',
    readingTime: '8 min read',
    category: 'Threat Intel',
  },
  {
    slug: 'why-self-hosted-ai-agents-are-a-security-risk',
    title: 'Why Self-Hosted AI Agents Are a Security Risk',
    description: 'The hidden dangers of running unmanaged AI coding agents and how to fix them.',
    date: '2026-02-01',
    author: 'OpenSyber Team',
    readingTime: '6 min read',
    category: 'Security',
  },
  {
    slug: 'complete-guide-ai-agent-security',
    title: 'The Complete Guide to AI Agent Security in 2026',
    description: 'Everything you need to know about securing AI agents in production — from runtime isolation to supply chain verification.',
    date: '2026-03-15',
    author: 'OpenSyber Team',
    readingTime: '12 min read',
    category: 'Security',
  },
  {
    slug: 'introducing-opensyber',
    title: 'Introducing OpenSyber: Secure AI Agent Hosting',
    description: 'Why we built OpenSyber and what it means for AI agent security.',
    date: '2026-01-15',
    author: 'OpenSyber Team',
    readingTime: '4 min read',
    category: 'Product',
  },
];
