#!/usr/bin/env node
/**
 * heal-to-fix.mjs — convert heal-proposals.json into /ll-fix prompt bundles.
 *
 * Reads test-results/heal-proposals.json (from browser-heal.mjs) and writes:
 *   test-results/ll-fix-prompts.jsonl     — one prompt per line for claude -p
 *   test-results/ll-fix-batch.sh          — runnable bash invoking claude CLI
 *
 * Optionally pipes first proposal directly via: node heal-to-fix.mjs --pipe
 */

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const REPO = resolve(ROOT, '../..');
const PROPOSALS = resolve(ROOT, 'test-results', 'heal-proposals.json');
const OUT_JSONL = resolve(ROOT, 'test-results', 'll-fix-prompts.jsonl');
const OUT_SHELL = resolve(ROOT, 'test-results', 'll-fix-batch.sh');

const args = new Set(process.argv.slice(2));
const pipeFirst = args.has('--pipe');
const dryRun = args.has('--dry-run');

if (!existsSync(PROPOSALS)) {
    console.error(`[heal-to-fix] ${PROPOSALS} missing — run browser-heal.mjs first`);
    process.exit(1);
}

const data = JSON.parse(readFileSync(PROPOSALS, 'utf8'));
const proposals = data.proposals || [];
const failures = data.failures || [];

if (proposals.length === 0) {
    console.log('[heal-to-fix] no failures to convert — exiting clean');
    process.exit(0);
}

mkdirSync(dirname(OUT_JSONL), { recursive: true });

const prompts = proposals.map((p, i) => {
    const f = failures[i] || {};
    const relPath = f.file ? relative(REPO, resolve(ROOT, f.file)) : 'unknown';
    return {
        id: `heal-${i + 1}`,
        file: relPath,
        title: p.title,
        project: p.project,
        signature: p.signature,
        hint: p.hint,
        prompt: buildPrompt(p, f, relPath),
    };
});

writeFileSync(OUT_JSONL, prompts.map((p) => JSON.stringify(p)).join('\n') + '\n');

const shellLines = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '# Generated by heal-to-fix.mjs — run each /ll-fix invocation in sequence.',
    '# Requires: claude CLI authenticated.',
    '',
];
for (const p of prompts) {
    const safe = p.prompt.replace(/'/g, "'\\''");
    shellLines.push(`echo "--- ${p.id}: ${p.title} ---"`);
    shellLines.push(`claude -p '/ll-fix ${safe}' || echo "ll-fix ${p.id} failed"`);
    shellLines.push('');
}
writeFileSync(OUT_SHELL, shellLines.join('\n'));
execSync(`chmod +x ${OUT_SHELL}`);

console.log(`[heal-to-fix] wrote ${prompts.length} prompt(s)`);
console.log(`  jsonl: ${OUT_JSONL}`);
console.log(`  shell: ${OUT_SHELL}`);

if (pipeFirst && !dryRun) {
    const first = prompts[0];
    console.log(`[heal-to-fix] piping first prompt (${first.id}) to claude -p ...`);
    try {
        execSync(`claude -p '/ll-fix ${first.prompt.replace(/'/g, "'\\''")}'`, { stdio: 'inherit' });
    } catch {
        console.error('[heal-to-fix] claude CLI invocation failed — leaving files for manual run');
        process.exit(1);
    }
}

function buildPrompt(proposal, failure, relPath) {
    const lines = [
        `Browser test failure in ${relPath}.`,
        `Test: "${proposal.title}" (project=${proposal.project})`,
        `Signature: ${proposal.signature || '(no signature)'}`,
        `Hint: ${proposal.hint}`,
    ];
    if (failure.error) lines.push(`Error excerpt: ${failure.error.slice(0, 300)}`);
    lines.push('Fix the failing test or the underlying code. Keep blast radius minimal.');
    return lines.join(' ');
}
