/**
 * OpenSyber Test Configuration
 * Target: opensyber.cloud (production)
 * Generated by Qestro AI Test Engine
 */

export const OPENSYBER = {
  baseURL: process.env.OPENSYBER_URL || 'https://opensyber.cloud',
  tokenforgeURL: process.env.TOKENFORGE_URL || 'https://tokenforge.opensyber.cloud',
  screenshotDir: 'test-results/opensyber',

  /** Test timeouts */
  timeout: {
    navigation: 30_000,
    action: 15_000,
    screenshot: 5_000,
  },

  /** Public pages that should load without auth */
  publicPages: [
    '/',
    '/pricing',
    '/marketplace',
    '/docs',
    '/blog',
    '/demo',
    '/threats',
    '/about',
    '/security',
    '/enterprise',
    '/governance',
    '/compliance',
    '/partners',
    '/privacy',
    '/terms',
    '/sign-in',
    '/sign-up',
    '/compare/opensyber-vs-diy-monitoring',
    '/compare/tokenforge-vs-traditional-sessions',
  ],

  /** Blog articles */
  blogPosts: [
    '/blog/introducing-opensyber',
    '/blog/ai-agent-kill-chain',
    '/blog/complete-guide-ai-agent-security',
    '/blog/ai-agents-attacking-ai-agents',
    '/blog/why-self-hosted-ai-agents-are-a-security-risk',
    '/blog/supply-chain-attacks-targeting-ai-agents',
    '/blog/supply-chain-attack-in-auditor',
    '/blog/slopsquatting-npm-attacks',
    '/blog/trivy-attack-inevitable',
    '/blog/mcp-security-best-practices',
    '/blog/secure-ai-coding-agents',
    '/blog/ai-code-reviewer-hacked',
    '/blog/github-mutable-tags-broken',
    '/blog/github-actions-misconfiguration',
    '/blog/eu-ai-act-compliance-for-agent-platforms',
    '/blog/gartner-guardian-agents',
  ],

  /** Docs pages */
  docPages: [
    '/docs',
    '/docs/getting-started',
    '/docs/security',
    '/docs/skills',
    '/docs/skills/audit-methodology',
    '/docs/api',
    '/docs/oasf',
    '/docs/faq',
  ],

  /** Marketplace skill categories */
  skillCategories: [
    'Security',
    'CI/CD',
    'AI Agents',
    'Alerts',
    'Runtime',
    'Compliance',
    'Infrastructure',
  ],

  /** Dashboard protected routes (require auth) */
  dashboardPages: [
    '/dashboard',
    '/dashboard/agents',
    '/dashboard/agents/activity',
    '/dashboard/skills',
    '/dashboard/marketplace',
    '/dashboard/logs',
    '/dashboard/mcp-monitoring',
    '/dashboard/security',
    '/dashboard/security/alerts',
    '/dashboard/security/vulnerabilities',
    '/dashboard/security/incidents',
    '/dashboard/kill-chain',
    '/dashboard/threat-feed',
    '/dashboard/threat-level',
    '/dashboard/attack-paths',
    '/dashboard/mitre-attack',
    '/dashboard/security/network',
    '/dashboard/security/supply-chain',
    '/dashboard/security/uptime',
    '/dashboard/oasf',
    '/dashboard/soc2',
    '/dashboard/cloud',
    '/dashboard/assets',
    '/dashboard/team',
    '/dashboard/integrations',
    '/dashboard/settings',
    '/dashboard/profile',
  ],

  /** Navigation items expected in header */
  headerNav: [
    'PRICING',
    'SKILLS',
    'DOCS',
    'BLOG',
    'DEMO',
  ],

  /** Pricing plans */
  plans: ['Free', 'Professional', 'Team', 'Enterprise'],

  /** Personas for persona-based testing */
  personas: {
    soloDevSecOps: {
      name: 'Solo DevSecOps',
      description: 'Individual developer securing personal AI agent projects',
      plan: 'Free',
      flows: ['signup', 'deploy-agent', 'view-alerts', 'install-skill', 'view-docs'],
    },
    startupCTO: {
      name: 'Startup CTO',
      description: 'Tech lead evaluating OpenSyber for a 5-person eng team',
      plan: 'Professional',
      flows: ['signup', 'deploy-agent', 'connect-integration', 'view-analytics', 'upgrade-plan'],
    },
    securityEngineer: {
      name: 'Security Engineer',
      description: 'Security professional managing agent fleet and compliance',
      plan: 'Team',
      flows: ['signup', 'deploy-agent', 'configure-policies', 'investigate-incident', 'generate-compliance-report', 'manage-team'],
    },
    enterpriseCISO: {
      name: 'Enterprise CISO',
      description: 'Chief security officer evaluating for enterprise deployment',
      plan: 'Enterprise',
      flows: ['landing-evaluation', 'enterprise-contact', 'security-review', 'compliance-review', 'pricing-review'],
    },
  },
} as const;
