/**
 * Generates a Falco YAML configuration fragment.
 *
 * Output is a partial falco.yaml that an operator drops into
 * `/etc/falco/falco.local.yaml`. It does NOT replace falco.yaml — it
 * only declares:
 *   - rules_files     : which rule packs to load
 *   - rules           : an inline `rules_filter` selecting the curated subset
 *   - http_output     : webhook target for our alerts pipeline
 *   - json_output     : true (so receivers parse structured events)
 *
 * Falco config reference (Apache 2.0):
 *   https://github.com/falcosecurity/falco/blob/master/falco.yaml
 *   https://falco.org/docs/configuration/
 */

import { z } from 'zod';
import { FALCO_RULES, type FalcoRule } from './falco-rules.js';

export const falcoConfigSchema = z.object({
  /** HTTPS webhook URL to POST JSON events to. */
  webhookUrl: z.string().url(),
  /** Optional bearer token sent in `Authorization: Bearer ...` header. */
  webhookBearer: z.string().min(1).optional(),
  /** Rule files to load (relative to /etc/falco). */
  ruleFiles: z.array(z.string().min(1)).min(1).default(['falco_rules.yaml']),
  /** Optional rule-name allow-list. If omitted, all curated rules apply. */
  enabledRuleNames: z.array(z.string().min(1)).optional(),
  /** Optional buffered_outputs setting (default false). */
  buffered: z.boolean().default(false),
});

export type FalcoConfigInput = z.input<typeof falcoConfigSchema>;
export type FalcoConfigOptions = z.output<typeof falcoConfigSchema>;

/**
 * YAML-quote a string. We deliberately stick to a tiny dialect (block
 * scalars + flow-quoted strings) so we never need a runtime YAML lib.
 */
function yamlString(value: string): string {
  // Use double quotes; escape " and \.
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}

function selectedRules(opts: FalcoConfigOptions): FalcoRule[] {
  if (!opts.enabledRuleNames || opts.enabledRuleNames.length === 0) {
    return [...FALCO_RULES];
  }
  const set = new Set(opts.enabledRuleNames);
  return FALCO_RULES.filter((r) => set.has(r.name));
}

/**
 * Build the falco.local.yaml fragment.
 *
 * @throws ZodError if input fails validation.
 */
export function buildFalcoConfig(input: FalcoConfigInput): string {
  const opts = falcoConfigSchema.parse(input);
  const rules = selectedRules(opts);

  const lines: string[] = [];
  lines.push('# Generated by @opensyber/wlp-orchestrator — do not edit by hand');
  lines.push('# Source rules: https://github.com/falcosecurity/rules');
  lines.push('');

  // rules_files block — Falco reads each file in order.
  lines.push('rules_files:');
  for (const f of opts.ruleFiles) {
    lines.push(`  - /etc/falco/${f}`);
  }
  lines.push('');

  // JSON output (required for downstream parsers).
  lines.push('json_output: true');
  lines.push('json_include_output_property: true');
  lines.push(`buffered_outputs: ${opts.buffered ? 'true' : 'false'}`);
  lines.push('');

  // http_output block — POSTs each event as a JSON line.
  lines.push('http_output:');
  lines.push('  enabled: true');
  lines.push(`  url: ${yamlString(opts.webhookUrl)}`);
  if (opts.webhookBearer) {
    lines.push('  user_agent: "falcosecurity/falco"');
    lines.push('  echo: false');
    lines.push('  insecure: false');
    lines.push('  custom_headers:');
    lines.push(
      `    Authorization: ${yamlString(`Bearer ${opts.webhookBearer}`)}`,
    );
  }
  lines.push('');

  // Inline rule reference list — operators can use `rules_filter` in
  // newer Falco builds; for older builds these comments serve as audit.
  lines.push('# Curated rule set (verbatim upstream names):');
  for (const r of rules) {
    lines.push(
      `#   - ${r.name}  [${r.severity}, MITRE ${r.mitreTechnique}]`,
    );
  }
  lines.push('');

  // Priority floor — Falco silently drops events below this priority.
  lines.push('priority: NOTICE');
  lines.push('');

  return lines.join('\n');
}

/**
 * Returns the list of rule names that will be active for the given config.
 * Used by the API for inventory/auditing.
 */
export function activeRuleNames(input: FalcoConfigInput): string[] {
  const opts = falcoConfigSchema.parse(input);
  return selectedRules(opts).map((r) => r.name);
}
