import { describe, it, expect } from 'vitest';
import { buildWazuhAgentConfig, wazuhConfigSchema } from './wazuh-config.js';

const baseInput = { managerAddress: 'wazuh.opensyber.cloud' };

describe('wazuhConfigSchema', () => {
  it('applies defaults', () => {
    const r = wazuhConfigSchema.parse(baseInput);
    expect(r.managerPort).toBe(1514);
    expect(r.protocol).toBe('tcp');
    expect(r.falcoLogPath).toBe('/var/log/falco/events.json');
    expect(r.osqueryLogPath).toBe('/var/log/osquery/osqueryd.results.log');
    expect(r.notifyTime).toBe(10);
    expect(r.timeReconnect).toBe(60);
  });

  it('rejects empty managerAddress', () => {
    expect(wazuhConfigSchema.safeParse({ managerAddress: '' }).success).toBe(
      false,
    );
  });

  it('rejects an obviously-invalid hostname', () => {
    expect(
      wazuhConfigSchema.safeParse({ managerAddress: 'not valid host!' })
        .success,
    ).toBe(false);
  });

  it('accepts an IPv4 address', () => {
    expect(
      wazuhConfigSchema.safeParse({ managerAddress: '10.0.0.1' }).success,
    ).toBe(true);
  });

  it('rejects out-of-range port numbers', () => {
    expect(
      wazuhConfigSchema.safeParse({ ...baseInput, managerPort: 0 }).success,
    ).toBe(false);
    expect(
      wazuhConfigSchema.safeParse({
        ...baseInput,
        managerPort: 70_000,
      }).success,
    ).toBe(false);
  });

  it('rejects unknown protocols', () => {
    expect(
      wazuhConfigSchema.safeParse({ ...baseInput, protocol: 'sctp' }).success,
    ).toBe(false);
  });
});

describe('buildWazuhAgentConfig', () => {
  it('opens with the audit comment and ossec_config root', () => {
    const xml = buildWazuhAgentConfig(baseInput);
    expect(xml).toContain('Generated by @opensyber/wlp-orchestrator');
    expect(xml).toContain('<ossec_config>');
    expect(xml).toContain('</ossec_config>');
  });

  it('writes the manager address and port into the client block', () => {
    const xml = buildWazuhAgentConfig({
      managerAddress: 'wazuh.example.test',
      managerPort: 1515,
    });
    expect(xml).toContain('<address>wazuh.example.test</address>');
    expect(xml).toContain('<port>1515</port>');
  });

  it('uses the configured protocol', () => {
    const xml = buildWazuhAgentConfig({ ...baseInput, protocol: 'udp' });
    expect(xml).toContain('<protocol>udp</protocol>');
  });

  it('XML-escapes &, <, > in the labels and paths', () => {
    const xml = buildWazuhAgentConfig({
      ...baseInput,
      labels: { 'env"': 'a&b<c>d' },
      falcoLogPath: '/log/falco<events>.json',
    });
    expect(xml).toContain('a&amp;b&lt;c&gt;d');
    expect(xml).toContain('/log/falco&lt;events&gt;.json');
    // attribute escaping: " becomes &quot;
    expect(xml).toContain('key="env&quot;"');
  });

  it('omits <labels> when no labels are supplied', () => {
    const xml = buildWazuhAgentConfig(baseInput);
    expect(xml).not.toContain('<labels>');
  });

  it('emits two <localfile> blocks for falco + osquery logs', () => {
    const xml = buildWazuhAgentConfig(baseInput);
    const localfileCount = (xml.match(/<localfile>/g) ?? []).length;
    expect(localfileCount).toBe(2);
    expect(xml).toContain('<location>/var/log/falco/events.json</location>');
    expect(xml).toContain(
      '<location>/var/log/osquery/osqueryd.results.log</location>',
    );
  });

  it('honours custom falcoLogPath and osqueryLogPath', () => {
    const xml = buildWazuhAgentConfig({
      ...baseInput,
      falcoLogPath: '/srv/falco.json',
      osqueryLogPath: '/srv/osquery.log',
    });
    expect(xml).toContain('<location>/srv/falco.json</location>');
    expect(xml).toContain('<location>/srv/osquery.log</location>');
  });

  it('writes notify_time and time-reconnect from input', () => {
    const xml = buildWazuhAgentConfig({
      ...baseInput,
      notifyTime: 30,
      timeReconnect: 600,
    });
    expect(xml).toContain('<notify_time>30</notify_time>');
    expect(xml).toContain('<time-reconnect>600</time-reconnect>');
  });

  it('always sets crypto_method=aes and auto_restart=yes', () => {
    const xml = buildWazuhAgentConfig(baseInput);
    expect(xml).toContain('<crypto_method>aes</crypto_method>');
    expect(xml).toContain('<auto_restart>yes</auto_restart>');
  });
});
