/**
 * Generates a Wazuh agent ossec.conf fragment.
 *
 * The generated XML is a `<ossec_config>` block with:
 *   - <client>      : manager address + protocol
 *   - <localfile>   : tail Falco JSON output + osquery results
 *   - <labels>      : tenant + agent metadata for filtering on the manager
 *
 * Wazuh configuration reference (GPL v2):
 *   https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/
 *   https://github.com/wazuh/wazuh/blob/main/etc/ossec.conf
 *
 * The agent ships Falco events to the manager via the `json` log_format.
 * Decoders for Falco/osquery JSON are configured on the MANAGER side and
 * are out of scope for the agent fragment.
 */

import { z } from 'zod';

const HOSTNAME_RE = /^[a-zA-Z0-9](?:[a-zA-Z0-9.-]{0,253}[a-zA-Z0-9])?$/;

export const wazuhConfigSchema = z.object({
  /** Wazuh manager hostname or IPv4. */
  managerAddress: z
    .string()
    .min(1)
    .max(255)
    .regex(HOSTNAME_RE, 'managerAddress must be a hostname or IPv4'),
  /** Manager listening port (default 1514). */
  managerPort: z.number().int().min(1).max(65_535).default(1514),
  /** Transport protocol — Wazuh supports tcp or udp. */
  protocol: z.enum(['tcp', 'udp']).default('tcp'),
  /** Path to Falco JSON output file (read by localfile). */
  falcoLogPath: z.string().min(1).default('/var/log/falco/events.json'),
  /** Path to osquery results.log. */
  osqueryLogPath: z
    .string()
    .min(1)
    .default('/var/log/osquery/osqueryd.results.log'),
  /** Agent labels — surfaced in every event for tenant filtering. */
  labels: z.record(z.string(), z.string()).default({}),
  /** Notify time (seconds) — heartbeat to manager. */
  notifyTime: z.number().int().min(10).max(3600).default(10),
  /** Time-reconnect after notify-time elapses (seconds). */
  timeReconnect: z.number().int().min(10).max(86_400).default(60),
});

export type WazuhConfigInput = z.input<typeof wazuhConfigSchema>;
export type WazuhConfigOptions = z.output<typeof wazuhConfigSchema>;

/** XML-escape a text node. */
function xmlText(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/** XML-escape an attribute value. */
function xmlAttr(value: string): string {
  return xmlText(value).replace(/"/g, '&quot;');
}

/** Indent every line of a block by N spaces. */
function indent(block: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return block
    .split('\n')
    .map((l) => (l.length ? pad + l : l))
    .join('\n');
}

/** Builds the agent-side ossec.conf fragment as XML. */
export function buildWazuhAgentConfig(input: WazuhConfigInput): string {
  const opts = wazuhConfigSchema.parse(input);

  const client = [
    '<client>',
    '  <server>',
    `    <address>${xmlText(opts.managerAddress)}</address>`,
    `    <port>${opts.managerPort}</port>`,
    `    <protocol>${opts.protocol}</protocol>`,
    '  </server>',
    `  <notify_time>${opts.notifyTime}</notify_time>`,
    `  <time-reconnect>${opts.timeReconnect}</time-reconnect>`,
    '  <auto_restart>yes</auto_restart>',
    '  <crypto_method>aes</crypto_method>',
    '</client>',
  ].join('\n');

  const labels = Object.keys(opts.labels).length
    ? [
        '<labels>',
        ...Object.entries(opts.labels).map(
          ([k, v]) =>
            `  <label key="${xmlAttr(k)}">${xmlText(v)}</label>`,
        ),
        '</labels>',
      ].join('\n')
    : '';

  const falcoTail = [
    '<localfile>',
    '  <log_format>json</log_format>',
    `  <location>${xmlText(opts.falcoLogPath)}</location>`,
    '</localfile>',
  ].join('\n');

  const osqueryTail = [
    '<localfile>',
    '  <log_format>json</log_format>',
    `  <location>${xmlText(opts.osqueryLogPath)}</location>`,
    '</localfile>',
  ].join('\n');

  const sections = [client, labels, falcoTail, osqueryTail].filter(Boolean);

  const body = sections.map((s) => indent(s, 2)).join('\n\n');

  return [
    '<!--',
    '  Generated by @opensyber/wlp-orchestrator.',
    '  Drop into /var/ossec/etc/ossec.conf as part of the <ossec_config> block.',
    '  Source: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/',
    '-->',
    '<ossec_config>',
    body,
    '</ossec_config>',
    '',
  ].join('\n');
}
