apiVersion: v1
kind: Namespace
metadata:
  name: questro-prod
  labels:
    name: questro-prod
    environment: production
    project: questro
    managed-by: questro-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: questro-monitoring
  labels:
    name: questro-monitoring
    environment: production
    project: questro
    managed-by: questro-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: questro-logging
  labels:
    name: questro-logging
    environment: production
    project: questro
    managed-by: questro-platform