/**
 * Sync TenantIQ alerts → ConnectWise Service Tickets.
 * Creates tickets for new critical/high alerts, updates status on resolution.
 */
import type { ConnectWiseClient } from './client';
import type { SyncResult } from '../base/types';
import { SEVERITY_MAP } from '../base/types';
import { measureSync } from '../base/provider';

export interface Alert {
	id: string;
	title: string;
	description: string;
	severity: 'critical' | 'high' | 'medium' | 'low';
	status: 'active' | 'acknowledged' | 'resolved' | 'dismissed';
	tenantId: string;
	createdAt: string;
}

export interface TicketSyncDeps {
	client: ConnectWiseClient;
	integrationId: string;
	/** Unsynced alerts to create as tickets */
	alerts: Alert[];
	/** Resolved alerts that have existing tickets */
	resolvedAlerts: { alertId: string; ticketId: string }[];
	/** tenantId → CW companyId mapping */
	tenantToCompany: Map<string, string>;
	/** Save ticket mapping */
	saveMapping: (alertId: string, ticketId: string) => Promise<void>;
}

export async function syncTickets(deps: TicketSyncDeps): Promise<SyncResult> {
	return measureSync('connectwise', 'alert', async () => {
		const { client, alerts, resolvedAlerts, tenantToCompany, saveMapping } = deps;
		let created = 0;
		let updated = 0;
		let failed = 0;
		const errors: string[] = [];

		// Create tickets for new alerts
		for (const alert of alerts) {
			try {
				const companyId = tenantToCompany.get(alert.tenantId);
				if (!companyId) {
					failed++;
					errors.push(`Alert ${alert.id}: tenant ${alert.tenantId} not mapped to CW company`);
					continue;
				}

				const ticket = await client.createTicket({
					summary: `[TenantIQ] ${alert.title}`,
					description: formatTicketDescription(alert),
					priority: SEVERITY_MAP[alert.severity].connectwise,
					status: 'New',
					companyId,
				});

				await saveMapping(alert.id, ticket.id);
				created++;
			} catch (e) {
				failed++;
				errors.push(`Alert ${alert.id}: ${e instanceof Error ? e.message : 'Failed'}`);
			}
		}

		// Update resolved alerts → close tickets
		for (const { alertId, ticketId } of resolvedAlerts) {
			try {
				await client.updateTicket(ticketId, { status: 'Closed' });
				await client.addTicketNote(ticketId, 'Resolved automatically by TenantIQ');
				updated++;
			} catch (e) {
				failed++;
				errors.push(`Close ticket ${ticketId} for alert ${alertId}: ${e instanceof Error ? e.message : 'Failed'}`);
			}
		}

		return { created, updated, failed, errors };
	});
}

function formatTicketDescription(alert: Alert): string {
	return [
		`Severity: ${alert.severity.toUpperCase()}`,
		`Status: ${alert.status}`,
		`Detected: ${alert.createdAt}`,
		'',
		alert.description,
		'',
		'— Generated by TenantIQ Security Platform',
	].join('\n');
}
