'use strict';

import { Router, Request, Response } from 'express';
import { authenticate, requireRole } from '../../../middleware/authenticate.js';
import { AuditLogger } from '../AuditLogger.js';
import { AuditFilter } from '../types.js';
import { logger } from '../../../utils/logger.js';

const router = Router();
const auditLogger = new AuditLogger();

/**
 * GET /api/audit/logs
 * Query audit logs (admin only)
 */
router.get('/logs', authenticate, requireRole('admin'), async (req: Request, res: Response): Promise<void> => {
  try {
    const filter: AuditFilter = {
      userId: req.query.userId as string | undefined,
      projectId: req.query.projectId as string | undefined,
      action: req.query.action as any,
      category: req.query.category as any,
      status: req.query.status as 'success' | 'failure' | undefined,
      limit: parseInt(req.query.limit as string) || 100,
      offset: parseInt(req.query.offset as string) || 0,
    };

    if (req.query.startDate) {
      filter.startDate = new Date(req.query.startDate as string);
    }
    if (req.query.endDate) {
      filter.endDate = new Date(req.query.endDate as string);
    }

    const result = await auditLogger.query(filter);

    logger.info(
      `Audit logs queried by ${req.user?.userId}: ${result.entries.length} entries`
    );

    res.json({
      count: result.entries.length,
      total: result.total,
      limit: result.limit,
      offset: result.offset,
      entries: result.entries.map((e) => ({
        id: e.id,
        timestamp: e.timestamp,
        userId: e.userId,
        email: e.userEmail,
        action: e.action,
        category: e.category,
        projectId: e.projectId,
        status: e.status,
        ipAddress: e.ipAddress,
        description: e.description,
        errorMessage: e.errorMessage,
      })),
    });
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Unknown error';
    logger.error(`Failed to query audit logs: ${msg}`);
    res.status(500).json({ error: msg });
  }
});

/**
 * GET /api/audit/users/:userId/activity
 * Get user activity
 */
router.get(
  '/users/:userId/activity',
  authenticate,
  async (req: Request, res: Response): Promise<void> => {
    try {
      if (!req.user) {
        res.status(401).json({ error: 'Authentication required' });
        return;
      }

      const userId = req.params.userId;
      const days = parseInt(req.query.days as string) || 30;

      // Users can only view their own activity unless admin
      if (req.user.userId !== userId && req.user.role !== 'admin') {
        res.status(403).json({ error: 'Insufficient permissions' });
        return;
      }

      const activities = await auditLogger.getUserActivity(userId, days);
      const stats = await auditLogger.getUserStats(userId);

      logger.info(
        `User activity viewed for ${userId} by ${req.user.userId}`
      );

      res.json({
        userId,
        period: `Last ${days} days`,
        stats,
        count: activities.length,
        activities: activities.map((a) => ({
          id: a.id,
          timestamp: a.timestamp,
          action: a.action,
          category: a.category,
          status: a.status,
          description: a.description,
          projectId: a.projectId,
        })),
      });
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown error';
      logger.error(`Failed to get user activity: ${msg}`);
      res.status(500).json({ error: msg });
    }
  }
);

/**
 * GET /api/audit/compliance-report
 * Generate compliance report (admin only)
 */
router.get(
  '/compliance-report',
  authenticate,
  requireRole('admin'),
  async (req: Request, res: Response): Promise<void> => {
    try {
      if (!req.user) {
        res.status(401).json({ error: 'Authentication required' });
        return;
      }

      const startDate = req.query.startDate
        ? new Date(req.query.startDate as string)
        : new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
      const endDate = req.query.endDate
        ? new Date(req.query.endDate as string)
        : new Date();
      const organizationId = req.query.organizationId as string || 'default';

      const report = await auditLogger.generateComplianceReport(
        organizationId,
        startDate,
        endDate,
        req.user.userId
      );

      logger.info(
        `Compliance report generated by ${req.user.userId} for period ${startDate.toISOString()} to ${endDate.toISOString()}`
      );

      res.json(report);
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown error';
      logger.error(`Failed to generate compliance report: ${msg}`);
      res.status(500).json({ error: msg });
    }
  }
);

/**
 * GET /api/audit/export
 * Export audit logs as CSV (admin only)
 */
router.get(
  '/export',
  authenticate,
  requireRole('admin'),
  async (req: Request, res: Response): Promise<void> => {
    try {
      if (!req.user) {
        res.status(401).json({ error: 'Authentication required' });
        return;
      }

      const filter: AuditFilter = {
        userId: req.query.userId as string | undefined,
        projectId: req.query.projectId as string | undefined,
        action: req.query.action as any,
        category: req.query.category as any,
        status: req.query.status as 'success' | 'failure' | undefined,
      };

      if (req.query.startDate) {
        filter.startDate = new Date(req.query.startDate as string);
      }
      if (req.query.endDate) {
        filter.endDate = new Date(req.query.endDate as string);
      }

      const csv = await auditLogger.exportToCSV(filter);

      logger.info(
        `Audit logs exported by ${req.user.userId}`
      );

      res.header('Content-Type', 'text/csv');
      res.header('Content-Disposition', `attachment; filename="audit-logs-${Date.now()}.csv"`);
      res.send(csv);
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown error';
      logger.error(`Failed to export audit logs: ${msg}`);
      res.status(500).json({ error: msg });
    }
  }
);

/**
 * POST /api/audit/log
 * Manually log an action (internal use)
 */
router.post('/log', async (req: Request, res: Response): Promise<void> => {
  try {
    const {
      userId,
      userEmail,
      action,
      category,
      projectId,
      resourceId,
      resourceType,
      description,
      ipAddress,
      userAgent,
      status,
      errorMessage,
      metadata,
    } = req.body;

    if (!userId || !action || !category || !description) {
      res.status(400).json({
        error: 'userId, action, category, description are required',
      });
      return;
    }

    const entry = await auditLogger.log({
      userId,
      userEmail,
      action,
      category,
      projectId,
      resourceId,
      resourceType,
      description,
      ipAddress: ipAddress || 'internal',
      userAgent: userAgent || 'internal',
      status: status || 'success',
      errorMessage,
      metadata,
    });

    res.status(201).json({
      id: entry.id,
      timestamp: entry.timestamp,
      message: 'Audit entry logged',
    });
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Unknown error';
    logger.error(`Failed to log audit entry: ${msg}`);
    res.status(500).json({ error: msg });
  }
});

/**
 * GET /api/audit/stats
 * Get audit statistics (admin only)
 */
router.get('/stats', authenticate, requireRole('admin'), async (req: Request, res: Response): Promise<void> => {
  try {
    const userId = req.query.userId as string | undefined;

    if (userId) {
      const stats = await auditLogger.getUserStats(userId);
      res.json({ userId, stats });
    } else {
      res.status(400).json({ error: 'userId query parameter required' });
    }
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Unknown error';
    logger.error(`Failed to get audit stats: ${msg}`);
    res.status(500).json({ error: msg });
  }
});

export default router;
