#!/usr/bin/env python3
"""
Prometheus Text Exposition Exporter

Formats counters, gauges, and histograms for Prometheus scraping.
"""

from collections import defaultdict
from typing import Dict, List, Optional, Tuple


def label_key(labels: Optional[Dict[str, str]]) -> str:
    """Create a stable string key from a label dict for bucketing."""
    if not labels:
        return ""
    return ",".join(f'{k}="{v}"' for k, v in sorted(labels.items()))


def format_labels(labels: Optional[Dict[str, str]]) -> str:
    """Format labels for Prometheus text exposition."""
    if not labels:
        return ""
    inner = ",".join(f'{k}="{v}"' for k, v in sorted(labels.items()))
    return "{" + inner + "}"


# Standard metric definitions for FinSavvyAI
METRIC_DEFINITIONS: Dict[str, Tuple[str, str]] = {
    # Counters
    "requests_total": ("counter", "Total number of HTTP requests received"),
    "responses_total": ("counter", "Total number of HTTP responses sent"),
    "errors_total": ("counter", "Total number of errors"),
    "completions_success": ("counter", "Total successful chat completions"),
    "completions_failed": ("counter", "Total failed chat completions"),
    "auth_attempts_total": ("counter", "Total authentication attempts"),
    "auth_failures_total": ("counter", "Total authentication failures"),
    "rate_limit_hits_total": ("counter", "Total rate limit rejections"),
    "circuit_breaker_trips_total": ("counter", "Total circuit breaker trips"),
    "heartbeats_total": ("counter", "Total heartbeats processed"),
    "node_registrations_total": ("counter", "Total node registrations"),
    "model_loads_total": ("counter", "Total model load operations"),
    "model_unloads_total": ("counter", "Total model unload operations"),
    "tokens_generated_total": ("counter", "Total tokens generated by inference"),
    "audit_events_total": ("counter", "Total audit events recorded"),
    # Gauges
    "active_connections": ("gauge", "Number of active connections"),
    "cluster_nodes_online": ("gauge", "Number of online cluster nodes"),
    "cluster_nodes_total": ("gauge", "Total number of cluster nodes"),
    "models_loaded": ("gauge", "Number of models currently loaded"),
    "queue_depth": ("gauge", "Current request queue depth"),
    "worker_load": ("gauge", "Current worker load (0-10)"),
    "memory_usage_bytes": ("gauge", "Current memory usage in bytes"),
    "cpu_usage_percent": ("gauge", "Current CPU usage percentage"),
    "uptime_seconds": ("gauge", "Service uptime in seconds"),
    # Histograms
    "request_duration_seconds": ("histogram", "Request duration in seconds"),
    "inference_duration_seconds": ("histogram", "Model inference duration in seconds"),
    "model_load_duration_seconds": ("histogram", "Model loading duration in seconds"),
    "heartbeat_latency_seconds": ("histogram", "Heartbeat round-trip latency in seconds"),
}

# Prometheus histogram buckets
DEFAULT_BUCKETS: List[float] = [
    0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0,
]


def export_prometheus_format(
    counters: Dict[Tuple[str, str], float],
    counter_labels: Dict[Tuple[str, str], Dict[str, str]],
    gauges: Dict[Tuple[str, str], float],
    gauge_labels: Dict[Tuple[str, str], Dict[str, str]],
    histograms: Dict[Tuple[str, str], List[float]],
    histogram_labels: Dict[Tuple[str, str], Dict[str, str]],
) -> str:
    """Export metrics in Prometheus text exposition format (v0.0.4)."""
    lines: List[str] = []
    seen_help: set = set()

    # --- counters ---
    for (name, lk), value in sorted(counters.items()):
        prom_name = f"finsavvyai_{name}"
        if prom_name not in seen_help:
            seen_help.add(prom_name)
            defn = METRIC_DEFINITIONS.get(name)
            help_text = defn[1] if defn else f"Counter {name}"
            lines.append(f"# HELP {prom_name} {help_text}")
            lines.append(f"# TYPE {prom_name} counter")
        labels = counter_labels.get((name, lk), {})
        lines.append(f"{prom_name}{format_labels(labels)} {value}")

    # --- gauges ---
    for (name, lk), value in sorted(gauges.items()):
        prom_name = f"finsavvyai_{name}"
        if prom_name not in seen_help:
            seen_help.add(prom_name)
            defn = METRIC_DEFINITIONS.get(name)
            help_text = defn[1] if defn else f"Gauge {name}"
            lines.append(f"# HELP {prom_name} {help_text}")
            lines.append(f"# TYPE {prom_name} gauge")
        labels = gauge_labels.get((name, lk), {})
        lines.append(f"{prom_name}{format_labels(labels)} {value}")

    # --- histograms ---
    histo_by_name: Dict[str, List[Tuple[str, Dict[str, str], List[float]]]] = (
        defaultdict(list)
    )
    for (name, lk), values in histograms.items():
        labels = histogram_labels.get((name, lk), {})
        histo_by_name[name].append((lk, labels, values))

    for name in sorted(histo_by_name.keys()):
        prom_name = f"finsavvyai_{name}"
        if prom_name not in seen_help:
            seen_help.add(prom_name)
            defn = METRIC_DEFINITIONS.get(name)
            help_text = defn[1] if defn else f"Histogram {name}"
            lines.append(f"# HELP {prom_name} {help_text}")
            lines.append(f"# TYPE {prom_name} histogram")

        for _lk, labels, values in histo_by_name[name]:
            sorted_values = sorted(values)
            total = sum(values)
            count = len(values)

            for bound in DEFAULT_BUCKETS:
                bucket_count = sum(1 for v in sorted_values if v <= bound)
                bucket_labels = {**labels, "le": str(bound)}
                lines.append(
                    f"{prom_name}_bucket{format_labels(bucket_labels)} {bucket_count}"
                )
            inf_labels = {**labels, "le": "+Inf"}
            lines.append(f"{prom_name}_bucket{format_labels(inf_labels)} {count}")
            lines.append(f"{prom_name}_sum{format_labels(labels)} {total}")
            lines.append(f"{prom_name}_count{format_labels(labels)} {count}")

    return "\n".join(lines) + "\n"
