#!/usr/bin/env bash
# refresh-llamafile-checksums.sh
#
# Fetches SHA256 sums for the latest N llamafile releases from GitHub and
# emits a Go map literal you can paste into KnownLlamafileSHA256 in
# internal/clawpipe/llamafile_checksums.go.
#
# Usage:  scripts/refresh-llamafile-checksums.sh [count]
#         scripts/refresh-llamafile-checksums.sh 3
#
# Requires: curl, jq, sha256sum (or shasum on macOS).

set -euo pipefail

COUNT="${1:-3}"
REPO="Mozilla-Ocho/llamafile"
API="https://api.github.com/repos/${REPO}/releases?per_page=${COUNT}"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi

if command -v sha256sum >/dev/null 2>&1; then
  HASHER=(sha256sum)
elif command -v shasum >/dev/null 2>&1; then
  HASHER=(shasum -a 256)
else
  echo "sha256sum or shasum required" >&2
  exit 1
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "// Generated by scripts/refresh-llamafile-checksums.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "// Source: https://github.com/${REPO}/releases"
echo "var KnownLlamafileSHA256 = map[string]string{"

curl -fsSL "$API" \
  | jq -r '.[] | .assets[] | select(.name|test("^llamafile")) | "\(.name)\t\(.browser_download_url)"' \
  | while IFS=$'\t' read -r name url; do
      out="$TMP/$name"
      curl -fsSL -o "$out" "$url"
      sum="$(${HASHER[@]} "$out" | awk '{print $1}')"
      printf '\t%q: %q,\n' "$name" "$sum"
    done

echo "}"
