//go:build ignore

package main

// demoConnections returns the 4 demo connection payloads.
func demoConnections() []map[string]interface{} {
	return []map[string]interface{}{
		{
			"name":     "github-prod",
			"platform": "github",
			"token":    "DEMO_GITHUB_TOKEN_NOT_REAL",
		},
		{
			"name":     "gitlab-staging",
			"platform": "gitlab",
			"token":    "DEMO_GITLAB_TOKEN_NOT_REAL",
			"base_url": "https://gitlab.com",
		},
		{
			"name":         "bitbucket-ci",
			"platform":     "bitbucket",
			"username":     "demo-user",
			"app_password": "demo_app_password_placeholder",
		},
		{
			"name":     "jenkins-internal",
			"platform": "jenkins",
			"token":    "jenkins_demo_api_token",
			"base_url": "https://jenkins.example.internal",
		},
	}
}

// demoFindings returns 20 realistic security findings.
func demoFindings() []map[string]interface{} {
	return []map[string]interface{}{
		// Critical (3)
		{
			"connection_name": "github-prod",
			"run_id":          "run-001",
			"severity":        "critical",
			"category":        "secret-exposure",
			"title":           "AWS access key exposed in workflow env",
			"description":     "AKIA* key found hardcoded in .github/workflows/deploy.yml environment block.",
			"remediation":     "Remove from workflow, rotate key, use GitHub Secrets instead.",
			"file":            ".github/workflows/deploy.yml",
			"line":            42,
			"confidence":      0.98,
			"status":          "open",
		},
		{
			"connection_name": "gitlab-staging",
			"run_id":          "run-002",
			"severity":        "critical",
			"category":        "secret-exposure",
			"title":           "GitLab personal access token hardcoded",
			"description":     "glpat- token found in .gitlab-ci.yml script block.",
			"remediation":     "Move to GitLab CI/CD Variables (masked).",
			"file":            ".gitlab-ci.yml",
			"line":            17,
			"confidence":      0.97,
			"status":          "open",
		},
		{
			"connection_name": "jenkins-internal",
			"run_id":          "run-003",
			"severity":        "critical",
			"category":        "supply-chain",
			"title":           "curl | bash pattern detected in Jenkinsfile",
			"description":     "Piping untrusted remote script directly to bash without checksum verification.",
			"remediation":     "Pin the script version and verify SHA256 before execution.",
			"file":            "Jenkinsfile",
			"line":            88,
			"confidence":      0.95,
			"status":          "open",
		},
		// High (5)
		{
			"connection_name": "github-prod",
			"run_id":          "run-004",
			"severity":        "high",
			"category":        "supply-chain",
			"title":           "GitHub Actions not SHA-pinned",
			"description":     "actions/checkout@v4 used without full commit SHA pinning.",
			"remediation":     "Pin to full SHA: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683",
			"file":            ".github/workflows/ci.yml",
			"line":            12,
			"confidence":      0.92,
			"status":          "open",
		},
		{
			"connection_name": "github-prod",
			"run_id":          "run-004",
			"severity":        "high",
			"category":        "supply-chain",
			"title":           "Third-party action from unverified publisher",
			"description":     "uses: some-user/some-action@v1 — publisher has no verified badge.",
			"remediation":     "Audit action source, fork to org, or replace with official equivalent.",
			"file":            ".github/workflows/release.yml",
			"line":            35,
			"confidence":      0.88,
			"status":          "open",
		},
		{
			"connection_name": "bitbucket-ci",
			"run_id":          "run-005",
			"severity":        "high",
			"category":        "container-security",
			"title":           "Docker image pulled with :latest tag",
			"description":     "node:latest used in bitbucket-pipelines.yml — not reproducible.",
			"remediation":     "Pin to specific digest: node:20.14.0@sha256:...",
			"file":            "bitbucket-pipelines.yml",
			"line":            8,
			"confidence":      0.91,
			"status":          "suppressed",
		},
		{
			"connection_name": "gitlab-staging",
			"run_id":          "run-006",
			"severity":        "high",
			"category":        "policy",
			"title":           "SAST stage missing from pipeline",
			"description":     "No static analysis stage detected. OPA policy require-sast violated.",
			"remediation":     "Add a SAST stage using gitlab-org/security-reports or semgrep.",
			"file":            ".gitlab-ci.yml",
			"line":            1,
			"confidence":      0.99,
			"status":          "open",
		},
		{
			"connection_name": "jenkins-internal",
			"run_id":          "run-007",
			"severity":        "high",
			"category":        "secret-exposure",
			"title":           "Slack webhook URL in plaintext",
			"description":     "https://hooks.slack.com/services/... found in pipeline environment.",
			"remediation":     "Store in Jenkins Credentials Store and inject via withCredentials.",
			"file":            "Jenkinsfile",
			"line":            54,
			"confidence":      0.93,
			"status":          "resolved",
		},
		// Medium (7)
		{
			"connection_name": "github-prod",
			"run_id":          "run-008",
			"severity":        "medium",
			"category":        "policy",
			"title":           "No test stage in workflow",
			"description":     "CI workflow does not include a test job. Policy require-tests violated.",
			"remediation":     "Add a jobs.test step that runs the test suite before deploy.",
			"file":            ".github/workflows/deploy.yml",
			"line":            1,
			"confidence":      0.87,
			"status":          "open",
		},
		{
			"connection_name": "github-prod",
			"run_id":          "run-008",
			"severity":        "medium",
			"category":        "container-security",
			"title":           "Container runs as root",
			"description":     "Dockerfile does not set a non-root USER instruction.",
			"remediation":     "Add USER nonroot or USER 1001 after package installation.",
			"file":            "Dockerfile",
			"line":            18,
			"confidence":      0.85,
			"status":          "open",
		},
		{
			"connection_name": "gitlab-staging",
			"run_id":          "run-009",
			"severity":        "medium",
			"category":        "supply-chain",
			"title":           "npm install without lockfile",
			"description":     "npm install used without --frozen-lockfile; versions may drift.",
			"remediation":     "Use npm ci or add --frozen-lockfile to prevent version drift.",
			"file":            ".gitlab-ci.yml",
			"line":            24,
			"confidence":      0.80,
			"status":          "open",
		},
		{
			"connection_name": "bitbucket-ci",
			"run_id":          "run-010",
			"severity":        "medium",
			"category":        "policy",
			"title":           "Dependency vulnerability scan missing",
			"description":     "No dependency audit step (npm audit / trivy) in pipeline.",
			"remediation":     "Add a vulnerability scan stage before deploy.",
			"file":            "bitbucket-pipelines.yml",
			"line":            1,
			"confidence":      0.84,
			"status":          "open",
		},
		{
			"connection_name": "jenkins-internal",
			"run_id":          "run-011",
			"severity":        "medium",
			"category":        "secret-exposure",
			"title":           "SSH private key path referenced in script",
			"description":     "~/.ssh/id_rsa referenced directly; key may be world-readable.",
			"remediation":     "Use ssh-agent plugin and inject key via credentials binding.",
			"file":            "Jenkinsfile",
			"line":            71,
			"confidence":      0.78,
			"status":          "open",
		},
		{
			"connection_name": "github-prod",
			"run_id":          "run-012",
			"severity":        "medium",
			"category":        "container-security",
			"title":           "Multi-stage build not used",
			"description":     "Single-stage Dockerfile includes build tools in runtime image.",
			"remediation":     "Use multi-stage build to separate build and runtime layers.",
			"file":            "Dockerfile",
			"line":            1,
			"confidence":      0.75,
			"status":          "resolved",
		},
		{
			"connection_name": "gitlab-staging",
			"run_id":          "run-013",
			"severity":        "medium",
			"category":        "policy",
			"title":           "Pipeline runs on unprotected branch",
			"description":     "Deployment job triggers on feature/* branches without approval gate.",
			"remediation":     "Add environment: production with required_approvals: 1.",
			"file":            ".gitlab-ci.yml",
			"line":            61,
			"confidence":      0.82,
			"status":          "open",
		},
		// Low (5)
		{
			"connection_name": "github-prod",
			"run_id":          "run-014",
			"severity":        "low",
			"category":        "policy",
			"title":           "Workflow timeout not set",
			"description":     "No timeout-minutes set; runaway jobs can exhaust minutes quota.",
			"remediation":     "Add timeout-minutes: 30 to each job.",
			"file":            ".github/workflows/ci.yml",
			"line":            7,
			"confidence":      0.70,
			"status":          "open",
		},
		{
			"connection_name": "bitbucket-ci",
			"run_id":          "run-015",
			"severity":        "low",
			"category":        "supply-chain",
			"title":           "Pipe version not pinned",
			"description":     "atlassian/aws-s3-deploy:1 used without SHA digest.",
			"remediation":     "Pin Bitbucket Pipe to full SHA for reproducibility.",
			"file":            "bitbucket-pipelines.yml",
			"line":            22,
			"confidence":      0.65,
			"status":          "suppressed",
		},
		{
			"connection_name": "gitlab-staging",
			"run_id":          "run-016",
			"severity":        "low",
			"category":        "policy",
			"title":           "Cache key too broad",
			"description":     "Cache key uses only $CI_COMMIT_BRANCH; may serve stale artifacts.",
			"remediation":     "Include lockfile hash: $CI_COMMIT_BRANCH-${MD5_LOCK}.",
			"file":            ".gitlab-ci.yml",
			"line":            11,
			"confidence":      0.60,
			"status":          "open",
		},
		{
			"connection_name": "jenkins-internal",
			"run_id":          "run-017",
			"severity":        "low",
			"category":        "container-security",
			"title":           "HEALTHCHECK not defined in Dockerfile",
			"description":     "No HEALTHCHECK instruction; orchestrators cannot auto-restart unhealthy containers.",
			"remediation":     "Add HEALTHCHECK CMD curl -f http://localhost:8080/health || exit 1",
			"file":            "Dockerfile",
			"line":            1,
			"confidence":      0.58,
			"status":          "open",
		},
		{
			"connection_name": "github-prod",
			"run_id":          "run-018",
			"severity":        "low",
			"category":        "policy",
			"title":           "Verbose logging enabled in production job",
			"description":     "ACTIONS_STEP_DEBUG=true leaks secrets in log output.",
			"remediation":     "Remove debug variable from production workflow or scope to dev only.",
			"file":            ".github/workflows/deploy.yml",
			"line":            5,
			"confidence":      0.62,
			"status":          "resolved",
		},
	}
}

// demoAuditEntries returns 5 realistic audit log entries.
func demoAuditEntries() []map[string]interface{} {
	return []map[string]interface{}{
		{
			"action":        "connection_added",
			"actor":         "admin@example.com",
			"resource":      "github-prod",
			"resource_type": "connection",
			"details":       map[string]string{"platform": "github"},
		},
		{
			"action":        "scan_completed",
			"actor":         "system",
			"resource":      "github-prod",
			"resource_type": "connection",
			"details":       map[string]string{"findings": "8", "duration_ms": "1240"},
		},
		{
			"action":        "finding_suppressed",
			"actor":         "dev@example.com",
			"resource":      "bitbucket-ci",
			"resource_type": "finding",
			"details":       map[string]string{"reason": "false_positive", "finding_id": "3"},
		},
		{
			"action":        "schedule_set",
			"actor":         "admin@example.com",
			"resource":      "github-prod",
			"resource_type": "schedule",
			"details":       map[string]string{"cron_expr": "0 */6 * * *"},
		},
		{
			"action":        "connection_tested",
			"actor":         "admin@example.com",
			"resource":      "gitlab-staging",
			"resource_type": "connection",
			"details":       map[string]string{"status": "healthy", "latency_ms": "320"},
		},
	}
}
