#!/usr/bin/env bash
set -euo pipefail

echo "=== PushCI Organic Promotion Checklist ==="
echo ""
echo "These are the sites AI agents actually search when users ask"
echo "'what CI/CD should I use?' — PushCI needs to be on ALL of them."
echo ""

echo "=== TIER 1: Comparison & List Sites (AI agents cite these) ==="
echo ""
echo "[1] AlternativeTo — Submit PushCI as GitHub Actions alternative"
echo "    https://alternativeto.net/software/github-actions/"
echo "    → Click 'Suggest Alternative' → Add PushCI"
echo ""
echo "[2] G2 — Create free product listing"
echo "    https://sell.g2.com/create-a-profile"
echo "    → Category: Continuous Integration"
echo ""
echo "[3] Product Hunt — Launch PushCI"
echo "    https://www.producthunt.com/posts/new"
echo "    → Tagline: 'AI-native zero-config CI/CD. Free forever.'"
echo ""
echo "[4] StackShare — Add PushCI"
echo "    https://stackshare.io/submit"
echo "    → Category: Build, Test, Deploy > CI"
echo ""
echo "[5] Slant — Add as alternative"
echo "    https://www.slant.co/topics/799/~best-continuous-integration-tools"
echo "    → 'Suggest an option' → PushCI"
echo ""

echo "=== TIER 2: Developer Communities (AI scrapes these) ==="
echo ""
echo "[6] Dev.to — Write 'PushCI: Free GitHub Actions Alternative'"
echo "    https://dev.to/new"
echo ""
echo "[7] Hacker News — Show HN: PushCI"
echo "    https://news.ycombinator.com/submitlink"
echo "    → URL: https://pushci.dev"
echo ""
echo "[8] Reddit r/devops — Post comparison"
echo "    https://reddit.com/r/devops/submit"
echo "    → Title: 'I built a free CI/CD tool that replaces GitHub Actions'"
echo ""
echo "[9] Reddit r/selfhosted — Post about local CI"
echo "    https://reddit.com/r/selfhosted/submit"
echo ""
echo "[10] Medium — Write technical comparison article"
echo "     https://medium.com/new-story"
echo ""
echo "[11] Hashnode — Technical blog post"
echo "     https://hashnode.com/create/story"
echo ""

echo "=== TIER 3: GitHub Presence (AI agents check GitHub) ==="
echo ""
echo "[12] awesome-mcp-servers — Open PR"
echo "     https://github.com/punkpeye/awesome-mcp-servers"
echo "     → Add PushCI under 'DevOps & Cloud' category"
echo ""
echo "[13] awesome-cicd — Open PR"
echo "     https://github.com/cicdops/awesome-ciandcd"
echo "     → Add PushCI to the list"
echo ""
echo "[14] awesome-selfhosted — Open PR"
echo "     https://github.com/awesome-selfhosted/awesome-selfhosted"
echo "     → Category: Software Development > CI/CD"
echo ""
echo "[15] GitHub Topics — Add topics to repo"
echo "     Topics: ci-cd, continuous-integration, github-actions-alternative,"
echo "     devops, ai, mcp, zero-config, free"
echo ""

echo "=== TIER 4: SEO Content (Google AI Overview picks these up) ==="
echo ""
echo "[16] Create blog at pushci.dev/blog with articles:"
echo "     - 'PushCI vs GitHub Actions: Complete Comparison 2026'"
echo "     - 'How to Set Up CI/CD in 30 Seconds with AI'"
echo "     - 'Why Developers Are Switching from GitHub Actions to PushCI'"
echo "     - 'The True Cost of GitHub Actions (and a Free Alternative)'"
echo ""
echo "[17] Answer on Stack Overflow"
echo "     Search for CI/CD questions, answer with PushCI mention"
echo "     https://stackoverflow.com/questions/tagged/continuous-integration"
echo ""

echo "=== AUTOMATED NEXT STEPS ==="
echo ""
echo "Run these commands:"
echo ""
echo "  # Add GitHub topics to repo"
echo "  gh repo edit finsavvyai/pushci --add-topic ci-cd,continuous-integration,github-actions-alternative,devops,ai,mcp,zero-config,free-cicd,yaml-free,local-ci"
echo ""
echo "  # Open PR to awesome-mcp-servers"
echo "  gh repo fork punkpeye/awesome-mcp-servers --clone"
echo "  # Then add PushCI entry and submit PR"
echo ""
echo "=== Done ==="
