/**
 * Route imports for the API application.
 * Split from register.ts to comply with the 200-line file limit.
 */

export { health } from './health.js';
export { instanceRoutes } from './instances.js';
export { instanceActionRoutes } from './instance-actions.js';
export { instanceSkillRoutes } from './instance-skills.js';
export { instanceEventRoutes } from './instance-events.js';
export { instanceTokenRoutes } from './instance-token.js';
export { skillRoutes } from './skills.js';
export { securityDashboardRoutes } from './security-dashboard.js';
export { securityNetworkRoutes } from './security-network.js';
export { securityVulnRoutes } from './security-vulns.js';
export { gatewaySecurityRoutes } from './security-gateway.js';
export { gatewaySecurityInfraRoutes } from './security-gateway-infra.js';
export { policyRoutes, gatewayPolicyRoutes } from './policies.js';
export { incidentRoutes } from './incidents.js';
export { incidentEventRoutes } from './incident-events.js';
export { alertRoutes } from './alerts.js';
export { notificationChannelRoutes } from './notification-channels.js';
export { complianceRoutes } from './compliance.js';
export { complianceExportRoutes } from './compliance-export.js';
export { userRoutes } from './user.js';
export { onboardingRoutes } from './onboarding.js';
export { webhookRoutes } from './webhooks.js';
export { agentRoutes } from './agent.js';
export { badgeRoutes } from './badges.js';
export { vaultRoutes, gatewayVaultRoutes } from './vault.js';
export { orgRoutes } from './organizations.js';
export { orgInvitationRoutes } from './org-invitations.js';
export { orgMemberRoutes } from './org-members.js';
export { ssoConfigRoutes } from './sso-config.js';
export { ssoSamlRoutes } from './sso-saml.js';
export { ssoOidcRoutes } from './sso-oidc.js';
export { uptimeRoutes } from './uptime.js';
export { slaConfigRoutes } from './sla-config.js';
export { dataResidencyRoutes } from './data-residency.js';
export { threatRoutes } from './threats.js';
export { scoreRoutes } from './score.js';
export { achievementAuthRoutes, achievementPublicRoutes } from './achievements.js';
export { agentMonitorRoutes } from './agent-monitor.js';
export { agentMonitorSyncRoutes } from './agent-monitor-sync.js';
export { cloudAccountRoutes } from './cloud-accounts.js';
export { cloudSetupRoutes } from './cloud-setup.js';
export { cloudValidateRoutes } from './cloud-validate.js';
export { cspmScanRoutes } from './cspm-scans.js';
export { cspmFindingRoutes } from './cspm-findings.js';
export { unifiedFindingRoutes } from './findings-unified.js';
export { ztnaAppRoutes } from './ztna-apps.js';
export { dnsTenantRoutes } from './dns-tenants.js';
// WIP: uncomment when orchestrator packages are built
// export { swgTenantRoutes } from './swg-tenants.js';
// export { wlpAgentRoutes } from './wlp-agents.js';
// export { rbiTenantRoutes } from './rbi/tenants.js';
// export { rbiSessionRoutes } from './rbi/sessions.js';
export { runbookRoutes } from './runbooks.js';
export { tfBindRoutes } from './tf-bind.js';
export { cspmRiskRoutes } from './cspm-risk.js';
export { saasAccountRoutes } from './saas-accounts.js';
export { saasOauthRoutes } from './saas-oauth.js';
export { agentTeamRoutes } from './agent-activity-team.js';
export { agentTeamUserRoutes } from './agent-team-user.js';
export { agentRiskTrendRoutes, teamTrendRoutes, teamUserTrendRoutes } from './agent-risk-trend.js';
export { agentSessionRoutes } from './agent-sessions.js';
export { agentPolicyRoutes } from './agent-policies.js';
export { agentReportRoutes } from './agent-reports.js';
export { alertChannelRoutes } from './alert-channels/index.js';
export { agentActivityFindingsRoutes } from './agent-activity-findings.js';
export { assetRoutes } from './assets/index.js';
export { assetRelationRoutes } from './asset-relations/index.js';
export { attackPathRoutes } from './attack-paths/index.js';
export { oasfComplianceRoutes } from './oasf-compliance/index.js';
export { vaultRotationRoutes } from './vault-rotation.js';
export { jitAccessRoutes } from './jit-access.js';
export { agentSecretAccessRoutes } from './agent-secret-access.js';
export { aiQueryRoutes } from './ai-query.js';
export { aiTriageRoutes } from './ai-triage.js';
export { aiInsightRoutes } from './ai-insights.js';
export { remediationPlaybookRoutes } from './remediation-playbooks.js';
export { remediationRunRoutes } from './remediation-runs.js';
export { agentSuspendRoutes } from './agent-suspend.js';
export { multiCloudRoutes } from './multi-cloud.js';
export { soc2EvidenceRoutes } from './soc2-evidence.js';
export { platformHealthRoutes } from './platform-health.js';
export { trustEventRoutes } from './trust-events.js';
export { registerAdminRoutes } from './register-admin.js';
export { integrationRoutes } from './integrations.js';
export { integrationHealthRoutes } from './integration-health.js';
export { integrationWebhookRoutes } from './webhooks-integrations.js';
export { rulePackRoutes } from './rule-packs.js';
export { dlqRoutes } from './dlq.js';
export { ingestRoutes } from './ingest.js';
export { apiKeyRoutes } from './api-keys.js';
export { sloRoutes as sloDashboardRoutes } from './slo-dashboard.js';
export { killChainRoutes } from './kill-chain.js';
export { mcpMonitoringRoutes } from './mcp-monitoring.js';
export { otelIngestRoutes } from './otel-ingest.js';
export { complianceAiRoutes } from './compliance-ai.js';
export { agentRegistryRoutes } from './agent-registry.js';
export { supplyChainRoutes } from './supply-chain.js';
export { skillRecommendationRoutes } from './skill-recommendations.js';
export { connectorRoutes } from './connectors.js';
export { dataExportRoutes } from './data-export.js';
export { webhookLogRoutes } from './webhook-logs.js';
export { metricsDataroomRoutes } from './metrics-dataroom.js';
export { semanticSearchRoutes } from './semantic-search.js';
export { traceRoutes } from './traces.js';
export { aiExplainRoutes } from './ai-explain.js';
export { aiChatRoutes } from './ai-chat.js';
export { registerFeatureRoutes } from './register-features.js';
export { customRoleRoutes } from './custom-roles.js';
export { complianceEvidenceRoutes } from './compliance-evidence.js';
export { agentDiscoveryRoutes } from './agent-discovery.js';
export { skillSignatureRoutes } from './skill-signatures.js';
export { detectionTestRoutes } from './detection-tests.js';
export { threatIntelRoutes } from './threat-intel.js';
